### ISSUE TITLE
I want set our kubeconfig at ease 

### ISSUE THREAD

**Issue by JacksChoco** [GoogleCloudPlatform/cloud-code-vscode#100]
**Environment**:
Extension version: 0.0.8
VSCode version: 1.33.1
OS: darwin

**Description**:

**Repro step**:

similar this one
<img width="284" alt="스크린샷 2019-05-01 오후 10 02 59" src="https://user-images.githubusercontent.com/26213544/57018086-ec5fc080-6c5c-11e9-81a2-b89c4e019c65.png">

**Comment by quoctruong** [comment]
@JacksChoco Please refer to https://github.com/GoogleCloudPlatform/cloud-code-vscode/issues/34
