### ISSUE TITLE
Open Terminal feature should allow specifying a container for a new pod

### ISSUE THREAD

**Issue by nikhilk** [GoogleCloudPlatform/cloud-code-vscode#102]
**Use case**
What are you trying to do that our extension doesn't let you?

I want to open a terminal, but not to one of my existing pods, but rather a pod using a container which I have that contains various CLI/diagnostic tools.

The Open Terminal command only allows me to pick existing pods from the default namespace.

**Comment by quoctruong** [comment]
@nikhilk Do you mean that we should allow opening a terminal to a pod that exists in a namespace other than the default namespace?

**Comment by nikhilk** [comment]
Thats one aspect of this feature requests.
For example, I might have a "shell" pod within an "infra" namespace.

Alternatively, and quite often, I need to first deploy a shell pod when I want a terminal prompt. Usually such a pod is not always running. For example, here is the shell.sh script I currently use:

```
PROJECT=$(gcloud config list project --format "value(core.project)")

kubectl run -i --tty --rm --restart Never \
  --image "gcr.io/${PROJECT}/shell:latest" \
  --namespace infra \
  --serviceaccount infra-service-account \
  shell --command -- \
  bash
```

Note - I also need to be able to specify service accounts, because I might want to make changes to k8s objects from my shell that requires the pod to have a service account that has been authorized to make such API calls.

**Comment by quoctruong** [comment]
@nikhilk Does the pod shows up in the Resource Browser? If so, I think you can right click and select `Get Terminal`.

**Comment by nikhilk** [comment]
In most cases, the pod won't pre-exist - don't have clusters running pods continually that are meant for debugging use cases or in-cluster tinkering. And in most cases, don't want to get a shell within a pod running an actual workload.

However for the purposes of this bug, I tried right clicking on an existing pod in the resource browser, but I don't see a Get Terminal command in the right click menu.

**Comment by quoctruong** [comment]
Can you right click on a container of the pod instead?

**Comment by nikhilk** [comment]
Yes, drilling down and right clicking on the container does surface command -- and will be usable in the rare case that a shell terminal already exists.

I don't know if kubectl exec requires you to specify a container if the pod contains just a single container, but seems redundant.

**Comment by quoctruong** [comment]
@nikhilk It shouldn’t. We will improve the experience in future releases.

**Comment by nikhilk** [comment]
Seems like a separate feature/improvement to file and track. This bug should probably focus on making it simpler to get a terminal, when getting a terminal requires deployment of a terminal pod as well.

**Comment by quoctruong** [comment]
Yes you’re right, that is a separate improvement. In addition to the existing pods, we can add an option when running the GetTerminal command for you to select an image of a pod that you want to deploy and open the terminal to. Does that sound reasonable?

**Comment by nikhilk** [comment]
This is getting into the design of the feature, but I don't think as a user I would want to provide this information every time I use the terminal command.

I would want to define the manifest of the terminal pod once, and it should go in/alongside .vscode and just used when the command is invoked.

**Comment by jmah-cc** [comment]
After reviewing this request again, it's not at the top of our prioritized list. Adding it to backlog and keeping the issue open so other users can upvote this.

**Comment by sivakku** [comment]
Closing this one as it is not the focus of the team now, Getting a terminal to bootstrapping pod that is meant for administration operations of other cluster operations. The Cloud Shell on pantheon can be used for administrative operations.
