### ISSUE TITLE
Diff feature should canonicalize yaml files

### ISSUE THREAD

**Issue by nikhilk** [GoogleCloudPlatform/cloud-code-vscode#103]
**Use case**
What are you trying to do that our extension doesn't let you?

I was trying to diff the YAML manifest descriptor in my source tree with what the k8s API server reports using the diff command. The resulting diff is a fairly large diff because of line reorderings.

The source yaml file had things listed in logical order chosen by the author of the yaml file.
The k8s api server generated yaml listed things in alphabetical order.

Result was a huge diff.

**Feature**
What would help?

It would be interesting to canonicalize the source file - eg. things like sort order of the various sections.
Also found the k8s version introduced some things like: `annotations: {}` within a k8s metadata block, but that wasn't in my source file.

**Comment by redborian** [comment]
Thanks for using our extension and reporting an enhancement. If you did a `kubectl apply` on the resource or created the resource with `--save-config` flag, the diff would be much smaller. If not, we are unable to narrow-down the diff size. One feature that we are currently working on is better ordering of items in diff view. Would that feature be helpful for you?

**Comment by nikhilk** [comment]
You could sort the source file regardless of how the resource was deployed, and that would already significantly cut down on the diff noise. In my case, the resource is deployed through some other infrastructure -- not manually.

**Comment by j-windsor** [comment]
Closing as it looks like the possible fix is in #458
