### ISSUE TITLE
Apply yaml feature should support templatization

### ISSUE THREAD

**Issue by nikhilk** [GoogleCloudPlatform/cloud-code-vscode#104]
**Use case**
What are you trying to do that our extension doesn't let you?

The YAML manifests in my source tree are templates containing placeholders that must be substituted before applied using kubectl apply. For example, the following exists in my YAML file:

```
containers:
  foo: gcr.io/$PROJECT/foo:latest
```

**Feature**
What would help?

It would be useful to have an extendable/customizable list of placeholder values, some of which are configured from the current environment (eg. project, region/zone, user, etc.) that are used to produce deployable YAML manifests from template yaml files at the source code level.

**Comment by iantalarico** [comment]
@nikhilk thanks for the feedback. 

What are you using for templating now?

**Comment by jmah-cc** [comment]
This can be solved by using Kustomize on your end. We don't have plans to do any other work here.
