### ISSUE TITLE
New Cluster UI says to retry selecting a zone if Compute API isn't enabled but no retry button exists

### ISSUE THREAD

**Issue by russwolf** [GoogleCloudPlatform/cloud-code-vscode#106]
**Environment**:
Extension version: 0.0.8
VSCode version: 1.33.1
OS: darwin

**Description**:
New Cluster UI says to retry selecting a zone if Compute API isn't enabled but no retry button exists. If you enable the Compute Engine API, you need to back out and reselect the project to get the zones to appear. It would be much smoother if there were a retry button or if the text "retry" were a clickable link to retry. 

**Repro step**:
1. Create a new Cloud project in the Cloud Console
2. In VS Code, select New Cluster 
3. Enter the project id and click "Set Project ID" 
4. See the error that says you need to visit a link to enable Compute API to retry
5. Visit the link and enable Compute API
6. Return to VS Code

Expected: 
There is a button I can click to retry to load the zones

Actual: 
There is no button to retry to load the zones. I needed to return to the previous step and set the project ID again to see the list of zones.

**Comment by redborian** [comment]
This has been fixed in the next release

**Comment by sujit-kamireddy** [comment]
The fix for this issue is in our latest [release](https://github.com/GoogleCloudPlatform/cloud-code-vscode/releases/tag/v0.0.12). Please update the extension and retry the scenario.

**Comment by redborian** [comment]
We have fixed this release in the latest release (v0.0.13)
