### ISSUE TITLE
Creating GKE does not reflect selected instance type

### ISSUE THREAD

**Issue by Maziak2520** [GoogleCloudPlatform/cloud-code-vscode#107]
**Environment**:
Extension version: 0.0.8
VSCode version: 1.33.1
Extension version:
VSCode version:
OS: Chrome OS  (linux crostini)
Google Chrome OS
Version 75.0.3770.24 (Official Build) beta (64-bit)

**Description**:
cloud code create gke does nto reflect selected instance type... 

**Repro step**:
vscode, \cloud code create gke, select instance micro and the command that will be spinned has parameter instance type "standard"

**Comment by Maziak2520** [comment]
Screenshots of the manifest (making of GKE guide)  and resulting instances on GCP
![Screenshot 2019-05-17 at 23 32 12](https://user-images.githubusercontent.com/14327861/57965431-6d61cc00-796e-11e9-8046-7f49d3325ea2.png)
![Screenshot 2019-05-17 at 23 41 30](https://user-images.githubusercontent.com/14327861/57965440-85395000-796e-11e9-87c8-08cad80da612.png)

**Comment by iantalarico** [comment]
@Maziak2520 Thanks for the feedback!

@redborian Can you take a look at this?

**Comment by redborian** [comment]
This is fixed in head and will be part of next release.

**Comment by redborian** [comment]
This is part of the latest release
