### ISSUE TITLE
Issue%20Name

### ISSUE THREAD

**Issue by leeclark7878** [GoogleCloudPlatform/cloud-code-vscode#109]
**Environment**%3A%0AExtension%20version%3A%200.0.8%0AVSCode%20version%3A%201.34.0%0AOS%3A%20linux%0A%0A**Description**%3A%0A%0A**Repro%20step**%3A

**Comment by quoctruong** [comment]
@leeclark7878 Please edit the description and content of the issue.

**Comment by iantalarico** [comment]
If you have more context to add please reopen this issue.
