### ISSUE TITLE
Custom attributes in skaffold.yaml erased by Profile Wizard

### ISSUE THREAD

**Issue by chairy** [GoogleCloudPlatform/cloud-code-vscode#110]
**Environment**%3A%0AExtension%20version%3A%200.0.8%0AVSCode%20version%3A%201.34.0%0AOS%3A%20darwin%0A%0A**Description**%3A%0A%0A**Repro%20step**%3A

I added an attribute in one of my deployment profile by directly editing skaffold.yaml. When I tried to edit the profile via the profile wizard and save, the attribute I added earlier disappeared.

**Comment by iantalarico** [comment]
@sujit-kamireddy Can you TAL at this?

**Comment by sujit-kamireddy** [comment]
@chairy , can you provide more info like the sample skaffold.yaml (with attribute) you have?

**Comment by chairy** [comment]
Repo step:
1. Open the attached yaml file in VS code, and you will see the _timeout_ attribute under _googleCloudBuild_.
2. Close the file.
3. Edit the profile via the wizard by modifying the project id. Save the change.
4. Open the yaml file and the _timeout_ attribute is no longer there.



[skaffold-cc.yaml.zip](https://github.com/GoogleCloudPlatform/cloud-code-vscode/files/3229908/skaffold-cc.yaml.zip)

**Comment by sujit-kamireddy** [comment]
Got it. This is a sync issue between the wizard and the skaffold.yaml. There is a TODO in the code to fix this case.
