### ISSUE TITLE
"Open Dashboard" on the Cluster Explorer doesn't seem to work

### ISSUE THREAD

**Issue by matthewmichihara** [GoogleCloudPlatform/cloud-code-vscode#111]
**Environment**%3A%0AExtension%20version%3A%200.0.8%0AVSCode%20version%3A%201.34.0%0AOS%3A%20darwin%0A%0A**Description**%3A%0A%0A**Repro%20step**%3A

Doing so takes me to `http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/` in my browser which displays the following JSON:

```json
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "services \"kubernetes-dashboard\" not found",
  "reason": "NotFound",
  "details": {
    "name": "kubernetes-dashboard",
    "kind": "services"
  },
  "code": 404
}
```
![in](https://user-images.githubusercontent.com/79073/58661094-f7a61a80-82f4-11e9-922a-b575cbcbc407.gif)

**Comment by quoctruong** [comment]
@matthewmichihara What happens if you run `kubectl proxy` on the command line?

**Comment by matthewmichihara** [comment]
On the command line, I get --

```
$ kubectl proxy
Starting to serve on 127.0.0.1:8001
```

**Comment by quoctruong** [comment]
@matthewmichihara This is actually by design, you have to deploy the dashboard first (https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/#deploying-the-dashboard-ui).

**Comment by matthewmichihara** [comment]
oh ok, thanks for taking a look.
