### ISSUE TITLE
Selecting namespace for debugging pod

### ISSUE THREAD

**Issue by engmsaleh** [GoogleCloudPlatform/cloud-code-vscode#114]
**Environment**:
*(Hint: "Report Kubernetes Extension Issue on Github" command will fill these out for you.)*
Extension version:
VSCode version: 1.35.0
OS: OSX 10.14.5

**Description**:
When I want to debug microservice we use `podSelector` to select the required pod, the problem that if I want to select also the namespace it is in is there any way for that?

**Comment by quoctruong** [comment]
@engmsaleh currently there’s no way to select the namespace. What you can do as a workaround is to set the current context of kubectl to a context that uses the namespace you want.

**Comment by engmsaleh** [comment]
@quoctruong ok, I have switched the context to the required namespace, now I'm facing two problems when I run debugging for my python project

- It vscode keeps asking for *ptvsd* and want to install it, although it is already installed on my local venv and I have added it to Dockerfile for the pod container
- It gives the following error after `Debugging is not supported for multiple pods.`, I don't understand as I'm running only one pod of that service

**Comment by engmsaleh** [comment]
For `Debugging is not supported for multiple pods` I have figured it out, it was my fault with the second pod with the same label, removing it made it start the debug process 

I'm facing now a problem `Matches multiple schemas when only one must validate.` here is my `launch.json` file

```
// launch.json contains information needed for the debugger to attach to  processes
// See https://code.visualstudio.com/Docs/editor/debugging#_launch-configurations
// for documentation about how to create and manage configurations
{
  "version": "0.2.0",
  "configurations": [
    {
      "podSelector": {
        "app": "helpers-service"
      },
      "type": "cloudcode",
      "request": "attach",
      "localRoot": "${workspaceFolder}/src",
      "language": "Python",
      "remoteRoot": "/app",
      "name": "Debug Helpers-Service",
      "debugPort": 3000
    }
  ]
}
```

Although the debug process started, it doesn't fire the breakpoint

**Comment by redborian** [comment]
@engmsaleh Are you seeing this "Matches multiple schemas" error in launch.json?
If so, @quoctruong is there anything that we need to do (like bumping up "version", providing custom schema, etc.) for launch.json file?

**Comment by engmsaleh** [comment]
Hi @redborian Yes, it is on `launch.json` Please check attached screenshot
![Screen Shot 2019-06-10 at 4 55 14 PM](https://user-images.githubusercontent.com/462150/59204608-4a0ef300-8ba1-11e9-8254-409cb70d3760.png)

**Comment by redborian** [comment]
Thanks for the screenshot @engmsaleh. It is just a warning and can be safely ignored for now. To come back to your previous problem, can you try restarting VSCode after installing PTVSD? Can you also scale down the deployment to just 1 pod and try debugging?

**Comment by engmsaleh** [comment]
@redborian I have made the restart, but the same has happened and it asks me for install `PTVSD` and after I click install I get 
```> Executing task: /Users/mohamedsaleh/.pyenv/shims/python -m pip install --user ptvsd <

Requirement already satisfied: ptvsd in /Users/mohamedsaleh/.local/lib/python3.7/site-packages (4.2.10)
You are using pip version 10.0.1, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

The terminal will be reused by tasks, press any key to close it.```

Then the **output**  window gives the following

```Forwarding from 127.0.0.1:56366 -> 3000

Forwarding from [::1]:56366 -> 3000

Handling connection for 56366

E0610 18:54:40.724498   59834 portforward.go:400] an error occurred forwarding 56366 -> 3000: error forwarding port 3000 to pod 7e83143d70c5622d48710c69fdfee63f82755bb551a5490a506e841771c2a512, uid : exit status 1: 2019/06/10 16:54:40 socat[9181] E connect(5, AF=2 127.0.0.1:3000, 16): Connection refused```

**Comment by redborian** [comment]
Two things:
1. I see that you are using python3. Can you set an alias in your bashrc or zshrc: `alias python=python3`, restart terminal and start VSCode from terminal? (We have some bad assumptions regarding python binary names which we will fix soon, fyi @quoctruong)
2. We run `python -m pip list --format json` to determine whether ptvsd is installed. Can you run that command and see if ptvsd shows up?

**Comment by engmsaleh** [comment]
@redborian I have make the alias and now the problem of asking for `PTVSD` is gone and the output of the command is 
```[{"name": "autopep8", "version": "1.4.4"}, {"name": "Click", "version": "7.0"}, {"name": "Flask", "version": "1.0.3"}, {"name": "gunicorn", "version": "19.9.0"}, {"name": "itsdangerous", "version": "1.1.0"}, {"name": "Jinja2", "version": "2.10.1"}, {"name": "MarkupSafe", "version": "1.1.1"}, {"name": "pip", "version": "19.1.1"}, {"name": "psycopg2", "version": "2.8.2"}, {"name": "psycopg2-binary", "version": "2.8.2"}, {"name": "ptvsd", "version": "4.2.10"}, {"name": "pycodestyle", "version": "2.5.0"}, {"name": "python-dotenv", "version": "0.10.3"}, {"name": "setuptools", "version": "39.0.1"}, {"name": "Werkzeug", "version": "0.15.4"}]```

But the problem of debugging still the same 

```
Forwarding from 127.0.0.1:50226 -> 3000

Forwarding from [::1]:50226 -> 3000

Handling connection for 50226

E0610 20:17:05.341658   61446 portforward.go:400] an error occurred forwarding 50226 -> 3000: error forwarding port 3000 to pod 7e83143d70c5622d48710c69fdfee63f82755bb551a5490a506e841771c2a512, uid : exit status 1: 2019/06/10 18:17:05 socat[28906] E connect(5, AF=2 127.0.0.1:3000, 16): Connection refused
```

**Comment by redborian** [comment]
Awesome! Let's tackle the next problem.
It looks like port 3000 is not being opened by the pod properly. Have you configured your `Dockerfile` to boot up your python app with ptvsd enabled? If possible, can you share your `Dockerfile`?

**Comment by engmsaleh** [comment]
@redborian here is my **Dockerfille**

```
# Python image to use.
FROM python:3.7-alpine as base
FROM base as builder

# Maintainer
MAINTAINER Mohamed Saleh

# Set the working directory to /install
RUN mkdir /install
WORKDIR /install

# copy the requirements file used for dependencies
COPY requirements.txt .

# Install any needed packages specified in requirements.txt
RUN apk --no-cache add build-base
RUN apk --no-cache add postgresql-dev
RUN pip install --trusted-host pypi.python.org --install-option="--prefix=/install" -r requirements.txt

# Move to the final stage
FROM base
COPY --from=builder /install /usr/local
RUN apk --no-cache add libpq
WORKDIR /app

# Install ptvsd for debugging
RUN pip install ptvsd

# Copy the rest of the working directory contents into the container at /app
COPY . .

# Run app.py when the container launches
ENTRYPOINT ["python", "-m", "ptvsd", "--port", "3000", "--host", "0.0.0.0", "app.py"]

# For Production only as gunicorn cannot run remote debugging
# CMD ["gunicorn", "--config", "./conf/gunicorn_conf.py", "app:app"]
```

Here is my **app.py** file

```
import logging
import os
from flask import Flask, jsonify
from helpers_api import helpers_api_blueprint

# pylint: disable=C0103
app = Flask(__name__)

app.register_blueprint(helpers_api_blueprint)

# Pass Flask logger to Gunicorn logger
gunicorn_logger = logging.getLogger('gunicorn.error')
app.logger.handlers = gunicorn_logger.handlers
app.logger.setLevel(gunicorn_logger.level)

# @app.route('/')
# def hello():
#     """Return a friendly HTTP greeting."""
#     message = "Hello World"
#     return message

@app.route('/liveness')
def return_ok():
    return 'Ok!', 200

if __name__ == '__main__':
    server_port = os.environ.get('PORT')
    if server_port is None:
        print("error: PORT environment variable not set")
        exit(1)

    app.run(debug=True, port=server_port, host='0.0.0.0') 
```

**Comment by quoctruong** [comment]
@engmsaleh Can you try cleaning up the deployment with `skaffold delete`, do a fresh deployment and try the debugging?

**Comment by redborian** [comment]
@engmsaleh As you are troubleshooting this issue, there might be multiple `kubectl portforward` processes running in the background. I would suggest you do a `ps aux | grep portforward`, kill all the portforwarding processes and starting a new debug session.

**Comment by engmsaleh** [comment]
@quoctruong @redborian I have made `skaffold delete` and made a fresh deployment, the error seems to be gone, but still, it doesn't stop at breakpoints, it simply ignores it and continues running

**Comment by quoctruong** [comment]
Can you show us a screenshot/gif of the debugging process? Also, is your `app.py` file located in a `src` folder on your machine?

**Comment by engmsaleh** [comment]
@quoctruong here is `app.py` file

```
import logging
import os
from flask import Flask, jsonify
from helpers_api import helpers_api_blueprint

# pylint: disable=C0103
app = Flask(__name__)

app.register_blueprint(helpers_api_blueprint)

# Pass Flask logger to Gunicorn logger
gunicorn_logger = logging.getLogger('gunicorn.error')
app.logger.handlers = gunicorn_logger.handlers
app.logger.setLevel(gunicorn_logger.level)

# @app.route('/')
# def hello():
#     """Return a friendly HTTP greeting."""
#     message = "Hello World"
#     return message

@app.route('/liveness')
def return_ok():
    return 'Ok!', 200

if __name__ == '__main__':
    server_port = os.environ.get('PORT')
    if server_port is None:
        print("error: PORT environment variable not set")
        exit(1)

    app.run(debug=True, port=server_port, host='0.0.0.0')
```

Here is my structure
```
│   ├── helpers.deployment.yaml
│   ├── helpers.service.yaml
│   └── ingress.yaml
├── skaffold.yaml
├── src
│   ├── Dockerfile
│   ├── __pycache__
│   │   ├── __init__.cpython-37.pyc
│   │   └── app.cpython-37.pyc
│   ├── app.py
│   ├── conf
│   │   └── gunicorn_conf.py
│   ├── helpers_api
│   │   ├── __init__.py
│   │   ├── __pycache__
│   │   │   ├── __init__.cpython-37.pyc
│   │   │   ├── faqs.cpython-37.pyc
│   │   │   ├── local_banks.cpython-37.pyc
│   │   │   ├── referral_code_image.cpython-37.pyc
│   │   │   └── referral_detail.cpython-37.pyc
│   │   ├── faqs.py
│   │   ├── local_banks.py
│   │   ├── referral_code_image.py
│   │   └── referral_detail.py
│   └── requirements.txt
└── tests
    └── test_end_to_end.py
```

**Comment by engmsaleh** [comment]
Here is a recording for the debug
http://recordit.co/V1EmCtYukY

**Comment by quoctruong** [comment]
@engmsaleh Can you change `app.run(debug=True, port=server_port, host='0.0.0.0')` to `app.run(debug=False, port=server_port, host='0.0.0.0')` and try redeploying and debugging?

**Comment by engmsaleh** [comment]
@quoctruong This time when changed **debug** to **False** it worked and the breakpoints are hit... Is that the correct behavior? as I understand it should be the opposite

**Comment by quoctruong** [comment]
@engmsaleh That's actually the correct behavior. The `debug` option in `Flask` actually interferes with `ptvsd` if I understand correctly. That is why we set that to `False` in the sample too.

**Comment by engmsaleh** [comment]
@quoctruong Ok, no problem, Thanks a lot for your kind help :)

**Comment by quoctruong** [comment]
No problem! Thanks for being so responsive. I'll close this issue.
