### ISSUE TITLE
Getting Error Message: "Http load balancing must be enabled in order to enable the Cloud Run addon."

### ISSUE THREAD

**Issue by HaimWeFi** [GoogleCloudPlatform/cloud-code-vscode#117]
Extension version: v0.0.9
VSCode version: 1.35.0 (1.35.0)
OS: Mac OS 10.14.5

**Description**:
When trying to invoke a the "Create GKE cluster" command I chose my project, the region (us-central1) with Node Count:2 and enabled both istio and Cloud Run I get the following message:
Http load balancing must be enabled in order to enable the Cloud Run addon.

**Comment by sujit-kamireddy** [comment]
This issue has been fixed in the latest release 0.0.10. Please try it out.

As always, please keep issues coming our way.
