### ISSUE TITLE
Console error message after launching VSCode

### ISSUE THREAD

**Issue by Maples7** [GoogleCloudPlatform/cloud-code-vscode#118]
**Environment:**
Extension version: 0.0.9
VSCode version: 1.35.1
OS: darwin

**Description:**
After launching VSCode, there is always some annoying error message showed in Console tab output from this extension:
```
[Error - 11:42:54 PM] (node:24937) UnhandledPromiseRejectionWarning: #<Object>
[Error - 11:42:54 PM] (node:24937) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[Error - 11:42:54 PM] (node:24937) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Repro step:**
Install this extension and relaunch VSCode for times.

**Comment by redborian** [comment]
Thanks for reporting this issue. We will investigate and fix this issue.

**Comment by stessaris** [comment]
@redborian this is not an enhancement, but a bug preventing the use of the extension! I had the same issue and I was forced to disable the extension because VSCode kept popping up the error message by switching to the log window.

**Comment by redborian** [comment]
Thanks for the feedback @stressaris. We will fix it in next release.

**Comment by sujit-kamireddy** [comment]
This issue has been fixed in the latest release 0.0.10. Please try it out.

As always, please keep issues coming our way.

**Comment by Maples7** [comment]
This issue occurs again after I update VSCode to version 1.37.0:

Output:
```
[Error - 1:36:13 PM] [object Object]
[Error - 1:36:13 PM] [object Object]
```

**Comment by redborian** [comment]
Thanks for reporting the issue @Maples7. Can you set `"cloudcode.yaml.trace.server"` to `"verbose"` and attach your logs from `"CloudCode Yaml Support"` output channel?

**Comment by Maples7** [comment]
Sorry, it seems disappeared in hours after the update, I don't know the reason.

**Comment by Maples7** [comment]
It's recurrent on VSCode version 1.38.0. 
Sorry, feeling so sad.

**Comment by redborian** [comment]
Thanks for reporting the issue @Maples7. We will investigate the issue.

**Comment by redborian** [comment]
@Maples7 we are awaiting more information to troubleshoot this issue. Can you provide the requested information above?

**Comment by Maples7** [comment]
It turns out I should re-install the extension to avoid the issues for each time after VSCode is updated. I think there might be some configurations are not compatible.
I'll set "cloudcode.yaml.trace.server" to "verbose" to see what will happen for next update of VSCode, for now I'll close the issue. Cheers!
