### ISSUE TITLE
Remote debug of .NET Core app deployed to Kubernetes cluster extremely slow

### ISSUE THREAD

**Issue by trenslow** [GoogleCloudPlatform/cloud-code-vscode#119]
**Environment**:
*(Hint: "Report Kubernetes Extension Issue on Github" command will fill these out for you.)*
Extension version: 0.0.9
VSCode version: 1.35.1
OS:  Windows 10 Enterprise

**Description**:
I'm attempting to debug my .NET Core app running in my local Docker for Desktop Kubernetes cluster. However, whenever I make a HTTP request to my app, it takes at least a minute to hit the breakpoint in my code. This unfortunately makes the Cloud Code remote debug feature unusable for me.

**Repro step**:
I first tried debugging the app running on a GKE cluster with the same result, except slightly more lag, for obvious reasons.

I thought there may be some middleware that was interfering with the connection to the debugger. However, I started from one of Cloud Code's toy applications and added my app's middleware piece-by-piece, and experienced no increase in lag in the debugging process. At that point I suspected that my Kubernetes cluster was somehow improperly configured.

I then attempted to debug the app a docker container running the app, using docker as the pipe program, and it worked like a charm.

To test further, I found [this article](https://iboware.com/development/2018/10/12/remote-debugging-asp-net-core-applications-on-kubernetes/) which allows you to attach to a pod using kubectl as the pipe program. However, this also works just like the docker approach, with hardly any lag.

This then led me to believe there is something wrong with the mechanism that underlies the podSelector in the Cloud Code remote debug, as it's the only difference in configuration between Cloud Code and the kubectl exec approach. 

I really like the workflow of continuous deployment to a Kubernetes cluster as I make changes to my code (I'm a big fan of Skaffold!), but unfortunately, the Cloud Code remote debug of .NET Core apps is currently too slow. I would greatly appreciate if you can look into this matter.

Cheers

**Comment by trenslow** [comment]
Hello,

I found a workaround but I don't know if this is intended behavior.

I created a separate service (doesn't matter if it's LoadBalancer or ClusterIP) that exposed my Deployment at the .NET Core debugger port 9229 and now I'm hitting the breakpoint in a comparable time to if I were developing the app on my local machine.

I got this idea by realizing that I hadn't specified this port in the container spec of the Deployment, as was done in the guestbook example provided by Cloud Code. This was the only difference between my configuration and the guestbook at the time of creating the issue. However, when I added the debug port to the Deployment container spec, it actually didn't speed up my debugging.

When I stream the logs of my pod, I see that the incoming HTTP request is received quickly. Therefore it seems that the information from the debugger is taking a while to make it back to VS Code from the pod. The fact that it takes around the same amount of time each time (~70 seconds) makes me feel like the pod is trying every port starting from 1 up to 9229 to relay the information back to me.

What I don't understand however, is why specifying the debug port on the deployment spec works for the guestbook app, but not mine.

Hope this helps.

**Comment by quoctruong** [comment]
@trenslow That's very interesting. Do you mind sharing the manifests?

**Comment by trenslow** [comment]
Hello,

Sorry for the late response, I was busy with other projects in the meantime.

I realized that I was limiting the CPU resources in the Deployment manifest, which caused the majority of the lag. It seems that the debugger requires quite a bit of computing power!

So that solves the extreme delay, but unfortunately there is still a bit of lag (~1-2 seconds to show information like variable values from the debugger) when debugging on my local machine. It's still unclear to me why the sample .NET Core app debugs with practically no delay, whereas mine does. Maybe it's the size difference, or some middleware that's fighting for resources.

As my original issue is resolved, I will go ahead and close it for now. But it would be awesome if the devs could look into the delay a little more, as I'd much rather prefer to develop the app remotely in a K8s cluster to ensure app compatibility with infrastructure.

Cheers!
