### ISSUE TITLE
Can't create AKS Cluster

### ISSUE THREAD

**Issue by jungopro** [GoogleCloudPlatform/cloud-code-vscode#120]
**Environment**:

Extension version: 0.0.9
VSCode version: 1.35.1
OS: Mac High Sierra

**Description**:
After choosing resource group and location in the Create AKS Cluster wizard, the wizard is stuck on `loading machine types`
**Repro step**:
Create AKS cluster from cloud code extension

**Comment by redborian** [comment]
Thanks for reporting the issue @jungopro. We will investigate this issue and update this thread with any updates.

**Comment by redborian** [comment]
Sorry for the late turn-around. When I revisited this issue with the latest version of azure cli, I couldn't reproduce it (version: `2.0.74`). In the background, we just run `az vm list-sizes -l <LOCATION> -ojson`. See if you can run the command manually in VS Code with the latest version of azure CLI.

**Comment by redborian** [comment]
I will go ahead and close this bug as there was no response. Feel free to re-open this bug when it repros again.
