### ISSUE TITLE
Creating an issue from VS Code on OSX give the following starter text

### ISSUE THREAD

**Issue by iantalarico** [GoogleCloudPlatform/cloud-code-vscode#123]
**Environment**%3A%0AExtension%20version%3A%200.0.9%0AVSCode%20version%3A%201.36.1%0AOS%3A%20darwin%0A%0A**Description**%3A%0A%0A**Repro%20step**%3A

**Comment by redborian** [comment]
Thanks @iantalarico for reporting this issue. This was caused by escaping the string twice. This has been fixed in our upcoming release.

**Comment by redborian** [comment]
This has been fixed in the latest release.
