### ISSUE TITLE
Setting an AWS cluster to the current cluster does not refresh the cluster explorer

### ISSUE THREAD

**Issue by iantalarico** [GoogleCloudPlatform/cloud-code-vscode#124]
**Environment**:
Extension version: 0.0.9
VSCode version: 1.36.1
OS: darwin

**Description**:
Setting an AWS cluster to the current cluster does not refresh the cluster explorer

**Comment by redborian** [comment]
Thanks for using our product! We will investigate and fix this issue in our upcoming releases.

**Comment by redborian** [comment]
This will be fixed in our upcoming release.

**Comment by jmah-cc** [comment]
This was done as a part of Jan release (v1.1.0)
