### ISSUE TITLE
Add support for local/on-prem kubernetes clusters other than minikube

### ISSUE THREAD

**Issue by tonyjames** [GoogleCloudPlatform/cloud-code-vscode#125]
**Use case**
I have an on-prem kubernetes cluster that I'd like to use with this extension.  Right now it appears that minikube is the only option.

**Feature**
Maybe adding an option to specify a kubeconfig file?  Not sure what else would be required.

**Comment by redborian** [comment]
Thanks for trying out our product! CloudCode should just work for any accessible Kubernetes cluster. So, in case of you on-prem cluster, you would need to add the cluster information (IP, user token etc) into your kubeconfig file (as detailed here: https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/)

**Comment by tonyjames** [comment]
Thanks this worked.
