### ISSUE TITLE
Provide an option to test templates file when launching cloud code

### ISSUE THREAD

**Issue by simonz130** [GoogleCloudPlatform/cloud-code-vscode#126]
Currently when user creates a new app using *Cloud Code: New Application*, .templates file is downloaded to determine which templates are supported. We want to have an option to specify the location of templates file when vscode starts so users who submit a new template can test them manually before enabling the templates for all the users. The option should allow specifying a physical path of templates file or github location with a custom branch.

**Comment by kschaab** [comment]
Not planning on doing this.
