### ISSUE TITLE
Support multiple natural language for documentation tooltip

### ISSUE THREAD

**Issue by remyleone** [GoogleCloudPlatform/cloud-code-vscode#129]
**Use case**

I would like to have the kubernetes documentation coming from a different language.
In case a person is not at ease with English, and documentation for Kubernetes is available in a different language, I would like to be able to configure the help to come from a different language.

**Feature**

I would like to have the opportunity to set up as an option that I would like to use a different natural language.

**Comment by redborian** [comment]
Thanks for the feedback @remyleone. We will plan on including such a feature in future.
**To everyone**: What languages would you like to be supported?

**Comment by remyleone** [comment]
I would like to have French but would like to understand what data are
scrapped to provide those tooltips. Are they version scopped?

**Comment by redborian** [comment]
They are version scoped. We currently get the schema from https://github.com/garethr/kubernetes-json-schema.

**Comment by remyleone** [comment]
@zacharysarah How could we make it possible for the different translation team to provide localization of those schemas? The benefit would be to have localized documentation for each attributes natively supported inside the editor.

**Comment by kschaab** [comment]
This will be dependent on kubernetes OpenAPI documentation supporting multiple languages.  Is this planned at all @zacharysarah?

**Comment by zacharysarah** [comment]
@kschaab @remyleone That's a better question for the Kubernetes API Machinery SIG. @lavalamp @deads2k

**Comment by lavalamp** [comment]
😰 Uh... yeah...

There's no obvious existing place for this to go.

It would not make sense to put all languages in the OpenAPI spec, it is already quite large.

One could use the schema to assign each english blob a relatively stable identifier and its corresponding english text. Can you make do with that?

"some assembly required"

**Comment by redborian** [comment]
@lavalamp In that case would we need to translate the english blob ourselves offline? Would it be possible for the Kubernetes cluster to surface this at least for popular languages (like French)?

**Comment by lavalamp** [comment]
If you're talking about having the cluster have multiple translations
available for the OpenAPI spec and choosing one based on a e.g. header, no
one's ever really proposed that before.

I'd think that you'd want validation functions to be translated first.

Neither of those would be simple or easy :/

**Comment by kschaab** [comment]
Reassess when k8s supports this in the future.
