### ISSUE TITLE
[K8 Explorer] Organizing the cluster by context names

### ISSUE THREAD

**Issue by andythehood** [GoogleCloudPlatform/cloud-code-vscode#131]
**Use case**
In the Cluster Explorer panel, Cloud Code lists the cluster names from kubeconfig, not the context names. Given that you can have multiple contexts referring to the same cluster, the result is duplicate entry names in this list and it is not immediately obvious to which context each one refers. Also, as users can use 'kubectl config rename-context' to create a more friendly name for the context (esp. for GKE clusters), Cloud Code should display the context name.

**Feature**
If there is a use case for retaining a Cluster-centric view as well, then maybe there should be separate Cluster Explorer and Context Explorer panels.

**Comment by quoctruong** [comment]
@andythehood Currently, if you hover over the cluster, you can see additional info like `user` and `namespace` as well. Is this information not enough for differentiating between the clusters?

**Comment by andythehood** [comment]
It certainly helps, and if nothing else, it would be more helpful if hovering also displayed the context name, along with the user and namespace.

However, i still think that it should show the context name, given that that is the unique key from the kubeconfig and is the friendly name a user may have previously configured, with hovering then displaying the cluster name, user and namespace. 

It does seem that it is using the terms context and cluster interchangeably, e.g. the right-click action is 'Set as Active Cluster' which presumably is mapping onto 'kubectl config use-context'?

**Comment by quoctruong** [comment]
@andythehood Thank you for the feedback. We will investigate and look into how to surface this information better.

**Comment by jmah-cc** [comment]
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-vscode-internal](https://github.com/GoogleCloudPlatform/cloud-code-vscode-internal/issues/1847)

**Comment by jmah-cc** [comment]
@andythehood We revisited this request and we'll be targeting it in our April 2020 release. Thank you for your patience.

**Comment by msgongora** [comment]
Do we have any update here?

**Comment by kschaab** [comment]
Due to some issues it was not in our previous release.  We are actively looking at it.  It will be in our next release.

**Comment by kschaab** [comment]
This is released in Cloud Code 1.4.0

**Comment by msgongora** [comment]
I was expecting a new panel to be honest. k8s context in my mind it's like domains for Ip addresses. I can't remember a website public ip address but I can do it with a nice domain.

I'll need to resize your panel most of the occasions that I'm switching contexts if they are not from same cluster.

Can you see the difference from those 2 screen shoots?
[Using Contexts](https://storage.googleapis.com/dto-monitoring/Screen%20Shot%202020-06-01%20at%206.27.46%20PM.png)

[Using Cluster Name](https://storage.googleapis.com/dto-monitoring/Screen%20Shot%202020-06-01%20at%206.28.06%20PM.png)

**Comment by kschaab** [comment]
I appreciate your feedback and we are discussing this internally.  Just a tip for you, cluster name in kube config is arbitrary in this particular setting, for example I changed my cluster name from GKE's prefixed name to simply foo:

![image](https://user-images.githubusercontent.com/7329029/83472620-9b606400-a43c-11ea-9abd-e817877daac3.png)

Thus you don't necessarily have to overload context to be a name entry to find a server, you can use it to alias a namespace and user as it is intended.

**Comment by msgongora** [comment]
Thanks for the tip, this is useful as long as you don't generate config again using `gcloud container ...` and you are switching between contexts that much in your daily bases, however having been managing k8s since version 1.6 as devops and I have to switch context many times in a regular day. it's more natural for me to use contexts as starting point when I need to do some operations in a cluster. This particularly useful when you have multiple context per clusters. I would say this is the common way to go for most of users not just me. I think this is one the reason why kubectx have became so popular.

**Comment by kschaab** [comment]
Reopening as we will want to do more here.

**Comment by jmah-cc** [comment]
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-vscode-internal](https://github.com/GoogleCloudPlatform/cloud-code-vscode-internal/issues/2875)

**Comment by sivakku** [comment]
The two choices we have about how do we organize the clusters names:
- Either current approach (Cluster as a root and friendly context names as sub-level)
- A flattened approach of context being the top level for user to have friendly names. 
i see pros and cons either side, going to leave this work item in the feature request backlog to see if there is more interest in what way is going to be more useful, to see sufficient votes pop up.

**Comment by jmah-cc** [comment]
At this point we're not planning on making any additional changes here.
