### ISSUE TITLE
Unable to open minikube dashboard - X Error executing status template

### ISSUE THREAD

**Issue by asishrs** [GoogleCloudPlatform/cloud-code-vscode#132]
**Environment**: macOS 10.14.6
*(Hint: "Report Kubernetes Extension Issue on Github" command will fill these out for you.)*
Extension version: 0.0.11
VSCode version: 1.36.1
OS: macOS 10.14.6

**Description**:
Unable to open the `minikube` dashboard via `Open Minikube Dashboard` option Kubernetes Explorer. I am able to see all the namespaces and pods from the minikube default workspace.

**Error message**- 
```
Error getting Minikube status: X Error executing status template: template: status:1:82: executing "status" at <.ApiServer>: can't evaluate field ApiServer in type cmd.Status * Sorry that minikube crashed. If this was unexpected, we would love to hear from you: - https://github.com/kubernetes/minikube/issues/new
```
**Repro step**:

- Install VS Code v1.36.1
- Install plugin v0.0.11 on VS Code
- Install minikube v1.2.0 on VirtualBox v6.0.10
- Open the `minikube` dashboard via `Open Minikube Dashboard`

**Comment by asishrs** [comment]
similar issue is mentioned here https://github.com/GoogleCloudPlatform/cloud-code-vscode/issues/38#issuecomment-490077017 But that is marked as closed.

**Comment by redborian** [comment]
Thanks for reporting this issue @asishrs. This affects the latest version of minikube. We have already fixed this in the upcoming release. I will update this issue once it is released.

**Comment by asishrs** [comment]
Thanks! Happy to beta test if you need help.

**Comment by sujit-kamireddy** [comment]
The fix for this issue is in our latest [release](https://github.com/GoogleCloudPlatform/cloud-code-vscode/releases/tag/v0.0.12). Please update the extension and retry the scenario.

**Comment by asishrs** [comment]
I can confirm this, Thanks! 

Tested on below environment.
```VS Code v1.38.1
Plugin v0.0.12 on VS Code
minikube v1.4.0 on Darwin 10.14.6
VirtualBox v6.0.10```
