### ISSUE TITLE
extensive use of CPU

### ISSUE THREAD

**Issue by bhavani725** [GoogleCloudPlatform/cloud-code-vscode#133]

**Comment by quoctruong** [comment]
@bhavani725 Thank you for using the extension. Can you provide more details on this? For example, what you were doing when you noticed the use of CPU, what platform you were using, how much CPU was used

**Comment by bhavani725** [comment]
@quoctruong I am using ubuntu 18.04, I have noticed in htop this extension and eslint was using one core to 100%. When I uninstall this extension it was back to normal. I just enabled the extension but was not using it.

**Comment by redborian** [comment]
Thanks for reporting the issue @bhavani725. Can you give some more context on what kind of workspace you have open in VS Code? Your system/platform specifications?

**Comment by bhavani725** [comment]
Hi ,

Apologies its the other extention using more cpu "mysql-inline-decorator" .
Well I do not have extention console log for this. I will install
cloud-code extention again and will let you know if any issues and will
share the logs which might help you better.

Anyways I am using Ubuntu 18.04 and vscode 1.37.0 .

Thanks,
Bhavani Prasad

**Comment by quoctruong** [comment]
@bhavani725 Thank you for the update. We’ll close this issue for now but feel free to open another one if you encounter any problems while using the extension again.
