### ISSUE TITLE
Cannot read property 'kind' of null

### ISSUE THREAD

**Issue by ZacharyJoswick** [GoogleCloudPlatform/cloud-code-vscode#137]
**Environment**:
Extension version: 0.0.11
VSCode version: 1.38.1
OS: linux

**Description**:
After deploying an application to our cluster we the error message ```Cannot read property 'kind' of null.``` There does not seem to be any noticeable problems with the deployment or application, however, skaffold never prints out the success message as a result. 

**Repro step**:
I am using the google cloud code extension inside of a docker container through the vscode remote extension. The cluster is accessed using a certificate and is pointed at an ip address. Kubectl seems to be completely fine. Skaffold is at version ```v0.34.1```. Skaffold is configured to push to our internal registry, use buildkit, and use the docker cli. This is reproducible to several different containers.

**Comment by quoctruong** [comment]
@ZacharyJoswick Thank you for reporting the issue. Can you provide a screenshot of the error message?

**Comment by ZacharyJoswick** [comment]
Attached you will find the relevant screenshot

![google_cloud_code_error](https://user-images.githubusercontent.com/5191408/65076556-3d9bf280-d967-11e9-97a2-713261cecf4b.png)

**Comment by quoctruong** [comment]
I see. To know if this is an error from the extension or from skaffold, could you scroll up the Output Panel all the way to the top and retrieve the `skaffold` command that was run? If you try running that command in the terminal, will you get the same error at the end?

**Comment by ZacharyJoswick** [comment]
When I run the command specified in the output window I get the proper output (see attached screenshot). It does appear that whatever is throwing this error is happening after the completion of the skaffold command.
![google_cloud_code_bug_2](https://user-images.githubusercontent.com/5191408/65140004-9a38f500-d9db-11e9-9f3f-e1a2fc9f50f6.png)

**Comment by sujit-kamireddy** [comment]
The fix for this issue is in our latest [release](https://github.com/GoogleCloudPlatform/cloud-code-vscode/releases/tag/v0.0.12). Please update the extension and retry the scenario.

**Comment by ZacharyJoswick** [comment]
After updating the version of the extension in my dev container everything worked as intended and I did not get the error message. Thank you. Marking as closed.
