### ISSUE TITLE
Google App Engine Support

### ISSUE THREAD

**Issue by IsaacLf** [GoogleCloudPlatform/cloud-code-vscode#138]
**Use case**
What are you trying to do that our extension doesn't let you?
I want to deploy an App Engine Standard (Java) application, currently i use a Eclipse IDE (because of the extension "Google Cloud Tools for Eclipse")

**Feature**
What would help?
The support of App Engine to deploy apps to production or locally, as Eclipse's extension mentioned above

**Note:** I got really curious about this, 'cause i just downloaded the extension (Cloud Code) and saw this:
![image](https://user-images.githubusercontent.com/36938997/65623820-3dff4380-df8e-11e9-8063-084258ff478a.png)
![image](https://user-images.githubusercontent.com/36938997/65623849-4c4d5f80-df8e-11e9-8200-3da0d3b79992.png)

So, this could be referenced either as a request or a question of "if is this feature is going to be developed soon?"

**Comment by russwolf** [comment]
Thank you for the feedback, Isaac. 

We are not actively working on developing this feature so we'll take this as a feature request. 

As we look at this in more detail, would it be okay if we reached out to you for you more info?

**Comment by IsaacLf** [comment]
Of course, I'm available to give the info you might need.

I knew it could not be in develop since the extension appear as "beta", but it would be very cool to include more functionality 😃

**Comment by kschaab** [comment]
Tagged for reassessment in the future, closing for now.

**Comment by jthegedus** [comment]
To those finding this issue in the future, as mentioned in the other linked issue, up-voting this will help the team asses whether or not this will be reopened and addressed.
