### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by rpus** [GoogleCloudPlatform/cloud-code-vscode#140]
- Issue Type: `Performance`
- Extension Name: `cloudcode`
- Extension Version: `0.0.12`
- OS Version: `Windows_NT x64 6.1.7601`
- VSCode version: `1.38.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\khankk\googlecloudtools.cloudcode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by rpus** [comment]
Trying again to attach the file...

[googlecloudtools.cloudcode-unresponsive.cpuprofile.txt](https://github.com/GoogleCloudPlatform/cloud-code-vscode/files/3676318/googlecloudtools.cloudcode-unresponsive.cpuprofile.txt)

**Comment by redborian** [comment]
Thank you for reporting the issue @rpus . We have been fixing performance issues with our extensions.
Can you answer a few more questions to help us investigate this issue?
1. How many yaml files does your workspace have? 
1. How large are those files? 
1. How many vscode instances do you have open?  
1. When do you see the CPU spike? Is it during startup time or any specific operation?

**Comment by rpus** [comment]
Hello... The answers are:

  1. zero
  2. (zero)
  3. two
  4. Yes; it was at startup.

But I should add: I was not (subjectively) aware of any CPU spike or delay at all; I only knew there was an issue because VSCode told me! And I have only seen this issue once (on the last time I opened VSCode).

So, please don't take my opening this issue as a complaint; I filed it merely because I thought my auto-generated logs and "problem" notification might help you tune your code (and because it was so conveniently easy to notify you)!

Many thanks for your attention. And thanks for (your work on) the extension!

**Comment by redborian** [comment]
Thanks for the quick turnaround @rpus. We are aware of slow startup times of our extension and actively working on improving it.
I will keep this issue open until all the fixes are merged and a new release has been pushed out.

**Comment by redborian** [comment]
This should be fixed in v0.0.13
