### ISSUE TITLE
Rust support

### ISSUE THREAD

**Issue by onsails** [GoogleCloudPlatform/cloud-code-vscode#141]
**Use case**
I am developing rust applications most of which are cloud-native.

**Feature**
Support of rust language. Is it planned?

**Comment by russwolf** [comment]
Hi there, 

We don't currently have plans for Rust support in Cloud Code. Are there specific Cloud Code features that you would like to see for Rust?

Thanks,
Russell

**Comment by ahmed-masud** [comment]
> I'd be interested in rapid creation of http and grpc hello worlds. With one hello method, OpenAPI specification (in case of HTTP1), Dockerfile template with build caching support (it's tricky but solvable), automatic Knative yaml declaration.
> User should be able to create a fully new project from template or add a new workspace to an existing Cargo project. Would be happy to help.

I would be happy to help in this too.

**Comment by jmah-cc** [comment]
Revisited this again and this is not at the top of our priority list for now. Tagging it for re-assessment in the future.
