### ISSUE TITLE
Custom snippets

### ISSUE THREAD

**Issue by feloy** [GoogleCloudPlatform/cloud-code-vscode#142]
As a developer, I would like to be able to declare new snippets of YAML templates with my own requisites. For example, a specific Deployment template with pre-added environment variables, mounted volume, etc

**Comment by redborian** [comment]
Thanks for the feedback @feloy. VS Code already supports adding snippets (`Preferences: Configure User Snippets` command). Will that be adequate or do you think we need to provide a more robust way?

**Comment by feloy** [comment]
Ok cool.
