### ISSUE TITLE
Change $HOME/cloudcode-projects folder

### ISSUE THREAD

**Issue by JCzz** [GoogleCloudPlatform/cloud-code-vscode#146]
When creating a "New Application" you end up in $HOME/cloudcode-projects

Is it possible to change this folder?

**Comment by sujit-kamireddy** [comment]
It is possible to change this default location. Try creating an application in a different location and you will be prompted to make the new location as the default project creation location.

**Comment by JCzz** [comment]
Thanks @sujit-kamireddy

It worked
