### ISSUE TITLE
Cloud Code is detect only skaffold.yaml and cannot detect skaffold.yml

### ISSUE THREAD

**Issue by dmakeroam** [GoogleCloudPlatform/cloud-code-vscode#148]
**Environment**:
*(Hint: "Report Kubernetes Extension Issue on Github" command will fill these out for you.)*
Extension version: Cloud Code v0.0.12 (2019-09-23)
VSCode version:
Version: 1.39.2
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:33:00.827Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0

**Description**:

I cannot deploy a service with Skaffold using skaffold.yml.

**Repro step**:

1. Initial a service repository which contains skaffold.yml 
2. Deploy the service to Kubernetes using Cloud Code

**Comment by kschaab** [comment]
Thank you for reporting this issue.  Please kindly provide additional information such as the error that is occurring.

**Comment by sujit-kamireddy** [comment]
Hi @dmakeroam , we deprecated the old commands 'Cloud Code: Deploy' and 'Cloud Code: Continuous Deploy' in favor of the new command 'Cloud Code: Run on Kubernetes'. 

This new command guides you to create a run configuration (in .vscode/launch.json), where you can configure any skaffold.yaml file or skaffold profile. 
For more details, please read the [documentation](https://cloud.google.com/code/docs/vscode/running-an-application#customizing_run_configuration).
