### ISSUE TITLE
 fail to save user setting in WSL2

### ISSUE THREAD

**Issue by zoftdev** [GoogleCloudPlatform/cloud-code-vscode#149]
**Environment**: WSL2 on windows 10 Prof.
Extension version: v0.0.13 (2019-11-07)
VSCode version: 1.40.0
OS:   WSL2 on windows 10 Prof.

**Description**:
When using cloud code in WSL2 to create new application.
Extension tries to save setting into windows path and failed.

[Error - 12:42:29 AM] (node:10448) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'c:/Users/hlexj/AppData/Roaming/Code/User/settings.json'

**Comment by redborian** [comment]
Thanks for reporting the issue @zoftdev . We will investigate and fix the issue.

**Comment by quoctruong** [comment]
@zoftdev I am trying to repro the issue. Can I ask how you ran GUI VSCode on WSL?

**Comment by kschaab** [comment]
We have a fix, this will be delivered in our December release.

**Comment by jmah-cc** [comment]
This is fixed in release v1.1.0 @zoftdev
