### ISSUE TITLE
Please add support for multiple aws regions

### ISSUE THREAD

**Issue by ARKKYN** [GoogleCloudPlatform/cloud-code-vscode#150]
**Use case**
What are you trying to do that our extension doesn't let you?
I am trying to create Kubernetes cluster on aws ap-south-1 but only 4 regions are listed 

**Feature**
What would help?
Please add the region

**Comment by redborian** [comment]
Thanks for reporting the issue @ARKKYN. We will fix the issue in the upcoming releases.

**Comment by sivakku** [comment]
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-vscode-internal](https://github.com/GoogleCloudPlatform/cloud-code-vscode-internal/issues/3747)

**Comment by sivakku** [comment]
We are re-visiting our explorer changes so to simplify being able to deploy to AWS cluster in any region.

**Comment by sivakku** [comment]
With June release, the cloud code plugin will deploy to any K8 cluster that is available through kube-config. The cluster creation will re-direct user to AWS/Azure portal that will make it to have all options available for creating any advanced config clusters provided by vendors.
