### ISSUE TITLE
error: current-context is not set

### ISSUE THREAD

**Issue by JCzz** [GoogleCloudPlatform/cloud-code-vscode#151]
**Environment**:
Extension version: 0.0.13
VSCode version: 1.40.0
OS: MacOs Catalina 10.15.1 (19B88)

**Description**:
When deploying any "New Application" I get: `error: current-context is not set`
It comes up as a red text toast message.

**Repro step**:
1. Create a new Application
2. Deploy this new application

Note: I am able to use Skaffold run: `skaffold run --default-repo=gcr.io/<projectid>/cloudcode`

**Comment by redborian** [comment]
Thanks for reporting the issue @JCzz. Can you confirm that you have a current context set? You can find it through "Cloud Code" -> "Kubernetes Explorer" (or) from your `current-context` field in your kubeconfig file.

**Comment by JCzz** [comment]
Thanks @redborian 

It was already set. I then reloaded `~/.kube/config` and now it gets me to building the template app "Go: Hello-World" but with the following error:
`failed to build: build failed: build failed: building [go-hello-world]: extracting projectID from image name: unable to guess GCP projectID from image name [go-hello-world]
`

Full output:
```
Running: skaffold run --enable-rpc -v info --rpc-http-port 50237 --filename skaffold.yaml -p cloudbuild --default-repo gcr.io/<my_google_project_id>
port 50051 for gRPC server already in use: using 50052 instead
starting gRPC server on port 50052
starting gRPC HTTP server on port 50237
Skaffold &{Version:v1.0.0 ConfigVersion:skaffold/v1 GitVersion: GitCommit:decf9f76b69f3a23c102cfccf4c4dba8feba30d0 GitTreeState:clean BuildDate:2019-11-07T18:37:59Z GoVersion:go1.13.4 Compiler:gc Platform:darwin/amd64}
applying profile: cloudbuild
Using kubectl context: <my_context_name>
Generating tags...
 - go-hello-world -> gcr.io/<my_google_project_id>/go-hello-world:latest
Checking cache...
Tags generated in 559.579µs
 - go-hello-world: Not found. Building
Building [go-hello-world]...
Cache check complete in 16.694472ms
failed to build: build failed: build failed: building [go-hello-world]: extracting projectID from image name: unable to guess GCP projectID from image name [go-hello-world]
Application deployment failed/aborted.
```

**Comment by JCzz** [comment]
Hi again @redborian
Ok, I fixed this issue.

1. I had manually installed Skaffold, so I deleted Skaffold
2. Removed ~/.kube and then `gcloud container clusters get-credentials my-cluster`
3. re-installed cloud-code and in the flow I let Cloud-Code install Skaffold

Looking forward to the new flow - this is still the best flow out there, so keep up the good work

**Comment by JCzz** [comment]
Hi again @redborian
Ok, I fixed this issue.

I had manually installed Skaffold, so I deleted Skaffold
Removed ~/.kube and then gcloud container clusters get-credentials my-cluster
re-installed cloud-code and in the flow I let Cloud-Code install Skaffold
Looking forward to the new flow - this is still the best flow out there, so keep up the good work
