### ISSUE TITLE
Logs Viewer is crashing when container logs size is very high

### ISSUE THREAD

**Issue by RamYadlapalli** [GoogleCloudPlatform/cloud-code-vscode#153]
Extension version: 0.0.13
VSCode version: 1.40.0
OS: MAC OS Catalina

**Description**: When my container logs data is more, > 500 MB then logs viewer page is crashing 

**Repro step**:
1. Select a cluster
2. Select a pod under a namespace 
3. Right click on pod and select view logs 
4. Make sure that pod logs size is high
5. Observe Log viewer extension crash 
6. Refer the attached image after the crash 
![image](https://user-images.githubusercontent.com/5554812/68658239-16befe80-055b-11ea-9df2-04cb777052c8.png)

**Comment by quoctruong** [comment]
@RamYadlapalli Thank you for reporting the issue. Can I also ask whether this cluster uses Stackdriver Logging API?

**Comment by quoctruong** [comment]
@RamYadlapalli What do you think if we default to loading logs from the past hour for you? I think this should prevent the Logs Viewer from hanging.

**Comment by RamYadlapalli** [comment]
> @RamYadlapalli What do you think if we default to loading logs from the past hour for you? I think this should prevent the Logs Viewer from hanging.

@quoctruong Yes, that will be the perfect solution, in fact, I wanted to propose the same solution.
Loading the last 1 hour logs by default and let user change the duration.

**Comment by quoctruong** [comment]
@RamYadlapalli We just released a new version of the extension, can you try it out and see whether this fixes it?

**Comment by RamYadlapalli** [comment]
@quoctruong Perfect, it's working smooth. Thanks for this extension, it makes working with Kubernetes so easy.
