### ISSUE TITLE
cannot view pod logs

### ISSUE THREAD

**Issue by KimMJ** [GoogleCloudPlatform/cloud-code-vscode#155]
**Environment**:
*(Hint: "Report Kubernetes Extension Issue on Github" command will fill these out for you.)*
Extension version: 0.0.12, 0.0.13
VSCode version: 1.40.0
OS: Windows

**Description**:
Hi. I'm using cloud code with remote-ssh.
When I try to view pods' logs with cloud code in 0.0.12, it ask me which container I want.
But after I clicked container name, it said

```
Error running command cloudcode.viewKubectlLog: Error from server (NotFound): pods "spin-clouddriver-86dc69d468-smqb6" not found
. This is likely caused by the extension that contributes cloudcode.viewKubectlLog.
```

like this.
It occurred in new version too. When I clicked view logs in pod or container, it shows error something like 

```
Error from server (NotFound): pods "spin-clouddriver-75f7f79d86-bgp8d" not found
```

I found that open logs viewer in new version and select deployment and container (not pod), it is okay but when I specify pod, it occurs that error.

**Repro step**:
right click on any pod -> view logs

**Comment by quoctruong** [comment]
Hi @KimMJ, can you provide a screenshot? Also, can you give me the output of `kubectl get pod spin-clouddriver-86dc69d468-smqb6`? Thanks!

**Comment by KimMJ** [comment]
for v0.0.12 with local vscode and `kubectl` (not `remote-ssh`)
![image](https://user-images.githubusercontent.com/6358016/68817158-2574f500-06c4-11ea-9b3d-0dd20d5fd3c0.png)
![image](https://user-images.githubusercontent.com/6358016/68817180-332a7a80-06c4-11ea-9d21-477f04e3dfe9.png)
but
![image](https://user-images.githubusercontent.com/6358016/68817234-68cf6380-06c4-11ea-8b52-95c55c62694c.png)
and
![image](https://user-images.githubusercontent.com/6358016/68817253-74bb2580-06c4-11ea-85f1-2b07e0b971de.png)
this error is not a problem cause it's a `kubectl`'s normal behavior.
![image](https://user-images.githubusercontent.com/6358016/68817258-7e448d80-06c4-11ea-900d-06b05df8f10a.png)
I can get logs with `kubectl`
If clicked specific container and view logs, it works
![image](https://user-images.githubusercontent.com/6358016/68817430-0b87e200-06c5-11ea-856c-1ccafff4709b.png)
![image](https://user-images.githubusercontent.com/6358016/68817437-12aef000-06c5-11ea-8c69-796c1db8dde4.png)

There is no difference between local and `remote-ssh`

For v0.0.13
![image](https://user-images.githubusercontent.com/6358016/68817499-3a05bd00-06c5-11ea-9108-a130d113b5e8.png)
![image](https://user-images.githubusercontent.com/6358016/68817509-42f68e80-06c5-11ea-82f5-5ec398d15d60.png)
logs viewer fell into infinite loop. 
![image](https://user-images.githubusercontent.com/6358016/68817611-8fda6500-06c5-11ea-9521-0be7d5a52901.png)
if I clicked on containers
![image](https://user-images.githubusercontent.com/6358016/68817638-9ec11780-06c5-11ea-8a05-630385faff8a.png)
again, it is not over.
If I open Logs Viewer with command palette and chose something like this,
![image](https://user-images.githubusercontent.com/6358016/68817766-1d1db980-06c6-11ea-88ed-d8a3b1279331.png)
it said there is no pod.
![image](https://user-images.githubusercontent.com/6358016/68817777-24dd5e00-06c6-11ea-9031-d22776525d6b.png)
but there it is.
and if I chose container "redis", same error occurred.
![image](https://user-images.githubusercontent.com/6358016/68817798-3888c480-06c6-11ea-9ea6-2352abeaf2e6.png)
but with `kubectl`, I could get logs
![image](https://user-images.githubusercontent.com/6358016/68817846-55bd9300-06c6-11ea-9c96-3050827cdbab.png)
I selected StatefulSet but for Deployment, it is same.

Is there any known issue about proxy environment?

Thx.

**Comment by quoctruong** [comment]
Thank you for the detail screenshots @KimMJ, this is most likely a bug in our code for handling pod with multiple containers. Does it work for you if the pod only has 1 container?

**Comment by redborian** [comment]
Also, @KimMJ do you a use proxy environment? If so, can you check if GKE tree view shows the right projects?

**Comment by KimMJ** [comment]
@quoctruong 
It doesn't work with the pod has 1 container..
@redborian 
I don't use GKE cluster. It's an onprem Kubernetes. 
\+ `gcloud` is already installed.

**Comment by quoctruong** [comment]
@KimMJ We have a bug where viewing logs from a different namespace would not work. A fix will be coming out in the next release.

**Comment by quoctruong** [comment]
@KimMJ We just released a new version of the extension, can you try it out and see whether this fixes the bug?

**Comment by KimMJ** [comment]
@quoctruong Thanks! It is fixed.
