### ISSUE TITLE
Use Ingress when having more LoadBalancer

### ISSUE THREAD

**Issue by JCzz** [GoogleCloudPlatform/cloud-code-vscode#156]
When having multiple application is it possible to use Ingress in between a LoadBalancer?

**Comment by redborian** [comment]
Thanks for the feedback @JCzz. Is this feedback about how the built-in samples have been written? If so, please open an issue here: https://github.com/GoogleCloudPlatform/cloud-code-samples/issues. If not, can you give more context into how Cloud Code can help with your use-case?

**Comment by JCzz** [comment]
Thanks @redborian

Nope, it is more on how you deploy to Kubernetes and keep the Cloud-Code gRPC debugger working, if possible to use an Ingress in between a "Google" LoadBalancer.

I would like to share LoadBalancers as you pay for each LoadBalancer.

**Comment by redborian** [comment]
Thanks for the reply @JCzz. For deployments, you should be able to configure your services to use your own LoadBalancer. For debugging, we attach to the pod using port-forwarding as LoadBalancer hits a different node each time. Do you have any specific user-journeys that Cloud Code can assist with?

**Comment by jmah-cc** [comment]
Closing as a part of backlog clean up. @JCzz If you're still seeing this issue, please re-open, with a reply to @redborian 's question above.
