### ISSUE TITLE
Browse Daemonsets and Horizontal Pod Autoscaler resources

### ISSUE THREAD

**Issue by marcfong** [GoogleCloudPlatform/cloud-code-vscode#157]
**Use case**
I am trying to browse details of daemonsets and HPAs installed in my cluster via the Cloud Code GUI. These are not available today.

**Feature**
What would help?
Add daemonsets and HPA to the GUI

**Comment by jmah-cc** [comment]
After reviewing this request again, it's not at the top of our prioritized list. Adding it to backlog and keeping the issue open so other users can upvote this.

**Comment by kschaab** [comment]
Closing as this is very stale and hasn't received in upvotes.  We definitely want to reassess this as we have time, tagging.
