### ISSUE TITLE
Unable to edit Ingress objects

### ISSUE THREAD

**Issue by marcfong** [GoogleCloudPlatform/cloud-code-vscode#158]
**Environment**:
Extension version: 0.0.13
VSCode version: 1.39.2
OS: darwin

**Description**:
The little pencil icon does not appear for ingress objects and I cannot view nor edit the YAML
**Repro step**:

**Comment by redborian** [comment]
Thanks for the feedback @marcfong. I have merged a fix for this and will be part of next release.

**Comment by redborian** [comment]
This is fixed in the latest release (`v1.0.0`)
