### ISSUE TITLE
Option to add a permanent environment var

### ISSUE THREAD

**Issue by comino** [GoogleCloudPlatform/cloud-code-vscode#160]
**Use case**
I need to inject my SSH credentials into the docker build process in order for the docker build to fetch private repositories. I currently do this with skaffolds buildEnv configuration which lets you inject certain environment variables as a docker "buildVar". 

Any secret hardcoded in skaffold.yaml would likely end up in the repository. 

**Feature**
I would like to have an option to permanently add a (secret) Environment Variable for all Cloud Code scripts being parsed on to Skaffold. 

Of course, I would also be happy with a more elegant idea to solve this. 

Edit: 

just saw, there is a option for that in the references: 
https://cloud.google.com/code/docs/vscode/reference

"Add Secret as Environment Variable"

But cant find the script in the command explorer in vscode

Edit2:

Executing "Add Secret as Environment Variable" manually just throws "Cannot read property 'kubeObject' of undefined"

**Comment by quoctruong** [comment]
@comino The "Add Secret as Environment Variable" will just add a Kubernetes Secret Object to an existing deployment or pod. What's happening behind the scene is that we are simply adding a secret field to the YAML of the deployment or pod and then apply it. So I don't think that is what you are looking for?

**Comment by jmah-cc** [comment]
Cloud Code v1.0.1 has a fix for "Executing "Add Secret as Environment Variable" manually just throws "Cannot read property 'kubeObject' of undefined"

@comino Will Kustomize work for you here?

**Comment by jmah-cc** [comment]
@comino We have not heard back from you on this so closing the issue. Please let us know if Kustomize works for you in this case.
