### ISSUE TITLE
stackdriver logs are visually overlapping the logs header.

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/cloud-code-vscode#163]
**Environment**:
Extension version: 1.0.1
VSCode version: 1.40.2
OS: darwin

**Description**:
When I open logs from a k8s pod the logs view header floats under the log messages when I scroll.
![image](https://user-images.githubusercontent.com/7862557/69667099-586f9f00-105b-11ea-9203-d5edbbcf7f45.png)

**Comment by kschaab** [comment]
Thank you for reporting this issue.  We will be looking into fixing this.

**Comment by jmah-cc** [comment]
This has been fixed in the latest release (v1.1.0) @patflynn
