### ISSUE TITLE
Support for AlibabaCloud 

### ISSUE THREAD

**Issue by PolGuixe** [GoogleCloudPlatform/cloud-code-vscode#164]
**Use case**
Access Alibaba's Cloud Kubernetes using the this package

**Feature**
Support for Alibaba's Cloud Kubernetes

**Comment by kschaab** [comment]
Thank you for using Cloud Code for VS Code.  We currently support AlibabaCloud in a limited fashion through the Kubernetes Explorer as well as Skaffold deploy.  Would you mind elaborating what you are looking to do that is not supported?

**Comment by PolGuixe** [comment]
@kschaab thanks for your prompt reply. I am new to Kubernetes and I am doing an integration with a cluster provided by Alibaba. 

Right now I don't have any particular issue. As I work with it I'll be posting them here.

**Comment by kschaab** [comment]
Sounds great, looking forward to your feedback.
