### ISSUE TITLE
Refusal to deploy

### ISSUE THREAD

**Issue by fabltd** [GoogleCloudPlatform/cloud-code-vscode#165]
**Environment**:
Extension version: 1.0.1
VSCode version: 1.40.2
OS: 10.15.1

**Description**:

Cannot deploy to K8S.

Log is as follows: ( Project Name changed to XXXXXX)

Running: skaffold run --enable-rpc -v info --rpc-http-port 52196 --filename skaffold.yaml --default-repo gcr.io/XXXXXXX
port 50051 for gRPC server already in use: using 50053 instead
starting gRPC server on port 50053
Using kubectl context: gke_XXXXXX_europe-west1-b_prod

**Repro step**:

Try to deploy the Quick Start as per instructions but fails.

**Comment by redborian** [comment]
Thanks for reporting the issue @fabltd. Is it an intermittent issue or can you repro this consistently? What is the version of your skaffold CLI?

**Comment by jmah-cc** [comment]
@fabltd We have not heard back from you on this. Closing this issue for now. If you encounter this again, please re-ope the bug with the details redborian asked for above.
