### ISSUE TITLE
Cloud Code crashes application host when there is no network connectivity

### ISSUE THREAD

**Issue by kschaab** [GoogleCloudPlatform/cloud-code-vscode#170]
Extension version: 1.0.1
VSCode version:
Version: 1.40.1
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:49:30.162Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0

OS:  Windows 10

Application host crashes with Cloud Code loaded when there is no network connectivity

Run cloud code in VS Code and disconnect the network.  The extension host process will terminate.

**Comment by sujit-kamireddy** [comment]
I couldn't repro this issue. I tried cloud code new application, deploy commands and also browsing the kubernetes explorer, I got error messages in all the cases and the extension/host didn't crash.

**Comment by jmah-cc** [comment]
@kschaab Please re-open if you see this issue again
