### ISSUE TITLE
windows/wsl: can't create sample application

### ISSUE THREAD

**Issue by remoe** [GoogleCloudPlatform/cloud-code-vscode#171]
**Environment**:
Extension version: 1.0.1
VSCode version: 1.40.2
OS: windows / wsl

**Description**:

can't create sample applications. Nothing logged on "Cloud Code" logger.

**Repro step**:

- call "Cloud Code: New Application"
- accept the default path like "/home/user/cloudcode-projects/nodejs-guestbook-1"
- press ```<enter>```
- nothing happens

**Comment by redborian** [comment]
Thanks for your feedback @remoe. We will investigate and fix this issue right away.

**Comment by redborian** [comment]
This has been fixed already and will be part of the next release.

**Comment by jmah-cc** [comment]
This is fixed in the latest release @remoe
