### ISSUE TITLE
Support jsonPayload

### ISSUE THREAD

**Issue by barthuijgen** [GoogleCloudPlatform/cloud-code-vscode#172]
**Environment**:
Extension version: 1.0.1
VSCode version: 1.40.2
OS: darwin

**Description**:
log lines that use jsonPayload instead of textPayload do not show up at all

Our applications rely heavily on using jsonPayload instead of textPayload and our logs viewed by the Cloud Code extensions are only showing dates and nothing else, this extension looks amazing but that one small oversight really renders it completely useless for my use case.

**Repro step**:
- Log a JSON string from your kubernetes pod
- stackdriver turns it into a jsonPayload
- use Cloud Code to view the log
- "message" column is empty

**Comment by redborian** [comment]
Thanks for reporting this issue @barthuijgen. Can you attach a screenshot of your logs viewer? In the meantime, we will fix the underlying issue in the next release.

**Comment by znorris** [comment]
I believe I'm impacted by this same case. The top two log entries are expanded as much as possible.

<img width="1281" alt="Screen Shot 2019-12-10 at 11 17 10" src="https://user-images.githubusercontent.com/995047/70561224-ec9f3300-1b3e-11ea-9dd3-6d728c110250.png">

**Comment by barthuijgen** [comment]
Thanks @znorris that is indeed exactly the same as it looks like for me, in some cases I have some log lines mixed in that contain a textPayload, they do show up as expected. 

![Screenshot 2019-12-11 at 08 23 23](https://user-images.githubusercontent.com/45095973/70600268-99d18400-1bef-11ea-9b83-618b798f1084.png)

top two lines as seen in google cloud console

![Screenshot 2019-12-11 at 08 25 59](https://user-images.githubusercontent.com/45095973/70600512-2714d880-1bf0-11ea-824a-d5f8e9fb666e.png)

**Comment by pongad** [comment]
Closed by https://github.com/GoogleCloudPlatform/cloud-code-vscode-internal/pull/1688
