### ISSUE TITLE
prevent aggressive output panel opening

### ISSUE THREAD

**Issue by stefanomiccoli** [GoogleCloudPlatform/cloud-code-vscode#176]
**Use case**
when in continuos deployment is on, any output from containers will automatically open the output panel if not in focus already.
It is really frustrating to be continuously pushed in the output panel, especially when wip services are writing output periodically (ping, polling etc). 

Looking at vscode issues it is something that pops up periodically, last time few hours ago. Besides the fact that I think there should be a general flag to disable the behaviour for any extension, they suggest to talk to the extension developer to comply with their apis.
https://github.com/microsoft/vscode/issues/87331

**Feature**
it should be possible to configure cloudcode settings to prevent autofocus of the output panel

**Comment by kschaab** [comment]
Thanks for your feedback Stefan.  This is something that we need to address as you rightly point out.

**Comment by GavinOsborn** [comment]
+1 This is quite frustrating.
And made even worse by #198

**Comment by sujit-kamireddy** [comment]
@stefanomiccoli , @GavinOsborn ,
The fix is coming in the next release.

With the fix, output panel will be opened only once, at the start of the deployment.

**Comment by GavinOsborn** [comment]
That's great, thanks!

**Comment by GavinOsborn** [comment]
Hey @sujit-kamireddy just checking - you mean in 1.1.3?
There's something similar in the 1.1.2 release notes but I don't think that's it.

**Comment by sujit-kamireddy** [comment]
@GavinOsborn , it ll be in either 1.1.3 or 1.2

**Comment by sujit-kamireddy** [comment]
@stefanomiccoli , @GavinOsborn , This has been fixed in the latest release (1.2).
