### ISSUE TITLE
More options in the Kubernetes explorer right click to create resource using template

### ISSUE THREAD

**Issue by remyleone** [GoogleCloudPlatform/cloud-code-vscode#178]
**Use case**

I would like to add a given resource. Let's say a config map. If I'm looking at the Kubernetes explorer and doing a right-click on Namespace/Default/Config Maps and I right-click on that I just got a refresh option. I would like to have the option to add this resource from a right click and have a template showing up ready to be edited.

**Feature**

Having a New option in the right-click that pops up a new template for editing a ConfigMap in this particular example would be useful. This could also be added to the Visual studio code menu (at least for all base resources). I would like to type in this menu "add config map" and the same default template pops up ready to be edited.

**Comment by redborian** [comment]
Thanks for the valuable feedback @remyleone. We will add this to our future road map and update on the progress further.

**Comment by jmah-cc** [comment]
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-intellij-internal](https://github.com/GoogleCloudPlatform/cloud-code-intellij-internal/issues/3166)

**Comment by jmah-cc** [comment]
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-vscode-internal](https://github.com/GoogleCloudPlatform/cloud-code-vscode-internal/issues/3757)

**Comment by jmah-cc** [comment]
We're looking to improve options in the explorer, in general, but at this point in time we don't have any explicit plans to make this specific change.

**Comment by jmah-cc** [comment]
Re-opening as it seems to line up with the investigation we're doing on explorer improvements in general

**Comment by kschaab** [comment]
We continue to track this on our backlog but don't have plans to do this work.
