### ISSUE TITLE
Unable to load schema from 'k8s://schema/v1

### ISSUE THREAD

**Issue by bwnyasse** [GoogleCloudPlatform/cloud-code-vscode#179]
**Environment**:
*(Hint: "Report Kubernetes Extension Issue on Github" command will fill these out for you.)*
Extension version: 1.0.1
VSCode version: 1.41.1
OS: MacOS 10.14.6

**Description**:
All my k8s resources show linting errors in the first character despite them being valid.
For example the simplest pod definition has an error:

<img width="387" alt="Capture d’écran 2019-12-27 à 18 29 18" src="https://user-images.githubusercontent.com/5323628/71526390-e814a180-28d6-11ea-8133-34868a569288.png">

```
# error (red underline in first character)
Unable to load schema from 'k8s://schema/v1@Pod': 
```

**Repro step**:

Happened after installing cloud code. 
I have [kubernetes extension](https://marketplace.visualstudio.com/items?itemName=ms-kubernetes-tools.vscode-kubernetes-tools) installed. I have the problem only if I install cloud code.

**List of vscode extensions**

```
➜ code --list-extensions
aaron-bond.better-comments
alefragnani.project-manager
batisteo.vscode-django
CoenraadS.bracket-pair-colorizer
Dart-Code.dart-code
Dart-Code.flutter
donjayamanne.python-extension-pack
eamodio.gitlens
evilz.vscode-reveal
foxundermoon.shell-format
googlecloudtools.cloudcode
Gruntfuggly.todo-tree
magicstack.MagicPython
ms-azuretools.vscode-docker
ms-kubernetes-tools.vscode-kubernetes-tools
ms-python.python
Nash.awesome-flutter-snippets
nrwl.angular-console
PKief.material-icon-theme
redhat.java
redhat.vscode-xml
redhat.vscode-yaml
Remisa.shellman
VisualStudioExptTeam.vscodeintellicode
vscjava.vscode-java-debug
vscjava.vscode-java-dependency
vscjava.vscode-java-pack
vscjava.vscode-java-test
vscjava.vscode-maven
vscode-icons-team.vscode-icons
vsls-contrib.gistfs
wholroyd.jinja
wwm.better-align
xaver.clang-format
zxh404.vscode-proto3
```

**Comment by redborian** [comment]
Thanks for reporting the issue @bwnyasse.
Can you add this to your VS Code settings: ` "cloudcode.yaml.trace.server": "verbose",` and collect logs from your `Cloud Code Yaml Support` output stream?

**Comment by bwnyasse** [comment]
Hello @redborian  , thanks you for the reply.  In attachment is the output stream while opening the related `simple-pod.yaml` file :

[simple-pod.yml.txt](https://github.com/GoogleCloudPlatform/cloud-code-vscode/files/4009439/simple-pod.yml.txt)

**Comment by redborian** [comment]
Thanks for the log file, @bwnyasse. We will investigate and fix the issue in the upcoming releases.

**Comment by jmah-cc** [comment]
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-vscode-internal](https://github.com/GoogleCloudPlatform/cloud-code-vscode-internal/issues/1844)

**Comment by jmah-cc** [comment]
Hi @bwnyasse, we were unable to repro this issue. If you're still seeing this issue, please re-open and let us know

**Comment by agabhinav** [comment]
I've the same problem as well even when kubernetes extension is not installed.
![vscodecloudcodeerr](https://user-images.githubusercontent.com/24555566/91194401-b9e19e80-e6bd-11ea-9a3d-869464086e45.png)

**Comment by amitlevy21** [comment]
having the same issue when try to create a namespace 
![image](https://user-images.githubusercontent.com/28672915/103411666-d9139f80-4b79-11eb-884c-230e6e0b9ffc.png)

**Comment by Intelrunner** [comment]
This is still ongoing in 2022:

Version: 1.68.1
Commit: 30d9c6cd9483b2cc586687151bcbcd635f373630
Date: 2022-06-14T12:52:13.188Z
Electron: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin x64 21.5.0

<img width="853" alt="image" src="https://user-images.githubusercontent.com/22569319/174485597-983b3753-f709-4ae2-bd87-25d7d3b13527.png">
