### ISSUE TITLE
Flag --export has been deprecated

### ISSUE THREAD

**Issue by remyleone** [GoogleCloudPlatform/cloud-code-vscode#181]
**Environment**:
Extension version: 1.0.1
VSCode version: 1.41.1
OS: linux

**Description**:

I often get a vscode notification like: 

`Flag --export has been deprecated, This flag is deprecated and will be removed in future.`

**Repro step**:

Apply changes on a resource such as a Deployment

**Comment by remyleone** [comment]
Can a deployment be modified several time in a row? I try to change the number of replicas from 3 to 4, save and apply and then move it again from 4 to 3 and it doesn't seem to work. Is there an automatic refresh triggered on the sidebar when you modify a given resource ?

**Comment by quoctruong** [comment]
@remyleone You should be able to modify it. Once the changes are applied, the browser should refresh to update the number of replicas in the pods.

**Comment by remyleone** [comment]
Where can I modify the command that uses flag `--export`?

**Comment by quoctruong** [comment]
The command that uses the flag `--export` is the one that shows the "exported" version of the YAML (used when you click on `Edit YAML` button). It is more or less a warning and shouldn't have any effect.

**Comment by jmah-cc** [comment]
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-vscode-internal](https://github.com/GoogleCloudPlatform/cloud-code-vscode-internal/issues/1843)

**Comment by redborian** [comment]
This should be fixed in the latest version of Cloud Code (v1.2.0). Feel free to reopen this issue if you still see the issue.
