### ISSUE TITLE
Add a dependency check option

### ISSUE THREAD

**Issue by remyleone** [GoogleCloudPlatform/cloud-code-vscode#185]
**Environment**:
Extension version: 1.0.1
VSCode version: 1.41.1
OS: linux

**Description**:

cloud code uses several external dependencies such as skaffold, gcloud, and potentially several other tools for various purposes. All those tools are not fully managed by cloud-code and can potentially be present or not on the user machine with an unexpected version. 

It would be a good idea to have a page/option that checks all the required dependencies and provide helpful guidance about what are the requirements (a minimal version of a given tool required) and how to install them.

**Comment by jmah-cc** [comment]
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-vscode-internal](https://github.com/GoogleCloudPlatform/cloud-code-vscode-internal/issues/1841)

**Comment by sivakku** [comment]
Cloud Code now has the auto dependencies turned on by default and installs necessary deps(like gcloud, skaffold, ...) except docker.  Please re-open if that doesn't cover the deps managment issue you have run in to.
