### ISSUE TITLE
Add support for deleting a deployment profile

### ISSUE THREAD

**Issue by remyleone** [GoogleCloudPlatform/cloud-code-vscode#186]
**Environment**:
Extension version: 1.0.1
VSCode version: 1.41.1
OS: linux

**Description**:

When I get inside the deployment Profile Wizard, there is no way to delete an existing profile. Could you add a way to delete one?

**Comment by jmah-cc** [comment]
We're working on a new workflow that should resolve this. Let us get back to you once that workflow is available.

**Comment by jmah-cc** [comment]
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-vscode-internal](https://github.com/GoogleCloudPlatform/cloud-code-vscode-internal/issues/1754)

**Comment by jmah-cc** [comment]
We are deprecating the commands '_Cloud Code: Deploy'_ and '_Cloud Code: Continuous Deploy'_ commands in favor of a single '_Cloud Code: Run on Kubernetes'_ command (available in the latest release), which doesn't show the Deployment Wizard. You can edit the profile information using the skaffold.yaml IntelliSense @remyleone
