### ISSUE TITLE
Add a command in the command palette to scale a deployment quickly

### ISSUE THREAD

**Issue by remyleone** [GoogleCloudPlatform/cloud-code-vscode#188]
**Environment**:
Extension version: 1.0.1
VSCode version: 1.41.1
OS: linux

**Description**:

To perform a scaling operation at the moment, I look for the deployment in the Kubernetes explorer, find a deployment, open this deployment for editing, look for the `.spec.replicas` field, and edit the value I want.

Could it be possible to have a command palette command so that I just have to type, "scale" the name of the deployment and then the editor opens automatically the edition with my cursor selecting the number of replicas so that I can edit it directly?

**Comment by jmah-cc** [comment]
Revisited this again and this is not at the top of our priority list for now. Tagging it for re-assessment in the future.
