### ISSUE TITLE
Add a secret snippet

### ISSUE THREAD

**Issue by remyleone** [GoogleCloudPlatform/cloud-code-vscode#189]
**Environment**:
Extension version: 1.0.1
VSCode version: 1.41.1
OS: linux

**Description**:

Could you add a Secret snippet to the snippets provided by cloud code?

**Comment by redborian** [comment]
Thanks for your feedback @remyleone. This has been added and will be part of the next release.

**Comment by jmah-cc** [comment]
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-vscode-internal](https://github.com/GoogleCloudPlatform/cloud-code-vscode-internal/issues/1753)

**Comment by jmah-cc** [comment]
This functionality has been added to the latest release (v1.1.0) @remyleone
