### ISSUE TITLE
Official support for Deployment Manager templates?

### ISSUE THREAD

**Issue by red8888** [GoogleCloudPlatform/cloud-code-vscode#190]
The AWS Toolkit for VS code has official support for Cloudformation templates. Will I get the same level of IDE features for Deployment Manager templates? Deployment Manager is different than cloudformation in that its less of a DSL and more just a python library you import, but there are a lot of DM specifics I really want IDE support for to make writing templates easier.

Features like:
- autocomplete for the supported "types" (like gcp-types/cloudfunctions-v1:projects.locations.functions, etc)
- auto complete supported "properties:" for a type (this I believe is what the cloudformation template feature of aws toolkit does). This is super valuable and could save soooo much time
- Throw a warning/error if my .schema files are wrong or missing references

There is probably a lot more that would be valuable I'm missing here too. Just want to know if this is on the roadmap

**Comment by jmah-cc** [comment]
Revisited this again and this is not at the top of our priority list for now. Tagging it for re-assessment in the future.
