### ISSUE TITLE
Request initialize failed with message: ENOENT

### ISSUE THREAD

**Issue by JCzz** [GoogleCloudPlatform/cloud-code-vscode#197]
VSCode: Version 1.41.1
CloudCode: Version 1.01

In VSCode there is a red TOAST message coming up saying:
`Request initialize failed with message: ENOENT: no such file or directory, open '<localpath>/triggers/vendor/github.com/tektoncd/pipeline/config/300-imagecache.yaml'`

And it says: source: Cloud Code (Extension)

The file and path, I guess, has no relevance  - but where is this call coming from.

**Comment by jmah-cc** [comment]
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-vscode-internal](https://github.com/GoogleCloudPlatform/cloud-code-vscode-internal/issues/1752)

**Comment by jmah-cc** [comment]
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-vscode-internal](https://github.com/GoogleCloudPlatform/cloud-code-vscode-internal/issues/1803)

**Comment by redborian** [comment]
This should be fixed in the latest version of Cloud Code (v1.2.0). Feel free to reopen this issue if you still see the issue.
