### ISSUE TITLE
Run in Kubernetes: Cant disable the watch

### ISSUE THREAD

**Issue by GavinOsborn** [GoogleCloudPlatform/cloud-code-vscode#198]
**Environment**:
Extension version: 1.1.0
VSCode version: 1.41.1
OS: win32

**Description**:
The default configuration for "Run in Kubernetes" includes a watcher for continuous deploy.
When I use this command VS code pops up a debug window that includes a stop button.

**Repro step**:
Open Skaffold Enabled VSCode project
Run the command "Run in Kubernetes"
Observe that it will successfuly build and deploy your application.
Subsequent changes will cause a hot-reload of your code

*Expected*: Clicking on the stop icon (red square) not only stops the session but also kills any watch that might be in place.

*Actual*: While clicking on stop does kill the active debug session it does not kill the watch meaning any further changes will prompt a new build and deploy.

An equally good alternative solution would be to re-instate the "Stop" command.

**Comment by sujit-kamireddy** [comment]
@GavinOsborn , Have you turned off the watch flag in launch.json and tried the "Run on Kubernetes" command?

If the watch flag is off, it should not re-deploy the application.

**Comment by sujit-kamireddy** [comment]
@GavinOsborn , I could not repro this issue. When I click on the stop button, it stops the session and watcher. Would you mind sharing a gif of the issue you are encountering?

**Comment by GavinOsborn** [comment]
Hey @sujit-kamireddy,

I'd be happy to.

In the meantime, some things that may help:
 - I'm running on Windows.
 - I don't want to disable continuous deploy, I just want it to stop once I end the session.
 - I haven't tried using the launch.json version - I'm just using the 'Run on Kubernetes' command in the command pallet.

**Comment by GavinOsborn** [comment]
As requested :)
![badreload](https://user-images.githubusercontent.com/581588/73700276-3d479c80-473a-11ea-9835-dbc86bcaf4d9.gif)

**Comment by sujit-kamireddy** [comment]
Thanks @GavinOsborn. It indeed is a bug, but seems to be happening only in certain scenarios. Did you install skaffold through chocolatey?

**Comment by GavinOsborn** [comment]
Sure did. I installed the whole tool chain through choco.

**Comment by GavinOsborn** [comment]
(except cloud code which I installed through vscode)

**Comment by sujit-kamireddy** [comment]
@GavinOsborn , thanks a lot for filing this issue. We released a patch (v1.1.1) which should fix this issue along with bringing back Cloud Code: Deploy and Cloud Code: Continuous Deploy functionality.

Please try it out and let us know if you find any issues.

**Comment by GavinOsborn** [comment]
Thanks Sujit. Will test it out today and get back to you.

**Comment by GavinOsborn** [comment]
Hey Sujit, just to confirm I can no longer replicate the issue. 👍

**Comment by sujit-kamireddy** [comment]
That's great to know. Thanks for verifying Gavin.
