### ISSUE TITLE
Breaking Changes: Consider better stage management

### ISSUE THREAD

**Issue by GavinOsborn** [GoogleCloudPlatform/cloud-code-vscode#199]
For your consideration:

Cloud Code 1.1 deprecated several significant commands (Deploy, Continuous Deploy, Stop, et al) that your users have come to depend upon to do their day job. Whilst I **fully** support your right to innovate on your features I just wonder if it could have been stage managed a bit better.

The company I work for employ ~80 developers who are adopting or have already adopted Cloud Code. These developers rely on Cloud Code to power the developer workflow 8 hours a day, 5 days a week.

As a rule VS Code keeps your extensions ever green, adopting new versions. This means when you ship the kind of changes you shipped in 1.1 entire departments of developers have to:
 - Learn how to use the new feature set before they can continue being productive
 - Disable updates which I'd argue is equally undesirable

I feel it would have been preferable to ship these changes over multiple release:

1. Introduce _Run on Kubernetes_ in the first release while renaming _Deploy_, _Continuous Deploy_ and _Stop_ to <x> [Deprecated]_. The deprecated commands would still work as before but developers would be alerted that something is happening.

2. Remove the deprecated commands in this second release (a month later?) after the teams have been given the opportunity to transition to Run on Kubernetes in their own time.

Both releases could have relevant Changelog updates to guide developers about what is going on.

**Comment by vsubramani** [comment]
Gavin, thank you for bringing this our attention. Your suggestion makes sense. We're working on a patch. 

In the meantime, as a workaround, you can rollback to the previous version of the Cloud Code plugin. You can do this by going to the Extensions panel, selecting the settings button next to Cloud Code, and selecting 'Install Another Version...' and selecting the 1.0.1 version.

Once we roll out a patch with the functionality that you were suggestion, we'll notify you and you can upgrade to the latest version to get the latest additions.

**Comment by GavinOsborn** [comment]
Thanks @vsubramani, I appreciate the rapid turn around.

**Comment by vsubramani** [comment]
@GavinOsborn, we just released a patch version 1.1.1. In this we have both the old functionality (Deploy, Continuous Deploy etc.) along with new one (Run on Kubernetes). 

We'll follow your suggestion to phase out the older functionality over a few releases. Thanks for the suggestion.

Hope this works for you and your org.

**Comment by GavinOsborn** [comment]
👍

**Comment by sujit-kamireddy** [comment]
@GavinOsborn , can you confirm that you were able to use the old commands (Deploy, Continuous Deploy)?

**Comment by GavinOsborn** [comment]
Confirmed, and thanks.

We will look at migrating over to new commands shortly 🙂

**Comment by sujit-kamireddy** [comment]
Great. Thanks @GavinOsborn . 

Please file any issues/feedback with the new command.
