### ISSUE TITLE
Kubernetes Explorer - Unable to view logs when missing "list namespaces"-permission

### ISSUE THREAD

**Issue by mlamm** [GoogleCloudPlatform/cloud-code-vscode#201]
**Environment**:
Extension version: 1.1.0
VSCode version: 1.41.1
OS: Linux x64 5.4.15-arch1-1

**Description**:
When I right-click a container or pod and select "view logs" the Logs-Viewer is in a never-ending "Loading..."-cycle.
I am accessing a quite well restricted k8s-cluster, missing rights to list namespaces. But being able to list pods, and see containers logs, I can access the information I am trying to view through the Logs-Viewer by command-line.
So, this is probably caused by:
```
Cannot list namespaces: Error from server (Forbidden): namespaces is forbidden: User "xxx" cannot list resource "namespaces" in API group "" at the cluster scope
. The Kubernetes Explorer will use the lalalala namespace.
```

**Repro step**:
1) Open up Kubernetes Explorer
2) unfold cluster in navigation
3) Notice error-message-poup "Cannot list namespaces: Error from server (Forbidden)..."
2) Find a Pod/Container
3) right-click on it
4) select "View Logs"
5) notice popping up "Logs Viewer"
6) notice never ending "Loading..." without any error-message coming up

**Comment by quoctruong** [comment]
@mlamm So the pod is inside the `lalalala` namespace that you are trying to view?

**Comment by mlamm** [comment]
Yes, I obfuscated it, but it matches.

I noticed a kubernetes-debugging setting within vscode, can anyone explain me howto use it? If it would be of any benefit here.

**Comment by jmah-cc** [comment]
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-vscode-internal](https://github.com/GoogleCloudPlatform/cloud-code-vscode-internal/issues/1839)

**Comment by quoctruong** [comment]
@mlamm When we cannot list namespace, we are simply running "kubectl logs <pod-name>" without any namespace specified. One option to fix this is to create a Kubernetes Context with namespace `lalalala` and sets that as the default Kubernetes Context and run view logs with it. Can you try that?

**Comment by mlamm** [comment]
@quoctruong I have already a k8s-context set, running a simple `kubectl get po` in the terminal will list the namespaces' pods without explicity supplying it to the command.

How would the `kubectl logs` command look like?

```
 $ ~/> k logs
error: expected 'logs [-f] [-p] (POD | TYPE/NAME) [-c CONTAINER]'.
POD or TYPE/NAME is a required argument for the logs command
See 'kubectl logs -h' for help and examples
```

Hitting the refresh-Icon within "Logs Viewer" leads to an error-output within the Logs-Viewer:
```
error: You must provide one or more resources by argument or filename. Example resource specifications include: '-f rsrc.yaml' '--filename=rsrc.json' '<resource> <name>' '<resource>'
```

**Comment by quoctruong** [comment]
@mlamm Do you mind showing a GIF of the original repro step? The `kubectl logs` would be something like `kubectl logs <name-of-pod>`

**Comment by mlamm** [comment]
I can't share my real cluster info. However, I tried to reproduce the issue on minikube, even with the permissions for `k get ns` granted, it still fails with restrictive rbac in place (allowed: k get ns, k get po -n kube-system, k logs -n kube-system, everything else denied).
It fails without any error message, it keeps being stuck at "Loading...". Using the **minikube** context (admin), does not show this issue, it works then.

So this issue seems to be unrelated to the list-namespace-permissions then, it is some other rbac preventing it to function properly, anything I can help to debug it?

Repro-GIF for minikube, using a limited user1 context (following: https://medium.com/@HoussemDellai/rbac-with-kubernetes-in-minikube-4deed658ea7b): https://imgur.com/a/txRy6oo

**Comment by quoctruong** [comment]
Hmmm I see. I suspect this is because the logs viewer is trying to populate the dropdown with namespaces, deployments, pods, etc. I'll do some more investigation and get back to you.

**Comment by quoctruong** [comment]
@mlamm If you try running the command with `--all-namespaces` switch, will you get an error?

**Comment by mlamm** [comment]
@quoctruong are we talking about `k get po --all-namespaces` ?
This was one was previously denied by my rbac-config, I enabled it, the issue is still present.

Meanwhile I upgraded to:
Extension version: 1.1.2
VSCode version: 1.42.1

Since this new version I also notice random "The request is missing a valid API key." popping up in place of the "Loading...", this happens when I try to open the "Logs Viewer" on a 2nd pod, then the dropdowns are also filled (with my current, relaxed, minikube-rbac).

However, the first-try scenario stays the same, as shown in https://github.com/GoogleCloudPlatform/cloud-code-vscode/issues/201#issuecomment-590740781.

**Comment by quoctruong** [comment]
Yes. This could be a bug in our code because we are running some command with `--all-namespaces`. There is also a bug where we are not showing the errors probably.

**Comment by quoctruong** [comment]
@mlamm This has been improved in the recently released version. Please try it out!

**Comment by mlamm** [comment]
Extension version: 1.2.0
VSCode version: 1.42.1

On first attempt to view logs on a pod I do get presented with the following error in the "Logs Viewer" where normally the log-messages are:
> Error from server (Forbidden): nodes is forbidden: User "xxx" cannot list resource "nodes" in API group ""

On 2nd and subsequent tries:
> Error from server (Forbidden): namespaces is forbidden: User "xxx" cannot list resource "namespaces" in API group "" at the cluster scope

**Comment by quoctruong** [comment]
I see. I think there is another bug with listing nodes that needs to be fixed here. Thanks for the info!

**Comment by quoctruong** [comment]
@mlamm Can you try again with the latest version of the extension?

**Comment by quoctruong** [comment]
@mlamm Friendly ping. Can you still repro this?

**Comment by quoctruong** [comment]
@mlamm Feel free to reopen the issue if this still happens to you.

**Comment by ihelmer07** [comment]
@quoctruong I'm having this issue when I log into a cluster where I only have access to a single namespace (with very limited permissions):

Error from server (Forbidden): namespaces is forbidden: User "ME" cannot list resource "namespaces" in API group "" at the cluster scope
