### ISSUE TITLE
Cannot deploy to GKE cluster with IAP enabled

### ISSUE THREAD

**Issue by kschaab** [GoogleCloudPlatform/cloud-code-vscode#202]
Cloud Code extension 1.1.1 - user cannot deploy to GKE cluster where IAP is enabled.  Required directions and/or fixes to get this working.

**Comment by sujit-kamireddy** [comment]
@kschaab , can you elaborate? Is this a regression?

**Comment by kschaab** [comment]
Not a regression, we have a user attempting to do this and it isn't working.  Currently looking into what is necessary to get it working.

**Comment by sujit-kamireddy** [comment]
Thanks @kschaab

**Comment by jmah-cc** [comment]
USer was not using GKE / Cloud Code - N/A!
