### ISSUE TITLE
Add a guidance message in case no Kubernetes manifest are present

### ISSUE THREAD

**Issue by remyleone** [GoogleCloudPlatform/cloud-code-vscode#203]
**Environment**:
Extension version: 1.1.1
VSCode version: 1.41.1
OS: darwin

**Description**:

Could you add a message to guide a user to create kubernetes-manifest in case they are not present in the project folder?

**Repro step**:

Open a project with no kubernetes-manifests and try to deploy.

**Comment by sujit-kamireddy** [comment]
Thanks @remyleone . We will look into this.

**Comment by jmah-cc** [comment]
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-vscode-internal](https://github.com/GoogleCloudPlatform/cloud-code-vscode-internal/issues/1842)

**Comment by kschaab** [comment]
Fixed in v1.3.0 which just released.
