### ISSUE TITLE
Need skaffold delete equivalent in cloud code

### ISSUE THREAD

**Issue by smakam** [GoogleCloudPlatform/cloud-code-vscode#205]
**Use case**
After deploying application using cloud code, there is no option to delete all the kubernetes resources. cloud code delete option deletes individual resources but not all the resources in 1 shot.

**Feature**
We need something equivalent of "skaffold delete". Ideally "cloud code"->delete should have done the same.

**Comment by sujit-kamireddy** [comment]
Hi @smakam ,
We recently added a new command 'Run on Kubernetes' in the release (v1.1.0) that provides several [customization options](https://cloud.google.com/code/docs/vscode/running-an-application#customizing_run_configuration) including cleanUp.

Please give it a try and let us know if it works for your situation.

_Note that 'Cloud Code: Deploy' and 'Cloud Code: Continuous Deploy' commands will be deprecated in favor of this command._

**Comment by jmah-cc** [comment]
@smakam please try out the new command based on Sujit's feedback and re-open the issue if you have any other comments.
