### ISSUE TITLE
Allow to `kubectl edit` any Kubernetes resource of the cluster

### ISSUE THREAD

**Issue by PierreBesson** [GoogleCloudPlatform/cloud-code-vscode#21]
As of version 0.0.1, it is possible to open any Kubernetes resource of the cluster in the editor as shown in the screenshot below.

<img width="1407" alt="screenshot 2019-02-25 at 18 06 27" src="https://user-images.githubusercontent.com/513471/53355370-27760880-3929-11e9-8575-793dd0f56dc2.png">

It would be very useful to be able to edit the file in the current buffer and then when saving it would work like the `kubectl edit` command and actually directly modify the resource in the cluster. Of course this is a pretty dangerous things to do but IMO it should be enabled in development clusters which I think are the target of this extension.

**Comment by jtfogarty** [comment]
I was editing a configmap in namespace kf-04 but it was saved to the default namespace.  Thanks, this is a great extension!!

**Comment by iantalarico** [comment]
@PierreBesson This is a great idea, I think it's technically possible and I agree we should try and fix that as it's misleading.

@jtfogarty Glad you are enjoying the extension and thank you for the feedback! We will be sure to fix this up.

@quoctruong Can you take a look at fixing these two issues up?

**Comment by iantalarico** [comment]
@quoctruong Any update here?

**Comment by quoctruong** [comment]
@PierreBesson we can’t mark the file as read-only because of the limitation from VSCode. Feel free to reopen the issue if you found any problems with the feature.
