### ISSUE TITLE
Issue Name

### ISSUE THREAD

**Issue by sollo387420489-user262144** [GoogleCloudPlatform/cloud-code-vscode#218]
**Environment**:
Extension version: 1.2.0
VSCode version: 1.43.0-insider
OS: win32

**Description**:

**Repro step**:

**Comment by sollo387420489-user262144** [comment]
Workspace
{
  "textDocuments": [
    {
      "fileName": ".mailmap",
      "isUntitled": false,
      "languageId": "plaintext",
      "uri": "file:///c%3A/Users/sollo/Desktop/.mailmap"
    }
  ]
}
Configs
{
  "folder": {
    "inherited": {
      "languageIdsEnabled": "default",
      "locales": "default"
    },
    "languageIdsEnabled": [
      "asciidoc",
      "c",
      "cpp",
      "csharp",
      "css",
      "git-commit",
      "go",
      "handlebars",
      "haskell",
      "html",
      "jade",
      "java",
      "javascript",
      "javascriptreact",
      "json",
      "jsonc",
      "latex",
      "less",
      "markdown",
      "php",
      "plaintext",
      "python",
      "pug",
      "restructuredtext",
      "rust",
      "scala",
      "scss",
      "text",
      "typescript",
      "typescriptreact",
      "yaml",
      "yml"
    ],
    "locales": [
      "en"
    ]
  },
  "user": {
    "inherited": {
      "languageIdsEnabled": "default",
      "locales": "default"
    },
    "languageIdsEnabled": [
      "asciidoc",
      "c",
      "cpp",
      "csharp",
      "css",
      "git-commit",
      "go",
      "handlebars",
      "haskell",
      "html",
      "jade",
      "java",
      "javascript",
      "javascriptreact",
      "json",
      "jsonc",
      "latex",
      "less",
      "markdown",
      "php",
      "plaintext",
      "python",
      "pug",
      "restructuredtext",
      "rust",
      "scala",
      "scss",
      "text",
      "typescript",
      "typescriptreact",
      "yaml",
      "yml"
    ],
    "locales": [
      "en",
      "en-GB",
      "en-US",
      "fr-FR"
    ]
  },
  "workspace": {
    "inherited": {
      "languageIdsEnabled": "default",
      "locales": "default"
    },
    "languageIdsEnabled": [
      "asciidoc",
      "c",
      "cpp",
      "csharp",
      "css",
      "git-commit",
      "go",
      "handlebars",
      "haskell",
      "html",
      "jade",
      "java",
      "javascript",
      "javascriptreact",
      "json",
      "jsonc",
      "latex",
      "less",
      "markdown",
      "php",
      "plaintext",
      "python",
      "pug",
      "restructuredtext",
      "rust",
      "scala",
      "scss",
      "text",
      "typescript",
      "typescriptreact",
      "yaml",
      "yml"
    ],
    "locales": [
      "en"
    ]
  }
}

**Comment by sollo387420489-user262144** [comment]
[kmihovny.c.txt](https://github.com/GoogleCloudPlatform/cloud-code-vscode/files/4294338/kmihovny.c.txt)

**Comment by jmah-cc** [comment]
@sollo387420489-user262144 Can you describe the exact issue you're having? Did not see a description or repro steps.

**Comment by jmah-cc** [comment]
Please re-open the issue with more details.
