### ISSUE TITLE
Feature Request: Support AppEngine & AppEngine Flex

### ISSUE THREAD

**Issue by jthegedus** [GoogleCloudPlatform/cloud-code-vscode#219]
**Feature**

AppEngine deployments are supported with the [Cloud Code IntelliJ plugin](https://github.com/GoogleCloudPlatform/cloud-code-intellij). Feature parity here would be good so I do not have to use two editors for different projects.

EDIT: Sorry, didn't see https://github.com/GoogleCloudPlatform/cloud-code-vscode/issues/138 until after submitting this request.

**Comment by jmah-cc** [comment]
As mentioned in the other bug, we don't have plans for supporting this in the near future. Thanks for the request though, please upvote the other issue to help us prioritize this for future.

**Comment by jthegedus** [comment]
No worries. It's not clear that up-voting a closed GitHub issue will result in the issue being addressed.
