### ISSUE TITLE
Add custom templates to create new projects

### ISSUE THREAD

**Issue by Nithinbs18** [GoogleCloudPlatform/cloud-code-vscode#220]
Dear team,

I currently work on ML projects and would love to have an option to add new templates from which I can create a new project. Currently, the available templates are great but each time I create a new project I would have to do a lot of redundant changes before the development starts.
If I would get an option to add custom templates to have a predefined template suitable for my work.
Thank you.

Regards,
Nithin Bhardwaj

**Comment by kschaab** [comment]
It would be a while before we added such functionality.  Would you mind elaborating on what your workflow is so that we might get an idea of things that might be helpful in the meanwhile?  For example, if you were to clone a repo from github or start with existing code, what pieces do you need from the template that help you?

**Comment by Nithinbs18** [comment]
Hello,

It would be great if there was an option to add private git repo and get an option to view it under "New application", for instance in my on-prem setup I would like to use ingress instead of a loadbalncer service as I cannot assign an IP to my loadbalancer, or I would like to have an application that by default make use of helm charts for all such options I would now have to manually make changes under k8-manifest and skaffold.yaml file and each time I have to make changes within the folders. Currently, I have several Git repos and each time I have to clone it and than start working with cloud-code. If there was an option to add these repos within cloud-code it would be great.

Thank you.

Regards, 
Nithin

**Comment by jmah-cc** [comment]
We're looking to add this in the next 6 months, stay tuned!

**Comment by kschaab** [comment]
This will be in the next release!

**Comment by j-windsor** [comment]
This is released in v1.8.0. Please let us know how you like it!
