### ISSUE TITLE
Project without CloudBuild api enabled cause infinite loop of creating python.exeIssue Name

### ISSUE THREAD

**Issue by Mistic92** [GoogleCloudPlatform/cloud-code-vscode#221]
**Environment**:
Extension version: 1.2.0
VSCode version: 1.43.1
OS: win32

**Description**:
My laptop got blue screen two times. Then I started monitoring what's going on and I saw dozens of python.exe process in regular process explorer. I downloaded advanced one for windows and I saw that all of them are related to vscode. After opening vscode process explorer I saw that CloudCode extension is trying to do connection to cloud builder and open new python process every second. 

An hour ago I switched to new project where I have cloud build disabled. After enabling this api issue stopped. 
https://twitter.com/lukaszbyjos/status/1241750725866160129

**Repro step**:
1. Switch gcloud project to new one without cloud builder api enabled.
2. Open yaml file with k8s config.

**Comment by quoctruong** [comment]
@Mistic92 Thank you for reporting the issue. We will investigate the issue.

**Comment by jmah-cc** [comment]
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-vscode-internal](https://github.com/GoogleCloudPlatform/cloud-code-vscode-internal/issues/2085)

**Comment by Mistic92** [comment]
Today I got update of CloudCode to 1.2.1 and it's happening even when I have cloud build enabled. 

https://drive.google.com/file/d/1mobzgLeXqy_4WkuSvjJP6WEgIrzBjZoj/view?usp=sharing
https://drive.google.com/file/d/1in0C4mw989SQ5EqikqZoRHmMWPdZxCdW/view?usp=sharing

**Comment by quoctruong** [comment]
@Mistic92 I see. The patch was to fix an issue with gcloud. We're still investigating this issue and will update you soon!

**Comment by kschaab** [comment]
@Mistic92 - please give us the result of running `"%LOCALAPPDATA%\Google\Cloud SDK\google-cloud-sdk\bin"\gcloud version`.

**Comment by Mistic92** [comment]
I found that this extension is not causing issue but the other one. I'm closing this issue as it's not related.
https://github.com/an0rak-dev/vscode-gcp-cloudbuild
