### ISSUE TITLE
GKE Explorer does not work in windows 10

### ISSUE THREAD

**Issue by jdegraft** [GoogleCloudPlatform/cloud-code-vscode#224]
**Environment**:
Extension version: 1.2.1
VSCode version: 1.43.2
OS: win32

**Description**:
For some reason, after the login in process, gcp project and cluster information does not show in gke explorer.
My project is setup fine because this works in macos.
Also when I try to create cluster using gke explorer, it identifies the project, and passes the test that APIs are enabled, but fails when loading zones with 'login required'

**Repro step**:
Login into GCP using GKE using Cloud Code in VS Code on windows 10
Try adding a cluster

**Comment by kschaab** [comment]
Are you getting UAC prompt for elevation or something?  If you go to the terminal in VS Code can you type gcloud auth login and does it run?

**Comment by jdegraft** [comment]
Yes,

When I run gcloud auth login it runs fine.

Verified that I was connected in the terminal, by setting project id and listing clusters in project.

Both work.

But at that point when I go to GKE Explorer and refresh, it does not load.

Also whiles playing with it, I noticed this.

When I click to add cluster in GKE Explorer sometimes it recognizes my project sometimes it doesn’t.

By that I mean it allows me to use the set project id button.

In either case whether I use the button or enter project id manually the following occurs.

Even when it allows me to set project id the next steps fails.

It passes test to ensure that APIs are enabled but says it can’t list zones because login required.

Thanks

**Comment by juan-borrero** [comment]
Hello, its happening to me the same thing, gke explorer not show my gcp projects but if i try to create a new cluster i can select all of them.

**Comment by kschaab** [comment]
Are you getting this in the explorer window:
![image](https://user-images.githubusercontent.com/7329029/80389613-222f8900-8860-11ea-90e8-666e687b9c0e.png)

If so, when you click on it, do you get a terminal window with just this (and no other output):
![image](https://user-images.githubusercontent.com/7329029/80389468-fa402580-885f-11ea-9ce3-cdcfa854677d.png)

Does a browser window open?

**Comment by jdegraft** [comment]
Yes,

A browser windows opens and I authenticate.

It just doesn’t show clusters.

In the terminal when I run gcloud container list clusters I get my list of clusters.

**Comment by kschaab** [comment]
We found an issue that might be causing this, we will try and output a hotfix today.

**Comment by kschaab** [comment]
This should be fixed with our next release, which is imminent.  I will circle back once we have released.

**Comment by jdegraft** [comment]
Thanks

**Comment by kschaab** [comment]
Just released v1.3.0 which should fix this issue.
