### ISSUE TITLE
hanging while installing dependencies

### ISSUE THREAD

**Issue by ewuknadierf** [GoogleCloudPlatform/cloud-code-vscode#227]
**Environment**:
Extension version: 1.2.1
VSCode version: 1.45.0-insider
OS: linux

**Description**:
I used the plugin for a while, and was really happy with it.
Then I clicked something like 'install dependencies' (sorry, can't really remember).
The plugin tries to 'Installing dependencies' (message box in the lower right corner), and the Kubernetes Explorer in the left menu is not working anymore.
Even uninstalling and reinstalling the plugin doesn't help.

**Repro step**:
- successful installation and usage of the plugin
- clicking something like 'install dependencies'

**Comment by ewuknadierf** [comment]
Just solved by myself with setting `Auto dependencies` to `OFF`

**Comment by kschaab** [comment]
Thanks for the report @ewuknadierf.  We are making some changes in the next release which should address this problem.

**Comment by kschaab** [comment]
Just released v1.3.0 which should address this issue, thanks again for the issue!
