### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by LeoDupont** [GoogleCloudPlatform/cloud-code-vscode#230]
**Environment**:
Extension version: 1.2.1
VSCode version: 1.44.2
OS: Windows 10 Pro 1903

**Description**:
I noticed VSCode started using up all the CPU it could lately, even when idle.

According to VSCode's **Process Explorer**, the guilty process is:
`electron_node server.js`

Launched with:
```bash
"D:\Program Files\Microsoft VS Code\Code.exe" 
    c:\Users\Username\.vscode\extensions\googlecloudtools.cloudcode-1.2.1\dist\server\server.js 
    --node-ipc 
    --clientProcessId=24524
```

**Repro step**:
I just installed the extension and used it for debugging services in a simple test remote GKE cluster.
Even when I'm not using it, the problem subsists.

Please tell me if I can provide more info or logs.

**Comment by jmah-cc** [comment]
@LeoDupont Can you try the latest release and let us know if you're still seeing this issue? We're unable to repro it on our side.

**Comment by LeoDupont** [comment]
@jmah-cc All good, the bug seems to be gone.
