### ISSUE TITLE
Add support for Google Cloud Run

### ISSUE THREAD

**Issue by brpatel0202** [GoogleCloudPlatform/cloud-code-vscode#231]
**Use case**
What are you trying to do that our extension doesn't let you?
We want to develop, test, deploy, monitor & manage for Google Cloud Run.
Developer will have seamless support for gitops & devops for Google Cloud Run which will save their time. 

**Feature**
What would help?
First class support to develop, test, deploy & monitor and manage for google cloud run.
Same as you have done for intelliJ IDE.
Same you are providing support for GKE on google cloud.

Also add feature/syntax intellisense support for Google Cloud Run product development easily and faster.

**Comment by kschaab** [comment]
We are adding this to VS Code just as it was added to the IntelliJ extension.

**Comment by brpatel0202** [comment]
great, waiting then, thanks

**Comment by kschaab** [comment]
Just released v1.3.0!
