### ISSUE TITLE
Add official support for Terraform to manage Google Cloud Infrastructure As Code

### ISSUE THREAD

**Issue by beingminimal** [GoogleCloudPlatform/cloud-code-vscode#232]
**Use case**
What are you trying to do that our extension doesn't let you?
Officially supporting terraform to manage infra as code will really help teams & companies achieve more within less time and that will also increase different google cloud services adoption time.  
As such google cloud officially supported terraform back from 2017 but developers struggle to keep up with such cutting edge technologies, so to empower them and provide single windows solution to manage google cloud infra developers really need this.

**This feature implementation will not take too much time but its positive impact will be huge for google cloud and its developers**  

**Feature**  
What would help?  
Look at the products lists of terraform support to manage as infra as code for google cloud
https://www.terraform.io/docs/providers/google/guides/provider_reference.html  
Add support only for google cloud commands of terraform to manage google cloud infra  
Also keep it updated with terraform releases.  

Add features like auto complete and syntax intellisense for terraform google cloud commands.  

You guys can study more features from following not updated extensions of VS code.  
You are requested to add those features also which you will find helpful for developers from this following reference links.  
https://marketplace.visualstudio.com/items?itemName=mauve.terraform  
https://marketplace.visualstudio.com/search?term=terraform&target=VSCode&category=All%20categories&sortBy=UpdatedDate

Thank You

**Comment by brpatel0202** [comment]
@kschaab @sujit-kamireddy any update guys?

**Comment by kschaab** [comment]
This is not something that we are looking at for the immediate future.  I have added it to the backlog for future consideration.

**Comment by brpatel0202** [comment]
Thanks for the consideration.

**Comment by brpatel0202** [comment]
@kschaab I think if we measure this issue on value vs effort then it will have higher value against efforts. Because to add support for terraform as development as snippets it wont take too much time and then in small iteration we can make it better, what you think?
Snippets feature wont take too much time i think.

**Comment by beingminimal** [comment]
Official solution available now so closing this issue. Thanks for support.
https://marketplace.visualstudio.com/items?itemName=HashiCorp.terraform
