### ISSUE TITLE
Add Google Cloud Firestore Database support for development

### ISSUE THREAD

**Issue by brpatel0202** [GoogleCloudPlatform/cloud-code-vscode#233]
**Use case**
What are you trying to do that our extension doesn't let you?  
Add support to connect, develop, manage, monitor google cloud firestore database from this extension only, so developer can work from same screen and it can be a single window solution.  
Like to develop to build query, check query result, check database rules, monitor its usage etc.  

And for this official support would be better to trust for developers.  
Check reference links of other similar solutions for other databases  
https://marketplace.visualstudio.com/items?itemName=ms-mssql.mssql  
https://marketplace.visualstudio.com/items?itemName=jsayol.firebase-explorer  
https://marketplace.visualstudio.com/items?itemName=toba.vsfire  
https://marketplace.visualstudio.com/items?itemName=PeterHdd.firebase-firestore-snippets  

**PLEASE CHECK REMAINING FEATURES IF I MISSED ANYTHING FROM ABOVE REFERENCE LINKS**

**Feature**
What would help?
Features to connect, develop, manage & monitor google cloud firestore database with following features will help a lot to build products faster.
Requested Features like
Add and delete collection, documents, array elements inside documents
Snippets for syntax
Intellisense for firestore database collection and indexes
Firestore Index create, update, delete (Batch Operations also required)
Add, change, check firestore database rules
OnCreate, OnUpdate, OnDelete background functions support 
Other supported admin operations
Monitoring database usage from extension only
Run http functions with local emulator
Deploy specified functions

**Comment by brpatel0202** [comment]
@kschaab @sujit-kamireddy any update guys?

**Comment by kschaab** [comment]
Agreed, this would be really nice to have.  Adding to the backlog.

**Comment by brpatel0202** [comment]
Thanks for the consideration.

**Comment by brpatel0202** [comment]
@kschaab We have one more reference to be inspired.
check this. https://marketplace.visualstudio.com/items?itemName=mongodb.mongodb-vscode

**Comment by jmah-cc** [comment]
After reviewing this request again, it's not at the top of our prioritized list. Adding it to backlog and keeping the issue open so other users can upvote this.

**Comment by jmah-cc** [comment]
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-vscode-internal](https://github.com/GoogleCloudPlatform/cloud-code-vscode-internal/issues/3759)

**Comment by jmah-cc** [comment]
Keeping this open but don't have any concrete plans yet

**Comment by kschaab** [comment]
This is still on our backlog but we aren't planning on doing it in the near future.
