### ISSUE TITLE
minikube: only show acceptable drivers in minikube dropdown menu

### ISSUE THREAD

**Issue by priyawadhwa** [GoogleCloudPlatform/cloud-code-vscode#234]
**Environment**:
Extension version: 1.2.1
VSCode version: 1.44.2
OS: Mac

**Description**:
I'm able to select drivers that are unsupported on Mac for minikube, which is a bit confusing:

![image](https://user-images.githubusercontent.com/10676490/81209504-7c79c980-8f85-11ea-93e1-cdbc3ccca2bd.png)

Instead, it would be clearer if we only show acceptable drivers for the OS the user is running:

Linux
- kvm2
- none
- podman

Mac:
- hyperkit
- podman
- vmware

Windows
- hyperv

All OS's:
- docker
- virtualbox

**Comment by kschaab** [comment]
Agreed this should be fixed.  It would be nice if this issue had been addressed in minikube: 
 https://github.com/kubernetes/minikube/issues/2527 as we would prefer to get the list from minikube itself.

**Comment by kschaab** [comment]
Also to note the list that comes back from minikube is more extensive than both of the lists above, macos:  virtualbox, parallels, vmwarefusion, hyperkit, vmware, docker, podman

**Comment by kschaab** [comment]
Filed new issue for minikube to list supported drivers:  https://github.com/kubernetes/minikube/issues/8127

**Comment by jmah-cc** [comment]
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-vscode-internal](https://github.com/GoogleCloudPlatform/cloud-code-vscode-internal/issues/2407)

**Comment by priyawadhwa** [comment]
From minikube v1.11.0 and greater, you can now run:

```
$ minikube config defaults driver --output json
["virtualbox","parallels","vmwarefusion","hyperkit","vmware","docker","podman"]
```

to get a list of available drivers for the current OS
