### ISSUE TITLE
Create AKS cluster UI issues

### ISSUE THREAD

**Issue by Mexicoder** [GoogleCloudPlatform/cloud-code-vscode#239]
I am trying to create a cluster on Azure and the Active Subscription tool will not reload the Resource Group drop-down after changing the Active Subscription. 

the only way to get it to work is if you close the tab and go to the "Create AKS Cluster" page again. Now the default active subscription is the one we changed it to before and now the dropdown will populate

**Comment by redborian** [comment]
Thanks for reporting the issue, @Mexicoder. We will investigate and fix this issue in the upcoming release.

**Comment by jmah-cc** [comment]
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-vscode-internal](https://github.com/GoogleCloudPlatform/cloud-code-vscode-internal/issues/2877)

**Comment by sujit-kamireddy** [comment]
This issue has been fixed and should be available in the next release.
