### ISSUE TITLE
Add free support for self hosted environment to support remote development

### ISSUE THREAD

**Issue by beingminimal** [GoogleCloudPlatform/cloud-code-vscode#242]
**Use case**
What are you trying to do that our extension doesn't let you?
Add free support for self hosted environment to support remote development

**Feature**
What would help?
We would like to have remote development features like
1 - From VS Code developer A can register machine OR docker container as self-hosted dev environment & developer B can connect it from VS Code for remote development (like Microsoft offers it with Azure)
2 - After registering environment developers should be able to share it to specific team members to use it as their own remote development environment. One register environment t should be usable for more than 1 developer as like separate own dev environment.
3 - If developers can register with VS Code Cloud code Google's official extension
(https://github.com/GoogleCloudPlatform/cloud-code-vscode) then it would be better for them to work seamlessly with google cloud only ecosystem.
4 - And in google cloud shell it should shows in dropdown to select registered or shared register environment to start remote work, so this will make dev flow faster and easy remotely also.

**References**
Here are the references how Microsoft azure has implemented and offering
https://docs.microsoft.com/en-in/visualstudio/online/how-to/vscode
https://docs.microsoft.com/en-in/visualstudio/online/how-to/self-hosting-vscode

**Other details**
https://www.youtube.com/playlist?list=PLj6YeMhvp2S4Gg3ibZWGncyiRcLVvlBhY
https://github.com/microsoft/vscode-remote-release

**There is no alternative solution for developers who uses only google cloud.
And in this corona days this will support developers to work remotely.**

**I have submitted feature request in google cloud shell also so you guys are requested to collobrate with that team. You can check that issue details with following link https://issuetracker.google.com/issues/156780152**

**Comment by brpatel0202** [comment]
@kschaab @sujit-kamireddy any update guys?

**Comment by jmah-cc** [comment]
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-vscode-internal](https://github.com/GoogleCloudPlatform/cloud-code-vscode-internal/issues/2878)

**Comment by sivakku** [comment]
@beingminimal - Are you looking for VSCode to connect to dev hosted environment on premise (or) in the google cloud? if it is later you can do this with remote shell dev cloud plugin offers([tutorial](https://cloud.google.com/code/docs/vscode/quickstart-remote-dev)). You can build and deploy your project out of this remote environment.

**Comment by vincentjocodes** [comment]
Will close the issue for now due to inactivity, if you have any more comments on this please re-open this task. Thank you.
