### ISSUE TITLE
Remote Dev not working

### ISSUE THREAD

**Issue by teich** [GoogleCloudPlatform/cloud-code-vscode#243]
**Environment**:
Extension version: 1.3.0
VSCode version: 1.45.1
OS: darwin

**Description**:
Clicking the 'open with cloud code' button on the [quickstart page](https://cloud.google.com/code/docs/vscode/quickstart-remote-dev) doesn't work.

<img width="457" alt="Screen Shot 2020-05-18 at 9 25 16 AM" src="https://user-images.githubusercontent.com/47476/82237746-03fefb00-98eb-11ea-907e-5ee23b1557bc.png">

I'm not sure where this error is coming from. Locally I do have 292 installed:
```
$ gcloud --version                                                                                                                                        
Google Cloud SDK 292.0.0
beta 2019.05.17
bq 2.0.57
core 2020.05.08
gsutil 4.50
kpt
kubectl 2020.05.01
```
**Repro step**:
Click the 'open with cloud code' button on the [quickstart page](https://cloud.google.com/code/docs/vscode/quickstart-remote-dev)

**Comment by kschaab** [comment]
Thanks for reporting this, investigating...

**Comment by jmah-cc** [comment]
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-vscode-internal](https://github.com/GoogleCloudPlatform/cloud-code-vscode-internal/issues/2426)

**Comment by henninglebbaeus** [comment]
Any update on this already? I am experiencing the same issue

**Comment by kschaab** [comment]
@henninglebbaeus can you provide more information, do you have automatically manage dependencies setting turned to on (or not set)?  

In the command palette open Preferences (UI):

![image](https://user-images.githubusercontent.com/7329029/84921733-b9070d80-b079-11ea-8c27-dd51c17a816a.png)

**Comment by henninglebbaeus** [comment]
Thanks a lot, @kschaab, for pointing out the change in settings. That solved the issue for me and I got it to work today 👍

**Comment by kschaab** [comment]
I'm glad it worked, thanks to this information I found the issue and it will be addressed in the next release as well!

**Comment by jmah-cc** [comment]
This will be in the next release.

**Comment by kschaab** [comment]
This is fixed with our latest release.  Thank you again for reporting this issue.
