### ISSUE TITLE
osx python3 pip using python2 ptvsd

### ISSUE THREAD

**Issue by vptimmy** [GoogleCloudPlatform/cloud-code-vscode#245]
Extension version: 1.3.0
VSCode version: 1.45.1
OS: Catalina 10.15.4

launcher.json:
```
{
    "configurations": [
        {
            "name": "Run/Debug on Kubernetes",
            "type": "cloudcode.kubernetes",
            "request": "launch",
            "skaffoldConfig": "${workspaceFolder}/skaffold.yaml",
            "watch": true,
            "cleanUp": true,
            "portForward": true,
            "imageRegistry": "my-artifactory"
        },
        {
            "name": "Attach to Kubernetes Pod (Python)",
            "type": "cloudcode.kubernetes",
            "request": "attach",
            "language": "Python",
            "podSelector": {
                "app": "my-app"
            },
            "localRoot": "${workspaceFolder}/app",
            "remoteRoot": "/app"
        }
    ]
}
```
I can launch the code to k8 cluster just fine using the first line.  The entry point is `python -mptvsd --host localhost --port 5678 main.py`.  So everything is running and debug port created.  When I try to setup the second half of debugging I run into this:

![Screen Shot 2020-05-22 at 10 40 18 AM](https://user-images.githubusercontent.com/25960940/82685119-b0115080-9c21-11ea-9301-48822ba8f7d9.png)
![Screen Shot 2020-05-22 at 10 40 50 AM](https://user-images.githubusercontent.com/25960940/82685126-b30c4100-9c21-11ea-9977-3da556cddf6b.png)

I have python3 and ptvsd installed locally.  It seems cloud code is hard coded to /usr/bin/python?  How do I get it to use /usr/local/bin/python3?

This is my settings.json:
```
{

    "python.pythonPath": "/usr/local/bin/python3",
    "python.terminal.activateEnvInCurrentTerminal": true,
    "code-runner.executorMap.python": "python3 -u"
}
```

**Comment by vptimmy** [comment]
Solved this by installing and using pyenv on osx

**Comment by Pedrozena** [comment]
Hi @vptimmy, how did you solve this? I did the same, set 3.8.5 as global version, but still cloud code is launching `/usr/bin/python `
Thanks for your support

**Comment by Pedrozena** [comment]
Actually restarting the machine worked for me
