### ISSUE TITLE
Kubernetes Sample Applications are not downloading

### ISSUE THREAD

**Issue by RobertoDonPedro** [GoogleCloudPlatform/cloud-code-vscode#246]
Issue Type: <b>Bug</b>

Kubernetes Sample applications are not downloaded:
Steps on Cloud Code:
- New Application
- Kubernetes Application
- Go: Hello World (or any other)
- Confirm proposed path with 'Enter'

The message 'Downloading the "Go: Hello World' sample..." appears endless, but nothing gets downloaded.

Extension version: 1.3.0
VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (0.95GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by quoctruong** [comment]
@RobertoDonPedro The message appears when it's trying to download the package. I suspect this could also be an issue with Internet connectivity or Github availability. Can you retry it?

**Comment by RobertoDonPedro** [comment]
> @RobertoDonPedro The message appears when it's trying to download the package. I suspect this could also be an issue with Internet connectivity or Github availability. Can you retry it?

I can connect from vscode to my gke cluster without any problems and I do not have any other problems with the internet connectivity, therefore I don't think that thats the issue. Also I can connect to Github without any problems.
Please note that not even the proposed directory gets created locally...

**Comment by quoctruong** [comment]
Does this happen for the go sample only? How about the other samples?

**Comment by RobertoDonPedro** [comment]
It doesn't work with the other examples either. I also tried it with the node.js sample.

**Comment by redborian** [comment]
Thanks for checking, @RobertoDonPedro. We will investigate and fix this issue in the upcoming releases.

**Comment by quoctruong** [comment]
@RobertoDonPedro Can you retry with the latest version of the extension? I have not been able to repro this.

**Comment by RobertoDonPedro** [comment]
@quoctruong Yes, now it works, thanks!
