### ISSUE TITLE
extension host terminated unexpectedly

### ISSUE THREAD

**Issue by nguyenxndaidev** [GoogleCloudPlatform/cloud-code-vscode#253]
**Environment**:
Extension version: 1.4.0
VSCode version: 1.46.0
OS: Windows 10 version 1909 (OS Build 18363.836)

**Description**:
Error: *extension host terminated unexpectedly*
![image](https://user-images.githubusercontent.com/24372782/84368033-58895380-abd5-11ea-9305-4ce579106bff.png)

**Repro step**:
* Enable Cloud Code extension
* Restart Visual Studio Code. Error occurs with message: *extension host terminated unexpectedly*.
* Disable Cloud Code extension
* Restart Visual Studio Code or click *Restart Extension Host* in the notification. Error disappears.

**Comment by quoctruong** [comment]
@nguyenxndaidev If you open developer tools, do you see any additional messages from the console?

**Comment by nguyenxndaidev** [comment]
Today I enable the extension again, but it seems version 1.4.1 fixed the issue. Cannot reproduce the error again.
