### ISSUE TITLE
Cloud Code is not offering completions for some memory settings

### ISSUE THREAD

**Issue by matthewmichihara** [GoogleCloudPlatform/cloud-code-vscode#254]
In a Kubernetes pod manifest file, no completions are offered for this path:
`spec.containers[].resources.{request,limit}.xxxxxx`

This also seems to occur for the JetBrains Kubernetes plugin.

https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#resource-requests-and-limits-of-pod-and-container

https://github.com/GoogleCloudPlatform/cloud-code-intellij/issues/2695

**Comment by sivakku** [comment]
This is a low priority on our side since there are only few that can be discovered using documentation (cpu,memory, hugpages). Do let us know where the ask is coming from and how this one will be helpful for users. Closing for now.
