### ISSUE TITLE
[Open Marketplace] Please publish extension to https://open-vsx.org

### ISSUE THREAD

**Issue by jankeromnes** [GoogleCloudPlatform/cloud-code-vscode#256]
Hi Cloud Code team! 👋 

**Use case**
I would love to be able to easily install the Cloud Code VSCode extension in projects such as:
- [gitpod.io](https://www.gitpod.io/)
- [theia-ide.org](https://theia-ide.org/)
- [vscodium](https://github.com/VSCodium/vscodium)
- [code-server](https://github.com/cdr/code-server)

**Feature**
To that effect, please [publish](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions#how-to-publish-an-extension) the Cloud Code extension to https://open-vsx.org.

This can be achieved by setting up a [`OVSX_PAT`](https://open-vsx.org/user-settings/tokens) token and then running:

```
npx ovsx create-namespace GoogleCloudTools
npx ovsx publish
```

**Comment by sivakku** [comment]
@jankeromnes - How do you plan to use the extension in eclipse/gitpod? Can you describe your scenario.

**Comment by jankeromnes** [comment]
> @jankeromnes - How do you plan to use the extension in eclipse/gitpod? Can you describe your scenario.

Hi @sivakku! It's not just me, it's every Gitpod or VSCodium user who also uses Google Cloud, for example:
- Gitpod.io user developing a software project that is deployed on Google Cloud
- User who wants to deploy Gitpod Self-Hosted onto Google Cloud
- VSCodium user developing a software project that is deployed on Google Cloud

For example, we (Gitpod Inc.) develop Gitpod in Gitpod, and the main SaaS service gitpod.io is deployed on Google Cloud. Thus, we interact a lot with Google Cloud on the web or from within Gitpod, for example to:
- log in to our Kubernetes clusters in EU and US for monitoring, debugging or incident response
- manage Google Cloud buckets (for example, to download a backup for a user that has lost access to their Gitpod workspace)

We currently authenticate in our Gitpod dev environments using the `gcloud` CLI, but I believe that having access to the Google Cloud VSCode extension will prove very handy in many ways.

Also, you may be interested in having _every user_ of VSCodium, Gitpod, Theia, etc. being able to use the Google Cloud extension, for a relatively cheap cost (i.e. just running `npx ovsx publish` at least once).

**Comment by davemecha** [comment]
Please add Open VSX support so it is available in Gitpod. Since we have complete software defined environments in Gitpod, we can provide the environments with preinstalled VSCode extensions to our developers.

Right now I have to pull the extension from the releases (as laid out in [the gitpod forum](https://community.gitpod.io/t/missing-vscode-extension/3901/2?u=davemecha)) with a sticky version, so updates are not automatically applied to new workspaces. but it's at least some workaround for now.

**Comment by j-frost** [comment]
I too stumbled across this issue when moving to Gitpod. Can't find Cloud Code in VSCode there (nor install it without the workaround).

**Comment by ghuntley** [comment]
Yes please.

**Comment by fiveable-jferg** [comment]
Please -would love to use in gitpod.

**Comment by Cyclenerd** [comment]
I also want to be able to use [Cloud Code](https://marketplace.visualstudio.com/items?itemName=GoogleCloudTools.cloudcode) (`GoogleCloudTools.cloudcode`) in my OpenVSCode. My OpenVSCode runs in Google Cloud Shell. Please publish the extension to https://open-vsx.org/.

**Comment by thalesfsp** [comment]
2y to change a few lines...

**Comment by barbich** [comment]
A "Gemini Code Assist + Google Cloud Code" has been published in open-vsx.
I am doubtful its legit: its published by cloudcode-eng-github-admin and this github account has been created 1st of April.
Can a maintainer here confirm  its legitimate?

tx

**Comment by kschaab** [comment]
It is published to open-vsix:  https://open-vsx.org/extension/googlecloudtools/cloudcode.  This is the same ID and should match what is on the VS Code marketplace.  The publisher is our robot account as these are pushed automatically as of April.
