### ISSUE TITLE
Watch: No Longer Reloading

### ISSUE THREAD

**Issue by GavinOsborn** [GoogleCloudPlatform/cloud-code-vscode#257]
**Environment**:
Extension version: 1.4.1
VSCode version: 1.46.0
OS: win32

**Description**:
When using the "Run/Debug on Kubernetes" command configuring `watch: true` (which is the default anyway) should detect file changes and reload your application. This no longer works. It does not appear to react to file change events at all.

This used to work fine on version 1.2.1.
I have since tested it on 1.3.0, 1.4.0 and 1.4.1 and it does not work on any of these versions.

I am on windows but my colleagues on mac report the same issue.

**Repro step**:
 - Clone the [cloud-code-samples](https://github.com/GoogleCloudPlatform/cloud-code-samples) repository.
 - Open one of the nodejs samples (I used `nodejs-hello-world`) in vscode.
 - Observe that `watch: true` is configured in launch.json
 - Run the command "Cloud Code: Run on Kubernetes"
 - Wait for the app to build and deploy
 - Make a change to /src/app.js and save it
 - Observe that the app does not reload

**Comment by kschaab** [comment]
Are you using run or debug to launch the configuration?  If you use run (ctrl-f5) watch mode should work, but it doesn't work under debug (f5).

**Comment by vincentjocodes** [comment]
@quoctruong Also probably related to this: https://github.com/GoogleCloudPlatform/cloud-code-vscode-internal/issues/2582.

**Comment by quoctruong** [comment]
@GavinOsborn Thank you for reporting this bug. As a workaround for now, you can select the launch configuration in VSCode and do a `Run Without Debugging` (Ctrl + F5) and that will enable watch mode.

The `Run on Kubernetes` command is supposed to trigger this but there seems to be a bug in our code that triggers a normal `Run and Debug` instead.

**Comment by kschaab** [comment]
This is failing due to a bug in VS Code (https://github.com/microsoft/vscode/pull/99678).  This should be fixed the next time VS Code ships, good find @quoctruong !  Thanks for the bug report @GavinOsborn

**Comment by GavinOsborn** [comment]
Thanks all. Have briefly tested the Ctrl + F5 work around. It isn't a great option but it'll see us through to next vscode release I'm sure.

Do you know if this fix is available on insiders already?

**Comment by GavinOsborn** [comment]
@kschaab @quoctruong  I can confirm the same issue exists with on insiders builds with the latest cloud code extension.

I don't know exactly how commits flow into the insiders build so I don't know if this is useful information but thought it might be worth raising just in case.

**Comment by quoctruong** [comment]
@GavinOsborn Thank you for the update. We will investigate this further.

**Comment by jmah-cc** [comment]
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-vscode-internal](https://github.com/GoogleCloudPlatform/cloud-code-vscode-internal/issues/2624)

**Comment by quoctruong** [comment]
@GavinOsborn I just installed the insider build from yesterday and the watch mode seems to be working now.

**Comment by GavinOsborn** [comment]
Good news!
Will check it out today.

**Comment by GavinOsborn** [comment]
Hey @quoctruong confirmed latest builds do now work as expected. 👍 

Think we can close this now.

**Comment by quoctruong** [comment]
Thanks!
