### ISSUE TITLE
Changing a port does not remove the older port

### ISSUE THREAD

**Issue by thatcashcow** [GoogleCloudPlatform/cloud-code-vscode#260]
**Environment**:
Extension version: 1.4.1
VSCode version: 1.46.1
OS: Mac

**Description**:
When I try to change the port for a service. The new port gets saved but the older port also gets added as a second entry.
<img width="607" alt="(2)Screenshot_2020-06-22_at_5_58_19_PM" src="https://user-images.githubusercontent.com/53687035/85288123-dfcaa700-b4b2-11ea-8b4f-312f342e6395.png">
<img width="702" alt="(2)Screenshot_2020-06-22_at_5_56_27_PM" src="https://user-images.githubusercontent.com/53687035/85288121-de997a00-b4b2-11ea-9915-c3177212cb5f.png">
<img width="702" alt="Screenshot_2020-06-22_at_5_56_40_PM" src="https://user-images.githubusercontent.com/53687035/85288113-dccfb680-b4b2-11ea-9726-676649b89344.png">
<img width="702" alt="Screenshot_2020-06-22_at_5_56_56_PM" src="https://user-images.githubusercontent.com/53687035/85288126-e0633d80-b4b2-11ea-8cfa-fbb8dda3ed76.png">

**Comment by jmah-cc** [comment]
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-vscode-internal](https://github.com/GoogleCloudPlatform/cloud-code-vscode-internal/issues/2622)

**Comment by kschaab** [comment]
Thank you for reporting this issue, we are currently investigating making a fix.

**Comment by redborian** [comment]
Thanks for reporting the issue @thatcashcow. Cloud Code just delegates to kubectl CLI for applying your new patch which could vary depending on the Kubernetes version your cluster uses. I tried `1.16.11-gke.5` but couldn't repro the exact issue that you are mentioning here.
We can try to help if you can report back the Kubernetes version in your cluster. You can quickly check whether the behavior is identical with `"kubectl apply -f FILE_NAME"`.

**Comment by redborian** [comment]
Closing this issue due to lack of reply. Feel free to reopen this issue if you have more info.
