### ISSUE TITLE
"Debug on Kubernetes" doesn't behave as described in GCP documentation 

### ISSUE THREAD

**Issue by traturne** [GoogleCloudPlatform/cloud-code-vscode#263]
**Environment**:
Extension version: v1.4.1
VSCode version: 1.46.1
OS: Mac OS High Sierra

**Description**:
When selecting "Debug on Kubernetes" (following the tutorial here: https://cloud.google.com/code/docs/vscode/debug) I don't get presented with a pop-up to choose the container to debug.

**Repro step**:
CMD+Shift+P -> "Debug on Kubernetes" 

Watch Docker build / Helm deploy as usual

No option to select container to debug

Am happy to provide additional context as needed.

**Comment by kschaab** [comment]
Can you be specific as what is happening and what you expect?  You shouldn't get a pop-up to select a container, it should just attach the debugger to the running process after build.  Are you getting any errors in the skaffold output?

**Comment by traturne** [comment]
Sure.

In the documentation I linked there is a section that says: 

```
For each debuggable container in your application, you'll be prompted to confirm or enter the directory in the remote container where the program you'd like to debug is found.

Alternatively, you can press ESC to skip debugging the container.
```

I do not see such a popup.  

The only error I see from skaffold is: 

```
Starting deploy...
Deploying with helm v3.1.2 ...
Helm release lifecycle-service-skaffold not installed. Installing...
Building helm dependencies...
NAME: lifecycle-service-skaffold
LAST DEPLOYED: Fri Jul  3 08:58:35 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
error decoding parsed yaml: Object 'Kind' is missing in 'NAME: lifecycle-service-skaffold
```

But the deployment still succeeds so I've been ignoring it.  Could this be the cause?

**Comment by kschaab** [comment]
What programming language are you using?

**Comment by quoctruong** [comment]
@traturne Also, at the start of the log, there should be a line detailing the `skaffold` command that is run. Is it possible to paste it here? (After redacting all the private info of course).

**Comment by traturne** [comment]
I am programming in Golang: `go version go1.13.4 darwin/amd64`

Here is the `skaffold` command context:
```
Running "Run on Kubernetes" configuration (.vscode/launch.json) in Debug mode
Running: skaffold debug --enable-rpc -v info --port-forward --rpc-http-port 49825 --filename skaffold.yaml --default-repo [REDACTED]
 starting gRPC server on port 50051
starting gRPC HTTP server on port 49825
Skaffold &{Version:v1.12.0 ConfigVersion:skaffold/v2beta5 GitVersion: GitCommit:e680a831292e1c7efc54e0c6d40544ae141e6354 GitTreeState:clean BuildDate:2020-06-25T13:15:49Z GoVersion:go1.14.2 Compiler:gc Platform:darwin/amd64}
```

**Comment by quoctruong** [comment]
Okay so once you launch the debug session, please go to a web browser and go to `http://localhost:${rpc_http_port}/v1/event_log` where `${rpc_http_port}` is `49825` in the example above. And then can you paste the events logs in there here?

**Comment by traturne** [comment]
Here is the output: ```{"result":{"timestamp":"2020-07-21T01:16:20.007683Z","event":{"metaEvent":{"entry":"Starting Skaffold: \u0026{Version:v1.12.0 ConfigVersion:skaffold/v2beta5 GitVersion: GitCommit:e680a831292e1c7efc54e0c6d40544ae141e6354 GitTreeState:clean BuildDate:2020-06-25T13:15:49Z GoVersion:go1.14.2 Compiler:gc Platform:darwin/amd64}","metadata":{"build":{"numberOfArtifacts":2,"builders":[{"type":"DOCKER","count":2}],"type":"LOCAL"},"deploy":{"deployers":[{"type":"HELM","count":1}],"cluster":"GKE"}}}}}}
{"result":{"timestamp":"2020-07-21T01:16:20.009942Z","event":{"devLoopEvent":{"status":"In Progress"}},"entry":"DevInit Iteration 0 in progress"}}
{"result":{"timestamp":"2020-07-21T01:16:23.744143Z","event":{"deployEvent":{"status":"In Progress"}},"entry":"Deploy started"}}
{"result":{"timestamp":"2020-07-21T01:16:28.210831Z","event":{"deployEvent":{"status":"Complete"}},"entry":"Deploy complete"}}
{"result":{"timestamp":"2020-07-21T01:16:29.695561Z","event":{"statusCheckEvent":{"status":"Started"}},"entry":"Status check started"}}
{"result":{"timestamp":"2020-07-21T01:16:30.860449Z","event":{"resourceStatusCheckEvent":{"resource":"deployment/lifecycle-service-worker","status":"In Progress","message":"waiting for rollout to finish: 0 of 1 updated replicas are available...\n","statusCode":"STATUSCHECK_DEPLOYMENT_ROLLOUT_PENDING","actionableErr":{"errCode":"STATUSCHECK_DEPLOYMENT_ROLLOUT_PENDING","message":"waiting for rollout to finish: 0 of 1 updated replicas are available...\n"}}},"entry":"Resource deployment/corgis-lifecycle-service-worker status updated to In Progress"}}
{"result":{"timestamp":"2020-07-21T01:16:30.860449Z","event":{"resourceStatusCheckEvent":{"resource":"deployment/lifecycle-service","status":"In Progress","message":"waiting for rollout to finish: 0 of 1 updated replicas are available...\n","statusCode":"STATUSCHECK_DEPLOYMENT_ROLLOUT_PENDING","actionableErr":{"errCode":"STATUSCHECK_DEPLOYMENT_ROLLOUT_PENDING","message":"waiting for rollout to finish: 0 of 1 updated replicas are available...\n"}}},"entry":"Resource deployment/lifecycle-service status updated to In Progress"}}
{"result":{"timestamp":"2020-07-21T01:16:31.640104Z","event":{"resourceStatusCheckEvent":{"resource":"deployment/lifecycle-service-worker","status":"Succeeded","message":"Succeeded","statusCode":"STATUSCHECK_SUCCESS"}},"entry":"Resource deployment/lifecycle-service-worker status completed successfully"}}
{"result":{"timestamp":"2020-07-21T01:16:31.640105Z","event":{"resourceStatusCheckEvent":{"resource":"deployment/corgis-lifecycle-service","status":"Succeeded","message":"Succeeded","statusCode":"STATUSCHECK_SUCCESS"}},"entry":"Resource deployment/lifecycle-service status completed successfully"}}
{"result":{"timestamp":"2020-07-21T01:16:31.640178Z","event":{"statusCheckEvent":{"status":"Succeeded"}},"entry":"Status check succeeded"}}
{"result":{"timestamp":"2020-07-21T01:16:31.766596Z","event":{"portEvent":{"localPort":8080,"remotePort":8080,"namespace":"default","resourceType":"service","resourceName":"lifecycle-service","address":"127.0.0.1"}},"entry":"Forwarding container  to local port 8080"}}
{"result":{"timestamp":"2020-07-21T01:16:31.766689Z","event":{"portEvent":{"localPort":8081,"remotePort":8080,"namespace":"default","resourceType":"service","resourceName":"lifecycle-service-worker","address":"127.0.0.1"}},"entry":"Forwarding container  to local port 8081"}}
{"result":{"timestamp":"2020-07-21T01:16:32.122687Z","event":{"devLoopEvent":{"status":"Succeeded"}},"entry":"DevInit Iteration 0 successful"}}
{"result":{"timestamp":"2020-07-21T01:16:32.356905Z","event":{"portEvent":{"localPort":8082,"remotePort":8080,"podName":"lifecycle-service-worker-dfbb85db4-lbczp","containerName":"lifecycle-service-worker","namespace":"default","portName":"http","resourceType":"pod","resourceName":"lifecycle-service-worker-dfbb85db4-lbczp","address":"127.0.0.1"}},"entry":"Forwarding container lifecycle-service-worker to local port 8082"}}
{"result":{"timestamp":"2020-07-21T01:16:32.570374Z","event":{"portEvent":{"localPort":8083,"remotePort":8080,"podName":"lifecycle-service-6f4498475f-d6zt5","containerName":"corgis-lifecycle-service","namespace":"default","portName":"http","resourceType":"pod","resourceName":"lifecycle-service-6f4498475f-d6zt5","address":"127.0.0.1"}},"entry":"Forwarding container lifecycle-service to local port 8083"}}```

**Comment by traturne** [comment]
Any insight here as to how I can perhaps work around this?  I'd really love to be able to perform cluster debugging...

**Comment by jmah-cc** [comment]
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-vscode-internal](https://github.com/GoogleCloudPlatform/cloud-code-vscode-internal/issues/3045)

**Comment by sujit-kamireddy** [comment]
@quoctruong , any insight?

**Comment by quoctruong** [comment]
@traturne Please remove `EXPOSE 2345` and try:
`CMD ["dlv", "debug", "--continue", "--accept-multiclient", "--api-version=2", "--headless", "--listen=:2345", "--log"]

**Comment by quoctruong** [comment]
@traturne Feel free to comment and reopen with new updates. Thanks!
