### ISSUE TITLE
Kubernetes Explorer fails to load from kubeconfig

### ISSUE THREAD

**Issue by immber** [GoogleCloudPlatform/cloud-code-vscode#264]
**Environment**: 
*(Hint: "Report Extension Issue on Github" command will fill these out for you.)*
Extension version: v1.4.1
VSCode version: 1.46.1
OS: Mojave 10.14.6

**Description**:
Kubernetes explorer looks like it's loading, but never displays any resources. Behavior is as if I had a completely blank `kubeconfig`. In the GKE Explorer portion of the sidebar all of my GKE clusters for the current project are correctly displaying, and I'm able to switch contexts. 

In the GKE explorer, I can select "Set as Active Cluster" and I get the prompt to add the cluster to my config, then I get a success message that it was added, but no cluster shows up in Kubernetes Cluster Explorer section. Using kubectl confirms that context is correctly switching. I am getting the prompt to "Add to context" each time I switch to any cluster, even if I've previously seen the successfully added to context message. 

I've confirmed that my  `/.kube/config` does in fact still list all of the clusters that I've previously added, and I can't see any issues with the actual file. 

**Repro step**:
This started for me today upon opening the CloudCode extension in VSCode. Tried restarting both VSCode & computer. 
No recent changes to my VSCode installation, and before today the explorer worked great for me. 
Yesterday I did have a non-kubernetes issue with a bad file that caused VSCode to get into a crash loop and I had to force quit it a bunch of times, so guessing something related to that might have borked something in VSCode, but no idea what.

**Comment by j-windsor** [comment]
Can you ensure that in your vscode settings, `cloudcode.active-kubeconfig` is either "Default KubeConfig" or undefined, both for User and Workspace settings?
```
"cloudcode.active-kubeconfig": "Default KubeConfig"

**Comment by immber** [comment]
It was set to  `"cloudcode.active-kubeconfig": ""`, I tried setting both User and Workspace to `"cloudcode.active-kubeconfig": "Default KubeConfig"`, restarted vS Code, and saw the same behavior: no clusters listed in Kubernetes Explorer.

**Comment by j-windsor** [comment]
Do any error messages show up in the bottom right corner when you try to refresh the Kubernetes Explorer?

**Comment by immber** [comment]
Nope, no errors

**Comment by j-windsor** [comment]
Hmm ok. Can you send a screenshot of your kubernetes explorer just to make sure we are on the same page?

**Comment by immber** [comment]
<img width="549" alt="Screen Shot 2020-07-09 at 3 29 29 PM" src="https://user-images.githubusercontent.com/7496030/87097030-08fc6e80-c1f9-11ea-869c-977c095f61d4.png">

**Comment by j-windsor** [comment]
Sorry for all the requests, but we cannot repro this issue.

It is possible that your kubectl is broken or out of date if this operation is stalling out. Could you please ensure the following:
- In VSCode settings, the extension should be set to automatically download and manage dependencies: `"cloudcode.autoDependencies": "on"`. If it was off and you're changing it to on, restart VSCode, let the dependency installer run automatically, and see if that fixes your problem.
    - (If you have intentionally turned this setting off and would like to keep it off, make sure the kubectl in your `PATH` is up to date and run the following commands in using the kubectl in your `PATH` instead.)
- Behind the scenes, the operation uses `$HOME/Library/Application\ Support/cloud-code/installer/google-cloud-sdk/bin/kubectl config view --output json`. Please run this command in Terminal and ensure it outputs your kubeConfig.
- Check the installed version of kubectl using `$HOME/Library/Application\ Support/cloud-code/installer/google-cloud-sdk/bin/kubectl version`.

**Comment by immber** [comment]
No change to issue, just wanting to track what I've tried so far:
* `"cloudcode.autoDependenciesautoDependencies"` is turned `on`
* running the other commands suggested showed expected output, I can view kubeconfig and get this for installed `kubectl` version ```Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.10", GitCommit:"575467a0eaf3ca1f20eb86215b3bde40a5ae617a", GitTreeState:"clean", BuildDate:"2019-12-11T12:41:00Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.36", GitCommit:"34a615f32e9a0c9e97cdb9f749adb392758349a6", GitTreeState:"clean", BuildDate:"2020-04-06T16:33:17Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}```
* Uninstalled & reinstalled the CloudCode extension 
* I've also manually re-installed VS Code as well as Skaffold. When looking at dependencies, both  `skaffold` and `minikube` were not showing as installed on `PATH`, and required symlink updates, however saw same result even after re-intsalling or reloading the CloudCode extension with dependencies showing as installed

**Comment by immber** [comment]
The issue turned out to be with my installation of `openssl` which had been switched to an older version `1.0.2t`, and having reinstalled openssl 1.1 has resolved this issue in VS Code. 

I ran the following, then restarted vscode, and now my Kubernetes Explorer correctly displays the list of clusters from `kubeconfig`. 
```brew uninstall openssl
rm -rf /usr/local/etc/openssl
brew install openssl```

Not sure why VS Code wasn't able to determine this as being a missing dependency, but I'm marking this issue as closed as this is fully resolved for me now! Thanks for your help!
