### ISSUE TITLE
Specifying local docker container registry in vscode using Google Cloud code.

### ISSUE THREAD

**Issue by mohita-pr** [GoogleCloudPlatform/cloud-code-vscode#273]
**Environment**:
*(Hint: "Report Extension Issue on Github" command will fill these out for you.)*
Extension version:
VSCode version:
OS: MacOS X

**Description**:

I am trying to use a local docker container registry as my imageRegistry . I created a registry by -
`docker run –d –p 5000:5000 –-name registry registry:2`
I have tagged and pushed my image to localhost:5000, and I can see it running by docker images.

I have modified my launch.json as -

`{
    "configurations": [
        {
            "name": "Run/Debug on Kubernetes",
            "type": "cloudcode.kubernetes",
            "request": "launch",
            "skaffoldConfig": "${workspaceFolder}/skaffold.yaml",
            "watch": true,
            "cleanUp": true,
            "portForward": true,
            "imageRegistry": "localhost:5000"
        }
    ]
}`

But when I do a Run on Kubernetes,

I get an error  waiting for rollout to finish: 0 of 1 updated replicas are available...
pod/serviceb-847d79694c-6lxbd: container server is waiting to start: localhost:5000/serviceb:latest@sha256:*** can't be pulled.

**Repro step**:

**Comment by kschaab** [comment]
Would you please put the contents of your skaffold.yaml into this issue?

**Comment by jmah-cc** [comment]
Please re-open with additional details asked for in the comment above.
