### ISSUE TITLE
Create K8s manifests from snippets on Mac

### ISSUE THREAD

**Issue by elkana-cai** [GoogleCloudPlatform/cloud-code-vscode#274]
Environment:
Extension version: 1.4.1
VSCode version: 1.47.3
OS: MacOS Mojave

Hi, I am currently trying Cloud Code on VScode MacOS version and would like to create k8s deployment manifests from Cloud Code snippets, what is the shortcut for doing that on Mac because ctrl/command+space does not work for me?

Thank you

**Comment by kschaab** [comment]
Cmd+space should work, are you starting on an empty file which does not have a yaml extension or in an existing file?

**Comment by elkana-cai** [comment]
I tried using the snippets on an empty file with a YAML extension.

It turned out I had Japanese Keyboard installed and ctrl+space was bound to keyboard switcher shortcut. I turned off the shortcut a long time ago, but for it to be available to use on vscode I had to bind the keyboard switcher to another key combination and restart the mac.

Thank you for answering!
