### ISSUE TITLE
error: current-context is not set

### ISSUE THREAD

**Issue by mhn10** [GoogleCloudPlatform/cloud-code-vscode#275]
**Environment**:
*(Hint: "Report Extension Issue on Github" command will fill these out for you.)*
Extension version: v1.4.1
VSCode version: 1.47.3
OS: Mac OS 10.15.6 (19G73)

**Description**:
Trying to run/debug an application with skaffold.yaml in it, causes pop up error "error: current-context is not set"

I tried setting to the correct docker-desktop context using `kubectl config use-context docker-deskop` & also through the Cloud Code Kubernetes explorer page. It shows the docker-desktop is selected. Still I get the same error

**Repro step**:
Imported the project to workspace. Selected context in kubernetes explorer. Create launch.json file. Going into debug, and selecting "Run/Debug on Kubernetes" causing the attached error message
![Screen Shot 2020-08-06 at 4 00 29 PM](https://user-images.githubusercontent.com/31016811/89591027-02fcac00-d7fe-11ea-864b-5c3e2ed2d355.png)

```json
{
    "configurations": [
        {
            "name": "Run/Debug on Kubernetes",
            "type": "cloudcode.kubernetes",
            "request": "launch",
            "skaffoldConfig": "${workspaceFolder}/skaffold.yaml",
            "watch": true,
            "cleanUp": true,
            "portForward": true
        },
        {
            "name": "Run/Debug on Kubernetes",
            "type": "cloudcode.kubernetes",
            "request": "launch",
            "skaffoldConfig": "${workspaceFolder}/skaffold.yaml",
            "watch": true,
            "cleanUp": true,
            "portForward": true,
            "noDebug": false
        }
    ]
}
```

**Comment by ChaseMor** [comment]
Do you have any other clusters you can set as the active cluster in the Kubernetes Explorer and then switch back to the docker cluster and context? Is there a `current-context` field in your KubeConfig?

**Comment by cage1016** [comment]
![image](https://user-images.githubusercontent.com/678607/90731904-e6339e80-e2fc-11ea-87ae-4acff441fab1.png)

same issue. Set current context in Cloud Code > Kubernetes Explorer seems does not work.

**Comment by jmah-cc** [comment]
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-vscode-internal](https://github.com/GoogleCloudPlatform/cloud-code-vscode-internal/issues/3024)

**Comment by ChaseMor** [comment]
@cage1016 Did you use any `kubectl` commands or edit you KubeConfig file outside of the Kubernetes Explorer? And if you ran `kubectl config current-context` does it return `docker-desktop` like it should or does it say the context isn't set?

**Comment by cage1016** [comment]
@ChaseMor 

![image](https://user-images.githubusercontent.com/678607/90861005-a5e82500-e3bd-11ea-94ee-4992b304f431.png)

Yes, current-context has been set to `docker-desktop `

**Comment by ChaseMor** [comment]
@cage1016 I still can't seem to repro this. Do you have any repro steps for this? Perhaps things specific to your situation?

**Comment by kschaab** [comment]
@cage1016 - This might be related to an issue that was in docker, docker actually creates two entries in the kube/.config file.  It looks like you have docker-for-desktop and docker-desktop so probably not this, but would you mind checking to see if you have two contexts in the actual config file?  You can click the little button next to the Default KubeConfig node to pop up ~/.kube/config in VS Code.

**Comment by cage1016** [comment]
@kschaab 

![image](https://user-images.githubusercontent.com/678607/91924159-998c9200-ed04-11ea-8864-006115d2c78b.png)

the main cause is cloud-code-vscode seems could not resolve multiple kube config by enviorniment

```sh 
 export KUBECONFIG=$HOME/.kube/config:$HOME/.kube/retail.conf
```

After trial and error. It does work when I reload config at "Cloud Run - Kubernetes / Kubernetes explorer / Default KubeConfig" one by one

![image](https://user-images.githubusercontent.com/678607/91924359-056efa80-ed05-11ea-80bf-1db10d467427.png)

Thanks for your help

**Comment by sivakku** [comment]
The ask here is to support multiple kube configs in the path. This is a feature in our backlog. Going to close this one, do let me know if this is something you need and re-open of neeeded.
