### ISSUE TITLE
Kubernetes Explorer does not import any cluster configuration from {USER_HOME}/.kube/config

### ISSUE THREAD

**Issue by pavelbakh** [GoogleCloudPlatform/cloud-code-vscode#276]
**Environment**:
Extension version: 1.4.1
VSCode version: 1.47.3
OS: linux
Ubuntu 18.04

**Description**:
Kubernetes Explorer does not import any cluster configuration from {USER_HOME}/.kube/config

**Repro step**:
Bare VSCode installation with only Cloud Code extension
~.kube/config consists of only cluster configuration

**Comment by ChaseMor** [comment]
I can't seem to repro this. Does it populate with the correct information when you refresh the Kubernetes Explorer? How did you go about making the Kube config before you started using Cloud Code? Is it possible that it's not a completely valid config?

**Comment by kschaab** [comment]
Hi @pavelbakh - do you see any information at all, for example, is there an indicator at top with the config file loaded?  A screenshot would be helpful.

**Comment by pavelbakh** [comment]
Hi Chase,

thank you for the response.

Please have a look on the attached screenshots.

screenshot-1.png - Cloud Code - Kubernetes window

screenshot-2.png - Kubernetes window

screenshot-3.png - my .kube/config


Hope it helps.

Thanks,

Pavel

**Comment by pavelbakh** [comment]
Hi Keith,

thank you for the response.

Please have a look on the attached screenshots.

screenshot-1.png - Cloud Code - Kubernetes window

screenshot-2.png - Kubernetes window

screenshot-3.png - my .kube/config


Hope it helps.

Thanks,

Pavel

**Comment by ChaseMor** [comment]
Hey Pavel, it looks like the screenshots didn't go through. Would you mind responding with them embedded in your reply?

**Comment by shahasim** [comment]
Hi,

I have the same issue, Kubernetes explorer does not show anything. when I click on the refresh icon, I get the error "Component map not found". Please may you help.

I have also installed a kubernetes extension from Microsoft and it seems to work, as in it can pick info for my docker-desktop cluster.

 **Environment:**
Cloud code extension version: 1.4.1
VSCode version: 1.43.0
OS: macOS
Ubuntu 10.14.6

**~/.kube/config**
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: 
    server: https://kubernetes.docker.internal:6443
  name: docker-desktop
contexts:
- context:
    cluster: docker-desktop
    user: docker-desktop
  name: docker-desktop
- context:
    cluster: docker-desktop
    user: docker-desktop
  name: docker-for-desktop
current-context: docker-desktop
kind: Config
preferences: {}
users:
- name: docker-desktop
  user:
    client-certificate-data: 
    client-key-data: 

I have removed the values against **certificate-authority-data, client-certificate-data and client-key-data**

Thanks,
Asim

**Comment by vincentjocodes** [comment]
Hi @shahasim, are you on a Mac OS X or on Ubuntu? I see both listed. 

What is your `"cloudcode.autoDependencies"` settings set to? 

I tried repro'ing from my Mac OS X (having started Docker Desktop) but I don't see that error. I would like to get some more information from you on this. Thanks.

**Comment by shahasim** [comment]
Hi @vincentjocodes 

This setting cloudcode.autoDependencies is 'on', on my machine.

If you are unable to reproduce it, please don't spend time on it. I think I may have messed up my environment.

I was able to get around the issue, by completely uninstalling vscode i.e. removing the settings folder in $HOME.

Thanks for looking into it anyway :)

**Comment by vincentjocodes** [comment]
No problem @shahasim. Glad you got it figured out.

**Comment by vincentjocodes** [comment]
@pavelbakh Following up on your question.

**Comment by shahasim** [comment]
Hi @vincentjocodes,

I am following up on this, I've got the error "Component map not found" again. I believe i get this error when I am on my corporate VPN. I have http_proxy and other environment variables set in my bashrc and bash_profile. 

I dont have this problem with the vscode kubernetes extension. Please do let me know if you need information from me.

The ~/.kube/config file is same as the one pasted above, except that I have redacted **certificate-authority-data, client-certificate-data and client-key-data**.

thanks

**Comment by vincentjocodes** [comment]
@shahasim Hi shahasim, is your cloudcode.autoDependencies 'on'?  That error is encountered if we could not get list of components from gcloud.

**Comment by shahasim** [comment]
@vincentjocodes , I do have that setting 'on', from what you have suggested looks like cloud code needs internet access and I may need to configure http_proxy in vscode because I am on a vpn? I'll try this and update you.

**Comment by vincentjocodes** [comment]
@shahasim Yes that's possible. Some `gcloud` commands will need internet access even though they don't seem like they need it. Getting components might be one of them. Let us know.

**Comment by shahasim** [comment]
@vincentjocodes, that work around didn't work. I have my http_proxy variable setup in profile and vs code seems suggest it should the proxy settings from those env variables. However I am still getting component map not found error.

**Comment by vincentjocodes** [comment]
@shahasim Can you try the command `Users/<YOUR_USERNAME>/Library/Application Support/cloud-code/installer/google-cloud-sdk/bin/gcloud components list --format json`?

**Comment by shahasim** [comment]
@vincentjocodes , I get the following error, seems like my network is still blocking your services, even though I have proxy setup

ERROR: (gcloud.components.list) Failed to fetch component listing from server. Check your network settings and try again.

**Comment by vincentjocodes** [comment]
@shahasim Yes this looks like `gcloud` network calls are being blocked by your network. I would suggest checking with your network administrator? Cloud Code uses `gcloud` directly so it needs network access.

**Comment by shahasim** [comment]
@vincentjocodes, I have updated to v1.6.0 and I don't get the error anymore. I'll keep you posted in case this changes. knowing how stringent our networks and security team are I don't think I'll get very far with the request to change network settings. Given I am the only one using this extension so far

**Comment by jmah-cc** [comment]
Closing as this seems to have been fixed for the reporter. Please re-open if this issue pops up again.
