### ISSUE TITLE
docs: Additional dependencies Minikube

### ISSUE THREAD

**Issue by knowlet** [GoogleCloudPlatform/cloud-code-vscode#280]
**Environment**:
*(Hint: "Report Extension Issue on Github" command will fill these out for you.)*
Extension version: v1.5.0
VSCode version: 1.48.0
OS: linux
Ubuntu 20.04.1 LTS

**Description**:
After updating to v1.5.0 when you opt out of dependency management `cloudcode.auto-install` it will check if `minikube` installed.
```
minikube binary is not found.
```
The official installation guide does not mention it.
https://cloud.google.com/code/docs/vscode/install#prerequisites

**Repro step**:
1. Go to Extensions > Cloud Code > `Cloudcode: Auto Dependencies` and switch to off.
2. Install the [Additional dependencies](https://cloud.google.com/code/docs/vscode/install#additional_dependencies) as the guide mentions: `kubectl` and `Skaffold`
3.  `Show All Commands` and execute `>Cloud Code: Run on Kubernetes`
4. The detailed logs `Run/Debug on Kubernetes - Detailed` is empty and you will get a notify `minikube binary is not found.`

![image](https://user-images.githubusercontent.com/4388697/90621842-dbb6cd80-e246-11ea-93e5-a2ccbc883d2b.png)

**Comment by vincentjocodes** [comment]
Hi @knowlet,

I apologize for the inconvenience. 

Yes, the VSCode extension does need minikube for running local clusters (Cloud Run Emulator and if using minikube Kubernetes context). For now, I assume that the best way to install is through: https://kubernetes.io/docs/tasks/tools/install-minikube/. I will check with my team to double check and get back to you.

Thanks for bringing this to our attention. I will let the team know and see if we could get the docs updated.

**Comment by knowlet** [comment]
Hi @vincentjocodes,

In previous versions, I didn't use minikube because I was using k3d as my local cluster, but in the latest v1.5.0 release, I am forced to install it. I do solve this problem by installing minikube, but would like to know if in the future I can be reminded to install it only when needed.

**Comment by vincentjocodes** [comment]
@knowlet,

I see. I just spoke with my team and this is definitely a bug and we plan to address it. You shouldn't be required to install minikube if it isn't needed. Thanks for bringing it up.

**Comment by coldis** [comment]
Is there an update on this? We have been using skaffold to run our app on docker-desktop for a while now. I just tried to get started with Cloud Code and use the existing skaffold config, but am getting the same error of "minikube binary is not found"

**Comment by sivakku** [comment]
We are looking in to this one to do the validation.
