### ISSUE TITLE
Cloud Code fills my $ENV:TEMP directory with minikube files

### ISSUE THREAD

**Issue by TBBle** [GoogleCloudPlatform/cloud-code-vscode#286]
**Environment**:
Extension version: 1.5.0
VSCode version: 1.48.1
OS: win32

**Description**:

When the Cloud Code extension is enabled, it generates a new file in my `$ENV:TEMP` directory every few seconds, named something like _minikube.exe.au1-ww-002.CORP_p_hampson.log.INFO.20200825-083354.24568_.

The first is 897 bytes long, and contains what I assume is the output of `minikube --version` or similar.
```
Log file created at: 2020/08/25 08:32:10
Running on machine: au1-ww-002
Binary: Built with gc go1.14.6 for windows/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0825 08:32:10.644490   32892 translate.go:106] Setting Language to en-AU ...
I0825 08:32:10.648493   32892 translate.go:88] Failed to load translation file for en: Asset translations/en.json not found
I0825 08:32:10.648493   32892 out.go:190] Setting OutFile to fd 1068 ...
I0825 08:32:10.648493   32892 out.go:232] TERM=,COLORTERM=, which probably does not support color
I0825 08:32:10.648493   32892 out.go:203] Setting ErrFile to fd 1788...
I0825 08:32:10.648493   32892 out.go:232] TERM=,COLORTERM=, which probably does not support color
I0825 08:32:10.680489   32892 out.go:105] minikube version: v1.12.3
I0825 08:32:10.681490   32892 out.go:105] commit: 2243b4b97c131e3244c5f014faedca0d846599f5-dirty
```

The others are 928 bytes long, and contain what I guess is the output of `minikube --status` or similar.
```
Log file created at: 2020/08/25 08:33:54
Running on machine: au1-ww-002
Binary: Built with gc go1.14.6 for windows/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0825 08:33:54.851319   24568 translate.go:106] Setting Language to en-AU ...
I0825 08:33:54.855321   24568 translate.go:88] Failed to load translation file for en: Asset translations/en.json not found
I0825 08:33:54.855321   24568 out.go:190] Setting OutFile to fd 2304 ...
I0825 08:33:54.855321   24568 out.go:232] TERM=,COLORTERM=, which probably does not support color
I0825 08:33:54.855321   24568 out.go:203] Setting ErrFile to fd 1460...
I0825 08:33:54.855321   24568 out.go:232] TERM=,COLORTERM=, which probably does not support color
I0825 08:33:54.904322   24568 cli_runner.go:109] Run: docker ps -a --filter label=name.minikube.sigs.k8s.io --format {{.Names}}
I0825 08:33:55.024320   24568 out.go:105] {"invalid":[],"valid":[]}
```

I've confirmed that disabling the Cloud Code extension stops these files being created, and re-enabling it continues to do so.

I've not been able to find any relevant logs that would suggest a failure or error.

**Repro step**:
* Install Cloud Code extension in VS Code.
* Note that after a day or two, warnings are reported from Unreal Build Tool that `$ENV:TEMP` contains more than 10k files and this may affect build performance.

**Comment by jmah-cc** [comment]
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-vscode-internal](https://github.com/GoogleCloudPlatform/cloud-code-vscode-internal/issues/3047)

**Comment by kschaab** [comment]
@TBBle We aren't directly writing these logs to files.  I am investigating to see what is writing these logs, minikube or vs code.

**Comment by tstromberg** [comment]
minikube, through it's use of `glog`, saves a post-mortem log for every command-line invocation, but Cloud Code exacerbates the condition by calling "status" constantly. We should figure out a way to turn this off either by default or on demand.

Related to https://github.com/kubernetes/minikube/issues/9156

**Comment by ap0phi5** [comment]
I'm having this issue too, however I'm using Linux (Fedora 32).
500,000 files before /tmp was full.

```-rw-rw-r--. 1 xxx xxx  378 Sep 21 16:15 minikube.xxx.xxx.log.WARNING.20200921-161503.85189
-rw-rw-r--. 1 xxx xxx  948 Sep 21 16:15 minikube.xxx.xxx.log.INFO.20200921-161503.85189
lrwxrwxrwx. 1 xxx xxx   60 Sep 21 16:15 minikube.WARNING -> minikube.xxx.xxx.log.WARNING.20200921-161505.85201
lrwxrwxrwx. 1 xxx xxx   57 Sep 21 16:15 minikube.INFO -> minikube.xxx.xxx.log.INFO.20200921-161505.85201
-rw-rw-r--. 1 xxx xxx  378 Sep 21 16:15 minikube.xxx.xxx.log.WARNING.20200921-161505.85201
-rw-rw-r--. 1 xxx xxx  948 Sep 21 16:15 minikube.xxx.xxx.log.INFO.20200921-161505.85201```

**Comment by tstromberg** [comment]
@ap0phi5 - Thanks for the extra info. I've bumped up the priority of the associated minikube issue.

I do wonder how often VS Code is calling `minikube status` to fill things up so quickly.

**Comment by TBBle** [comment]
> minikube.xxx.xxx.log.INFO.20200921-161503.85189
> minikube.xxx.xxx.log.INFO.20200921-161505.85201

Every 2 seconds, I guess.

**Comment by logicalphase** [comment]
I timed at 2 files every 2 secs also. Awoke to a Ubuntu 20.04 workstation with more 224,000 status logs in /tmp had to reboot into a shell and mv /tmp to /tmp2 to boot the machine. Thank the heavens this got reported here. 😛

**Comment by FDFessler** [comment]
I am having this problem also!  Thanks goodness someone else has it and has reported it!
I am running Windows 10 (2004 build 19041.508)
VS Code info below (happened in multiple previous versions also):
Version: 1.49.2 (user setup)
Commit: e5e9e69aed6e1984f7499b7af85b3d05f9a6883a
Date: 2020-09-24T16:29:41.983Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

It does appear that disabling Cloud Code and relaunching VS Code solves the problem (for me)!
THANK YOU, THANK YOU, THANK YOU!

**Comment by raobystorm** [comment]
Community guys please do something! Otherwise uninstall cloud code from vs-code is my only option!

**Comment by kschaab** [comment]
We are going to hotfix this.  If you don't require minikube interaction through the status bar turning off the minikube status bar in settings will stop the behavior:  
![image](https://user-images.githubusercontent.com/7329029/96771290-4e067400-1396-11eb-8ea0-cec609e78335.png)

**Comment by redborian** [comment]
This has been fixed in our latest release.
