### ISSUE TITLE
WSL2: (1) Unable to load schema from 'k8s://schema/apps/v1, (2) No help on hover

### ISSUE THREAD

**Issue by agabhinav** [GoogleCloudPlatform/cloud-code-vscode#287]
**Environment**:
*(Hint: "Report Extension Issue on Github" command will fill these out for you.)*
Extension version: 1.5.1
VSCode version: 1.48.1
OS: 'Windows 10 Enterprise' Version 10.0.19041 with WSL 2 - ubuntu linux distro

**Description**:
**_Issue-1:_**
In VSCode on WSL2: Ubuntu, all kubernetes resources with apiVersion: apps/v1 (e.g. Deployment resource) show linting error on the first character. 'Unable to load schema from 'k8s://schema ...'
This doesn't happen in VSCode when run directly on the Windows host machine.
Also this error doesn't happen in WSL linux distro for resources using apiVersion: v1 (e.g. Pod)
Below screenshot shows this behavior - left is Windows 10 host and right is WSL: Ubuntu.

![image](https://user-images.githubusercontent.com/24555566/91206928-9161a080-e6cd-11ea-89ff-6b9c8171918c.png)

**_Issue-2:_**
Again, VSCode in WSL: Ubuntu doesn't show help on k8s resource. But it shows the help in VSCode directly on Windows 10. Below screenshot shows this issue.
![image](https://user-images.githubusercontent.com/24555566/91207072-cd950100-e6cd-11ea-95e7-6dd892708629.png)

Below is a list of extensions in my VSCode setup.
**> code --list-extensions**
googlecloudtools.cloudcode
ms-azuretools.vscode-docker
ms-vscode-remote.remote-containers
ms-vscode-remote.remote-wsl

**Cloud Code Yaml Support Output Stream**
[CloudCodeYamlSupportOutputStream.txt](https://github.com/GoogleCloudPlatform/cloud-code-vscode/files/5125399/CloudCodeYamlSupportOutputStream.txt)

**Repro step**:
1. Install VSCode Cloud Code extension.
2. Open VSCode in WSL2 linux distro. 
3. Create a new yaml file.
4. Create a new k8s resource such as Deployment (apiVersion: apps/v1)  using ctrl-space.
5. Observe the first character. -> Error: Unable to load schema from 'k8s://schema/apps/v1@Deployment':
6. Hover your mouse over anything in the yaml file. -> no help shown.
Note - these issues don't happen for resources using apiVersion: v1 even in WSL2 linux distro.

**Comment by jmah-cc** [comment]
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-vscode-internal](https://github.com/GoogleCloudPlatform/cloud-code-vscode-internal/issues/3048)

**Comment by redborian** [comment]
Thanks for reporting the issue @agabhinav. We will investigate and fix this in the upcoming release. We will also follow-up with any questions.

**Comment by redborian** [comment]
Hello @agabhinav, as I was investigating this issue, it seems that it doesn't repro in WSL2 Ubuntu environment. Here is a screenshot of a tooltip shown for a deployment resource in WSL2 Ubuntu (Windows 10 environment).
1. Will it be possible for you to try and repro with the latest build of Cloud Code?
2. Also, can you try creating a Job resource and see if you get the error? (which has apiVersion: batch/v1)

**Comment by agabhinav** [comment]
Hi.. After updating Cloud Code, I am not seeing those linting issues.
Regarding Job resource - I am not getting the error. However, when I just start typing Job, it is not auto-completing. But When I just type it manually then it is able to show the help for the Job resource and not showing any linting errors. Thank you.

**Comment by redborian** [comment]
Thanks for confirming the no-repro, @agabhinav. Regarding your comment about no snippet for "Job" resource type, we are actively expanding the snippets shipped with our extension and will add this in our subsequent releases.
