### ISSUE TITLE
Unable to remote debug a .Net Core service

### ISSUE THREAD

**Issue by bourquep** [GoogleCloudPlatform/cloud-code-vscode#289]
**Environment**:
Extension version: 1.5.1
VSCode version: 1.48.1
OS: darwin

- My runtime image is based on `mcr.microsoft.com/dotnet/core/aspnet:2.2` 
- The Linkerd proxy sidecar is deployed within the same Pod as my service

**Description**:

When trying to remote-debug a .Net Core service, I get an error at the `remoteProcessPickerScript` step.

**Repro step**:

- I have installed `vsdbg` and `procps` into my container, as per the [instructions](https://cloud.google.com/code/docs/vscode/debug-k8-pod#setting_up_a_container)
- I have created a VSCode launch configuration using the CloudCode extension (see `launch.json` content below)
- When I launch a debug session, I get the following error in `remote-attach` output (see below)
- If I copy/paste the `kubectl exec...` command from the `remote-attach` output into my terminal, it works (I get the output pasted below)

```json
// launch.json

{
  // Use IntelliSense to find out which attributes exist for C# debugging
  // Use hover for the description of the existing attributes
  // For further information visit https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger-launchjson.md
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Attach to Kubernetes Pod (.NET Core)",
      "type": "cloudcode.kubernetes",
      "request": "attach",
      "language": "NETCore",
      "podSelector": {
        "app": "foo",
        "service": "bar"
      },
      "localRoot": "${workspaceFolder}/services/foo",
      "remoteRoot": "/app"
    }
  ]
}
```

```bash
# Output

Executing: kubectl exec foo-84979cbdc-tqp4b -c foo --namespace foobar -i -- sh -s < "/Users/pascal/.vscode/extensions/ms-dotnettools.csharp-1.23.1/scripts/remoteProcessPickerScript"
Error Message: spawn /bin/sh ENOENT
```

```bash
# Output of manual command invocation in my terminal

Linux
        aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa 
      1 dotnet                                            dotnet Foo.dll
 298994 sh                                                sh -s
 299001 ps                                                ps -axww -o pid=,comm=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,args=
```

**Comment by bourquep** [comment]
I have just tried again after removing the Linkerd proxy sidecar, and getting the same error.

**Comment by bourquep** [comment]
I was able to make it work by opening the service's directory in VSCode, rather than opening the VSCode Workspace (which contains other services/projects).

Will try to figure out why.

**Comment by j-windsor** [comment]
Thanks for the investigation @bourquep!

It looks like our extension is generating the `kubectl` command correctly, but there might be some logic in the C# extension we are not privy to that might be contributing to this issue. It sounds like you got it working, but if you would like to further isolate the problem, here's some background: On debug request, we generate a C# debug request that looks like this:

```JSON
    {
      "name": ".NET Core Remote Attach",
      "type": "coreclr",
      "request": "attach",
      "processId": "${command:pickRemoteProcess}",
      "pipeTransport": {
        "pipeProgram": "kubectl",
        "pipeArgs": [
          "exec",
          "{{ POD NAME HERE }}",
          "-c",
          "{{ CONTAINER NAME HERE }}",
          "--namespace",
          "{{ NAMESPACE NAME HERE }}",
          "-i",
          "--"
        ],
        "debuggerPath": "/vsdbg/vsdbg",
        "quoteArgs": false
      }
    }
```

If you run this debug config, it might give you the same result.

**Comment by bourquep** [comment]
Thanks @j-windsor. After further investigation, it really looks like having a multi-csproj Workspace in VSCode doesn't play nicely with `launch.json` configuration files. I have been unable to get any variation of _remote attach_ configuration working in my workspace, while it is working fine when I open the project's directory in VSCode.

Closing.
