### ISSUE TITLE
Score Kubernetes Manifests

### ISSUE THREAD

**Issue by sunnygoel8** [GoogleCloudPlatform/cloud-code-vscode#291]
**Use case**
I want to validate and score Kubernetes manifests. Validating k8s manifest(s) will ensure that everything is correct. Scoring a k8s manifest will inform developers about missing sections such as liveness, readiness probes etc. and help them learn and adhere to Kubernetes best practices. 
**Feature**
2 separate features in Goocle Cloud code such as - 

"Validate Kubernetes Manifest" (developer will give K8s manifest folder as an input and it will validate all the manifests inside that folder and spit out the results in console)

"Score Kubernetes Manifest" ((developer will give K8s manifest folder as an input and it will score all the manifests inside that folder and spit out the results in console)

**Comment by sunnygoel8** [comment]
Hi @redborian , just wanted to know that is it being considered for future releases ? Please let me know. thanks

**Comment by redborian** [comment]
Thanks for suggesting an enhancement, @sunnygoel8. Missing/deprecated sections are already being highlighted through our current validation. Can you provide more details about the use case for scoring Kubernetes manifests?

**Comment by jmah-cc** [comment]
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-vscode-internal](https://github.com/GoogleCloudPlatform/cloud-code-vscode-internal/issues/3760)

**Comment by jmah-cc** [comment]
We already do the validation as redborian commented above. Scoring is an interesting idea, let us us discuss this internally and get back to you.

**Comment by sivakku** [comment]
Looking at the score of K8 manifests, it seems like a static linter to remind of what is missing based on what kube score(https://github.com/zegl/kube-score) does. Also makes me think why would you want it separately from the validation? if some of the validations are warnings. How do you plan to use the score in your dev tools?

**Comment by jmah-cc** [comment]
@sunnygoel8 Please provide a response to the comment above so we can scope this appropriately
