### ISSUE TITLE
.NET debugging broken

### ISSUE THREAD

**Issue by johnstairs** [GoogleCloudPlatform/cloud-code-vscode#292]
**Environment**:
Extension version: 1.5.2
VSCode version: 1.49.0
OS: linux

**Description**:
Attaching to a .NET process fails to open source file and highlight line when a breakpoint is it. 
But if I modify the dockerfile to copy the source files to a directory path that exactly matches the directory of the source code in my environment, then it works.

**Repro steps**:

1. Clone https://github.com/GoogleCloudPlatform/cloud-code-samples.git. 
1. Open VS code from the `dotnet/dotnet-hello-world` directory
1. Build the container image and create the deployment and service in a kubernetes cluster.
1. Attach to the process from using the VS code extension's "Attach to Kubernetes Pod" debugging configuration.
1. Open `src/Startup.cs` and set a breakpoint on `await context.Response.WriteAsync("Hello World!");`
1. Note that the red circle is cleared right away. In the breakpoints tab of the debug sidebar, it lists a breakpoint at `/src/Startup.cs`, which is not the correct path.
1. Hit the HTTP endpoint of the service.
1. The breakpoint is hit, but the line is not highlighted. Instead there is an error popup.

![image](https://user-images.githubusercontent.com/339432/93347875-9238ae80-f803-11ea-9f7f-17db4f765698.png)

Now if I modify the dockerfile to change the directory we copy the source files into from `/src` to the directory the source files are in my environment:

![image](https://user-images.githubusercontent.com/339432/93348647-7c77b900-f804-11ea-8b39-f774c8b6826a.png)

and repeat the experiment, debugging works as expected:
![image](https://user-images.githubusercontent.com/339432/93348515-4c301a80-f804-11ea-8e64-a0b82be55d01.png)

**Comment by GavinOsborn** [comment]
+1 Can confirm same behavior.

If I interpret @johnstairs images correctly he appears to be using VSO. I just wanted to drop a note to confirm that this also happens to me when running the dotnet samples (I used guestbook) locally in Minikube.

**Comment by GavinOsborn** [comment]
Hey folks,
Debugging .NET applications has been broken for at least 2 months now.
Can we expect some form of update soon? If not a fix then some kind of understanding of the situation?

//cc  @jmah-cc

**Comment by sivakku** [comment]
@GavinOsborn - We are investigating this one now and i will get back to you in a day or two.

**Comment by sivakku** [comment]
This will be coming in our next release.

**Comment by GavinOsborn** [comment]
Thank you for the update @sivakku .
