### ISSUE TITLE
Device not configured

### ISSUE THREAD

**Issue by ganeshmurthi** [GoogleCloudPlatform/cloud-code-vscode#293]
**Environment**:
*(Hint: "Report Extension Issue on Github" command will fill these out for you.)*
Extension version:v1.5.2
VSCode version:1.49.0
OS: MAC 10.15.6 (Catalina)

**Description**: I'm setting up the dev environment behind the proxy, I installed VS code and added extensions go, kubernetes, cloud code. I'm getting below error when I create application

/Users/XXXX/hello-world-1: Cloning into '/var/folders/pf/tshgkcl96w1f81kk16jqccr00000gq/T/tmp-97719xviKJQisBPAy'... fatal: could not read Password for 'http://XXXX@server.proxy.XXXX.com:XXXX': Device not configured

The proxy I'm using doesn't require authentication, but still its requiring authentication, I've added proxy in VS settings.xml but still no luck. 

Thanks in advance.

**Repro step**:

**Comment by ChaseMor** [comment]
@ganeshmurthi Were you able to find a solution to this? I don't think this is a Cloud Code issue. That's not an error message we use. If it's happening when the project is being cloned it might be an issue with git.

**Comment by sivakku** [comment]
Closing this one, as there is no response on it. Please add repro steps and re-open if this is something you need.
