### ISSUE TITLE
Unclear why Cloud Run emulator needs service and container name

### ISSUE THREAD

**Issue by averikitsch** [GoogleCloudPlatform/cloud-code-vscode#295]
It is not clear why the emulator needs a service and container name when running locally. 

Possible solution:
* This could be hidden in advance settings. 
* For use cases that do need this functionality, it would be best to have a tutorial or docs page to highlight it.

**Comment by jmah-cc** [comment]
After reviewing this ask again, it's not at the top of our priority list. We've added it to our Backlog. Leaving this issue open so other users can upvote this request.

**Comment by sivakku** [comment]
This issue will be addressed in March release of plugin.

**Comment by sivakku** [comment]
This is part of the v1.10.0 plugin update.
