### ISSUE TITLE
[Output Logging] Reduce k8s concepts in console for Cloud Run Fully managed users

### ISSUE THREAD

**Issue by averikitsch** [GoogleCloudPlatform/cloud-code-vscode#297]
Fully managed developers don’t necessarily have knowledge of containers or kubernetes tools. The product narrative is moving towards fully abstracting containers away from developers.

When running the Cloud Run emulator, Skaffold, Minikube, pods, deployments, etc are shown in the console. Users will be confused about what these are.

Expectation: Only show this print out in the debugging console

**Comment by sivakku** [comment]
Thanks @averikitsch. We went back and forth on what the user facing output logging would look like in the past(below screen shot) and recognize whether minikube needs to be there for cloud run (or) not.  We are working on re-organizing the user facing command output logging in our roadmap, that gives high level status and user can drill down further based on if they need more context on it (or) drill down on errors. 

![image](https://user-images.githubusercontent.com/16199637/104069867-72663580-51ba-11eb-84dc-8d52eb5631cd.png)

**Comment by sivakku** [comment]
This is a feature in the roadmap about re-iterating how we present status and important logs to user, coming out in the next quarter.

**Comment by kschaab** [comment]
We are looking at things that should make this easier, closing this for now.
