### ISSUE TITLE
Need Cloud Code docs for setting up project credentials

### ISSUE THREAD

**Issue by averikitsch** [GoogleCloudPlatform/cloud-code-vscode#299]
I am unable to find official documentation on how Cloud Code extracts project and credential details (from the terminal setup or potential other methods).

I would expect docs on:

* Setting up your Cloud Code environment
* With notes on how devs on a team can have individual GCP dev environment

**Comment by jmah-cc** [comment]
This should be in the Jan release.

**Comment by j-windsor** [comment]
@averikitsch just want to clarify. When you say...
> * With notes on how devs on a team can have individual GCP dev environment

We support the standard VS Code way of syncing launch configs, vscode settings, etc... with your team by checking in the `.vscode` directory. We also support syncing build configs by checking in the `skaffold.yaml` file. Are you looking for this to be documented somewhere or are you expecting other "dev environment" properties to be synced as well?

**Comment by averikitsch** [comment]
@j-windsor This comment was aimed at giving users an opinionated setup on how to setup a GCP project for individual development (like does a team share a project, how do permissions get setup to share a dev project) then how to setup individual permissions in Cloud Code.

**Comment by j-windsor** [comment]
We added some information around authentication and projects on [this page](https://cloud.google.com/code/docs/vscode/install). Let us know if this help! Closing for now.
