### ISSUE TITLE
[Feature] Deploy to Cloud Run Connected Cluster using Connected Gateway

### ISSUE THREAD

**Issue by treedy** [GoogleCloudPlatform/cloud-code-vscode#304]
**Environment**:
Extension version: 1.6.0
VSCode version: 1.49.2
OS: darwin

**Description**:
External or "attached" clusters with Cloud Run/Knative aren't shown in the Deployment platform list. This is inconsistent with the functionality in the Cloud Console. Images for comparison (and I double checked I was in the same project).
<img width="683" alt="Screen Shot 2020-10-01 at 10 45 51 AM" src="https://user-images.githubusercontent.com/1851066/94825687-73761280-03d4-11eb-8cdd-37744efda4c0.png">

<img width="659" alt="Screen Shot 2020-10-01 at 10 42 37 AM" src="https://user-images.githubusercontent.com/1851066/94825614-60634280-03d4-11eb-8610-e95f7bb91bd2.png">

**Repro step**:
Attach a non-GKE-on-GCP K8s cluster to the project (Anthos on-prem with Cloud Run enabled or an "attached cluster" with Knative installed).
Use Cloud Code's Deploy to Cloud Run command
Observe that the eligible cluster is not available.

**Comment by jmah-cc** [comment]
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-vscode-internal](https://github.com/GoogleCloudPlatform/cloud-code-vscode-internal/issues/3355)

**Comment by jmah-cc** [comment]
Looking at this for Jan release

**Comment by sivakku** [comment]
This one needs re-visiting of how we present private clusters to end user and then we can show those clusters as part of it. Going to add this to backlog of feature requests that we can look at.

**Comment by sivakku** [comment]
Closing this one since we don't have plans for supporting connected gateway in the short term for Cloud Run. Please re-open if an external customer runs into the issue.
