### ISSUE TITLE
Cloud Run Explorer doesn't list Cloud Run services deployed on attached clusters

### ISSUE THREAD

**Issue by treedy** [GoogleCloudPlatform/cloud-code-vscode#305]
**Environment**:
Extension version: 1.6.0
VSCode version: 1.49.2
OS: darwin

**Description**:
Cloud Run services that are deployed on attached clusters are not shown. This is inconsistent with what is displayed in the Cloud Console. Screenshots below.

**Repro step**:
Deploy a Cloud Run service to an attached cluster like an Anthos on-prem cluster with Cloud Run enabled.
Observe the service in the Cloud Console
Observe that the same service isn't listed in Cloud Code's Cloud Run Explorer

_Cloud Console_
<img width="1324" alt="Cloud Console" src="https://user-images.githubusercontent.com/1851066/94828909-f8aef680-03d7-11eb-9af9-2fcd5ca37921.png">

_Cloud Code_
<img width="255" alt="Cloud Code" src="https://user-images.githubusercontent.com/1851066/94828963-0b293000-03d8-11eb-865c-c9e0e388db9a.png">

**Comment by redborian** [comment]
Thanks for reporting the issue @treedy. If you could answer a few more questions, it would be helpful for us to troubleshoot this issue faster:
1. Do you observe this discrepancy consistently? Or is it a one-time thing?
1. Do managed cloud run instances show up correctly?
1. Does it show cloud run instances if you switch to a different project?

**Comment by treedy** [comment]
> Thanks for reporting the issue @treedy. If you could answer a few more questions, it would be helpful for us to troubleshoot this issue faster:
> 
> 1. Do you observe this discrepancy consistently? Or is it a one-time thing?
Consistently. The services from an attached K8s cluster have never shown there (CR services for managed CR and GKE on GCP clusters display as expected)
> 2. Do managed cloud run instances show up correctly?
Yes, no problem with managed cloud run instances
> 3. Does it show cloud run instances if you switch to a different project?
This will take some time to create a new project and connect another attached cluster

**Comment by jmah-cc** [comment]
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-vscode-internal](https://github.com/GoogleCloudPlatform/cloud-code-vscode-internal/issues/3356)

**Comment by jmah-cc** [comment]
This should be fixed in the next release (end of Jan timeframe)

**Comment by vincentjocodes** [comment]
Unfortunately, we cannot support listing on-premise Cloud Run services since there is not a consumable API that we can utilize.
