### ISSUE TITLE
`docker is not available in path. Ensure the latest version of docker is installed and available in the path.`

### ISSUE THREAD

**Issue by Jolg42** [GoogleCloudPlatform/cloud-code-vscode#309]
**Environment**:
Extension version: 1.6.0
VSCode version: 1.49.3
OS: darwin
Docker: Docker version 19.03.13, build 4484c46d9d

**Description**:
Impossible to debug or deploy from the extension even though I have the latest docker installed.

<img width="773" alt="Screenshot 2020-10-03 at 20 14 12" src="https://user-images.githubusercontent.com/1328733/94998981-4c773680-05b6-11eb-95f3-0a603266062c.png">
<img width="1261" alt="Screenshot 2020-10-03 at 20 14 34" src="https://user-images.githubusercontent.com/1328733/94998979-4aad7300-05b6-11eb-8f7a-c71c675bbaa8.png">
<img width="345" alt="Screenshot 2020-10-03 at 20 14 52" src="https://user-images.githubusercontent.com/1328733/94998978-497c4600-05b6-11eb-9e1d-bf27a849e516.png">

**Repro step**:
- Install gcloud sdk
- Install Cloud Code VS Code
- Click deploy to cloud run or run in emulator

**Comment by sujit-kamireddy** [comment]
Can you run the docker commands from the terminal in vscode?

**Comment by Jolg42** [comment]
@sujit-kamireddy Yes indeed, for example this is the output of `docker build .`
```
Sending build context to Docker daemon  270.8kB
Step 1/6 : FROM node:12-slim
12-slim: Pulling from library/node
abb454610128: Pull complete 
3dfc5a66c517: Pull complete 
8eb2c526284c: Pull complete 
5959e41dd3b6: Pull complete 
198ac4a2e944: Pull complete 
Digest: sha256:48fed529df5073cf92687ff8d4cd9140ab6cd84a9cae616b0f67226299fbf77e
Status: Downloaded newer image for node:12-slim
 ---> 544e10fd4863
Step 2/6 : WORKDIR /usr/src/app
 ---> Running in 7dd136459a33
Removing intermediate container 7dd136459a33
 ---> 6facbc02bb93
Step 3/6 : COPY package*.json ./
 ---> c127f2c89144
Step 4/6 : RUN npm install --production
 ---> Running in e7982f90a968
npm WARN nodejs-cloud-run-hello-world@0.0.1 No repository field.

added 98 packages from 93 contributors and audited 324 packages in 3.916s

1 package is looking for funding
  run `npm fund` for details

found 2 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
Removing intermediate container e7982f90a968
 ---> 514a4e1f5c8f
Step 5/6 : COPY . ./
 ---> eedd7d806b5f
Step 6/6 : CMD ["node", "index.js"]
 ---> Running in a562039cf32f
Removing intermediate container a562039cf32f
 ---> 12958e374eea
Successfully built 12958e374eea
```

**Comment by sujit-kamireddy** [comment]
Thats interesting. I have seen similar issue before, but it was for both terminal and the extension.
We use "which docker" to determine whether docker is installed or not, so there is not lot of magic there.

Have you tried closing and opening the vscode?

**Comment by Jolg42** [comment]
I also tried turning off an on my computer, without success 😅 
`which docker` returns `/usr/local/bin/docker`

The debug output of the extension only shows
```
Checking Docker Dependency Status.
Checking Docker Dependency Status.
Checking Docker Dependency Status.
```

Is there a way to make it more verbose? It doesn't really say if it was successful or not here.

**Comment by jmah-cc** [comment]
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-vscode-internal](https://github.com/GoogleCloudPlatform/cloud-code-vscode-internal/issues/3297)

**Comment by sujit-kamireddy** [comment]
Hmm.. Can you try opening vscode from a terminal that has the env vars?

**Comment by kschaab** [comment]
This will be fixed by a patch release in the near future.

**Comment by j-windsor** [comment]
The patch is out! Could you please try v1.6.1 of the extension and see if the update fixes the issue for you?

**Comment by Jolg42** [comment]
It does work! 🎊 

I had to uninstall the extension, reload VS Code and then install again but now it's doing its magic 😄 

![image](https://user-images.githubusercontent.com/1328733/96180735-27c67b80-0f33-11eb-8e33-16d8bf5d3961.png)

**Comment by chadbr** [comment]
The same thing just happened to me - 
I had to do an uninstall / reinstall of the extension to resolve it.

**Comment by guifeliper** [comment]
I have a similar issue today. I have to uninstall, kill all instances from vs code and install again.

**Comment by MaskyS** [comment]
Ran into this issue on MacOS 12.3 today- I didn't have Docker when I installed Cloud Code, and kept throwing this error  after Docker was installed/on path.

Reloading the window didn't help; just reinstalling Cloud Code also didn't work. Had to uninstall, kill VSCode, then install again.

**Comment by l3ra** [comment]
> Ran into this issue on MacOS 12.3 today- I didn't have Docker when I installed Cloud Code, and kept throwing this error after Docker was installed/on path.
> 
> Reloading the window didn't help; just reinstalling Cloud Code also didn't work. Had to uninstall, kill VSCode, then install again.

This worked for me. Thanks!
