### ISSUE TITLE
Cloud Run Emulator (.net) - Failed to find the VM status

### ISSUE THREAD

**Issue by jduplessis** [GoogleCloudPlatform/cloud-code-vscode#312]
**Environment**:
Extension version: 1.6.0
VSCode version: 1.50.0
OS: win32

**Description**:
I followed the instructions for getting started with VSCode. All seems well until I try to run/debug using Cloud Run Emulator. We tried on several different computers with the same end result.
![image](https://user-images.githubusercontent.com/2579639/95827637-44489500-0d34-11eb-92ed-a655acd59a0f.png)
![image](https://user-images.githubusercontent.com/2579639/95827859-9093d500-0d34-11eb-8e85-5d876b387a0b.png)

**Repro step**:

- Install VSCode
- Install CloudCode Extention and dependencies
- Create new .net CloudRun application
- Run/Debug using Cloud Run Emulator

**Comment by jduplessis** [comment]
Results of `minikube.exe docker-env --shell none -p cloud-run-dev-internal --alsologtostderr`

![image](https://user-images.githubusercontent.com/2579639/95828197-f6805c80-0d34-11eb-8fd1-db7823ed1465.png)

**Comment by kschaab** [comment]
@jduplessis we think this is related to an issue we are patching soon.

**Comment by jduplessis** [comment]
Thanks @kschaab.

**Comment by j-windsor** [comment]
The patch is out! Could you please try v1.6.1 of the extension and see if the update fixes the issue for you?

**Comment by jduplessis** [comment]
Problem solved thanks!
