### ISSUE TITLE
Minkube being repeatedly started and stopped every 3 seconds

### ISSUE THREAD

**Issue by asampal** [GoogleCloudPlatform/cloud-code-vscode#313]
**Environment**:

Extension version: 
1.6.1

VSCode version:
Version: 1.51.0-insider (user setup)
Commit: 89c002ab02f87102d91efc83c191ef1174756c6a
Date: 2020-10-15T23:17:08.035Z
Electron: 9.3.2
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

OS: 
OS Name	Microsoft Windows 10 Pro
Version	10.0.19041 Build 19041

Docker Desktop:
![image](https://user-images.githubusercontent.com/281639/96355431-9f211a00-10af-11eb-8280-a2578dca49d2.png)

**Description**:
Minikube continuously starts and restarts about every 3 seconds. This happens  at any time, i.e. even before the k8s cluster is started from the status bar,  through the time that the cluster is running and continues after the cluster is stopped. Note that the `docker-desktop` cluster is also running all the while.

![minikube-restarting](https://user-images.githubusercontent.com/281639/96355493-41410200-10b0-11eb-8a03-3b6b0868fcb3.gif)

**Repro step**:
Install the above versions of VSCode, the extension, and Docker Desktop and monitor the running processes.

**Comment by kschaab** [comment]
I think this is a call to minikube status, it shouldn't be starting anything, are you seeing it start something?

**Comment by asampal** [comment]
No, there's nothing visual - where should I look?

**Comment by asampal** [comment]
If you look at the command line, it looks like it's doing both `minikube profile list` and `minikube status`.

![1 12-29-20-6507](https://user-images.githubusercontent.com/281639/97029837-f6017600-152b-11eb-9b29-ec8653427828.png)

![13 12-29-20-9307](https://user-images.githubusercontent.com/281639/97030026-3660f400-152c-11eb-98ef-06b57cdf0536.png)

**Comment by kschaab** [comment]
Yes, we are looking at ways to address this.

**Comment by asampal** [comment]
Just noticed now that when this open/close happens lots of log files are created - there were about 140 000. Including a zip containing what was emitted over just one minute.

[minikube.exe.logs.zip](https://github.com/GoogleCloudPlatform/cloud-code-vscode/files/5432263/minikube.exe.logs.zip)

**Comment by sivakku** [comment]
@asampal - We are working on releasing a hotfix soon that would address this issue. Thank you for your patience.

**Comment by redborian** [comment]
The hotfix has been released. Feel free to try the latest release and provide feedback @asampal

**Comment by asampal** [comment]
Thanks, for the heads-up. I use the Insiders version so I got the fix immediately. Seems fine now.
