### ISSUE TITLE
Regions are not available when I use "Deploy to Cloud Run"

### ISSUE THREAD

**Issue by jwlee98** [GoogleCloudPlatform/cloud-code-vscode#314]
**Environment**:
*(Hint: "Report Extension Issue on Github" command will fill these out for you.)*
Extension version: 1.6.1
VSCode version: 1.50.1
OS: 10.15.6

**Description**:
After I developed sample application, I could not find out new launched region like asia-northeast3(Seoul) in the combobox like below

![image](https://user-images.githubusercontent.com/6903812/96832486-cbef7b80-1479-11eb-8b40-3d6d9b605cf6.png)

As you've already know, asia-northeast3 (Seoul, South Korea) is already launched. 
https://cloud.google.com/run/docs/release-notes#October_19_2020

**Repro step**: Click "Deploy to Cloud Run" then check regions in deployment platform.

**Comment by go-nelango** [comment]
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-vscode-internal](https://github.com/GoogleCloudPlatform/cloud-code-vscode-internal/issues/3429)

**Comment by go-nelango** [comment]
This is being tracked here - https://github.com/GoogleCloudPlatform/cloud-code-vscode-internal/issues/3428

**Comment by redborian** [comment]
This has been fixed in our latest release.
