### ISSUE TITLE
Deploy to Cloud Run fails to load due to  missing permission "container.clusters.list"

### ISSUE THREAD

**Issue by hadi-muhammad** [GoogleCloudPlatform/cloud-code-vscode#318]
**Environment**:
Extension version: 1.7.0
VSCode version: 1.50.1
OS: Mac OS Catalina 10.15.3

**Description**:
"Deploy to Cloud Run" does not open this view:
![image](https://user-images.githubusercontent.com/68080827/97760892-a518f100-1ada-11eb-9b4b-742471235780.png)

Instead following error message is show in the window:
```
Failed to fetch cloud run services of the project my-secretporject-dev-4819. Error: Required "container.clusters.list" permission(s) for "projectsmy-secretporject-dev-4819".
```
below is my log:
```
Checking Docker Dependency Status.
Retrieving builders.
Getting Gcloud Login State.
Getting Gcloud Project ID.
Checking Cloud Run API status.
Getting Cloud Run Services for project "my-secretporject-dev-4819".
Failed to fetch cloud run services of the project my-secretporject-dev-4819. Error: Required "container.clusters.list" permission(s) for "projects/my-secretporject-dev-4819".
```

**Repro step**:
1) click on `Cloud Code` status bar
![image](https://user-images.githubusercontent.com/68080827/97761406-05f4f900-1adc-11eb-91fb-0e88dfbef105.png)
2) select `Deploy to Cloud Run`
![image](https://user-images.githubusercontent.com/68080827/97761458-245af480-1adc-11eb-969b-57e9b141a5f8.png)

I have `run.admin` role in the project
Anthos and GKE are disabled in the project due to org policies

**Comment by sivakku** [comment]
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-vscode-internal](https://github.com/GoogleCloudPlatform/cloud-code-vscode-internal/issues/3708)

**Comment by sivakku** [comment]
@hadi-muhammad - Disabling the GKE on the project disables the default default permission list(container.clusters.list) for the project and we probably are failing when trying to list all the clusters(for Anthos) under the project. We are investigating and looking to fix not to query for Anthos clusters if the permission to list is disabled in the upcoming release. in the short time you can try the workaround of enable GKE on the service account on the project that would temporarily get you all the permissions needed for deploying to Cloud Run.

**Comment by Wijnko** [comment]
I second this issue. Only having cloud run permissions, I cannot even list the cloud run services in the cloud run explorer. I can get a list of services by running the command `gcloud run services list`, but in the Cloud Run Explorer I get: 

![image](https://user-images.githubusercontent.com/17784946/100845509-a5abfb00-347d-11eb-9208-0dca5bbd5394.png)

**Error: Required "container.clusters.list" permission(s) for "projects/xxxxxxxx".**

**Environment:**
Extension version: 1.7.0
VSCode version: 1.51.1
OS: Mac OS Catalina 10.15.6

**Comment by sivakku** [comment]
This will be addressed in the next release.
