### ISSUE TITLE
Marketplace README out of date

### ISSUE THREAD

**Issue by seanmcbreen** [GoogleCloudPlatform/cloud-code-vscode#321]
The marketplace images are now quite out of date vs. the current state of the product.  Perhaps we could grab some from the docs that are up-to-date.

Some I noticed:
- The hero animated GIF does not have the minikube status bar entry or the activity bar icons.
- The API animated GIF shows the API manager in it's old location within the K8s explorer

**Comment by sivakku** [comment]
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-vscode-internal](https://github.com/GoogleCloudPlatform/cloud-code-vscode-internal/issues/3548)

**Comment by sivakku** [comment]
We are going to follow up as part of V1.8.0 release.

**Comment by vincentjocodes** [comment]
Released as part of v1.8.0
