### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Dmarch28** [GoogleCloudPlatform/cloud-code-vscode#323]
- Issue Type: `Performance`
- Extension Name: `cloudcode`
- Extension Version: `1.7.0`
- OS Version: `Windows_NT x64 10.0.14393`
- VSCode version: `1.51.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\ADMINI~1\AppData\Local\Temp\googlecloudtools.cloudcode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by kschaab** [comment]
Thanks for the report, we'll take a look.

**Comment by kschaab** [comment]
Will you please send the profile or provide a reproduction of the issue?

**Comment by jmah-cc** [comment]
Closing this as we haven't seen a response in a few weeks. Please re-open with the logs asked for above.
