### ISSUE TITLE
[Arm64 Support] Getting ERR_INVALID_ARG_VALUE in Cloud code

### ISSUE THREAD

**Issue by beingminimal** [GoogleCloudPlatform/cloud-code-vscode#327]
![Screenshot from 2020-11-11 18-39-43](https://user-images.githubusercontent.com/19903008/98817746-9a524a80-2450-11eb-8989-386a839951eb.png)
**Environment**:
*(Hint: "Report Extension Issue on Github" command will fill these out for you.)*
OS: Linux arm64 5.8.0-1007-raspi
Node: 12.14.1
Chrome: 83
VS Code: 1.51.0

**Description**:
We are trying to use Cloud code extension on given environment and we are getting below error

`[Extension Host] 'gcloud config config-helper --format json --quiet' (managed) took 18ms and resulted in error: 'TypeError [ERR_INVALID_ARG_VALUE]: The argument 'file' cannot be empty. Received '''
notificationsAlerts.ts:38 TypeError [ERR_INVALID_ARG_VALUE] [ERR_INVALID_ARG_VALUE]: The argument 'file' cannot be empty. Received ''`

**Comment by kschaab** [comment]
@beingminimal Do you have Auto Dependencies turned off (below for reference)?

![image](https://user-images.githubusercontent.com/7329029/98980735-e09bbe00-24d1-11eb-8136-770f1eb201ed.png)

**Comment by beingminimal** [comment]
Hi @kschaab , 
Yes, the auto dependencies configuration is on.

Thanks

**Comment by kschaab** [comment]
@beingminimal Would you mind running `/Users/[username]/Library/Application\ Support/cloud-code/installer/google-cloud-sdk/bin/gcloud config config-helper --format json --quiet` to see what occurs?  We plan on releasing a small update next week that will have more instrumentation that might provide us with more information on this error.  Let's see if that command works, if not we can see about getting out a prerelease version of the extension which would give us more information.

**Comment by kschaab** [comment]
This might be the same issue as #310.

**Comment by beingminimal** [comment]
Hi @kschaab , sure we can run this command but can you please provide linux path for the same?

**Comment by kschaab** [comment]
On linux it is `rm -rf ~/.cache/cloud-code`

**Comment by beingminimal** [comment]
Hi @kschaab, ok we will try again after removing cloud-code cache and let you know the results soon

**Comment by beingminimal** [comment]
Hi @kschaab ,

I ran your command but getting same error. 
After spending some time with logs, I found that google cloud SDK is not supported in ARM processor.
 gcloud architecture check failed Unsupported architecture: linux/arm64.

Is there any way or workaround to deal with this error to use Cloud code extension in vscode?
(Raspberry Pi OS: Linux arm64 5.8.0-1007-raspi)

Thanks

**Comment by sivakku** [comment]
Our extension doesn't work on ARM processor and we are working on fixing the dependencies needed like docker, minikube, gcloud compatible with arm64 and as soon as the timelines are clear i will update back.

**Comment by sivakku** [comment]
This is tracked through #390

**Comment by timfallmk** [comment]
@sivakku This would seem to be slightly different than #390 as it involves support of `linux/arm64` systems rather than `darwin/arm64`. Aside from a separate download issue for M1 macs (there's an issue filed for that one) the extension still throws the above error on linux arm64 machines.
