### ISSUE TITLE
Allow loading a kubeconfig file from a non default location

### ISSUE THREAD

**Issue by PierreBesson** [GoogleCloudPlatform/cloud-code-vscode#34]
## Motivation and use case
This is my understanding that the extension executes `kubectl` behind the scenes. As such the kube-config file used is the default `~/.kube/config` with no ability to use a different one. 

When managing several clusters, it is frequent to have several of those kube-config files on your machine and to frequently switch between them. The ways to switch between them is to use `kubectl --kubeconfig=/path/to/kubeconfig` or set the `KUBECONFIG` environment variable to a different path.

## Description of the feature request

Allow the user to "load" a kube-config file which would adapt the context of the Kubernetes Cluster Explorer view.

**Comment by moltar** [comment]
This is a must-have feature IMO.

When I spin up development clusters, I never co-mingle the config files to prevent accidents.

I find myself  often spinning up clusters via `k3s` and putting the config in `/tmp/kubeconfig.json` or inside the dir I am currently working in.

Would be great to be able to:

- Define the default location per project in `.vscode/settings.json` file
- Load any config file at will via Cluster Explorer
- Load any config file at will via command palette

Thanks!

**Comment by iantalarico** [comment]
This is great feedback everyone, thank you!  We will be sure to get this into a future release.

Out of curiosity:
- How many kubeconfig files do each of you work with?
- Do you ever want to work with multiple kubeconfig files at the same time?

**Comment by moltar** [comment]
> How many kubeconfig files do each of you work with?

3-5 of which ~ 2 are ephemeral just for testing deployments / manifests.

> Do you ever want to work with multiple kubeconfig files at the same time?

Just to clarify, do you mean "loaded in the sidebar at the same time", or in an abstract way?

I might be working with a couple of clusters at the same time in different term tabs.

I think having the ability to expand/collapse multiple clusters in the sidebar could be good.

The way I see it, one should be able to just add a cluster config OR context to the sidebar and be able to expand/collapse it at will.

**Comment by iantalarico** [comment]
Sorry I should have been more clear. I mean in the sidebar.

Thanks for the info!

> The way I see it, one should be able to just add a cluster config OR context to the sidebar and be able to expand/collapse it at will.

I like it!

**Comment by quoctruong** [comment]
This is now available in the latest release of the extension. Please try it out!

![AddKubeConfigPathNew](https://user-images.githubusercontent.com/4371645/62172652-dc9d5a00-b2e7-11e9-9aef-596177a62b90.gif)

**Comment by redborian** [comment]
Thanks @quoctruong! I will go ahead and close this issue now.

**Comment by moltar** [comment]
Awesome, thanks 😁
