### ISSUE TITLE
Cannot view pods when missing events permission

### ISSUE THREAD

**Issue by forivall** [GoogleCloudPlatform/cloud-code-vscode#345]
Issue Type: <b>Bug</b>

When i open the kubernetes explorer, i see the namespaces, but i cannot view the pods inside the namespace and I see the error: "events is forbidden: User "emily" cannot list resource "events" in API Group "" in the namespace "<namespace name>"

Extension version: 1.7.0
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-11T01:11:34.018Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.13GB free)|
|Process Argv|--crash-reporter-id 8fe9c0a9-e20f-435b-9c29-daef6bc63196 --max-memory=4096 --crash-reporter-id 8fe9c0a9-e20f-435b-9c29-daef6bc63196|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by vincentjocodes** [comment]
Hello forivall, 

It seems that `kubectl` is trying to fetch a resource from an empty `namepace ""`. In your UI, which under which namespace did you try to view your pod from?

**Comment by j-windsor** [comment]
Also, can you run `kubectl get Event` on the cluster and paste the result here? Just making sure what is happening behind the scenes works.

**Comment by sivakku** [comment]
Closing this as we haven't seen a response in a few weeks. Please re-open with the details asked above.

**Comment by forivall** [comment]
Sorry i didn't reply, i lost track of my notifications and i've since been given the permissions to view the resources - as i'm a newbie to k8s (and that's why this extension is great!), i don't have enough understanding to set up a minimal reproduction case.
