### ISSUE TITLE
Could not login to Google Cloud SDK in Google Cloud Shell

### ISSUE THREAD

**Issue by nampdn** [GoogleCloudPlatform/cloud-code-vscode#347]
**Environment**: Extension version: 1.7.0 VSCode version: 1.51.1 OS: linux **Description**: **Repro step**:
- Follow instruction at:
https://cloud.google.com/code/docs/vscode/quickstart-remote-dev#node.js

- Stuck at: Click here to login to Google

- It's seem like the extension could not understand gcloud config in remote development Google Cloud Shell

**Comment by sivakku** [comment]
We can reproduce this on our end, we are investigation the issue further.

**Comment by kschaab** [comment]
A fix is rolling out for this, it will be fixed on the server end, so it does not require an update to the extension.
