### ISSUE TITLE
Cloud code removes the proxy-url flag from kubeconfig

### ISSUE THREAD

**Issue by tvvignesh** [GoogleCloudPlatform/cloud-code-vscode#348]
**Description**:

I use `proxy-url` flag in my kubeconfig which was introduced in `v1.19` of Kubectl (https://github.com/kubernetes/client-go/issues/351) since I access the cluster via a Bastion host. Now the problem is that, if I add the `proxy-url` flag in the config and switch the cluster context in the cluster explorer, the `proxy-url` flag gets removed from the kubeconfig which is very inconvenient since I have to add it again and again.

Also, since cloud code ships with older dependencies, I had to add `"cloudcode.autoDependencies": "off"` in settings and then make this work by installing the binaries manually.

I guess you are running `get-credentials` using gcloud sdk every time a user tries to switch context which replaces the `proxy-url` flag. I had filed a bug few months back here: https://issuetracker.google.com/issues/170232045 which was closed saying its the intended behavior but I feel that it shouldn't be since I don't know why kubeconfig is modified automatically patched even when changed manually.

**Repro step**:

1. Add a `proxy-url` flag to kubeconfig for accessing the cluster via bastion
2. Switch contexts in the extension
3. proxy-url flag disappears from the config

**Environment**:
Extension version: v1.7.0
VSCode version:
```
Version: 1.52.0-insider (user setup)
Commit: 5e350b1b79675cecdff224eb00f7bf62ae8789fc
Date: 2020-12-04T10:15:27.849Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.20201
```

```
Google Cloud SDK 319.0.0
alpha 2020.11.13
beta 2020.11.13
bq 2.0.62
core 2020.11.13
gsutil 4.55
kubectl 1.15.11
minikube 1.14.0
skaffold 1.14.0
```

OS: Windows 10 Home Host, Ubuntu 20.04 remote

**Comment by j-windsor** [comment]
Thanks for reporting this. I can repro your issue.

We are actually not running `get-credentials` on switching the current cluster. We are actually just simply running `kubectl config use-context`. I can repro the case where if you use the (old) version of kubectl that ships as a Cloud SDK component, the proxy-url field disappears. However, if I use the latest kubectl, I do not experience this issue in Cloud Code.

Could you please make sure that you have the latest kubectl in your `PATH`. If you have turned off managed dependencies, this is the kubectl that will be used.

**Comment by tvvignesh** [comment]
@j-windsor Hi. Thanks for your response. I can confirm that it works after I add `"cloudcode.autoDependencies": "off"` to the config. The `proxy-url` flag is no longer removed with the latest kubectl as you said.

I had been testing with Kind so far and switched to trying Cloud Code with GKE, and I get an error saying

<img width="245" alt="1" src="https://user-images.githubusercontent.com/1165845/101417768-5567e980-3912-11eb-8a88-582d3e0a50ae.PNG">

While I can install minikube, is minikube binary needed for Cloud code to work with GKE?

**Comment by tvvignesh** [comment]
@j-windsor Never mind. Just noticed that its already an open issue here: https://github.com/GoogleCloudPlatform/cloud-code-vscode/issues/280

Thanks.

**Comment by j-windsor** [comment]
Thanks! Closing
