### ISSUE TITLE
Ability to attach to a running pod

### ISSUE THREAD

**Issue by tvvignesh** [GoogleCloudPlatform/cloud-code-vscode#350]
**Use case**
Cloud code currently works well for the cases where I set cleanup to be true where the deployments are cleaned up after I press stop. But since I wanted to have the deployment running even after I exit from it, I had set cleanup to be false.

Now, while this works, every time I do `Run on Kubernetes`, it creates a new replica which is not what I want.

<img width="147" alt="1" src="https://user-images.githubusercontent.com/1165845/101564149-9d5d3e00-39f0-11eb-97ef-e88ac85ab381.PNG">

**What I wanted to do is this:**

1. Do run on kubernetes for the first time -> Deployment is ready and it watches my directory
2. I keep doing changes and then finally stop watching and the deployment keeps running in the background (this works so far)
3. I close VSCode and probably come back after some time and again do `Run on Kubernetes`
4. Now, I would like to do exactly the steps 1 and 2 without creating a new replica. I just want to restart the watcher and continue working where I left off. Currently new replica is created everytime I do run on kubernetes.
5. And if I go to debug mode, watch is disabled as per the design. So, I can't do that as well.

**Feature**
Ability to attach and resume watch (not debug) on an existing deployment without creating a new replica would be great.

Thanks.

**Comment by tvvignesh** [comment]
I may be wrong here, since the replica is getting scaled down back to 1 after some time. Closing this now. Will reopen this if I see this again. Thanks.

**Comment by tvvignesh** [comment]
Faced this again. 5 replicas got created even when the files I changed matched the sync rules.

<img width="398" alt="e1" src="https://user-images.githubusercontent.com/1165845/101566327-cd0e4500-39f4-11eb-9d14-40578913e313.PNG">

Anything I may be doing wrong? Thanks. Reopening this for now.

**Comment by j-windsor** [comment]
This might be what you are looking for. https://cloud.google.com/code/docs/vscode/debug-k8-pod

You can use the `cloudcode.kubernetes` `attach` request to attach the debugger to a running pod.

**Comment by tvvignesh** [comment]
@j-windsor I had tried using the debugger before and it worked well, but the problem is that debugger does not enable watch mode. It wont pick up changes and live sync my files if I attach with debugger.

**Comment by j-windsor** [comment]
Hmm ok I see what you mean here. It sounds like you want a to do a "Run on Kubernetes" without the first deployment? Is that correct?

I am curious as to what you are trying to accomplish with such a feature. It is rolling out the replicas in the normal way K8s would for a deployment to avoid downtime, and we want to make sure when a user runs they have the most up to date code deployed. Additionally, you will get the same scaling behavior the first time you save a file when you are "Running on Kubernetes" so you only save one deploy cycle.

Also, we are not attaching anything to the pod when doing a "Run on Kubernetes". It is a unidirectional build and deploy to the cluster.

**Comment by tvvignesh** [comment]
@j-windsor Thanks for your reply. Let me clarify. 

> you want a to do a "Run on Kubernetes" without the first deployment? Is that correct?

I want to do a `Run on Kubernetes` everytime but do the deployment only for the first time (since my commit sha has not changed) and on subsequent runs just attach the watcher and live sync whenever I do `Run on Kubernetes` avoiding the need to redeploy and waiting for it to scale down. The problem is that, while the **eventual state** looks fine (having 1 replica as specified in the deployment file), it takes close to 6 minutes for the deployment to scale down if you see below. It scales up and then down by the GKE controller.

<img width="470" alt="1" src="https://user-images.githubusercontent.com/1165845/101677657-dc3bd400-3a82-11eb-9978-2e91dd8c8001.PNG">

While this would be fine for a prod environment, I don't want old replicas to stay during development cycle since my API calls give me old responses because of load balancing from the old replicas and I have to wait for close to 6 minutes for it to scale down to 1. I always want to have 1 replica having the latest code I write whenever I do run on kubernetes. And maybe the deployment can happen if the commit sha has changed or if I change files which are not part of live sync.

Hope this clarifies.

**Comment by tvvignesh** [comment]
@j-windsor OOPS! Digged a bit more into this. This issue might be due to the HPA I have. Just checked it and I see this:

<img width="761" alt="1" src="https://user-images.githubusercontent.com/1165845/101684936-288c1180-3a8d-11eb-9bc7-36cec04dadf4.PNG">

I will check this a bit more and will close this issue again if this is the case. Thanks.

**Comment by tvvignesh** [comment]
Just looked into it. The issue with replicas only occur if I have a hpa in my cluster and I am using Skaffold in dev mode. If I disable the hpa, I don't see this issue. 

Also, as I see now a new deployment is always made whenever I do Run on Kubernernetes. But considering I need not wait for 5-6 minutes for the scaling down to happen, I guess I can work with this. But a possible issue which you might want to take a look at is, why skaffold creates many replicas when HPA is enabled (even when I have not hit the `targetCPUUtilizationPercentage`. This was my config:

```
maxReplicas: 5
minReplicas: 1
targetCPUUtilizationPercentage: 70
```

**Comment by j-windsor** [comment]
Hmm I am not sure. This is something best answered by the skaffold team. Can you [file an issue](https://github.com/GoogleContainerTools/skaffold/issues) with them if you believe this is a bug on their side?

**Comment by tvvignesh** [comment]
@j-windsor Sure. Have filed it here: https://github.com/GoogleContainerTools/skaffold/issues/5136

**Comment by j-windsor** [comment]
Looks like they have prioritized this bug on their side! Are we good to close this?

**Comment by tvvignesh** [comment]
@j-windsor Sure. Thanks
