### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by fachrisdakbar** [GoogleCloudPlatform/cloud-code-vscode#354]
- Issue Type: `Performance`
- Extension Name: `cloudcode`
- Extension Version: `1.7.1`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.52.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\Fiddin\AppData\Local\Temp\googlecloudtools.cloudcode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by quoctruong** [comment]
@fachrisdakbar Thank you for filing the bug. May I ask whether you can provide the details on what you are trying to do with the extension while the high CPU load happens?

**Comment by j-windsor** [comment]
Please reopen with more information. Thanks!
