### ISSUE TITLE
Debugger thinks *local* file is in project root, even with localRoot set

### ISSUE THREAD

**Issue by samdoeswork** [GoogleCloudPlatform/cloud-code-vscode#355]
**Environment**:
*(Hint: "Report Extension Issue on Github" command will fill these out for you.)*
Extension version: 1.7.1
VSCode version: 1.52.1
OS:  Win10 Pro

**Description**:
Connecting a debugger to a kubernetes instance using either method (Attach to Kubernetes Pod or Debugging a Kubernetes Application) I am able to see debug output, mapped correctly to TypeScript lines.

Clicking on a line of debug-output shows that VSCode thinks my local code is in the root of the application directory.

I've tried a few things including:
(for attach to pod) "localRoot": "${workspaceFolder}/k8s/mainBatch".
(for debug kubernetes app): "sourceFileMap": "${workspaceFolder}": "${workspaceFolder}/k8s/mainBatch"

**Repro step**:

**Comment by quoctruong** [comment]
Hi @samdoeswork, for the `sourceFileMap`, the key is the local folder and the value is the remote folder. So can you try `"${workspaceFolder}/k8s/mainBatch"` for the key and your remote folder as the value?

**Comment by samdoeswork** [comment]
Hi,
Thank you for coming back quickly on this.
I tried this a few times, including trying different formats:

"debug": [
                {
                    "image": "gcr.io/justaddfeatures-203400/mainbatch_dev",
                    "sourceFileMap": {
                        "${workspaceFolder}\\k8s\\mainBatch": "/",
                        "${workspaceFolder}/k8s/mainBatch": "/",
                        "${workspaceFolder}\\k8s\\mainBatch\\": "/",
                        "${workspaceFolder}/k8s/mainBatch/": "/"
                    },
                },
                {
                    "image": "gcr.io/justaddfeatures-203400/sendbatch_dev",
                    "sourceFileMap": {
                        "${workspaceFolder}/k8s/sendBatch": "/"
                    },
                }
            ]

Unfortunately this did not succeed.

**Comment by samdoeswork** [comment]
Is there any documentation around this feature. I'd been trying to fix this all day>

Perhaps it's possible to set a wildcard, or otherwise force it? Nothing I've done so far has had any affect at all. I can't confirm that sourceFileMap is even being parsed.

**Comment by j-windsor** [comment]
since you are using typescript, it you might have to specify your tsc output folder as the localRoot. For example, something like:
```json
"sourceFileMap": {
    "${workspaceFolder}/k8s/sendBatch/dist": "/"
}
```

Could you also make sure your typescript is generating sourcemaps in your out directory?

**Comment by kschaab** [comment]
@samdoeswork please do let us know if tuning tsc output helped.

**Comment by vincentjocodes** [comment]
We'll close this one due to inactivity. Please feel free to open it back up again if you have any more concerns.
