### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by forsaken-x2x** [GoogleCloudPlatform/cloud-code-vscode#357]
- Issue Type: `Bug`
- Extension Name: `cloudcode`
- Extension Version: `1.7.1`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.52.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by j-windsor** [comment]
Please reopen with more details. Thanks!
