### ISSUE TITLE
Debugging Go on Kubernetes does not find the source code

### ISSUE THREAD

**Issue by tommazzo89** [GoogleCloudPlatform/cloud-code-vscode#358]
Hi everyone,

**Environment**:
Extension version: 1.7.1
VSCode version: 1.52.1
OS: WSL 2 (Linux x64 4.19.128-microsoft-standard, Ubuntu 20.04 Distro)  on Windows 10 20H2

**Description**:
I'm trying to debug a custom Kubernetes scheduler, written in Go, in VS Code using a Cloud Code/skaffold debug configuration. The pod is built and deployed correctly, but the debugger does not seem to find my source code, because all breakpoints are declared as "Unverified" (see screenshot).

![Breakpoint](https://user-images.githubusercontent.com/11061338/103015132-2c656c80-4540-11eb-8e0b-a09645208373.png)

My project is based on the [scheduler-plugins](https://github.com/kubernetes-sigs/scheduler-plugins) project. To ease the reproduction of the issue, I've created a distinct fork of the scheduler-plugins project and placed by debug configuration there (see [this pull request](https://github.com/tommazzo89/scheduler-plugins/pull/1/files) for the changes that I made).

My cluster setup is a local `kind` cluster with a local registry (can be started with `start-kind-cluster-with-local-registry.sh`).

When I try to debug the project, I get the following output in "Kubernetes: Run/Debug - Detailed"
```
[...]
Successfully built 4c3c14afd2c5
Successfully tagged localhost:5000/scheduler-plugins/kube-scheduler:latest
Build complete in 2m44.3627103s
Test complete in 1.6µs
Tags used in deployment:
 - localhost:5000/scheduler-plugins/kube-scheduler -> localhost:5000/scheduler-plugins/kube-scheduler:4c3c14afd2c553a0bf1dceb3c23b85eead72241329a246b2782eb69ce39ea18c
Loading images into kind cluster nodes...
 - localhost:5000/scheduler-plugins/kube-scheduler:4c3c14afd2c553a0bf1dceb3c23b85eead72241329a246b2782eb69ce39ea18c -> Found
Images loaded in 250.5468ms
Starting deploy...
Artifact \"localhost:5000/scheduler-plugins/kube-scheduler\" has Go runtime: has env \"GOTRACEBACK\"
Configuring \"schedulingplugin\" for Go/Delve debugging
\"schedulingplugin\" requires debugging support image \"go\"
Configuring installation of debugging support files
 - deployment.apps/schedulingplugin created
Deploy complete in 594.777ms
Waiting for deployments to stabilize...
 - kube-system:deployment/schedulingplugin: waiting for init container install-go-debug-support to start
    - kube-system:pod/schedulingplugin-84f79cbd5d-4c8z4: waiting for init container install-go-debug-support to start
 - kube-system:deployment/schedulingplugin is ready.
Deployments stabilized in 7.8311394s
Press Ctrl+C to exit
Streaming logs from pod: schedulingplugin-84f79cbd5d-4c8z4 container: schedulingplugin
Streaming logs from pod: schedulingplugin-84f79cbd5d-4c8z4 container: install-go-debug-support
Not watching for changes...
[schedulingplugin] API server listening at: [::]:56268
[schedulingplugin] I1223 13:53:41.523664      12 registry.go:173] Registering SelectorSpread plugin
[schedulingplugin] I1223 13:53:41.523745      12 registry.go:173] Registering SelectorSpread plugin
[ Some app output ]
[install-go-debug-support] Installing runtime debugging support files in /dbg
[install-go-debug-support] Installation complete
[schedulingplugin] I1223 13:53:42.384057      12 serving.go:331] Generated self-signed cert in-memory
[schedulingplugin] open /etc/kubernetes/configs/scheduler-config.yaml: no such file or directory
[schedulingplugin] 2020-12-23T13:53:42Z error layer=rpc writing response:write tcp [::1]:56268->[::1]:51866: use of closed network connection
Port forwarding pod/schedulingplugin-84f79cbd5d-4c8z4 in namespace kube-system, remote port 56268 -> address 127.0.0.1 port 56268
```

The `main.go` file is located in the folder `cmd/scheduler` and the Dockerfile is in `build/scheduler`.
The Makefile target `build-scheduler-debug` uses the following command:
```
$(COMMONENVVAR) $(BUILDENVVAR) go build -gcflags="all=-N -l" -ldflags '-X k8s.io/component-base/version.gitVersion=$(VERSION)' -o bin/kube-scheduler cmd/scheduler/main.go
```

To me it seems that there is a problem with the source mapping. In `launch.json` it is currently configured as:
```
"sourceFileMap": {
    "${workspaceFolder}": "/bin"
}
```

**Repro step**:
1. Make sure that you have [kind](https://kind.sigs.k8s.io/docs/user/quick-start/#installation) installed.
2. Clone the https://github.com/tommazzo89/scheduler-plugins repository.
2. Checkout the `debug-config` branch.
3. Run the  `start-kind-cluster-with-local-registry.sh` script.
3. Open the root folder in VS Code.
4. Open the file `cmd/scheduler/main.go` and set a breakpoint in the `main()` function.
4. Go to the "Run" tab and click the "Start Debugging" button.

Can you please help me to fix this issue?

Best regards,
Thomas

**Comment by quoctruong** [comment]
@tommazzo89, have you try changing the sourceFileMap to something like:
```
"sourceFileMap": {
    "${workspaceFolder}/cmd/scheduler": "/bin"
}
```

**Comment by j-windsor** [comment]
Also, since you are selecting a specific node likely outside of the default namespace, you might have to change your active namespace to `kube-system`. Skaffold only searches the active namespace for pods to debug.

**Comment by tommazzo89** [comment]
Thank you for your responses! Sorry for my late reply, today is my first day back at work after Christmas.

I tried both your solutions and noticed an error when trying to set an additional breakpoint after the scheduler process had been launched:
```
Failed to halt delve before attempting to set breakpoint: "Process 13 has exited with status 0"
```

This error occurs also with my original config, so it seems to be a problem of the launch configuration of the scheduler (not related to CloudCode). I made some changes to the deployment config by adding a service account and replacing some arguments for the scheduler, so that it starts properly (I think).

Then I tried your solutions and my original one again. Here is what I tried:
1. Modified sourceFileMap to `"${workspaceFolder}/cmd/scheduler": "/bin"`
2. Set the `kube-system` namespace as the current namespace of the the current context in kubectl
3. Combination of 1 and 2.
4. My original debug config.

The result was unfortunately always the same:
The debugger attached to the process in the container, i.e.,
```
Attached debugger to container "localhost:5000/scheduler-plugins/kube-scheduler" successfully.
```
but the process didn't stop at the breakpoint. The existing breakpoint and any new breakpoint added during the debugging session were shown as "unverified breakpoints".

Do you have any other ideas?

**Comment by tommazzo89** [comment]
I've found a way to debug the scheduler locally, i.e., without deploying a pod. So, you can decrease the priority of this issue.

**Comment by quoctruong** [comment]
Thank you @tommazzo89. May I ask how did you figure it out?

**Comment by tommazzo89** [comment]
My solution requires some manual copying of configuration files at the beginning and it runs the scheduler as a local process, i.e., without Cloud Code/skaffold.

I added the following launch configuration to `.vscode/launch.json`:
```TypeScript
{
    // Runs the scheduler on the local machine in debug mode, using the configuration in bin/config/kubernetes.
    "name": "Local: Debug Scheduler",
    "type": "go",
    "preLaunchTask": "build-debug",
    "request": "launch",
    "mode": "exec",
    "program": "${workspaceFolder}/bin/kube-scheduler",
    "args": [
        "--config=${workspaceFolder}/bin/my-scheduler-config.yaml",
        "--authentication-kubeconfig=${workspaceFolder}/bin/config/kubernetes/scheduler.conf",
        "--authorization-kubeconfig=${workspaceFolder}/bin/config/kubernetes/scheduler.conf",
        "--bind-address=127.0.0.1",
        "--port=0",
        "--scheduler-name=test-scheduler",
        // Writes the active configuration to a file and exits.
        // "--write-config-to=${workspaceFolder}/bin/active-config.yaml",
        "--v=4"
    ]
}
```

The pre-launch task from `tasks.json` is:
```JSON
{
    "label": "build-debug",
    "type": "shell",
    "command": "make build-scheduler-debug"
}
```

Now, we can run the scheduler under the debugger using these steps:

1. Run the `start-kind-cluster-with-local-registry.sh` script to start the local cluster.
2. Copy the `/etc/kubernetes` folder from the control node to the local `bin` directory: `docker cp kind-control-plane:/etc/kubernetes ./bin/config`
3. Open `bin/config/kubernetes/scheduler.conf` and replace the server's address with the one of the `kind-kind` cluster in my KUBECONFIG file.
4. Copy one of the scheduler config files (e.g., `manifests/noderesources/scheduler-config.yaml`) to `bin/config/my-scheduler-config.yaml`.
5. Open this file and replace the string `REPLACE_ME_WITH_KUBE_CONFIG_PATH` with the absolute path to the `bin/config/kubernetes/scheduler.conf` file.
6. Open the file `cmd/scheduler/main.go` and set a breakpoint in the `main()` function.
7. Go to the "Run" tab and click the "Start Debugging" button.

This runs the scheduler as a local process, but in my case that is acceptable. Nevertheless, if anyone finds a solution for Cloud Code, I would of course be interested in that.

Thank you once again for your responses guys!

**Comment by vincentjocodes** [comment]
We'll close this issue for now. Thank you.

**Comment by vincentjocodes** [comment]
Thanks @tommazzo89! closing it for now.
