### ISSUE TITLE
(gcloud) Invalid choice: 'alpha'

### ISSUE THREAD

**Issue by ImanYZ** [GoogleCloudPlatform/cloud-code-vscode#359]
**Environment**:
*(Hint: "Report Extension Issue on Github" command will fill these out for you.)*
Extension version: 1.7.1
VSCode version: 1.51.1
OS: macOS Catalina 10.15.7

**Description**:
When running "Run/Debug on Cloud Run Emulator" I get the error "(gcloud) Invalid choice: 'alpha'"
**Repro step**:
It first asks me to enter the appropriate values for the settings and then passes the dependency validation check and returns the error: (gcloud) Invalid choice: 'alpha'

**Comment by j-windsor** [comment]
Hi @ImanYZ. Do you have the Auto Dependencies setting turned on or off (below for reference)?

![image](https://user-images.githubusercontent.com/7329029/98980735-e09bbe00-24d1-11eb-8136-770f1eb201ed.png)

**Comment by ImanYZ** [comment]
Yes, it's been on and I didn't touch it.
![Screen Shot 2021-01-05 at 12 26 31 PM](https://user-images.githubusercontent.com/3834517/103678211-41cf9300-4f51-11eb-9bdf-ac69c605af37.png)

**Comment by j-windsor** [comment]
Hmmm ok. Looks like some of your gcloud components failed to install here. Can you provide the output of `~/Library/Application\ Support/cloud-code/installer/google-cloud-sdk/bin/gcloud components list`

**Comment by ImanYZ** [comment]
```
│ Installed     │ BigQuery Command Line Tool                           │ bq                       │  < 1 MiB │
│ Installed     │ Cloud SDK Core Libraries                             │ core                     │ 15.9 MiB │
│ Installed     │ Cloud Storage Command Line Tool                      │ gsutil                   │  3.5 MiB │
│ Installed     │ Minikube                                             │ minikube                 │ 22.8 MiB │
│ Installed     │ Skaffold                                             │ skaffold                 │ 16.1 MiB │
│ Installed     │ gcloud Alpha Commands                                │ alpha                    │  < 1 MiB │
│ Installed     │ gcloud Beta Commands                                 │ beta                     │  < 1 MiB │
│ Installed     │ kubectl                                              │ kubectl                  │  < 1 MiB │
```

**Comment by j-windsor** [comment]
Ok actually looks like everything is installed. Could you then paste here the output of the Detailed Logs for your run/debug session?

**Comment by ImanYZ** [comment]
Starting to run the app using configuration 'Cloud Run: Run/Debug Locally' from .vscode/launch.json...

To view more detailed logs, go to Output channel : "Cloud Run: Run/Debug Locally - Detailed"

Dependency check started
Dependency check succeeded
ERROR: (gcloud) Invalid choice: 'alpha'.
,Maybe you meant:
  gcloud alpha code clean-up
  gcloud alpha code dev
  gcloud alpha run services logs read
  gcloud config get-value
  gcloud config list
  gcloud config set
  gcloud config unset

To search the help text of gcloud commands, run:
  gcloud help -- SEARCH_TERMS

**Comment by j-windsor** [comment]
@ImanYZ Sorry for the delay. 

It looks like you posted the standard logs instead of the detailed logs. Can you please find the output channel named "Cloud Run: Run/Debug Locally - Detailed" and paste the contents here?

Another step you can take to help us debug this is pasting the output of `~/Library/Application\ Support/cloud-code/installer/google-cloud-sdk/bin/gcloud alpha` (verify it outputs a list of commands in the `alpha` family of commands.)

If you would like to just get running, I would recommend deleting the dependencies directory by running `rm -rf ~/Library/Application\ Support/cloud-code/installer` and restarting VSCode to allow Cloud Code to reinstall these dependencies (hopefully correctly this time).

**Comment by sivakku** [comment]
We have fixed gcloud corrupt installer issues during Jan and Feb release. Please try out our latest version of plugin and do let us know if it worked for you (or) not.
