### ISSUE TITLE
Enabling Google cloud API services

### ISSUE THREAD

**Issue by PrahathessRaghavan** [GoogleCloudPlatform/cloud-code-vscode#36]
This is a part I dont enjoy doing in Gcloud UI as well. 

The flow :

Try to deploy / create stuff and later find out that you need to enable a relevant api on the console. This sort of breaks the train of thought and  sometimes can be very annoying from the UX perspective.

The Fix:

Given that this can be shelled out or scripted , for a set of actions user wants to do present him upfront with a consent to enable all the relevant api on his behalf and an agreement that binds for services that can be charged for. Ask consent upfront and enable the services he intends to use.

Also present with a command to check all the enabled services and the steps/commands to disable them.

**Comment by jmah-cc** [comment]
@PrahathessRaghavan: We have a new feature that let's you see information about other APIs and enable them from within the plugin itself, please take a look at the docs: https://cloud.google.com/code/docs/vscode/client-libraries
