### ISSUE TITLE
[Google CloudSource Repository] Show merge request of Google cloud source repo

### ISSUE THREAD

**Issue by brpatel0202** [GoogleCloudPlatform/cloud-code-vscode#361]
**Use case**
What are you trying to do that our extension doesn't let you?
Eg, I want to deploy frequently to manually test my code change.
Running deploy command every time is annoying.

 We have raised this issue to have merge request management available with the Google cloud source repository. https://issuetracker.google.com/issues/176686426

Once it is available it should be supported in the Cloud code extension. So that developers can manage their pull request lifecycle from Cloud Code extension directly.

Can you please collaborate with https://issuetracker.google.com/issues/176686426 assignee and try to make it available soon in extension.

**Feature**
What would help?
Eg, Maybe a continuous deploy command?

 A list of pull requests can be accessed in Cloud code extension and developers can see and update its status from vs code directly.

**Comment by kschaab** [comment]
So the request as it is written requires reevaluation at a later date (dependent on https://issuetracker.google.com/issues/176686426).  However, we do already have continuous deployment to clusters if that's what you are asking for, based local code changes, not source control merges.  If you are looking for this particular feature it is here:  https://cloud.google.com/code/docs/vscode/running-an-application.  If you are looking for something else please elaborate further.

**Comment by beingminimal** [comment]
Hi @kschaab ,

Basically, we want to manage our GitOps connected with the Google cloud source repository through VSCode.  
For example, Creating and listing pull requests, update assignee of the pull requests, comparing merge request branches, etc.

By having this feature, developers can manage GitOps from a single Google Cloud Repository. For more detail please go through https://issuetracker.google.com/issues/176686426 once.

Once this feature is available, it should also be supported in cloud code extensions.
For Example, 
GitHub Pull Requests and Issues extension allows you to review and manage GitHub pull requests and issues in Visual Studio Code. https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github.

So likewise vscode extension should support "review and manage pull request of Google cloud source repository" once it is available.

**Comment by kschaab** [comment]
Thanks for clarifying @beingminimal, I had thought you were asking for something completely different.  We don't have any immediate plans for this, but this is a fantastic suggestion.  FYI @viglesiasce
