### ISSUE TITLE
Installation of extension causes corrupt PATH variable entry

### ISSUE THREAD

**Issue by mhintzke** [GoogleCloudPlatform/cloud-code-vscode#362]
**Environment**: Win10 x64 w/WLS on
*(Hint: "Report Extension Issue on Github" command will fill these out for you.)*
Extension version: 1.7.1
VSCode version: 1.52.1
OS: Win10 Pro 10.0.18362 Build 18362

**Description**:
A couple days ago I installed the VS Code extension and recently realized a particular CLI wasn't available to me in my VS Code WLS shell, but was available in native WLS shells. After inspecting the `$env:PATH` variable in both I could see there was an extra entry for the Cloud Code path when in VS Code. Sure enough, the issue was there was a colon ":" instead of a semicolon ";" as the delimiter for the path. It was as if Cloud Code thought I was using Linux when I was using Windows. Not sure if its related to me have WLS installed.

Whatever is checking for the OS to determine this delimiter might be the culprit.

**Repro step**:
Install the Cloud Code extension on Win10 with WLS installed and then check your `$env:PATH` variable when opening a shell from VS Code and see if the delimiter following the Cloud Code `bin` path is a colon or semicolon.

**Comment by sivakku** [comment]
We are working on a fix for this one and preparing patch to be released and thanks for reporting.

**Comment by mhintzke** [comment]
Thank you!

**Comment by j-windsor** [comment]
This should be fixed in 1.7.2. Please check it out and reopen this issue if you are still having issues after updating.
