### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by brightonyoung** [GoogleCloudPlatform/cloud-code-vscode#364]
- Issue Type: `Performance`
- Extension Name: `cloudcode`
- Extension Version: `1.7.1`
- OS Version: `Windows_NT x64 10.0.20279`
- VSCode version: `1.52.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\BRIGHT~1\AppData\Local\Temp\googlecloudtools.cloudcode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by go-nelango** [comment]
@brightonyoung thanks for reporting this issue. Could you please re-attach the cpu profile file? Also could you answer a few questions to help us investigate:

1. When do you see the CPU spike? Is it during startup time or any specific operation?
2. How many vscode instances do you have open?
3. How many yaml files does your workspace have?
4. How large are those files?

**Comment by vincentjocodes** [comment]
We'll close this one due to inactivity. Please feel free to open it back up again if you have any more concerns.
