### ISSUE TITLE
cloud code not working on mac

### ISSUE THREAD

**Issue by hm-distro** [GoogleCloudPlatform/cloud-code-vscode#368]
**Environment**:
*(Hint: "Report Extension Issue on Github" command will fill these out for you.)*
Extension version: v1.7.2
VSCode version:
ersion: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:30:02.420Z (1 mo ago)
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 20.2.0

**Description**:

Unable to get the plugin working after install on mac.
Ran the glcoud command in a terminal and see the below errors.

_myuser-macbookpro1:bin myuser$_ /Users/myuser/Library/Application\ Support/cloud-code/installer/google-cloud-sdk/bin/gcloud 
ERROR: gcloud failed to load: No module named 'googlecloudsdk.third_party.apis.cloudkms.v1.cloudkms_v1_messages'
    gcloud_main = _import_gcloud_main()
    import googlecloudsdk.gcloud_main
    from googlecloudsdk.command_lib.util.apis import yaml_command_translator
    from googlecloudsdk.command_lib.iam import iam_util
    kms_message = core_apis.GetMessagesModule('cloudkms', 'v1')
    return __import__(api_def.messages_full_modulepath, fromlist=['something'])

This usually indicates corruption in your gcloud installation or problems with your Python interpreter.

Please verify that the following is the path to a working Python 2.7 or 3.5+ executable:
    **/Library/Developer/CommandLineTools/usr/bin/python3**

If it is not, please set the CLOUDSDK_PYTHON environment variable to point to a working Python 2.7 or 3.5+ executable.

If you are still experiencing problems, please reinstall the Cloud SDK using the instructions here:
    https://cloud.google.com/sdk/

_myuser-macbookpro1:bin myuser$_     **/Library/Developer/CommandLineTools/usr/bin/python3**
Python 3.8.2 (default, Nov  4 2020, 21:23:28) 
[Clang 12.0.0 (clang-1200.0.32.28)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 

**Repro step**:
Install VsCode on new mac
Install the cloud code extension
Attempt to login

**Comment by ChaseMor** [comment]
@hm-distro 

I can't seem to repro this issue so I think it might just be on your local machine.

You could removing the binary folder where the managed gcloud binary exists with `rm -rf /Users/myuser/Library/Application\ Support/cloud-code/installer/google-cloud-sdk/bin/`. Then rerunning the Cloud Code extension should install it again. 

You could also try, though it is not recommended, installing the dependencies yourself and turning off `Auto Dependencies` in the extension setting.

If that doesn't work, maybe try reinstalling python or installing a different version and linking it like it says with the `CLOUDSDK_PYTHON` environment variable.

See if that works.

**Comment by hm-distro** [comment]
A downgrade to v1.7.1 works fine .

**Comment by ChaseMor** [comment]
Good to see it's working now! Sorry you had an issue to begin with. We'll keep an eye out for similar bugs and see what we can do on our end to make it smoother for people starting with Cloud Code.

**Comment by sivakku** [comment]
The SDK corruption bugs are fixed in V1.8.0. Please upgrade and try to give us the feedback using the latest version.
