### ISSUE TITLE
Hang on deploy to Cloud Run or Cloud Run emulator

### ISSUE THREAD

**Issue by mykter** [GoogleCloudPlatform/cloud-code-vscode#371]
Issue Type: <b>Bug</b>

1. Open an existing Go/Docker project, that you haven't used with Cloud Code.
2. Log in to Cloud Code, so it can see your existing GCP projects.
3. From the task bar, press Cloud Code then choose "Deploy to cloud run" or "run on cloud run emulator"

When pressing deploy it hangs with "Analyzing workspace for builders" and the detailed log output is:
```
Checking Docker Dependency Status.
Retrieving builders.
```
When trying to emulate, it hangs with "Verifying dependencies" and there is no log output that I can see.

Extension version: 1.7.2
VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 5.8.0-34-generic
Google Cloud SDK: 324.0.0

**Comment by ChaseMor** [comment]
Do you have `Auto Dependencies` turned on or off under the extension settings?

**Comment by mykter** [comment]
It's on (the default I assume)

**Comment by ChaseMor** [comment]
Possibly. We'll keep an eye out for similar issues. Sorry it didn't work the first time, but I'm happy to hear that it's working now!

**Comment by maherobaid15** [comment]
I am having the same issue with Run on Kubernetes

It hangs on Dependency check started

**Comment by ChaseMor** [comment]
@maherobaid15 Which version are you using? We fixed some dependency issues with our latest release: 1.8.0.

**Comment by maherobaid15** [comment]
> @maherobaid15 Which version are you using? We fixed some dependency issues with our latest release: 1.8.0.

I was using 1.8.0 but downgrading fixed the issue, I was having the exact same issue as #346
