### ISSUE TITLE
Abeseba1

### ISSUE THREAD

**Issue by Abeseba** [GoogleCloudPlatform/cloud-code-vscode#372]
**Environment**:Extension version: 1.6.0VSCode version: 1.44.0OS: linux**Description**:**Repro step**:

**Comment by ChaseMor** [comment]
Please reopen if this issue wasn't opened accidentally. 1.6.0 is particular outdated. The current version in the VS Code marketplace is 1.7.2. Upgrading to the latest version may fix any issues you're having.
