### ISSUE TITLE
run on kubernetes failing after upgrade to 1.8

### ISSUE THREAD

**Issue by stefanomiccoli** [GoogleCloudPlatform/cloud-code-vscode#375]
Issue Type: <b>Bug</b>

1. upgrade to 1.8
2. trigger `run on kubernetes` for existing project
3. wait for it to fail with 
```
Dependency check started
Dependency check failed
Cloud SDK alpha component is not installed. Please install the latest version of the component using 'gcloud components install alpha'.
Cloud SDK beta component is not installed. Please install the latest version of the component using 'gcloud components install beta'.
```
No changes to the system other than upgradinv cloudcode extension from 1.7.2 to 1.8. I used to get warnings for failing gcloud login, but I ignored them as I'm not using gcp in any way, just found convenient to have cloud code + skaffold for local development

'Kubernetes: Run/Debug - Detailed' tab in output panel is not generated 

Rolling back to previous release resume the functionality

Extension version: 1.8.0
VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19042

**Comment by j-windsor** [comment]
@stefanomiccoli sorry for breaking this scenario for you.

Can you tell us if you are using our managed dependencies? That is, is the VSCode setting `"cloudcode.autoDependencies": "on"`?
![Screen Shot 2021-02-01 at 1 38 15 PM](https://user-images.githubusercontent.com/554839/106521216-c18a4800-6492-11eb-8555-db4ce4f0061d.png)

**Comment by stefanomiccoli** [comment]
Hi @j-windsor, no, the auto dependencies are off, as i thought it would be easier to keep consistency for example with kubectl version i run locally.

Does it has to be turned on?

**Comment by j-windsor** [comment]
A workaround for this would be to turn the auto dependencies on because the components are all installed for you there. You can also just go ahead and run the commands in the output to install them to your existing gcloud installation (which it looks like you already have).

We will work on a fix soon! Thanks for bringing this to our attention.

**Comment by redborian** [comment]
Just a quick update on this issue, we are planning to push out a new release to fix this issue. I will circle back once the release is out so that you can try it out and let us know if you still see this issue.

**Comment by redborian** [comment]
This issue has been fixed in the latest release. Feel free to try it and reopen this issue if something is not right.
