### ISSUE TITLE
Minikube dashboard should not require to be admin/root depending on driver

### ISSUE THREAD

**Issue by zbbfufu** [GoogleCloudPlatform/cloud-code-vscode#38]
<b>Environment</b>:
Extension Version: Not Found
VSCode version: 1.32.1
OS version: darwin

<b>Description:</b>
Minikube Dashboard display error message `Error getting Minikube status: Minikube needs admin privileges` before refreshing status or starting/stopping minikube instance.

Running Minikube as admin/root is required with Minikube driver 'None' (running kubernetes on local kernel), but not with `Virtualbox` driver (see https://github.com/kubernetes/minikube/issues/1899). I don't know about other drivers.
As I'm running Minikube on Virtualbox from macOs, it's not required to check for _privilege elevation_ in code below.

<b>Workaround:</b>
I commented out elevation tests in `cloudcode.kubernetes/out/actionregister.js` and Minikube dashboard works as expected.
```js
    getStatus() {
        return __awaiter(this, void 0, void 0, function* () {
            try {
                // if (!(yield this.isElevated())) {
                //     throw new Error(messages_1.Message.MINIKUBE_NOT_ADMIN);
                // }
                const info = yield this.minikubeClient.getStatus();
                const action = Object.assign({}, info, { type: actionTypes.GET_STATUS_COMPLETE });
                return action;
            }
            catch (e) {
                return new Actions.GetStatusErrorAction(e.message);
            }
        });
    }
```

**Comment by c0h1b4** [comment]
Any workarounds before the next release?

**Comment by iantalarico** [comment]
@redborian Can you look into this?

**Comment by redborian** [comment]
The only workaround for now would be to run VS Code with admin privileges.
This will be fixed in our next release.

**Comment by neilghosh** [comment]
@zbbfufu where do I find the file actionregister.js in my mac?

**Comment by zbbfufu** [comment]
@neilghosh
As of cloud-code 0.0.8, `actionregister.js` is minified into `~/.vscode/extensions/googlecloudtools.cloudcode-0.0.8/dist/extension.js`.

You can still look for and remove the 3 occurences of `if(!(yield this.options.isElevated()))throw new Error(P.Message.MINIKUBE_NOT_ADMIN);` in this file. Then reload the extension.

Take care while editing, it's a pretty huge file (7.7 MB) for a js editor. You may prettify it before editing.

**Comment by neilghosh** [comment]
@zbbfufu thanks after doing the changes I got the resources from minikube listed in my left hand side panel but in the main wizard I am getting the following error, not sure if its related 

> Error getting Minikube status: ! Error executing status template: template: status:1:82: executing "status" at <.ApiServer>: can't evaluate field ApiServer in type cmd.Status * Sorry that minikube crashed. If this was unexpected, we would love to hear from you: - https://github.com/kubernetes/minikube/issues/new

**Comment by redborian** [comment]
@neilghosh Can you explain a bit more on what you are trying to do in the Minikube dashboard? You mentioned that you have difficulties in listing minikube resources in Cluster Explorer. Is that the case?

**Comment by neilghosh** [comment]
The cluster explorer is working fine as expected , its the Minikube Dashboard which is unable to display the status. Attaching a screenshot with error message. Its not a big deal but wondering if its related to the elevated permission requirement.
<img width="1243" alt="Screenshot 2019-05-07 at 6 51 03 PM" src="https://user-images.githubusercontent.com/726337/57302620-3e8b6080-70f9-11e9-8a4e-f6bb506cccf8.png">

**Comment by zbbfufu** [comment]
Can't help more without access to sources (I'm not a Google dev).
@neilghosh Do you already have a running minikube VM ?

**Comment by redborian** [comment]
@neilghosh This will be part of the next release. In the meantime, you can run VS Code with elevated privileges to get around this error without editing code by hand.

**Comment by neilghosh** [comment]
@zbbfufu Yes, I started the minikube VM via command line alreadt 
@redborian Can you please help with an example how do I do that? launching with ```sudo code`` did not work.

**Comment by redborian** [comment]
I just verified that the steps detailed in this accepted answer works.
https://stackoverflow.com/questions/34861791/how-can-i-run-vscode-with-sudo-on-osx

**Comment by dmhendricks** [comment]
> I don't know about other drivers.

I get the same error with `hyperkit`.

**Comment by redborian** [comment]
Thanks for all the feedback. This has been fixed and will be part of our next release.

**Comment by iantalarico** [comment]
This is now fixed
