### ISSUE TITLE
[Feature Request] Query serverless databases directly via Cloud Code in vscode

### ISSUE THREAD

**Issue by vcx** [GoogleCloudPlatform/cloud-code-vscode#380]
**Use case**
Currently the query surfaces for Spanner, BigQuery are only via console or the command line. The web version in some cases is so basic that neither comments, select-and-run or proper autocomplete is supported. 
Having it on vscode would allow for a more seamless experience for developers, shorten 

**Feature**
It would ease developer journey and speed up dev cycle, eliminating context switches. Also, competitors offer this ability in standalone tools (still vscode-based) as well. 
The developer could benefit from other linting extensions and troubleshooting mechanisms (debugging, for instance).

**Comment by j-windsor** [comment]
Thanks for the feature suggestion! We will be looking into this.

**Comment by kschaab** [comment]
We continue to reevaluate this, it is in our backlog
