### ISSUE TITLE
Not able to debug app (No Pod selector available for debugging)

### ISSUE THREAD

**Issue by aryanPatilhm2** [GoogleCloudPlatform/cloud-code-vscode#382]
**Environment**:
Extension version: 1.8.0
VSCode version: 1.50.1
OS: Linux - Ubuntu 18.04
minikube: 1.11.0
kubectl: client/server 1.18.5/1.18.3

**Description**:
After latest update of extension I am not able to debug my application. I am getting "No Pod selector available for debugging" error. So for try, I downgraded the extension version to 1.6.1 and it start to working now. Is there any other configuration is require for latest version of extension?
here is my launch configuration.
```
        {
            "name": "Attach node Kubernetes Pod",
            "type": "cloudcode.kubernetes",
            "request": "attach",
            "language": "Node",
            "debugPort": 9229,
            "podSelector": {
              "app.kubernetes.io/name": "my-application-service"
            },
            "localRoot": "${workspaceFolder}",
            "remoteRoot": "/work"
        }
```

**Comment by quoctruong** [comment]
@aryanPatilhm2 This is possibly a regression bug. Can you try the same configuration but add `noDebug: true` to the configuration?

**Comment by aryanPatilhm2** [comment]
Hi @quoctruong,  I tried as per your suggestion by adding `  noDebug: true ` in my existing configuration. 
First It shows me below error.
![Screenshot from 2021-02-05 11-12-35](https://user-images.githubusercontent.com/22112409/106995410-de7d8e80-67a4-11eb-9fa3-c5393d5b9921.png)

And still if I try to start debug then below error popup.
`Attach request does not support noDebug mode. Please run F5 instead of Ctrl+F5.`
Here I am pressing F5 only not Ctrl + F5

I didn't try launch configuration. Because I am running my Kubernetes helm app using skaffold. So that I can debug my multiple services by attaching the respective pods at same time.

**Comment by evtimmy** [comment]
I am experiencing same issue, here's my environment:
Extension version: 1.8.0
VSCode Version: 1.53.0
OS: Mac OS 11.1
minikube version: v1.16.0 (running on VBox)
kubectl: client/server v1.19.3/v1.20.0

Same results, when I downgraded to CloudCode 1.7.2 everything works.

**Comment by v-shaaal** [comment]
I experienced the same issue in the following environment.
Extension version: 1.8.0
VSCode version: 1.53.0
OS: Windows 10 Enterprise

Even downgrading to 1.7.2 did not solve the issue. However, the issue was resolved by downgrading to 1.6.2 version.

**Comment by quoctruong** [comment]
@aryanPatilhm2 @evtimmy @v-shaaal We recently pushed out a fix for this issue, can you try to see if this still happens?

**Comment by sivakku** [comment]
The fix is going to be part of the feb release, will be out soon.

**Comment by redborian** [comment]
This is part of our latest release. Try it out and let us know if you still have this issue.
