### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by rjcc** [GoogleCloudPlatform/cloud-code-vscode#386]
- Issue Type: `Performance`
- Extension Name: `cloudcode`
- Extension Version: `1.8.0`
- OS Version: `Darwin x64 19.6.0`
- VSCode version: `1.53.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/var/folders/sf/xt_9zpb50l10529r4bjhgn_w0000gn/T/googlecloudtools.cloudcode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by sivakku** [comment]
@rjcc - Can you upload cpu profile that is at this location? thanks for the feedback.

/var/folders/sf/xt_9zpb50l10529r4bjhgn_w0000gn/T/googlecloudtools.cloudcode-unresponsive.cpuprofile.txt

**Comment by glouischandra** [comment]
Hello @rjcc ping on the cpuprofile.txt file so we can debug the issue more effectively. Thanks!

**Comment by sivakku** [comment]
Closing this issue as there is no response. Please re-open the issue when you have time to attache the profile @rjcc and thanks for the feedback.
