### ISSUE TITLE
Breakpoints in CloudRun Debugger remain unbound

### ISSUE THREAD

**Issue by calvin-sentry** [GoogleCloudPlatform/cloud-code-vscode#391]
**Environment**: Linux

Extension version: 
1.8.0
VSCode version:
1.53.2
OS: Ubuntu 20.04

**Description**:
Breakpoints remain grey and unbound to the container when on startup.

**Repro step**:

```
{
            "name": "Cloud Run: Run/Debug Locally",
            "type": "cloudcode.cloudrun",
            "request": "launch",
            "build": {
                "docker": {
                    "path": "dev.dockerfile"
                }
            },
            "image": "elastic-search",
            "service": {
                "name": "elastic-search",
                "containerPort": 80,
                "resources": {
                    "limits": {
                        "memory": "256Mi"
                    }
                }
            },
            "target": {
                "minikube": {}
            },
            "watch": true,
            "debug": {
                "sourceFileMap": {
                    "${workspaceFolder}": "/usr/src"
                }
            }
        }
```

**Comment by redborian** [comment]
Thanks for responding to the Slack channel with more information.

> ![image](https://user-images.githubusercontent.com/6260897/109566675-0d7fdb00-7a99-11eb-8a10-0c6360347da9.png)
> Dockerfile, Nodejs

Can you set this `"cloudcode.verboseLogging": true` in your settings file and pasting the output from "Cloud Code" output channel? Also, can you paste the contents of your Dockerfile? (We do some fancy edits to your Dockerfile to enable debugging)

**Comment by vincentjocodes** [comment]
Hi @calvin-sentry, just want to follow up on this. It looks like from the debug logs that @redborian reposted, the inspector fails to start? `address already in use`. Wondering if this has to do with the debug not being able to attach..

**Comment by jmah-cc** [comment]
Please respond to the comment above and re-open if you're still seeing this issue.
