### ISSUE TITLE
"Report Extension Issue on Github" and issue template should request Cloud SDK, Skaffold, and Minikube versions

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/cloud-code-vscode#392]
**Description**:

Currently the issue template asks for:
```
*(Hint: "Report Extension Issue on Github" command will fill these out for you.)*
Extension version:
VSCode version:
OS: 
```

It would have been helpful to have known which versions of Cloud SDK and Skaffold were in use in hunting down https://github.com/GoogleCloudPlatform/cloud-code-vscode/issues/379 and https://github.com/GoogleContainerTools/skaffold/issues/5355.  

The "Report Extension Issue on Github" should fill these versions.

**Comment by sivakku** [comment]
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-vscode-internal](https://github.com/GoogleCloudPlatform/cloud-code-vscode-internal/issues/4145)

**Comment by sivakku** [comment]
Thanks @briandealwis for suggestion, we will update the automatic file to include the SDK, skaffold & kubectl version.

**Comment by sivakku** [comment]
This is part of the v1.10.0 plugin update.
