### ISSUE TITLE
Setting Buildpack builder environment variables yields invalid scaffold yaml

### ISSUE THREAD

**Issue by jameslittle** [GoogleCloudPlatform/cloud-code-vscode#394]
Issue Type: <b>Bug</b>

*Context*
- Managed Dependencies: on

Setting builder environment variables (for buildpack) results in the following error:

    parsing skaffold config: unable to parse config: yaml: unmarshal errors:
    line 4: field buildpack not found in type latest.Artifact
    Exited with code 1.

And the run/debug process exits. 

Relevant part of launch config:

                "build": {
                "buildpacks": {
                    "path": "project.toml",
                    "builder": "gcr.io/buildpacks/builder:v1",
                    "env": [
                        {
                            "name": "GOOGLE_RUNTIME",
                            "value": "python"
                        },
                        {
                            "name": "PIP_NO_CACHE_DIR",
                            "value": "1"
                        }
                    ]
                }
            },

Digging out the scaffold.yaml from the temp directory; the location of the `env` list looks suspect; should be one level up?

    apiVersion: skaffold/v2beta10
    kind: Config
    metadata:
      name: cost-pricer
    build:
      artifacts:
        - image: cost_pricer
          buildpacks:
            builder: 'gcr.io/buildpacks/builder:v1'
          buildpack:
            env:
              - GOOGLE_RUNTIME=python
              - PIP_NO_CACHE_DIR=1

Extension version: 1.9.0
VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.83GB (4.42GB free)|
|Process Argv|. --crash-reporter-id a9015306-6389-4bee-a1ad-99a8decf6dfd|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspyt653:30253241
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244cf:30256637
pythonvsdeb440:30248342
pythonvsded773:30248341
vstes627:30244334
pythonvspyt875:30259475
dockersubset:30265998
pythontbcf:30265426
vspre833:30267464

```

</details>

**Comment by kschaab** [comment]
@jameslittle are you running kubernetes or cloud run application?

**Comment by kschaab** [comment]
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-vscode-internal](https://github.com/GoogleCloudPlatform/cloud-code-vscode-internal/issues/4184)

**Comment by kschaab** [comment]
Yes this is definitely broken, looks like we fat fingered the section name there.

**Comment by kschaab** [comment]
A fix for this will be available in the insider's channel sometime later today and will be in the next release.

**Comment by jameslittle** [comment]
Great! Thanks for the quick turnaround @kschaab

**Comment by sivakku** [comment]
The fix is available through our insider channel(you can see [here](https://github.com/GoogleCloudPlatform/cloud-code-vscode/blob/master/CHANGELOG.md#new-features) about how to enable insider channel). The fix will be in the next March/April release.

**Comment by sivakku** [comment]
This is slated for next release at the end of March'21.

**Comment by sivakku** [comment]
This is coming out tomorrow as part of v1.10 release to VSCode plugin.
