### ISSUE TITLE
Support Watch for Debug mode

### ISSUE THREAD

**Issue by alexgorbachev** [GoogleCloudPlatform/cloud-code-vscode#400]
**Use case**

Development lifecycle for fast starting pods (with dependency on slow starting pods)

I have an app with several pods. The foundational pod takes about 2 minutes to initialize but I basically never need to change it. I'm working on other pods and they start in few seconds if the foundational pod is already running. I'm trying to optimize my development lifecycle when I change the code in fast-starting pod and debugging it.

The "Run on Kubernetes" would be great as it watched the changes and re-deploys that fast-starting pod only. However, I can't debug it.

"Debug on Kubernetes" is what I would like to use but it doesn't watch the changes and re-deploy automatically and stopping and starting the whole app (all pods) is pain because it takes 2-3 minutes (due to slow starting but never changing pods).

I was thinking of have "Run on Kubernetes" and then use Attach to debug individual pods but it would require pre-configuring the pods/containers for debug in Dockerfile. I assume if I do that, I could detach debugger and let it re-deploy watching changes and re-attach again.

I was playing with multiple skaffold yaml files - one that includes foundation only (slow starting pod) and another one just for fast-starting pod where I need to do changes but then I have to disable clean up so it's manual pod stopping for me. Also, it seems to keep stopping/starting minikube when I stop/start "Debug on Kubernetes".

Am I missing anything? Any good ideas?
**Feature**
I wish I could just use "Debug on Kubernetes" that watches changes and re-deploys. But watch is not supported for Debug runs.

**Comment by sivakku** [comment]
Thanks @alexgorbachev for providing the feedback through ticket.

- We have been thinking about supporting watch mode in debug and ironing out small kirks about UI and language specific(Go, Python) that doesn't have hot swap support. it should be coming out some time soon and on our roadmaps. What language are you using for your development of the app?
- The stop/starting is intended if the cleanup flag is set to true in the config on minikube in the debug mode mostly for reason if they switch to remote cluster, it doesn't leave the cluster resources running(for charges). i think we are going to re-evaluate if we should leave that out for debugging on minikube to enable debugging artifacts post the process. 
-

**Comment by briandealwis** [comment]
Hi @alexgorbachev.  Would it be possible to describe your application set up a bit more?  Perhaps you could provide a redacted `skaffold.yaml` and your Kubernetes manifests?

Basically, pods should only be restarted when the referenced container image is rebuilt, and the container image is only rebuilt if a source file is changed.

Cloud Code uses Skaffold under the hood to build, launch, and debug applications.  One pattern that might work for you is to use [Skaffold profiles](https://skaffold.dev/docs/environment/profiles/) to adjust the artifacts that are being monitored in a session. So you'd have one profile to install your slow-running pod (perhaps launched outside of Cloud Code), and then a separate profile for your main development loop.

**Comment by sivakku** [comment]
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-vscode-internal](https://github.com/GoogleCloudPlatform/cloud-code-vscode-internal/issues/4354)

**Comment by quoctruong** [comment]
@alexgorbachev Hi Alex, we've recently introduced watch mode for debug in the latest version of the extension. It is currently under a flag called `cloudcode.beta.enableIterativeDebugging`. Please enable it and try out the feature! Some words of caution though, it does not work well with NodeJS multi-services applications at the moment because of a bug that is being addressed. Additionally, the debug session for subsequent session takes a few seconds to stabilize.

**Comment by sivakku** [comment]
This feature of iterative debugging is available through insider build, you can use Cloud Code preference settings to give us feedback.

**Comment by sivakku** [comment]
With the June release (v1.13.0) iterative debugging is supported for all languages. Give it a try and give us feedback.
