### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Actytyde** [GoogleCloudPlatform/cloud-code-vscode#401]
- Issue Type: `Performance`
- Extension Name: `cloudcode`
- Extension Version: `1.9.0`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.54.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\capoc\AppData\Local\Temp\googlecloudtools.cloudcode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by sivakku** [comment]
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-vscode-internal](https://github.com/GoogleCloudPlatform/cloud-code-vscode-internal/issues/4230)

**Comment by kschaab** [comment]
@actytyde we would really appreciate it if you would please attach the file referenced in the bug (`c:\Users\capoc\AppData\Local\Temp\googlecloudtools.cloudcode-unresponsive.cpuprofile.txt`)

**Comment by sivakku** [comment]
Please re-open if you can attach cpu profile for investigation. Thanks.

**Comment by go-nelango** [comment]
Opened an issue with vscode to automatically attach cpu profile with user consent - https://github.com/microsoft/vscode/issues/120767
