### ISSUE TITLE
Channel Error

### ISSUE THREAD

**Issue by seanmcbreen** [GoogleCloudPlatform/cloud-code-vscode#404]
Issue Type: <b>Bug</b>

![image](https://user-images.githubusercontent.com/1051190/111678897-0289b200-87de-11eb-80b5-b41a11260590.png)

*Context*
- Managed Dependencies: on

Extension version: 1.10.0-insiders.3
VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:02.420Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.28GB free)|
|Process Argv|--crash-reporter-id 4482d79a-8246-466f-83ff-fd0d5accef75|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt678:30270856
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubset:30270708
pythonvspyt943cf:30277002
vspre833cf:30267465
vsdfh931:30275552
vshan820cf:30276953

```

</details>

**Comment by sivakku** [comment]
It almost seems like a DNS failure to get the manifest. 
@j-windsor  - Do we need to show this retryable error notification toast to user when insider channel fetch fails? since the retry happens in the background every 6 hours, it doesn't seem to be user actionable.

**Comment by j-windsor** [comment]
yep given the syscall `getaddrinfo` this looks like a system DNS failure. Some node in DNS broke here.

We already retry 3 times every 1 second. Should we increase this? Hide this particular error message?

**Comment by sivakku** [comment]
The retries are great, leave them as it is, i was hinting more of the error message: The error message should be going in to the "cloud code" channel(already), that is good enough but we don't need to show to UI toast to user since it is not actionable. Can we suppress that one?

**Comment by sivakku** [comment]
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-vscode-internal](https://github.com/GoogleCloudPlatform/cloud-code-vscode-internal/issues/4276)

**Comment by j-windsor** [comment]
Yep! We can suppress all random http errors.

**Comment by vincentjocodes** [comment]
> yep given the syscall `getaddrinfo` this looks like a system DNS failure. Some node in DNS broke here.
> 
> We already retry 3 times every 1 second. Should we increase this? Hide this particular error message?

@j-windsor Maybe we could do a exponential backoff for these retries. It is possible that they are too close together (1 sec wait) to have any DNS problems resolve right away. 

Also for error messages... we should at least preserve them somewhere so we can debug it later if we don't want to show it to the user.

**Comment by sivakku** [comment]
This is part of the v1.10.0 plugin update.
