### ISSUE TITLE
Where's the code?

### ISSUE THREAD

**Issue by sorenisanerd** [GoogleCloudPlatform/cloud-code-vscode#410]
I'm trying to find the code, but I'm having no luck. What am I missing?

**Comment by sivakku** [comment]
@sorenisanerd - Thanks for asking. What are you looking for to do with code? How we can help? we have been thinking about it but haven't gotten time for open sourcing it. :)

**Comment by manterfield** [comment]
Right now we're reliant on the docs, but they're not exhaustive. They describe a user-friendly path through the process of creating and interacting with cloud code, but if you want to do anything off that path then you have no way to gain an understanding.

To give a concrete example, I wanted to update my launch.json config manually for a service to add environment variables. I didn't want to go through the creation flow again (and couldn't see a way to just update the existing one). I had to make an educated guess what the syntax was. Had I had code access I could have just walked backwards form there.

The ability to read the code unlocks the abilities of the community far better than any docs or guides will. People will have questions and reasons for those questions you will never anticipate. Working towards exhaustive docs is a great aim, but the only entirely reliable source of truth is the source itself.

**Comment by sorenisanerd** [comment]
@sivakku My immediate need was/is to learn from the debugging instrumentation in the local cloud run emulator. I had one container where it worked and one where it didn't, so I wanted to understand why.

As I use the plugin more, I'm sure my curiosity will raise other questions.

**Comment by kschaab** [comment]
Sorry @sorenisanerd the code isn't open source.  Please join us on slack to ask questions as they come up.  Can you elaborate on the issue that you had?

**Comment by manterfield** [comment]
Will the code eventually be made open source? It seems unusual for a project like this, aimed at developers as a development tool, to be closed source.

**Comment by sivakku** [comment]
Thanks for the interest, we are evaluating open source, until then please use slack(link is in README) and Github task to engage with any bugs/blockers/investigations that you need us to un-block.

**Comment by MaSven** [comment]
Is there another way to run the apigee emulator instead of using the vscode plugin?

**Comment by gaeshi** [comment]
@sivakku 

The Slack link seems to be only available with @google.com email address.

https://join.slack.com/t/googlecloud-community/shared_invite/zt-erdf4ity-8ZMUQ18DYV~5hkbZ~gCswg

<img width="475" alt="image" src="https://user-images.githubusercontent.com/14256421/172506731-9fc3c30b-1ef3-461b-946d-ddb7fd13ebcb.png">

**Comment by thebalaa** [comment]
With the recent addition of the Gemini capabilities to this extension I would urge the leadership behind this team to reconsider open sourcing it and providing a plugin system for direct integration with Gemini's code assistant capabilities. This would supercharge Gemini Code assist in closing the large adoption gap between itself and Copilot.

Create a plugin store and you've got a new billion dollar business. Do it!
