### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by hakiri** [GoogleCloudPlatform/cloud-code-vscode#413]
- Issue Type: `Bug`
- Extension Name: `cloudcode`
- Extension Version: `1.9.0`
- OS Version: `Windows_NT x64 10.0.21343`
- VS Code version: `1.55.0-insider`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by sivakku** [comment]
@hakiri - Can you add the details of what the issue is about? it seems you had something in the clipboard at the time of filing and that would help us understand what the issue is about.

**Comment by kschaab** [comment]
@hakiri please feel free to reopen this issue with some additional information.
