### ISSUE TITLE
Multiple prompts for `Minimum gcloud sdk version not met`

### ISSUE THREAD

**Issue by gsquared94** [GoogleCloudPlatform/cloud-code-vscode#414]
*Context*
- Managed Dependencies: off
- Cloud SDK Version: 322.0.0
- Skaffold Version: v1.21.0-23-g189edbeb9-dirty
- Minikube Version: 1.18.1

**Description**:
_Actual_:
If my gcloud version is lower than the minimum required version then I get multiple prompts about it.
![image](https://user-images.githubusercontent.com/39389231/114071716-49574e80-9856-11eb-90f6-39e733ff46fc.png)

_Expected_: A single prompt, preferably with upgrade instructions.

**Repro step**:
- Install old gcloud version
- Open any project in VSCode

**Comment by kschaab** [comment]
Thanks @gsquared94 I'll fix this in the next release.  Can you confirm that you do not have installation instructions at the end of the message?  It should read:  Please update Cloud SDK to the latest version using 'gcloud components update'.

**Comment by gsquared94** [comment]
It didn't have the update instructions on my Mac device.
![image](https://user-images.githubusercontent.com/39389231/114246900-b3502080-9948-11eb-8ad4-5a92ba6a292a.png)

**Comment by kschaab** [comment]
This has released
