### ISSUE TITLE
Prompt describing lacking m1 features happens on every startup

### ISSUE THREAD

**Issue by viglesiasce** [GoogleCloudPlatform/cloud-code-vscode#415]
Issue Type: <b>Bug</b>

*Context*
- Managed Dependencies: on
- Cloud SDK Version: 335.0.0
- Skaffold Version: v1.21.0
- Minikube Version: 1.18.1

We should not be taking up screen real estate on EVERY startup of VS Code, telling users that some things might not work. ATM things are working quite well for me.

There is no way to disable the prompt either.

Extension version: 1.10.0
VS Code version: Code 1.55.1 (08a217c4d27a02a5bcde898fd7981bda5b49391b, 2021-04-07T15:47:31.580Z)
OS version: Darwin arm64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|undefined|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 2|
|Memory (System)|16.00GB (2.21GB free)|
|Process Argv|--crash-reporter-id a843f45f-ab26-4c44-a3c0-1e597ea8026d|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by viglesiasce** [comment]
![Uploading Screen Shot 2021-04-08 at 9.16.02 PM.png…]()

**Comment by sivakku** [comment]
i see, for folks who got their M1 setup working, this notification would be annoying to show it on restart of VSCode. 
@kschaab - Can we add "don't show again" to the notification that doesn't show up once user choose that option?

**Comment by sivakku** [comment]
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-vscode-internal](https://github.com/GoogleCloudPlatform/cloud-code-vscode-internal/issues/4434)

**Comment by quoctruong** [comment]
We now have a way to suppress the prompt in the new release.
