### ISSUE TITLE
[Feature] Skaffold with Google Cloud Artifact Registry

### ISSUE THREAD

**Issue by faridghar** [GoogleCloudPlatform/cloud-code-vscode#416]
Issue Type: <b>Bug</b>

*Context*
- Managed Dependencies: on
- Cloud SDK Version: 335.0.0
- Skaffold Version: v1.21.0
- Minikube Version: 1.18.1

First I added an Artifact Registry under the "imageRegistry" key in the launch.json file.

Then, when I issue the "Run on Kubernetes" command, in the Run Configuration output window, I see the following message:

"Input image registry us-central1-docker.pkg.dev/<project-id>/docker-registry/<image-name> does not match the expected image registry gcr.io/<project-id> based on the GCP project associated with the current context"

It seems that Skaffold expects you to push the image to Container Registry instead of Artifact Registry. What's strange is that the push seems to be successful nonetheless and I see the image in the Artifact Registry UI. If pushing to Aftifact Registry works, why show this message? It's confusing and implies something is wrong.

Extension version: 1.10.0
VS Code version: Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:02:21.560Z)
OS version: Linux x64 5.4.74-10576-gb6cc41974db3

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|06/8e (4 x 1607)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 2, 2|
|Memory (System)|14.21GB (14.19GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 280c0b60-ff39-45a5-9908-66b0f306bfe7|
|Screen Reader|no|
|VM|40%|
|DESKTOP_SESSION|undefined|
|XDG_CURRENT_DESKTOP|undefined|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|undefined|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
vstes627:30244334
pythonvspyt875:30259475
pythonvspyt639:30281910
pythontb:30283811
wslfolderdoc:30282074
vspre833cf:30267465
pythonptprofiler:30281270
vshan820cf:30276953
pythondataviewer:30285071
vscus158:30286553

```

</details>

**Comment by sivakku** [comment]
@faridghar - Thanks for the feedback. The mismatch was meant for a warning/caution if you are using different container registry than the one available to the default project Id the app is configured(in this case gcr.io/<project>"), since the push semantics of AR is same as container registry the push of the build image works. The support for artifact container registry doesn't yet exist in plugin/skaffold. This is in our roadmap to support artifact registry and stay tuned for updates.

**Comment by kschaab** [comment]
This is rolled out.
