### ISSUE TITLE
[Feature] Firestore Support in the GCP API Explorer

### ISSUE THREAD

**Issue by jjdharmaraj** [GoogleCloudPlatform/cloud-code-vscode#420]
**Use case**
What are you trying to do that our extension doesn't let you?
Eg, I want to deploy frequently to manually test my code change.
Running deploy command every time is annoying.

**Feature**
What would help?
Eg, Maybe a continuous deploy command?

I would love to see Firestore support in the API Explorer.  Thanks!!

**Comment by sujit-kamireddy** [comment]
@jjdharmaraj,
To help me understand better, can you clarify that you are looking for two things?
1. A continuous deploy command to deploy your code changes frequently. Is this for kubernetes apps? Did you try the watch flag? 
https://cloud.google.com/code/docs/vscode/running-an-application#customizing_launch_configuration

2. Firestore Support in the API explorer

**Comment by sujit-kamireddy** [comment]
Thank you for this request. We will look into this.

**Comment by kschaab** [comment]
This is in the API browser now
