### ISSUE TITLE
Run on Cloud Run Emulator does not complete

### ISSUE THREAD

**Issue by simonyarde** [GoogleCloudPlatform/cloud-code-vscode#423]
**Environment**:
*(Hint: "Report Extension Issue on Github" command will fill these out for you.)*

**Version information**

Cloud Code Extension version: 1.11.0

VSCode version:
Version: 1.55.2
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:36:32.643Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 19.6.0

**Description**: Run on Cloud Run Emulator does not complete
Seems to live lock after the command below.

```
Running skaffold command:
...
Running: skaffold dev -v info --port-forward --rpc-http-port 49315 --filename /var/folders/pb/6qk5pbtd6klfd020q1wnkhb40000gp/T/cloud-code-cloud-run-H0lmvs/skaffold.yaml --kube-context cloud-run-dev-internal --minikube-profile cloud-run-dev-internal --status-check
```

**Comment by kschaab** [comment]
@simonyarde there is a detailed log view, can you check this please?

**Comment by simonyarde** [comment]
Progress pop-up 'Starting minikube' cycles through files rapidly, computer gets hot, have to quit vscode.

```
Running skaffold command: /Users/***/Library/Application Support/cloud-code/installer/google-cloud-sdk/bin/skaffold init --artifact {"image":"hello-run","builder":"Docker","payload":{"path":"Dockerfile"}} --kubernetes-manifest /var/folders/pb/6qk5pbtd6klfd020q1wnkhb40000gp/T/cloud-code-cloud-run-1VgHIi/pods_and_services.yaml --filename /var/folders/pb/6qk5pbtd6klfd020q1wnkhb40000gp/T/cloud-code-cloud-run-1VgHIi/skaffold.yaml --force
Setting build tagPolicy to SHA256.
Setting statusCheckDeadlineSeconds to 5 minutes
Setting build environment to 'local'
Created the file /var/folders/pb/6qk5pbtd6klfd020q1wnkhb40000gp/T/cloud-code-cloud-run-1VgHIi/skaffold.yaml.
Running gcloud command: /Users/***/Library/Application Support/cloud-code/installer/google-cloud-sdk/bin/gcloud alpha code export --service-name hello-run --image hello-run --no-skaffold-file --dockerfile= --kubernetes-file /var/folders/pb/6qk5pbtd6klfd020q1wnkhb40000gp/T/cloud-code-cloud-run-1VgHIi/pods_and_services.yaml --env-vars K_SERVICE=hello-run,K_REVISION=local,K_CONFIGURATION=hello-run --memory 256Mi --quiet
Created the file /var/folders/pb/6qk5pbtd6klfd020q1wnkhb40000gp/T/cloud-code-cloud-run-1VgHIi/pods_and_services.yaml.
Running: skaffold dev -v info --port-forward --rpc-http-port 56825 --filename /var/folders/pb/6qk5pbtd6klfd020q1wnkhb40000gp/T/cloud-code-cloud-run-1VgHIi/skaffold.yaml --kube-context cloud-run-dev-internal --minikube-profile cloud-run-dev-internal --status-check

```

**Comment by simonyarde** [comment]
@kschaab I actually just got startup to complete successfully, but it's really hammering the machine. I regularly run Docker apps on the same laptop without any dramas. Suggest something is not quite right with the process?

**Comment by medyagh** [comment]
@simonyarde do u mind verifying how much memory and CPUs your Docker Desktop has ? 
and do you have other containers running ? other than minikube

and do you mind also sharing the full output of "minikube logs'


and I am also curious if you have dangling docker volumes or containers ? that could be pruned using

`docker system prune -a`

does that help in speeding up ?

**Comment by j-windsor** [comment]
@simonyarde, when you have the chance, could you please try following the suggestions of @medyagh to see if you have any performance improvements?

**Comment by glouischandra** [comment]
@simonyarde feel free to reopen this bug if the suggestion ahead doesn't resolve the performance issue and share the information for debugging by @medyagh above. Thanks!
