### ISSUE TITLE
Feedback: Not enough differentiability between GKE resource status markers

### ISSUE THREAD

**Issue by bourgeoisor** [GoogleCloudPlatform/cloud-code-vscode#425]
**Feedback**
I was looking through the various GKE panes and noticed that status markers on the various resources lack contrast and differentiability. For example, the following screenshot contains 9 Pods in a `Ready` state and 2 Pods in a `Pending` state (two completely different statuses -- basically "ready" and "not ready") yet I need to look very closely to notice the minute difference in colour on the small dot between those two statuses:
![image](https://user-images.githubusercontent.com/3271352/116750883-83d98480-a9d9-11eb-95b6-31a1df4197d9.png)

This is made even more apparent when passing the image through a red-blind / protanopia (a type of colour-blindness) filter:
![image](https://user-images.githubusercontent.com/3271352/116751770-e7b07d00-a9da-11eb-9dcd-5a1c92e076ba.png)

Note: I am using the GCP-built-in Cloud Code, but this feedback is likely relevant to the VSCode version as well.

**Suggestions to Improve**
I can think of a couple of ways this could be improved:
- Enhanced contrast between the status colours (yellow / pending should likely be more obviously yellow rather than an off-green which is too similar to the "ready" green);
- Bigger circle / status dot size;
- Different shapes for different status (e.g. green / ready is a circle, yellow / pending is a square, etc.) for accessibility (especially to help enable developers with a form of colour-blindness);

Let me know if this is the wrong place for this sort of feedback (and where to submit it instead). I am happy to discuss this further and exchange more ideas.

**Comment by sivakku** [comment]
Thanks @bourgeoisor for the feedback. this is the right place for Cloud Code plugin feedback where sometimes with little dots are hard to notice over others because of color contrast. Adding @glouischandra

**Comment by glouischandra** [comment]
Hello @bourgeoisor, thanks for the feedback. We worked with our UX designer and updated the pods node to have better descriptive icons for status and also added Status label next to the node. This change will be released on september.

![image](https://user-images.githubusercontent.com/3677364/131713230-9eb99310-e0d8-4586-adab-2f3daf77d26d.png)

**Comment by j-windsor** [comment]
This has been fixed in Cloud Code v1.14.0. Thanks for reporting!
