### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by hollywoodclo** [GoogleCloudPlatform/cloud-code-vscode#427]
- Issue Type: `Bug`
- Extension Name: `cloudcode`
- Extension Version: `1.11.1`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.56.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by kschaab** [comment]
Please reopen with more details.
