### ISSUE TITLE
Custom Sample Repo requires .git at end of repo url

### ISSUE THREAD

**Issue by viglesiasce** [GoogleCloudPlatform/cloud-code-vscode#429]
**Version information**

Cloud Code Extension version: latest
 
VSCode version: latest

OS: mac m1

- Managed Dependencies: on
- Cloud SDK Version: 341.0.0
- Skaffold Version: v1.23.0
- Minikube Version: 1.20.0

**Description**:

The `git clone` command works on https repos without the `.git` suffix.

When adding a new Custom Samples repo if you exclude `git` (because you copied the url from the browser bar), you get an error that the extension cannot connect to the repository. 

**Repro step**:

1. Add this as a new Custom Sample repo: `https://github.com/viglesiasce/cloud-code-custom-templates-example-2`

**Comment by sivakku** [comment]
@viglesiasce - it should work with ".git" for http and i just tried and it seemed to work on latest build(1.11.1), i assume that is the latest version you are using. Can you paster what error you see when it runs in the VSCode terminal?

![image](https://user-images.githubusercontent.com/16199637/119182959-47250a00-ba28-11eb-9046-ba880d46fd8f.png)

i see the BOA in the sample list.

![image](https://user-images.githubusercontent.com/16199637/119183098-79366c00-ba28-11eb-9a8d-98c0d73bd949.png)

The VSCode terminal output.

```
$ git clone https://github.com/viglesiasce/cloud-code-custom-templates-example-2 "/Users/sivakk/Library/Application Support/cloud-code/custom-templates/https---github-com-viglesiasce-cloud-code-custom-templates-example-2-1"
Cloning into '/Users/sivakk/Library/Application Support/cloud-code/custom-templates/https---github-com-viglesiasce-cloud-code-custom-templates-example-2-1'...
remote: Enumerating objects: 502, done.
remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 502 (delta 1), reused 1 (delta 0), pack-reused 491
Receiving objects: 100% (502/502), 2.48 MiB | 4.41 MiB/s, done.
Resolving deltas: 100% (159/159), done.
```

**Comment by vincentjocodes** [comment]
I also cannot repro this issue.

**Comment by sivakku** [comment]
Vic confirmed he couldn't repro as well. Closing this one.
