### ISSUE TITLE
When cloning a Custom Sample it appears the name is used as the path

### ISSUE THREAD

**Issue by viglesiasce** [GoogleCloudPlatform/cloud-code-vscode#430]
Version information

Cloud Code Extension version: latest

VSCode version: latest

OS: mac m1

Managed Dependencies: on
Cloud SDK Version: 341.0.0
Skaffold Version: v1.23.0
Minikube Version: 1.20.0
Description:

When choosing a folder to put the cloned sample the UI uses a suffix that maps to the `name` ("Bank of Anthos") field of the entry in `.cctemplate` rather than the `path` ("bank-of-anthos")

Repro step:

1. Add this as a new Custom Sample repo: https://github.com/viglesiasce/cloud-code-custom-templates-example-2
2. Create a new app with the [Bank of Anthos sample](https://github.com/viglesiasce/cloud-code-custom-templates-example-2/blob/main/.cctemplate#L7)

**Comment by vincentjocodes** [comment]
Hey @viglesiasce 

Thank you for the report. 

I want to clarify a detail. Are you talking about the `Save As` field of the dialog being pre-populated?:
![image](https://user-images.githubusercontent.com/13400593/119194230-a2aac400-ba37-11eb-9f75-02be593f3694.png)

**Comment by viglesiasce** [comment]
Yep exactly. Spaces in the directory name are not great for when working in
the terminal.

**Comment by sivakku** [comment]
This needs to be consistent with the what we do with our regular sample, sanitizing to have dashes and lower cases, The registry name doesn't like Upper case as well.

![image](https://user-images.githubusercontent.com/16199637/119194794-7774a480-ba38-11eb-83aa-58ae99c14c79.png)
