### ISSUE TITLE
- Cloud SDK Version: 340.0.0

### ISSUE THREAD

**Issue by dd-kkk** [GoogleCloudPlatform/cloud-code-vscode#435]
Issue Type: <b>Feature Request</b>

*Context*
- Managed Dependencies: on
- Cloud SDK Version: 340.0.0
- Skaffold Version: v1.23.0
- Minikube Version: 1.19.0

Extension version: 1.12.1
VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.21359
Restricted Mode: No

**Comment by sivakku** [comment]
@dd-kkk - Not sure what this feature request is about. Please re-open with more details of the feedback you like to share with us.
