### ISSUE TITLE
Change default configuration image and service names.

### ISSUE THREAD

**Issue by Bacoknight** [GoogleCloudPlatform/cloud-code-vscode#436]
**Use case**
The default configuration on a given project has the image and service names set to "Script". Keeping this will lead to the Docker error:
`invalid reference format: repository name must be lowercase`

**Feature**
Change the default image and service names to "script" (or something else) and potentially enforce a lowercase name.

**Comment by sivakku** [comment]
@Bacoknight - Thanks for the feedback. Can you provide steps to repro about how you are setting up default configuration that contains image and service names set to  _'Script'_.

**Comment by Bacoknight** [comment]
Hi @sivakku,
I was following the tutorial [here](https://cloud.google.com/code/docs/vscode/deploying-a-cloud-run-service) to run services locally on VSCode - when initially running the addon mentioned it leads you to a configuration page where you can set the image and service names, with the default being "Script".

**Comment by sujit-kamireddy** [comment]
Hi @Bacoknight , 

Can you share a screenshot or gif of where you are seeing the default names set to "Script". 
The default names we are populating come from the name of the workspace root folder.

Is your workspace root folder named "Script"?

**Comment by Bacoknight** [comment]
@sujit-kamireddy you are right - my workspace folder is called "Script". Perhaps there could be a check for valid workspace names?

**Comment by sujit-kamireddy** [comment]
Yes, we plan to add validations for the image and service names. Thank you @Bacoknight .

**Comment by sivakku** [comment]
This has been fixed and addressed in v1.13.1 extension.
