### ISSUE TITLE
Searching feature mentioned in video - it's missing in todays Cloud Code for VSCode

### ISSUE THREAD

**Issue by exocode** [GoogleCloudPlatform/cloud-code-vscode#439]
Hi there, 

I followed this speech (timecode added: https://youtu.be/62GLbBDLiPE?t=1018) and try to launch "Cloud Code: deploy" but could not find that one mentioned in the video. It seems something has changed in the cloud-code-vscode.

Are you so kind and explain me how to get there?

thank you in advance

**Comment by sujit-kamireddy** [comment]
Hi @exocode ,

That feature is named to "Run on Kubernetes". You can find more details about it [here](https://cloud.google.com/code/docs/vscode/quickstart-k8s).
