### ISSUE TITLE
Exploring the ownerReferences of objects

### ISSUE THREAD

**Issue by feloy** [GoogleCloudPlatform/cloud-code-vscode#44]
With the apparition of the CRDs, it would be interesting to display in the K8s explorer the links between an object and its ownerReferences.

That would also work with Deployment / ReplicaSet / Pod:
In the Deployment tree, we could see the Replicaset owned by the Deployment, and in a Replicaset, we could see the Pods owned by the Replicaset.

In CRDs in general, it is usual that the operator creates different objects, with owner references between them (and with the operator itself). It could be interesting to get these links (that are less obvious than the links between deployment / replicaset / pod)

**Comment by iantalarico** [comment]
Just a quick update.  We are working on finding the best way to surface this.

**Comment by jmah-cc** [comment]
We added this support to the YAML editor. We don't have plans to add this to the tree-view explorer at this point.
