### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by thongpol** [GoogleCloudPlatform/cloud-code-vscode#440]
- Issue Type: `Performance`
- Extension Name: `cloudcode`
- Extension Version: `1.12.1`
- OS Version: `Windows_NT x64 10.0.21390`
- VS Code version: `1.57.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\VISION~1\AppData\Local\Temp\googlecloudtools.cloudcode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by ssmall** [comment]
Hi @thongpol, can you please attach the requested file so that I can investigate this issue further? Thanks!

**Comment by sivakku** [comment]
Please re-open the bug with adding the profile file. thanks @thongpol for reporting it.
