### ISSUE TITLE
Unable to utilize the cloud code template in VS code

### ISSUE THREAD

**Issue by shuxian86** [GoogleCloudPlatform/cloud-code-vscode#449]
**Environment**:
*(Hint: "Report Extension Issue on Github" command will fill these out for you.)*
Cloud code extension on VS code

**Version information**

Cloud Code Extension version: 1.13.0

VSCode version: 1.58.0

OS: Microsoft Windows 10 Enterprise version 1909 

Cloud SDK: latest version (unable to get it installed successfully. 

Skaffold: 

Kubectl: 1.19.7

**Description**:
Unable use the cloud code template in Visual Studio code
![image](https://user-images.githubusercontent.com/87307776/126119350-0fb77e83-11c5-427e-8c02-d693c4268daf.png)
![Error message in installing cloud SDK](https://user-images.githubusercontent.com/87307776/126119613-9d5f5129-7dde-4b85-a413-9e1999671d4e.JPG)

**Repro step**:

**Comment by vincentjocodes** [comment]
Hi @shuxian86,

Looks like from the error above, `git` is missing from your PC? 

For the SDK setup, one thing you could try is to turn on `autoDependencies`. Cloud code will install it for you. It should be on by default, have you turn it off by any chance? Thanks.

**Comment by shuxian86** [comment]
Hi Vincent,

Thank you for the information. Would you be able to advice on the steps to determine whether git is missing from my machine?

For SDK setup, how can I turn on the auto dependencies?

Regards,

***@***.***D602C7.BD8CD840]
Lee Shu Xian
Data Security
Group-wide Information Security & Privacy
D: +65 67047213 M:+65 83839732
E: ***@***.******@***.***>
1 Wallich Street #19-01,
Guoco Tower,
Singapore 078881

**Comment by vincentjocodes** [comment]
@shuxian86 The configuration to turn on auto dependency is `"cloudcode.autoDependencies": "on"` in your VSCode user or workspace settings file. 

Are you on a Windows system? If so, maybe try `where git`?

**Comment by shuxian86** [comment]
Hi Vincent,

Auto dependencies has been turn on for Cloud code in Visual Studio Code.
***@***.***D77F16.008C1EF0]

Does this consider to have git in place on my machine?
***@***.***D77F16.008C1EF0]


Regards,

***@***.***D602C7.BD8CD840]
Lee Shu Xian
Data Security
Group-wide Information Security & Privacy
D: +65 67047213 M:+65 83839732
E: ***@***.******@***.***>
1 Wallich Street #19-01,
Guoco Tower,
Singapore 078881

**Comment by vincentjocodes** [comment]
@shuxian86, 

We do not install `git` for you, that's something you need to install.

**Comment by shuxian86** [comment]
Hi Vincent,

What I meant was I do have git installed on my machine.
***@***.***D77FBD.D3AB3BC0]
Is this the compatible version to run the cloud code template?

Regards,

***@***.***D602C7.BD8CD840]
Lee Shu Xian
Data Security
Group-wide Information Security & Privacy
D: +65 67047213 M:+65 83839732
E: ***@***.******@***.***>
1 Wallich Street #19-01,
Guoco Tower,
Singapore 078881

**Comment by shuxian86** [comment]
Hi Vincent,

Further to my email, it is confirmed that GIT is installed on client endpoint.

While trying to use the cloud code in visual studio, the following error message appears.

***@***.***D7822C.1F719BB0]

Can I have you assistance to validate the error please?

Regards,

***@***.***D602C7.BD8CD840]
Lee Shu Xian
Data Security
Group-wide Information Security & Privacy
D: +65 67047213 M:+65 83839732
E: ***@***.******@***.***>
1 Wallich Street #19-01,
Guoco Tower,
Singapore 078881

**Comment by sivakku** [comment]
@shuxian86 - Can you make sure the GIT is in the path of the VSCode terminal? Can you paste the output of the below command from VSCode Terminal tab at the bottom.

```
$ which -a git
/usr/local/git/current/bin/git
/usr/bin/git
```
To understand the pre-reqs of Cloud Code, do look at it [here](https://cloud.google.com/code/docs/vscode/install).

**Comment by j-windsor** [comment]
@shuxian86 it looks like you are trying to send screenshots to us through the emails that are not showing up in the Github issue. Can you please post your screenshots directly to the Github issue in the browser?

Also, it looks like you are having difficulties installing the Google Cloud SDK because of some corporate proxying requirement in which the Cloud SDK installer is not able to download the SDK. You'll likely have to work with your IT department to get the appropriate permissions to install Cloud SDK.

You might be able to work around this by enabling Auto Dependencies in Cloud Code, but you will likely run into the same issue there.

**Comment by sivakku** [comment]
@shuxian86 - Please reopen this issue once you have detailed repro steps for us and the questions that @j-windsor pointed out.
