### ISSUE TITLE
Feature Request: Helm Support

### ISSUE THREAD

**Issue by jonbcampos** [GoogleCloudPlatform/cloud-code-vscode#45]
I think the title says it all, but I'll go into it more.

For our team we are helm heavy. It really makes working with Kubernetes and Spinnaker much easier for all of our deployments and build artifacts. Adding helm support would make things a lot easier for me to work with this plugin.

**Comment by redborian** [comment]
@jonbcampos or anyone interested in Helm support: We are doing preliminary investigation on Helm support. I was curious on how useful the following features would be:
1. Approximate auto-completion of "." values from `values.yaml`.
2. Local helm chart debugger where you would set breakpoints and view variables in current scope.

**Comment by jonbcampos** [comment]
Very helpful. The auto complete is really helpful in intellij so this is
something I would use.

#2 would really save me time. I am used to running a debug version of my
charts when they have issues. To do that from the IDE even better.

These would both turn my head.

I'm happy to discuss more as needed.

**Comment by vukasin-nikodijevic** [comment]
@iantalarico - here is some insight on how our helm workflow looks like:

1) in values.yaml we have only values which affect all of our 4 environments equally. This file is considered as base values file.
2) environment specific values are kept in environment values files which overwrites/adds to the base values.yaml
```
helm .......  -f values.yaml -f values-prod.yaml
helm .......  -f values.yaml -f values-qa.yaml
helm .......  -f values.yaml -f values-feature.yaml
helm .......  -f values.yaml -f values-sales.yaml
```

**Comment by pongad** [comment]
Thank you @vukasin-nikodijevic . I'm not 100% sure how to expose multiple environments from the UI yet, though my first impression is that this probably shouldn't change things too much :P

**Comment by vukasin-nikodijevic** [comment]
@pongad as end user I do not expect to have that visualized as part of the UI but only to have autocomplete for `.Values` with overwrites. I guess that couple of naming / overwriting conventions should be followed / introduced in order to get that work and not to bloat code so much. I can leave with that trade off.

I'll not complain to have auto complete for `.Release` as well :)

**Comment by pongad** [comment]
That makes sense :)

I unfortunately have been busy with other things and haven't had time to starting working on this in earnest yet. I'm currently planning to start simple and iterate. I think we can probably start with values in `values.yaml` then add support overwrites a little later (it sounds like it shouldn't be terribly difficult).

**Comment by dgethings** [comment]
@pongad I hope you are having success in progressing this feature. We exclusively use Helm. Our workflow slightly differs.

- We have one or more microservice repos. That contains not only the app code but also the Dockerfile and Helm Chart.
- We have a "master" Helm Chart that requires the microservices for an application/service
- We have deployment specific repos that overwrites the `values.yaml` in the master/microservice Helm Chart

I'm very keen for Helm support to be added. This will massively help with our development workflow and make our devs far more self-sufficient. If I can help in any way please let me know.

**Comment by jmah-cc** [comment]
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-vscode-internal](https://github.com/GoogleCloudPlatform/cloud-code-vscode-internal/issues/1846)
