### ISSUE TITLE
Run gcloud scripts in plugin

### ISSUE THREAD

**Issue by ProbStub** [GoogleCloudPlatform/cloud-code-vscode#451]
**Use case**
I have a number of infrastructure configurations that required gcloud commands. I like to run these commands and observe output. (currently working on PyCharm/MACOS)

**Feature**
A command line option would already be great but I dodnt find anything in the docs. Apologies if this is a RTFM case and kindly direct to the right space.

**Comment by vincentjocodes** [comment]
Hi @ProbStub,

Could you explain your use case in a little more detail? 

Do you want to use the script after Kubernetes/Cloud Run deployments?

**Comment by kschaab** [comment]
Kamino closed and cloned this issue to [GoogleCloudPlatform/cloud-code-intellij](https://github.com/GoogleCloudPlatform/cloud-code-intellij/issues/2964)

**Comment by kschaab** [comment]
Routing to the team that works on PyCharm.
