### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by froilson** [GoogleCloudPlatform/cloud-code-vscode#456]
- Issue Type: `Performance`
- Extension Name: `cloudcode`
- Extension Version: `1.13.1`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.58.2`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load
[googlecloudtools.cloudcode-unresponsive.cpuprofile.txt](https://github.com/GoogleCloudPlatform/cloud-code-vscode/files/6933642/googlecloudtools.cloudcode-unresponsive.cpuprofile.txt)

**Comment by glouischandra** [comment]
Thank you @froilson for the cpuprofile attachment, we're looking into this issue.

**Comment by ssmall** [comment]
Hi @froilson, I believe you are seeing the issue described in #452. We have a fix slated for the August release (1.14). I am going to close this issue for now, but if you still see this issue after the new release please re-open and attach a new cpuprofile. Thanks!
