### ISSUE TITLE
Smooth.Link

### ISSUE THREAD

**Issue by smooth80** [GoogleCloudPlatform/cloud-code-vscode#458]
Issue Type: <b>Feature Request</b>

*Context*
- Managed Dependencies: on
- Cloud SDK Version: 352.0.0
- Skaffold Version: v1.27.0
- Minikube Version: 1.22.0

Extension version: 1.13.1
VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:12.822Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by ssmall** [comment]
Hi, it appears that you did not include details about your feature request. Please edit the issue or open a new one with specific details of the feature you would like to see implemented in the Cloud Code plugin.
