### ISSUE TITLE
skyweb

### ISSUE THREAD

**Issue by RiyadhAsaameai** [GoogleCloudPlatform/cloud-code-vscode#461]
**Environment**:
*(Hint: "Report Extension Issue on Github" command will fill these out for you.)*

**Version information**

Cloud Code Extension version:

VSCode version:

OS: 

Cloud SDK:

Skaffold: 

Kubectl:

**Description**:

**Repro step**:

**Comment by sivakku** [comment]
Please reopen the bug with more details about the issue and repro steps.
