### ISSUE TITLE
Managed Dependency Check Failed

### ISSUE THREAD

**Issue by hikmahdwi** [GoogleCloudPlatform/cloud-code-vscode#462]
**Environment**:
*(Hint: "Report Extension Issue on Github" command will fill these out for you.)*

**Version information**

Cloud Code Extension version: 1.13.2

VSCode version: 1.59.1

OS: windows

Cloud SDK: google

Skaffold: 

Kubectl:

**Description**:
Hello, I'm new to use gcloud sdk, I'm trying to install google cloud code in VSCode on my local computer, but I got three errors when I run/debug the app.

1. gcloud
![image](https://user-images.githubusercontent.com/73873040/130314025-8194fdb8-ca61-4f1e-b374-d0f5c798e1cc.png)
Then I tried to solve it by updating google cloud SDK, but the result is still the same, this error still appears.

2. kubectl
![image](https://user-images.githubusercontent.com/73873040/130313962-8e1f07ec-2b5e-4f4b-bf6a-7f20d22914f0.png)

3. skaffold
![image](https://user-images.githubusercontent.com/73873040/130314103-7fea4b80-f802-4ff7-b10a-54fb7c13e28d.png)

I don't know how to fix it, any Help will mean a lot to me, Thank You.

**Repro step**:

**Comment by kschaab** [comment]
There was a bug in gcloud that caused this.  Deleting the `c:\Users\hp\AppData\Local\cloud-code\installer` directory will fix it.

**Comment by hikmahdwi** [comment]
Thank you very much @kschaab, after I deleted the installer directory, the problem was solved.

**Comment by j-windsor** [comment]
This has been fixed in Cloud Code v1.14.0. Thanks for reporting!
