### ISSUE TITLE
Option for Get Terminal to run '/bin/bash' instead of 'sh'

### ISSUE THREAD

**Issue by scgaston** [GoogleCloudPlatform/cloud-code-vscode#464]
**Environment**:
Windows 10 running Docker Desktop with WSL2 integration

**Version information**
Docker:
Docker Desktop 3.6.0

Client: Docker Engine - Community
 Cloud integration: 1.0.17
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:54:02 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:10 2021
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

Cloud Code Extension version:
v1.13.2

VSCode version:
1.59.1

OS: 
Windows 10 WSL2 (Ubuntu)

Cloud SDK:
Google Cloud SDK 354.0.0

Skaffold: 
1.27.0

Kubectl:
1.18.18

**Description**:
When running the "Get Terminal" on a container the extension issues the following command.
"/home/User/.cache/cloud-code/installer/google-cloud-sdk/bin/kubectl 'exec', '--stdin', '--tty', '<POD_Name>', '--container', '<Container_Name>', '--namespace', '<Namespace_Name>', '--kubeconfig', '/home/User/.kube/config', '--', 'sh'"

The containers I am running have issues with "sh" and instead work better with "/bin/bash". I do not want to have to type in "/bin/bash" every time I open a terminal. I instead would like the ability to change the last part of the baked in command from "sh" to "bash". I would like this to be in the extension configs where I can change the option the shell to use

**Repro step**:

**Comment by sivakku** [comment]
Feature: Support config to support other command line options.
