### ISSUE TITLE
FR: Allow port-forward and attaching terminal to pods/services

### ISSUE THREAD

**Issue by marcfong** [GoogleCloudPlatform/cloud-code-vscode#47]
<b>Environment</b>:
Extension Version: 0.0.3
VSCode version: 1.32.2
OS version: darwin

<b>Description:
Feature request: Add right click menu capability to directly port forward or terminal attach into a pod or service.
</b>

<b>Repro step:</b>

**Comment by iantalarico** [comment]
@marcfong Are you thinking about port forwarding in the context of debugging? Or do you have other flows and use cases?

**Comment by o1da** [comment]
It seems that the current version of Skaffold can do it https://skaffold.dev/docs/how-tos/portforward/
It must be invoked with `--port-forward` param. But it seems that Cloud Code doesn't invoke Skaffold with it. Can I configure it somehow?

**Comment by sbulman** [comment]
It would be great to (optionally?) enable --port-forward when using deploy (or continuous deploy). We use port forwarding so that we can call out internal services from localhost and supporting services such as MongoDB running on the cluster (so we can use DB tools etc.)

**Comment by sujit-kamireddy** [comment]
@marcfong , @o1da , @sbulman ,

We are pleased to let you know that we have added a new command 'Cloud Code: Run on Kubernetes' in our latest release (v1.1.1) that provides greater [customization](https://cloud.google.com/code/docs/vscode/running-an-application#customizing_run_configuration)(--watch, --cleanUp, --portForward etc) through run configurations (.vscode/launch.json).

This command should help you create a run configuration (in .vscode/launch.json) with certain defaults, which you can customize per your preference.

Please let us know if this works for you.

_Note that we have deprecated Cloud Code: Deploy and Cloud Code: Continuous Deploy commands in favor of this command._

**Comment by o1da** [comment]
Hi @sujit-kamireddy it works pretty well, thank you very much!

**Comment by sujit-kamireddy** [comment]
@o1da , Thank you for confirming!
