### ISSUE TITLE
Managed Dependency Check Failed

### ISSUE THREAD

**Issue by yblaize** [GoogleCloudPlatform/cloud-code-vscode#470]
**Environment**:
*(Hint: "Report Extension Issue on Github" command will fill these out for you.)*

**Version information**

Cloud Code Extension version:

VSCode version:

OS: 

Cloud SDK:

Skaffold: not installed

Kubectl: not installed

**Description**: kubectl binary is managed by Cloud Code but is not found. Please report this issue on our GitHub.
skaffold binary is managed by Cloud Code but is not found. Please report this issue on our GitHub.

**Repro step**:

**Comment by glouischandra** [comment]
Hello @yblaize, do you mind adding these informations?
Version information

Cloud Code Extension version:

VSCode version:

OS:

Cloud SDK:

They will help us debug this issue better. Thanks!

**Comment by sivakku** [comment]
Please re-open with more details to reproduce on our end.
