### ISSUE TITLE
Manifest Generation Functionality not Available

### ISSUE THREAD

**Issue by pantelis-karamolegkos** [GoogleCloudPlatform/cloud-code-vscode#471]
Issue Type: <b>Bug</b>

- VS Code Version: 1.60 (August 2021)
- OS Version: MacOS Big Sur

Steps to Reproduce:

1. Install `cloud-code` extension (I have also installed `kubernetes` extension although it is not strictly necessary)
2. Create a new `.yaml` file (e.g. `deployment.yaml`)
3. Hit `Ctrl+Space` so that a list of available `k8s` templates to select from pops up, as demoed [here](https://youtu.be/62GLbBDLiPE?t=640).
4. No list to select from appears

Extension version: 1.14.0
VS Code version: Code 1.60.0 (Universal) (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:54:53.442Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

**Comment by kschaab** [comment]
Are you using vim extension?  If so you have to be in edit mode.  Additional information from Cloud Code Yaml Support window in the output tab would be useful, do you see errors there?

**Comment by pantelis-karamolegkos** [comment]
I haven't install any `vim` - related plugins, therefore I am not using `vim` mode.

Regarding the second item Ι don't see any option for `cloud-code` in the `output` drop down list (don't know if this makes any sense) despite `cloud-code` indeed being installed on my VSCode.


![Screenshot 2021-09-14 at 8 39 45 AM](https://user-images.githubusercontent.com/50835081/133201232-f4d19259-bafd-4377-9244-284c903f9e13.png)

![Screenshot 2021-09-14 at 8 42 48 AM](https://user-images.githubusercontent.com/50835081/133201508-056a25de-5b53-4e2e-8de6-d315c8df7b8a.png)

**Comment by pantelis-karamolegkos** [comment]
Is the create manifest from template a command that should appear in cloud-code's list of commands? (in VSCode's command palette?)


![Screenshot 2021-09-14 at 8 58 42 AM](https://user-images.githubusercontent.com/50835081/133203037-dc1a7977-fc02-4fa8-ba45-5f2e92e2131a.png)

**Comment by pantelis-karamolegkos** [comment]
btw I just tested this on another machine (Ubuntu 20.04.3 LTS) with version 1.59 and it worked.

I then proceeded with uprading VSCode to 1.60 and it also worked.

Seems MacOS specific perhaps (?)

**Comment by pantelis-karamolegkos** [comment]
btw what is the way to remap this functionality?

**Comment by glouischandra** [comment]
Hi @pantelis-karamolegkos,

I cannot seem to repro this issue on Mac OSX + VSCode 1.60 + Cloud Code 1.14.1 either, when pressing ctrl + space, I got the auto complete list:
![image](https://user-images.githubusercontent.com/3677364/133723627-1b3b65e0-2752-4e46-8821-75a95d9b32c2.png)

I don't think this feature is available in Command Palette either. Can you ensure that the verbose logging enabled in cloud code: 
![image](https://user-images.githubusercontent.com/3677364/133723860-b4a60c1c-5fe1-46c1-a738-82b8a2aa7f52.png)

Then check if the Cloud Code output now shows up.

**Comment by pantelis-karamolegkos** [comment]
I have turned on the verbose logging feature. Unfortunately I still cannot see Cloud Code as an option in available Outputs.

![Screenshot 2021-09-17 at 11 03 25 AM](https://user-images.githubusercontent.com/50835081/133747453-06d09c1f-9f70-4b69-8860-b98ddb433f5e.png)
![Screenshot 2021-09-17 at 11 03 44 AM](https://user-images.githubusercontent.com/50835081/133747458-e35025d6-24bb-4ff5-83c8-cae99998dea2.png)

**Comment by glouischandra** [comment]
@pantelis-karamolegkos Ah, it shows up as the 5th option. Can you try clearing the output, repro the issue in your machine and send us the output? Thanks!

**Comment by pantelis-karamolegkos** [comment]
I haven't got back yet on this since I haven't found the time to sanitise the log output (check for sensitive info).

So this is an Intellisense feature and you suggest there might be an issue with my overall Intellisence setup on Mac, which might not be working, right?
