### ISSUE TITLE
Dart language support

### ISSUE THREAD

**Issue by mark-dropbear** [GoogleCloudPlatform/cloud-code-vscode#473]
**Use case**
What are you trying to do that our extension doesn't let you?

I want to be able to use the extension to generate and work with Dart language applications the same way I can with others such as .NET or JavaScript.

**Feature**
What would help?

Official support for the Dart language to help the growing community have a great development experience with Google Cloud.

**Comment by sivakku** [comment]
Thanks @mark-dropbear for asking for Dart. We don't have any plans to support Dart applications, but we will keep this in mind when we are doing language support for Cloud Code Extension.
