### ISSUE TITLE
Settings: Cloudcode › Yaml: Kubernetes Version outdated?

### ISSUE THREAD

**Issue by swe-pawe** [GoogleCloudPlatform/cloud-code-vscode#476]
While updating apiVersions today I found Cloudcode warning about an unknown apiVersion "networking.k8s.io/v1" for kind "Ingress".
Heading over to the settings I found the Cloudcode YAML editing support supports Kubernetes versions 1.12 to 1.17 only.
Are there plans to add support for current versions?
Or did I miss something elsewhere?

![image](https://user-images.githubusercontent.com/7745337/134385395-2670d289-1dd5-4194-9153-a378a355c068.png)

My current version of the VS Code Cloudcode plugin is 1.14.1

**Comment by ssmall** [comment]
Hi @swe-pawe,

We'll be updating these versions for the next release. For now, though, as a workaround you can set your current Kubernetes context to any reachable cluster and autocomplete will default to the API version of that cluster (even when it's a newer version that doesn't appear in this list).

**Comment by ssmall** [comment]
The updated list of versions is now available in our Insiders release. If you'd like to take advantage of the new versions, you can update the setting `cloudcode.updateChannel` to `Insiders` to switch to the Insiders channel, or you can wait for the official 1.15 release.

I'm going to go ahead and resolve this issue, but please re-open if you have any further questions or issues!

**Comment by thomasLeclaire** [comment]
Hello! following this update, I have this issue on Service declaration : 
![image](https://user-images.githubusercontent.com/43581346/136416170-ed229917-3670-4e46-89f4-feda5d6d50c9.png)

according to what I see in kubernetes doc, targetPort can be Int or String

**Comment by kazshinohara** [comment]
@ssmall Hi I could see the same issue at Cloud Code on Cloud Shell, do you have a plan to update it too ?  (Sorry this repo is for VSCode but I'm not sure the place I should ask)

**Comment by thomasLeclaire** [comment]
@kazshinohara 
FYI : https://issuetracker.google.com/issues?q=componentid:187188%20status:open&s=modified_time:desc
and https://cloud.google.com/shell/docs/release-notes

cloud code version in cloud shell is "only" at 1.14.1
