### ISSUE TITLE
.vsix install on OpenVSCode Server doesn't work

### ISSUE THREAD

**Issue by arborealglobal** [GoogleCloudPlatform/cloud-code-vscode#479]
**Environment**:
*(Hint: "Report Extension Issue on Github" command will fill these out for you.)*
(I tried this but it brought me to a blank bug report...)

**Version information**

Cloud Code Extension version: 1.14.1

VSCode version:

Version: 1.60.2
Commit: 5c8a1f382fff8e1da701d20cf2e50283475af062
Date: 2021-09-23T06:48:36.180Z
Browser: Mozilla/5.0 (X11; CrOS x86_64 14092.66.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.95 Safari/537.36

OS: 
Operating System: Ubuntu 20.04.3 LTS
Kernel: Linux 5.11.0-1019-aws
Architecture: x86-64

**Description**:

gcloud/kubectl work fine from the command line (https://www.gitpod.io/blog/openvscode-server-launch). I couldn't fine Cloud Code in the extension list, but really wanted to use it, so worked out that I could install it with the .vsix 

Sadly though, when I try to log in, I get this error. Also, when I then try again to use gcloud in the terminal that fails too. Would love to get this working if at all possible? Any ideas?

home/ubuntu/.cache/cloud-code/installer/google-cloud-sdk/bin/gcloud auth login --quiet
Traceback (most recent call last):
  File "/home/ubuntu/.cache/cloud-code/installer/google-cloud-sdk/lib/gcloud.py", line 104, in <module>
    main()
  File "/home/ubuntu/.cache/cloud-code/installer/google-cloud-sdk/lib/gcloud.py", line 62, in main
    from googlecloudsdk.core.util import encoding
  File "/home/ubuntu/.cache/cloud-code/installer/google-cloud-sdk/lib/googlecloudsdk/__init__.py", line 23, in <module>
    from googlecloudsdk.core.util import importing
ModuleNotFoundError: No module named 'googlecloudsdk.core'
**Repro step**:

Install OpenVSCode Server on a VM, try and install Cloud Code using the .vsix that is downloadable from the marketplace. Try and login.

**Comment by sivakku** [comment]
Thanks for the feedback. We haven't looked into publishing to Open VSX registry. i tried using VSCode server and don't seem to run in to any auth problems. Using a VM from GCP for the repro through: https://github.com/gitpod-io/openvscode-server/tree/main/docs/guides/gcp-gce 

Do make sure the VM has access to reach out to GCP auth servers.

```
user@cloudshell:~/cloudshell_open/openvscode-server$ gcloud auth login --quiet
Go to the following link in your browser:

    https://accounts.google.com/*****

Enter verification code: *************

You are now logged in as [**********].
Your current project is [None].  You can change this setting by running:
  $ gcloud config set project PROJECT_ID
```
