### ISSUE TITLE
FR: Allow user to add pull secrets to the cluster from the GUI

### ISSUE THREAD

**Issue by kostis-codefresh** [GoogleCloudPlatform/cloud-code-vscode#48]
I created the sample Java application and tried to deploy it with Cloud Code: deploy to a local cluster.

The deployment failed because the cluster did not have access to the Docker registry I used for deployment.

Maybe mention this in the deployment guide? Or even better allow the user to create pull secrets from the Kubernetes explorer?

**Comment by jmah-cc** [comment]
Closing as a dupe of #71
