### ISSUE TITLE
Iterative Debugging is broken with latest version v1.15.0

### ISSUE THREAD

**Issue by sivakku** [GoogleCloudPlatform/cloud-code-vscode#486]
The iterative debugging across languages is broken for now you have to turn off the the watch mode using below [instructions](https://cloud.google.com/code/docs/vscode/debug#debugging_an_application). 
We are doing a patch to turn off watch mode until the issue is resolved. 
Do subscribe to this ticket for further updates.

**Comment by kschaab** [comment]
This was fixed in 1.16
