### ISSUE TITLE
Clarify support for local clusters on Docker for desktop, microk8s

### ISSUE THREAD

**Issue by kostis-codefresh** [GoogleCloudPlatform/cloud-code-vscode#49]
Apart from Minikube, Mac/Win users can also create a local cluster with Docker for desktop. Linux users also may have a local cluster with microk8s.

It would be good for the docs to specify is these options are supported or not.

**Comment by iantalarico** [comment]
@sanguinecloud Can you help us get some updated docs around adding cluster to the users default config?

**Comment by sanguinecloud** [comment]
Docs have been updated to reflect local cluster support.

**Comment by redborian** [comment]
Thanks for the doc update @sanguinecloud. Closing this issue.
