### ISSUE TITLE
[Feature] Compute Engine Management

### ISSUE THREAD

**Issue by jdegregorio** [GoogleCloudPlatform/cloud-code-vscode#496]
**Use case**
Machine learning remote/hosted development environment management.

**Feature**
Create, delete, stop, and start instances in GCP product from VSCode. Spin up for development, ssh connect, then turn off.

**Comment by sivakku** [comment]
@jdegregorio - Thanks for the feedback. This is in our plans and we will be re-visiting our roadmaps, stay tuned for the updates.

**Comment by kschaab** [comment]
This is released
