### ISSUE TITLE
Deploy to Cloud Run - Deploy Docker Image to Artifact Registry

### ISSUE THREAD

**Issue by RubenAgDev** [GoogleCloudPlatform/cloud-code-vscode#500]
Issue Type: <b>Bug</b>

*Context*
- Managed Dependencies: on
- Cloud SDK Version: 364.0.0
- Skaffold Version: v1.34.0
- Minikube Version: 1.23.2

When deploying to Cloud Run using a local build environment based on a local Dockerfile setting the value of "Container image URL" to a valid Artifact Registry URL does not work but the Docker image is still deployed to "gcr.io".

Extension version: 1.15.1
VS Code version: Code 1.62.1 (Universal) (f4af3cbf5a99787542e2a30fe1fd37cd644cc31f, 2021-11-05T09:23:14.144Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

**Comment by j-windsor** [comment]
Hello @RubenAgDev, 

I just tried to repro on our latest version of Cloud Code (v.1.16.0) and could not while following the repro steps below. Could you please see if you could repro on the latest version of Cloud Code, and if so, provide detailed repro steps?

No repro steps:
1. Create a new Cloud Code Cloud Run NodeJS sample app.
2. Click Deploy to Cloud Run in the Cloud Run Explorer header.
3. Change the "Container image URL" to a valid artifact registry url beginning with "us-west1-docker.pkg.dev".
4. Click deploy.

**Comment by ChaseMor** [comment]
Wasn't able to repro this on 1.16.1 or with the latest release. We released 1.17.0 today which has some updates to make it easier to use Artifact Registry. Try it with that and if it still doesn't work reopen this issue.
