### ISSUE TITLE
Cloud API Browser is empty

### ISSUE THREAD

**Issue by ssmall** [GoogleCloudPlatform/cloud-code-vscode#501]
## Description

Cloud API Browser appears empty. This is a known issue in the 1.16.0 release that only affects Remote-SSH and Remote-WSL development sessions. 

![Screen Shot 2021-11-12 at 11 47 29](https://user-images.githubusercontent.com/641091/141526101-cf0a98ae-f643-4a34-b866-1ab9ba6273ff.png)

### Downgrade Cloud Code Extension

This issue can be mitigated by [downgrading](https://stackoverflow.com/questions/42626065/vs-code-how-to-rollback-extension-install-specific-extension-version/53755378#53755378) the remote version of Cloud Code to 1.15.1. After installing the previous version and reloading VSCode, it may then be possible to re-install Cloud Code 1.16.0 and use the Cloud API Browser. If not, please remain on 1.15.1 until this issue is resolved in the next release.

### Do not use Remote-SSH / Remote-WSL development mode

This issue does not affect Linux, macOS, or Windows when VSCode is running in normal development mode. If your developer environment allows, you can work around this issue by developing directly on Linux, macOS, or Windows without the use of the Remote Development extension.

## Affected VS Code version(s):
- All

## Affected Cloud Code version(s):
- 1.16.0

## Affected platform(s):
- Linux (Remote Development)

**Comment by quoctruong** [comment]
This issue is now fixed with the latest release (v1.16.1).
