### ISSUE TITLE
Apigee Emulator

### ISSUE THREAD

**Issue by fabltd** [GoogleCloudPlatform/cloud-code-vscode#502]
The Apigee Emulator appears to be a Intel Image when installed on a M1 Mac.

Is there an plan for an Apple Silicon version?

**Comment by shirishtrivikr** [comment]
The Emulator version is same as what we provide as part of hybrid or Apigee-X installation and we do not have specific plans for a different version.

**Comment by norberto-enomoto** [comment]
It will be very interesting to provide Apigee Emulator to run on Mac M1 (Apple Silicon)

**Comment by norberto-enomoto** [comment]
This is a workaround for Mac M1. Create a Google Apigee runtime 1.6.1 called "apigee". Open a terminal and delete this container called "apigee". Run this command: docker run --platform linux/amd64 --name=apigee -p 8080:8080 -p 8998:8998 gcr.io/apigee-release/hybrid/apigee-emulator:1.6.1
