### ISSUE TITLE
Releases since 1.15.0 don't include .vsix files

### ISSUE THREAD

**Issue by fiveable-jferg** [GoogleCloudPlatform/cloud-code-vscode#504]
I would like to use cloudcode in Gitpod, and I can work around it not being published to open-vsx by installing from the github release (https://github.com/GoogleCloudPlatform/cloud-code-vscode/releases/download/v1.12.0/cloudcode-1.12.0.vsix), but it seems releases from 1.15.0 onward don't include the .vsix file in the release.  Can this be remedied?

**Comment by j-windsor** [comment]
@fiveable-jferg thanks for bringing this to our attention! I've fixed the issue.

**Comment by fiveable-jferg** [comment]
Thanks so much!
