### ISSUE TITLE
Electron Process High CPU Usage

### ISSUE THREAD

**Issue by kennethlombardi** [GoogleCloudPlatform/cloud-code-vscode#518]
Issue Type: <b>Bug</b>

Use this extension and save and open and save a few files. I saved a combination of .ts, .js, .json, .yml and eventually the Electron process starts using 50 and then 100 percent of the CPU.

I used Extension Bisect and found it eventually.

Extension version: 1.17.0
VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:37:28.172Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 6, 6|
|Memory (System)|16.00GB (3.62GB free)|
|Process Argv|--crash-reporter-id e678bce4-1d1c-4cf5-a01d-d1e4579619f6|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30384385
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscop804cf:30404767
vscop341:30404997
vsrem710cf:30416617
vscexrecpromp3c:30407761

```

</details>

**Comment by ssmall** [comment]
Hi @kennethlombardi, was there by any chance a cpuprofile file that got generated that you could upload to this issue to help us investigate?

If you are able to reproduce the issue, you can follow these steps to capture a profile:

1. Open Help menu
1. Toggle Developer Tools
1. Go to Profile tab
1. Press Record
1. Reproduce issue
1. Stop recording and upload saved CPU profile to this issue

**Comment by glouischandra** [comment]
Hello, please reopen this bug with the .cpuprofile file for us to better debug the issue. Thanks!
