### ISSUE TITLE
Can't add a new GKE cluster after deleting Google project

### ISSUE THREAD

**Issue by subfuzion** [GoogleCloudPlatform/cloud-code-vscode#520]
Issue Type: <b>Bug</b>

After deleting a Google project in the Cloud Console that was previously used to create a GKE cluster from within the extension, the extension is "unable to initialize adding a cluster" (and references the previous project).

![image](https://user-images.githubusercontent.com/159738/148835249-f47f2001-1a9f-43f6-be4a-dc49a07769c4.png)

- Managed Dependencies: on
- Cloud SDK Version: 367.0.0
- Skaffold Version: v1.34.0
- Minikube Version: 1.24.0

Extension version: 1.17.0
VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:37:28.172Z)
OS version: Darwin x64 21.2.0
Restricted Mode: No

**Comment by subfuzion** [comment]
I just discovered that using gcloud to change the project (`gcloud config set project`) can fix this. Nevertheless (unless I'm missing something), it would be great to have a way to fix within the extension.

**Comment by glouischandra** [comment]
@subfuzion thanks for filing the bug, yes we think the extension is caching the deleted project and we should provide a way to switch the project in the kubernetes explorer, currently you can change the project in Cloud Run explorer.

**Comment by subfuzion** [comment]
Nice! I had `Cloud Run` (and a bunch of other explorers) hidden on the Activity Bar since I'm recording videos and wanted to keep focus on the `Kubernetes` view. Thanks for the tip!

**Comment by subfuzion** [comment]
I can see that the Cloud Run project selector must be caching, however, because it still shows the deleted cluster. Not sure how to force it to refresh, but in any case I'm at least able to continue working with a solution that doesn't require me to use gcloud. Thanks again!

**Comment by glouischandra** [comment]
Yes, we will address the caching issue and have better UX to notify outdated project.

**Comment by glouischandra** [comment]
closing this issue as there's a workaround to change project via Cloud Run.
