### ISSUE TITLE
Can't use kind-kind context because cloud code gets stuck "starting minikube if profile exists"

### ISSUE THREAD

**Issue by snickell** [GoogleCloudPlatform/cloud-code-vscode#521]
Issue Type: <b>Bug</b>

- Setup a `kind-kind` instance using `kind create cluster`
- Set kube context to `kind-kind`
- Switch to `Cloud Code - Kubernetes` extension
- Ensure that `kind-kind` is selected as ACTIVE in the Clusters panel
- Create `hello world (flask)` project
- Try to run the project from "cloud code - kubernetes"

Results:
Cloud code gets stuck ("IN PROGRESS" for a long long long time) trying to "Initialize Session - Starting minikube if profile exists"

Why is cloud code trying to start minikube when I'm using an existing k8s cluster context not under its management? Because minikube does not work in my context (that's why I'm using kind), it never starts. I'm using `kind` to work around known arm64 with amd64 DOCKER_HOST issues with minikube.... my whole goal here is to avoid minikube because it won't start!

*Context*
- Managed Dependencies: on
- Cloud SDK Version: 368.0.0
- Skaffold Version: v1.35.1
- Minikube Version: 1.24.0

Extension version: 1.17.0
VS Code version: Code 1.63.2 (Universal) (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:37:28.172Z)
OS version: Darwin arm64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 7, 6|
|Memory (System)|16.00GB (0.87GB free)|
|Process Argv|--crash-reporter-id c2a861b4-7bb2-4e60-b907-ff761c4cfd0a|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30421291
pythonvs932:30410667
vscop804:30404766
vscop940:30404999
vsrem710:30416614

```

</details>

**Comment by ssmall** [comment]
Hi @snickell,

Thanks for your report and sorry that you're having issues. It would help if you could provide some more background on this comment?

> Because minikube does not work in my context (that's why I'm using kind), it never starts. I'm using kind to work around known arm64 with amd64 DOCKER_HOST issues with minikube.... my whole goal here is to avoid minikube because it won't start!

We have been unable to reproduce this on our end -- we test the latest version of the Cloud Code extension with minikube on our M1 Macs. Have you already reported this issue to https://github.com/kubernetes/minikube? I saw that you had opened https://github.com/kubernetes/minikube/issues/13303 in that repo but you appear to be describing a different issue here.

**Comment by glouischandra** [comment]
Please feel free to reopen this ticket with more information for us to debug/repro the issue.
