### ISSUE TITLE
cloude

### ISSUE THREAD

**Issue by efremrob** [GoogleCloudPlatform/cloud-code-vscode#522]
Issue Type: <b>Bug</b>

*Context*
- Managed Dependencies: on
- Cloud SDK Version: 368.0.0
- Skaffold Version: v1.35.1
- Minikube Version: 1.24.0

Extension version: 1.17.0
VS Code version: Code - Insiders 1.64.0-insider (753319a08f8e74700b1dba3a29bf0a6af7c2953f, 2022-01-12T05:16:42.486Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2689 0 @ 2.60GHz (16 x 2594)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.99GB (3.89GB free)|
|Process Argv|--crash-reporter-id c79ab907-bb06-4845-96a2-909191215aca|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vsdfh931:30280409
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
pythonvspyt200:30323110
vsccppwt:30421239
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
wslgetstartedc:30421358
vscop804cf:30404767
vs360cf:30404996
vsclayoutctrc:30405799
azactmsal:30409287
vsccppwtstudy:30421978

```

</details>

**Comment by ssmall** [comment]
Hi @efremrob,

Can you please update the issue description to provide more information about the bug you're experiencing?

**Comment by ssmall** [comment]
Closing this issue, please feel free to re-open with additional information about the issue you're experiencing.
