### ISSUE TITLE
Unable to create new application: Can't find Git

### ISSUE THREAD

**Issue by Jens-EstateMate** [GoogleCloudPlatform/cloud-code-vscode#535]
Issue Type: <b>Bug</b>

If I create a new application (e.g. Cloud Run Flask) using the Cloud Code extension I immediately get an error that "git is required to clone...", but I have Git installed and use it for all other projects.

My Git output shows an alternative error:  
"fatal: No remote repository specified.  Please, specify either a URL or a
remote name from which new revisions should be fetched."

- Managed Dependencies: on
- Cloud SDK Version: 373.0.0
- Skaffold Version: v1.35.1
- Minikube Version: 1.24.0

Extension version: 1.17.0
VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1246 v3 @ 3.50GHz (8 x 3492)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.76GB (13.39GB free)|
|Process Argv|--crash-reporter-id 16e05daa-2d6c-47d9-9935-0995ece22a89|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30425749
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstartedc:30433508
vsclayoutctrc:30437038
vsrem710cf:30416617
dsvsc009:30440023
pythonvsnew555cf:30436485
vsbas813:30436447
vscscmwlcmc:30438804
helix:30440343

```

</details>

**Comment by kschaab** [comment]
We do not install Git as part of our dependencies.  If you install Git after starting VS Code you must restart VS Code in order for it to pick up the changes to the PATH in the environment block.  Please let us know if you are able to continue after this or require more assistance.

**Comment by kschaab** [comment]
Can you specify the version of git you are using (`git --version`)?

**Comment by Jens-EstateMate** [comment]
![image](https://user-images.githubusercontent.com/29678418/155270359-72869249-c12f-4c05-994e-a57f3b92e6f3.png)

I will update Git and then try again and report back.

**Comment by Jens-EstateMate** [comment]
After updating Git on PC to 2.35 it worked like a charm.
