### ISSUE TITLE
Unable to start cloud run emulator: Unexpected token { in JSON at position 331

### ISSUE THREAD

**Issue by Jens-EstateMate** [GoogleCloudPlatform/cloud-code-vscode#536]
Issue Type: <b>Bug</b>

To recreate I click on the "Cloud Code" button, Run on Cloud Run Emulator, and build using Docker.

After about 2mins I get a VS Code error " Unexpected token { in JSON at position 331"

The output provided gives no further details as to what the issue is:
```
Running skaffold command: C:\USERS\JENS.HIESTERMANN\APPDATA\LOCAL\CLOUD-CODE\INSTALLER\GOOGLE-CLOUD-SDK\BIN\SKAFFOLD.EXE init --artifact {"image":"template","builder":"Docker","payload":{"path":"server/Dockerfile"}} --kubernetes-manifest C:\Users\JENS~1.HIE\AppData\Local\Temp\cloud-code-cloud-run-1bwz4W\pods_and_services.yaml --filename C:\Users\JENS~1.HIE\AppData\Local\Temp\cloud-code-cloud-run-1bwz4W\skaffold.yaml --force
Setting build tagPolicy to SHA256.
Setting statusCheckDeadlineSeconds to 5 minutes
Setting build environment to 'local'
Created the file C:\Users\JENS~1.HIE\AppData\Local\Temp\cloud-code-cloud-run-1bwz4W\skaffold.yaml.
Running gcloud command: GCLOUD.CMD beta code export --readiness-probe --service-name template --image template --no-skaffold-file --dockerfile= --kubernetes-file C:\Users\JENS~1.HIE\AppData\Local\Temp\cloud-code-cloud-run-1bwz4W\pods_and_services.yaml --env-vars K_SERVICE=template,K_REVISION=local,K_CONFIGURATION=template --memory 256Mi --quiet
Created the file C:\Users\JENS~1.HIE\AppData\Local\Temp\cloud-code-cloud-run-1bwz4W\pods_and_services.yaml.
Running: skaffold dev -v info --port-forward --rpc-http-port 65339 --filename C\:\\Users\\JENS~1.HIE\\AppData\\Local\\Temp\\cloud-code-cloud-run-1bwz4W\\skaffold.yaml --kube-context cloud-run-dev-internal --minikube-profile cloud-run-dev-internal --status-check
```

My launch.json file:
```
{
    "configurations": [
        {
            "name": "Cloud Run: Run/Debug Locally",
            "type": "cloudcode.cloudrun",
            "request": "launch",
            "build": {
                "docker": {
                    "path": "server/Dockerfile"
                }
            },
            "image": "template",
            "service": {
                "name": "template",
                "containerPort": 8080,
                "resources": {
                    "limits": {
                        "memory": "256Mi"
                    }
                }
            },
            "target": {
                "minikube": {}
            },
            "watch": true
        }
    ]
}
```

- Managed Dependencies: on
- Cloud SDK Version: 373.0.0
- Skaffold Version: v1.35.1
- Minikube Version: 1.24.0

Extension version: 1.17.0
VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1246 v3 @ 3.50GHz (8 x 3492)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.76GB (13.36GB free)|
|Process Argv|--crash-reporter-id 16e05daa-2d6c-47d9-9935-0995ece22a89|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30425749
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstartedc:30433508
vsclayoutctrc:30437038
vsrem710cf:30416617
dsvsc009:30440023
pythonvsnew555cf:30436485
vsbas813:30436447
vscscmwlcmc:30438804
helix:30440343

```

</details>

**Comment by kschaab** [comment]
If you would:

1. Please turn on verbose logging

<img width="707" alt="image" src="https://user-images.githubusercontent.com/7329029/155235800-d73789ea-8af6-4ab0-b762-65ac1ce83b63.png">

2. Restart VS Code
3. Send us the gist of the Cloud Code output window when you hit this error:
<img width="1063" alt="image" src="https://user-images.githubusercontent.com/7329029/155235925-5a732f1f-fd07-4b56-8b87-c821f62d83e4.png">

**Comment by Jens-EstateMate** [comment]
Keith, thank you for your response. I ended up removing the docker image generated by the "Cloud Code" (Docker Desktop), updating the Docker for Windows, and then running this Cloud Run emulator again. It then worked without the error reported.

Apologies now I can't recreate the issue to provide further logs
