### ISSUE TITLE
Stream logs from multiple pods(across all containers) simultaneously 

### ISSUE THREAD

**Issue by femrtnz** [GoogleCloudPlatform/cloud-code-vscode#54]
<b>Environment</b>:
Extension Version: 0.0.4
VSCode version: 1.32.2
OS version: darwin

<b>Description:</b>
Would be great if we could stream logs from multiple pods, similar to what we can get using [stern](https://github.com/wercker/stern) or using `--all-containers` flag

**Comment by iantalarico** [comment]
This was fixed in a previous release, please give it a try from the deployment!

<img width="565" alt="Screen Shot 2019-06-19 at 3 29 18 PM" src="https://user-images.githubusercontent.com/5264734/59805814-2c2f4580-92a7-11e9-9704-426cb7884025.png">


@sanguinecloud Can you help us get some update docs to show this is possible?

**Comment by femrtnz** [comment]
From what I tested it seem it chose a pod randomly. WE can see this in the beginning of the logs
```
Streaming Logs from deployment my-app
Found 11 pods, using pod/my-app-7b4c8d9549-5jn84
```

**Comment by iantalarico** [comment]
@quoctruong Can you take a closer look at this?

**Comment by quoctruong** [comment]
@iantalarico @femrtnz This is the expected behavior from kubectl. However, we can work to add the streaming logs from all the pods support too.

**Comment by jmah-cc** [comment]
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-vscode-internal](https://github.com/GoogleCloudPlatform/cloud-code-vscode-internal/issues/3756)

**Comment by quoctruong** [comment]
@femrtnz If you are using GKE cluster, you can now stream logs from multiple pods with Stackdriver. Otherwise, there is no plan to add support for streaming logs from multiple pods with `kubectl` right now. Feel free to reopen if you have any questions!
