### ISSUE TITLE
VS Code Pass in argument to skaffold

### ISSUE THREAD

**Issue by imilic1** [GoogleCloudPlatform/cloud-code-vscode#540]
Hi. I am trying to debug local Kubernetes with Cloud Code in VS Code but I need to pass in some arguments to skaffold, for instance to skip tests (--skip-tests). I can't find a way to do that. I need my skaffold command to be something like:

skaffold debug -v info --port-forward --auto-build --auto-deploy ...... --skip-tests

**Comment by glouischandra** [comment]
Hello @imilic1, we currently do not support passing arguments to skaffold through Cloud Code and the feature is still being discussed. For workaround you should be able to pass the skip tests flag via environment variable in your VSCode instance: SKAFFOLD_SKIP_TESTS is the env_var per https://skaffold.dev/docs/references/cli/

**Comment by imilic1** [comment]
@glouischandra thank you very much. Yes, passing in the env var would work for me. I tried passing this by adding env var to launch.json but i doesn’t end up in skaffold and it still runs all the tests. Do you know the way to pass in the env var that scaffold will consider?

**Comment by imilic1** [comment]
Is there anyone guys who can help me and explain how to pass in the skip-tests flag to skaffold when debugging local Kubernetes?

**Comment by sujit-kamireddy** [comment]
The below steps should help.
1. Open a terminal
2. Set SKAFFOLD_SKIP_TESTS env var to true. https://skaffold.dev/docs/references/cli/#skaffold-dev
3. Open the vscode from this terminal.
4. Use the debug functionality.

**Comment by imilic1** [comment]
Thanks, @sujit-kamireddy. This works well!

**Comment by tiagovrtr** [comment]
@sujit-kamireddy is there a proposal for how this could ideally be passed?  It would be great to set it in `launch.json` in `configurations.[].environment` like similar runners, so it could then take input or command variables, and be used in skaffold's templated fields. I'd love to help but it's closed-source 😅
