### ISSUE TITLE
Cloud Code should accept directory(or path expressions) as input for Adding own crds.

### ISSUE THREAD

**Issue by phanimarupaka** [GoogleCloudPlatform/cloud-code-vscode#545]
**Use case**
Cloud Code should accept directory as input for Adding own crds.

**Feature**
Here is the documentation for [Add your own crds](https://cloud.google.com/blog/products/containers-kubernetes/cloud-code-features-expanded-support-for-kubernetes-crds). However, we need to add each file to onboard a CRD. It would be great if we can add a directory or path expressions.

**Comment by kschaab** [comment]
This is the "cloudcode.yaml.crdSchemaLocations" setting:

<img width="753" alt="image" src="https://user-images.githubusercontent.com/7329029/158267738-f7672e8c-af8c-45e1-8db9-1d6750d13cc7.png">

**Comment by phanimarupaka** [comment]
@kschaab I agree that we can pass multiple locations. But my request to accept a directory/path expressions instead of needing to list each individual crd file.
