### ISSUE TITLE
Cloud SDK reported as corrupted while using Remote - SSH extension 

### ISSUE THREAD

**Issue by javiercanadillas** [GoogleCloudPlatform/cloud-code-vscode#550]
Issue Type: <b>Bug</b>

*Context*
- Managed Dependencies: on
- Cloud SDK Version: Not installed
- Skaffold Version: Not installed
- Minikube Version: Not installed

**Remote machine**: Ubuntu 21.10, up-to-date at the time of this report, with Google Cloud SDK installed following [official procedure](https://cloud.google.com/sdk/docs/install#deb). `gcloud --version` from terminal in remote machine reports:

```text
Google Cloud SDK 378.0.0
alpha 2022.03.18
beta 2022.03.18
bq 2.0.74
bundled-python3-unix 3.8.11
core 2022.03.18
gsutil 5.8
````

**Local machine**: Mac OS X 12.3 with Cloud Code extension installed in VSCode.

Steps to repro:

1. Open vscode in local machine. Call command palette (Shift + Cmd + P) and type `Remote - SSH: connect to host...`. Select remote machine as host.
2. On new vscode window in remote host, go to Extensions, search for Cloud Code, and select "Install in SSH: <remote-machine>
3. Cloud Code starts installing
4. After finishing installation, an error dialog appears with the message: `Cloud SDK was installed but was found to be invalid or corrupted so it was removed. Attempting to reinstall. Managed dependencies will be unavailable during this process. (install attempt 3)`
5. After this one, another error message appears: `Managed dependencies are currently unavailable. Failed to install managed dependencies successfully too many times, will reattempt after Visual Studio Code is restarted. Unable to initialize gcloud`

Google Cloud SDK is installed locally in the remote machine. I've tried reinstalling Cloud Code unssuccessfully.

Extension version: 1.17.1
VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:49.188Z)
OS version: Darwin x64 21.4.0
Restricted Mode: No
Remote OS version: Linux x64 5.13.0-37-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz (8 x 2000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 4|
|Memory (System)|16.00GB (0.24GB free)|
|Process Argv|. --crash-reporter-id 946943d7-92f2-432a-8a16-f77f913bdebd|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: deus.home|
|OS|Linux x64 5.13.0-37-generic|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 1852)|
|Memory (System)|62.73GB (55.64GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvsnew555:30457759
vscscmwlcmc:30438804
vscgsvidc:30447482
pynewfile477:30450038

```

</details>

**Comment by kschaab** [comment]
I cannot reproduce this issue, is it possible there was an issue with space?
