### ISSUE TITLE
Hurricane

### ISSUE THREAD

**Issue by bugalwena** [GoogleCloudPlatform/cloud-code-vscode#558]
All God did was create new reality

Issue Type: <b>Bug</b>

*Context*
- Managed Dependencies: on
- Cloud SDK Version: 380.0.0
- Skaffold Version: v1.37.1
- Minikube Version: 1.25.2

Extension version: 1.19.0-insiders.1
VS Code version: Code 1.66.1 (8dfae7a5cd50421d10cd99cb873990460525a898, 2022-04-06T14:50:12.141Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Connection to 'WSL: docker-desktop' could not be established  VS Code Server for WSL closed unexpectedly.
Check WSL terminal for more details.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.78GB (2.98GB free)|
|Process Argv|--crash-reporter-id daa1d57b-cf08-4f46-80e0-fdc00b21fc00 --inspect-extensions=51987 --crash-reporter-id daa1d57b-cf08-4f46-80e0-fdc00b21fc00|
|Screen Reader|no|
|VM|0%|

Connection to 'WSL: docker-desktop' could not be established  VS Code Server for WSL closed unexpectedly.
Check WSL terminal for more details.
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
pynewfile477:30463512

```

</details>

**Comment by glouischandra** [comment]
Hello @bugalwena can you provide repro steps? and also if possible paste in "Check WSL terminal for more details" content. This will help us better debug. Thanks!
