### ISSUE TITLE
Cloud Code uses a lot of CPU on initial start on Windows

### ISSUE THREAD

**Issue by kschaab** [GoogleCloudPlatform/cloud-code-vscode#565]
Looks like gcloud cli install/update is consuming a lot of CPU on each start of VS Code on Windows.  From marketplace review:

Unusable on Windows. Python kicks in as soon as installed starting an endless loop triggering MS Defender resulting 30-40% CPU utilization. Launching the Windows 11 Sandbox, I installed VS Code and then the extension and have similar behaviour.

Update: after selecting Cloud Code Kubernetes and letting it complete its initial work, the whole thing came back to a normal state. It's quite unusual for an extension to take 5-10 minutes to complete on first run. Now that bad thing is that everytime I launch Code, Python consume lots of CPU and memory for a couple of minutes. There's clearly a bug in the extension startup code.

**Comment by khmseu** [comment]
I see pretty much the same thing under Linux. "Unusable" seems a good description.

**Comment by kschaab** [comment]
@khmseu - This is fixed, can you please include your extension version?
