### ISSUE TITLE
svn workspace und amd64 fehlen

### ISSUE THREAD

**Issue by maltewiidos** [GoogleCloudPlatform/cloud-code-vscode#571]
Issue Type: <b>Bug</b>

*Context*
- Managed Dependencies: on
- Cloud SDK Version: 384.0.1
- Skaffold Version: v1.38.0
- Minikube Version: 1.25.2

Extension version: 1.18.1
VS Code version: Code 1.66.2 (Universal) (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:49:20.994Z)
OS version: Darwin arm64 21.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 3, 3|
|Memory (System)|8.00GB (0.13GB free)|
|Process Argv|--crash-reporter-id c9840404-d29c-4dbe-9d7c-76d972fdbe2b|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by ssmall** [comment]
Closing for now as there has been no further response. Please feel free to re-open with more details. Thanks!
