### ISSUE TITLE
HTTPTargetConnection.SSLInfo.Enabled = true not working

### ISSUE THREAD

**Issue by ziggy-vladar** [GoogleCloudPlatform/cloud-code-vscode#579]
hi, as an integration developer, I want to connect to a target server via HTTPS with Apigee Emulator (1.6.1)

I exported my apirproxy from Apigee EdgeUI, which has this **HTTPTargetConnection configuration** in the Target Proxy:

    <HTTPTargetConnection>
        <LoadBalancer>
            <Server name="my_server"/>
        </LoadBalancer>
        <SSLInfo>
            <Enabled>true</Enabled>
        </SSLInfo>
    </HTTPTargetConnection>

Note: I can save this and deploy with Apigee EdgeUI without error. I presume, it will then use JVM's default `cacerts` keystore.

When I do „Deploy to Apigee Emulator” in VS Code, I get:
```
EMULATOR INFO Deploying environment dev, to Container apigee-local (1.6.1)
EMULATOR ERROR Code   : messaging.config.beans.KeyStoreNotSpecified
EMULATOR ERROR Message: Keystore or KeyStoreReference must be specified
EMULATOR ERROR File   : {my_path}\apigee-workspace\src\main\apigee\apiproxies\{my_apiproy}\apiproxy\targets\default.xml:32:18
EMULATOR ERROR Code   : messaging.config.beans.KeyAliasNotSpecified
EMULATOR ERROR Message: The KeyAlias to be used in Keystore null must be specified
EMULATOR ERROR File   : {my_path}\apigee-workspace\src\main\apigee\apiproxies\{my_apiproy}\apiproxy\targets\default.xml:32:18
EMULATOR ERROR Environment dev deployment, to Container apigee-local (1.6.1) failed with Error: 400
EMULATOR ERROR Deploy to Container apigee-local (1.6.1), failed with Error: Environment dev deployment, to Container apigee-local (1.6.1) failed with Error: 400
```
I would like to request that Apigee Emulator supports above **HTTPTargetConnection configuration** similar to Apigee EdgeUI.

Thanks and regards, Ziggy

<details>
<summary>Context</summary>

- Managed Dependencies: on
- Cloud SDK Version: 385.0.0
- Skaffold Version: v1.38.0
- Minikube Version: 1.25.2
- Extension version: 1.18.2
- VS Code version: Code 1.67.1 (da15b6fd3ef856477bf6f4fb29ba1b7af717770d, 2022-05-06T12:37:03.389Z)
- OS version: Windows_NT x64 10.0.19042
- Restricted Mode: No

</details>

**Comment by ssmall** [comment]
@shirishtrivikr could you take a look at this?

**Comment by shirishtrivikr** [comment]
We are working on getting keystore support for emulator.

**Comment by shirishtrivikr** [comment]
@ziggy-vladar 
For now could you please try by completely skipping the `<SSLInfo>` block in your load balancer definition.  This should use the default SSL.

I will try and get back to you as soon as I have updates on a full fledged SSL support.

**Comment by shirishtrivikr** [comment]
Full TLS support for target servers has been added. [Docs here](https://cloud.google.com/apigee/docs/api-platform/local-development/vscode/deploy-environment#target-servers)
