### ISSUE TITLE
Error: Unable to connect to GKE Autopilot cluster

### ISSUE THREAD

**Issue by agathor2399** [GoogleCloudPlatform/cloud-code-vscode#582]
I have got an error during the connection to the cluster managed by Autopilot. This is my first time with Autopilot and I don't look that issue reported.

I have managed standard kubernetes clusters before, and I made step by step the connection with the official guide provided by Google Cloud to create an Autopilot cluster. (The step 6 exactly).

My KubeConfig file have the credentials and all needed information to manage a cluster. I can use kubectl to connect to my cluster with no errors. The problem appears when I'm trying to connect from Cloud Code extension.

### Open Kubernetes dashboard error:
```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "services \"https:kubernetes-dashboard:\" is forbidden: User \"xxx@foo.com\" cannot get resource \"services/proxy\" in API group \"\" in the namespace \"kube-system\": GKEAutopilot authz: the namespace \"kube-system\" is managed and the request's subresource \"services/proxy\" is denied",
  "reason": "Forbidden",
  "details": {
    "name": "https:kubernetes-dashboard:",
    "kind": "services"
  },
  "code": 403
}
```

### Error view from VS Code:
![ViewErrorVSCode](https://user-images.githubusercontent.com/94570789/169514938-0690dc95-6eb4-42ea-9aa8-6b94be687564.png)

> As you can see I have a cluster working fine (That's Standard cluster)

**Comment by sushicw** [comment]
Hello! Thanks for reporting the error you saw. A couple of questions to help debug / reproduce the issue:

* Are there any other non-default settings in your autopilot cluster? If you create an autopilot cluster with all default values, does the issue still occur for you?)

**Comment by j-windsor** [comment]
Hi @agathor2399! This is very likely a known issue that we will be releasing a fix for in our next release. Could you please click on the broken cluster in the Kubernetes Explorer which will bring up a dialog with the actual error message to help us verify this is the case?

**Comment by glouischandra** [comment]
@agathor2399 Feel free to reopen the bug with more information if its still reproable. Thanks!
