### ISSUE TITLE
how to deploy by specifying the service.yaml file?

### ISSUE THREAD

**Issue by kincjf** [GoogleCloudPlatform/cloud-code-vscode#589]
**Feature Request**
- Is there any way to deploy by specifying the service.yaml file? Neither the cloud code vscode version nor the intellij version could find a way to deploy using service.yaml.

**Comment by ChaseMor** [comment]
There is an existing feature that might do what you're looking for. https://cloud.google.com/code/docs/vscode/yaml-editing#applying_a_yaml_file

You can try applying the yaml using this command palette entry or you can try to Run on Kubernetes.
https://cloud.google.com/code/docs/vscode/running-an-application


If you have additional questions, feel free to reopen this issue.
