### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by PeezoSlug** [GoogleCloudPlatform/cloud-code-vscode#590]
- Issue Type: `Performance`
- Extension Name: `cloudcode`
- Extension Version: `1.19.0-insiders.0`
- OS Version: `Windows_NT x64 10.0.22621`
- VS Code version: `1.68.0-insider`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/peezo/AppData/Local/Temp/googlecloudtools.cloudcode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by ChaseMor** [comment]
Could you please attach the profile contents to this issue?

**Comment by ssmall** [comment]
Closing this issue for now. Please feel free to attach profile contents and re-open. Thanks!
