### ISSUE TITLE
Apigee emulator unable to reach targets when behind a proxy

### ISSUE THREAD

**Issue by cosmok** [GoogleCloudPlatform/cloud-code-vscode#592]
Issue Type: <b>Bug</b>
When running the emulator (started from VsCode) on a machine that requires internet traffic to go via proxy, I am unable to get the endpoints to work. I think this is due to a few reasons:

1. /etc/resolv.conf
   does not contain private nameserver
2. the JVM option:
 -Djava.net.useSystemProxies=true
 is not set

*Log*

{"level":"SEVERE","thread":"NIOThread@1","mdc":{"messageId":"de2b8bc1-7a6c-46e6-b2ad-b673dcae0f802","apiName":"mock-api","env":"dev","org":"hybrid","revision":"0"},"className":"com.apigee.protocol.http.HTTPClient$Context","method":"onConnectFailure","severity":"SEVERE","message":"connect to mocktarget.apigee.net failed with exception","formattedDate":"2022-05-31T05:12:20.386Z","logger":"HTTP.CLIENT","exceptionStackTrace":"java.lang.RuntimeException: Host not reachable\n\tat com.apigee.protocol.http.HTTPClient$Context.initConnect(HTTPClient.java:847)\n\tat com.apigee.protocol.http.HTTPClient$Context.send(HTTPClient.java:776)\n\tat com.apigee.messaging.adaptors.http.flow.data.TargetRequestSender.sendRequest(TargetRequestSender.java:399)\n\tat com.apigee.messaging.adaptors.http.flow.data.InlineTargetRequestSender.sendRequestOverride(InlineTargetRequestSender.java:75)\n\tat com.apigee.messaging.adaptors.http.flow.data.TargetRequestSender.sendRequest(TargetRequestSender.java:273)\n\tat com.apigee.messaging.adaptors.http.flow.data.TargetRequestSender.sendRequest(TargetRequestSender.java:297)\n\tat com.apigee.messaging.adaptors.http.flow.execution.SendRequest.execute0(SendRequest.java:80)\n\tat com.apigee.messaging.adaptors.http.flow.execution.SendRequest.execute(SendRequest.java:41)\n\tat com.apigee.flow.execution.SyncExecutionStrategy.execute0(SyncExecutionStrategy.java:80)\n\tat com.apigee.flow.execution.SyncExecutionStrategy.execute(SyncExecutionStrategy.java:43)\n\tat com.apigee.flow.MessageFlowImpl.execute(MessageFlowImpl.java:583)\n\tat com.apigee.flow.MessageFlowImpl.resume(MessageFlowImpl.java:411)\n\tat com.apigee.flow.execution.ExecutionContextImpl.lambda$resume$0(ExecutionContextImpl.java:130)\n\tat com.apigee.nio.NIOSelector.runTasks(NIOSelector.java:386)\n\tat com.apigee.nio.NIOSelector.access$000(NIOSelector.java:29)\n\tat com.apigee.nio.NIOSelector$2.findNext(NIOSelector.java:305)\n\tat com.apigee.nio.NIOSelector$2.findNext(NIOSelector.java:296)\n\tat com.apigee.nio.util.NonNullIterator.computeNext(NonNullIterator.java:12)\n\tat com.apigee.nio.util.AbstractIterator.hasNext(AbstractIterator.java:41)\n\tat com.apigee.nio.handlers.NIOThread.run(NIOThread.java:135)\n"}

*curl works*
```
apigee@apigee-emulator:~$ curl https://mocktarget.apigee.net/
Hello, Guest!
```

*Context*
- Managed Dependencies: on
- Cloud SDK Version: 387.0.0
- Skaffold Version: v1.38.0
- Minikube Version: 1.25.2

Extension version: 1.18.2
VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Remote OS version: Linux x64 4.18.0-305.25.1.el8_4.x86_64
Remote OS version: Linux x64 4.18.0-305.25.1.el8_4.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (1.43GB free)|
|Process Argv|--crash-reporter-id 2e28ea9e-7161-4de3-b5dc-16269216702e|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: ddspmgt201|
|OS|Linux x64 4.18.0-305.25.1.el8_4.x86_64|
|CPUs|Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (8 x 2394)|
|Memory (System)|62.62GB (2.85GB free)|
|VM|50%|

|Item|Value|
|---|---|
|Remote|SSH: ddspmgt201|
|OS|Linux x64 4.18.0-305.25.1.el8_4.x86_64|
|CPUs|Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (8 x 2394)|
|Memory (System)|62.62GB (2.85GB free)|
|VM|50%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdc:30486549

```

</details>

**Comment by kschaab** [comment]
@shirishtrivikr

**Comment by shirishtrivikr** [comment]
https://cloud.google.com/apigee/docs/hybrid/v1.4/forward-proxy gives some details on how the outbound proxies are dealt with, when running in Apigee.

In summary this would requires 2 things
- A setting at the emulator level to enable forward proxies
- A setting at the Target endpoint to use forward proxies

Currently we do not have the capability to allow customization of the emulator itself. We would have to build a such a feature to allow this level of customization.

**Comment by cosmok** [comment]
Thanks,  two questions:
1. What is poulating resolv.conf? As that is missing the companies nameservers and hence unable to reach some internal only domains.
2. As a workaround while this feature is available, how can I make use of a fork of the emulator image be recognized by VS Code?

**Comment by shirishtrivikr** [comment]
1. What is populating resolv.conf

We do not populate this.

2. I would need some time to figure out what is the best solution for you. It may involve 

-   creating a Docker file which uses emulator's base image 
-  Setting a certain properties. 
-  Creating an image with certain tags 
-  Creating the container instance manually.

**Comment by shirishtrivikr** [comment]
The forward proxy support has been added to the emulator via a simple environment level setting. Please refer [doc](https://cloud.google.com/apigee/docs/api-platform/local-development/vscode/manage-apigee-emulator#configuring_the_apigee_emulator_to_support_http_forward_proxy) for more details.
