### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by j2thev** [GoogleCloudPlatform/cloud-code-vscode#602]
- Issue Type: `Performance`
- Extension Name: `cloudcode`
- Extension Version: `1.18.3`
- OS Version: `Windows_NT x64 10.0.19043`
- VS Code version: `1.68.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/JUPJAY~1/AppData/Local/Temp/googlecloudtools.cloudcode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by sushicw** [comment]
Could you please attach the profile contents to this issue?
