### ISSUE TITLE
Lack of debug information on failure

### ISSUE THREAD

**Issue by kimjh12** [GoogleCloudPlatform/cloud-code-vscode#605]
*Context*
- Managed Dependencies: on
- Cloud SDK Version: 390.0.0
- Skaffold Version: v1.38.0
- Minikube Version: 1.25.2

Hi. While I was trying to run a `kubernetes: run/debug` task I came across errors as following
```
Failed to debug container "django-container-15". Retrying for 4 more attempts.
```
It tries 5 times and end up failing to attach. I managed to figure out that `socat` is not installed in my machine. It would be better if I can see detailed logs about why it's failing. Thank you.

**Comment by sushicw** [comment]
Hello @kimjh12, thanks for reporting! 

For more detailed logging, you can check "Cloudcode: Verbose Logging" in vscode settings. (`"cloudcode.verboseLogging": true` in settings.json). Did you already have this checked when you encountered the above?
