### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by konate** [GoogleCloudPlatform/cloud-code-vscode#616]
- Issue Type: `Performance`
- Extension Name: `cloudcode`
- Extension Version: `1.19.0`
- OS Version: `Windows_NT x64 10.0.19044`
- VS Code version: `1.69.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/User/AppData/Local/Temp/googlecloudtools.cloudcode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by kschaab** [comment]
Please attach the cpuprofile.txt (c:\Users\User\AppData\Local\Temp\googlecloudtools.cloudcode-unresponsive.cpuprofile.txt) and reopen.  Without this file it is impossible to see what is wrong.
