### ISSUE TITLE
CloudLogging support in Apigee Emulator

### ISSUE THREAD

**Issue by gaeshi** [GoogleCloudPlatform/cloud-code-vscode#617]
**Use case**
We want to use MessageLogging policy with CloudLogging in Apigee Emulator, to achieve a better dev/prod parity.
Unfortunately, Apigee Emulator doesn't seem to have any support for CloudLogging.
In order to test CloudLogging, we first have to manually add the policy with CloudLogging to the code, then manually deploy proxy to Apigee X. This impedes our dev process. Also, being unable to check if the proxy works locally before deploying it onto cloud environment doesn't sound right.

**Feature**
Please add support for CloudLogging in Apigee Emulator.

**Comment by shirishtrivikr** [comment]
@gaeshi 

The required support for Cloud logging is now available as a part of the insider build. The prerequisite for this is using the latest emulator build 1.9.1 along with the latest [insider release](https://cloud.google.com/code/docs/vscode/insiders#get)

Please follow the documentation to explore this feature
[Customizing the Apigee Emulator to support service account-based authentication](https://cloud.google.com/apigee/docs/api-platform/local-development/vscode/manage-apigee-emulator#customizing_the_apigee_emulator_to_support_service_account-based_authentication)
[Configuring service accounts with proxy and shared flow deployments](https://cloud.google.com/apigee/docs/api-platform/local-development/vscode/deploy-environment#configuring_service_accounts_with_proxy_and_shared_flow_deployments)
