### ISSUE TITLE
Deploying new app to existing cluster fails in VS Code

### ISSUE THREAD

**Issue by pribettacap** [GoogleCloudPlatform/cloud-code-vscode#628]
**Environment**:
*(Hint: "Report Extension Issue on Github" command will fill these out for you.)*

**Version information**

Cloud Code Extension version: 1.19

VSCode version: 1.70

OS: Mac OS Big Sur

Cloud SDK:

Skaffold: 

Kubectl: 1.23

**Description**:  Kubernetes config is pointing to k8s config of remote cluster. Resources of the cluster are listed fine but when trying to deploy and run the application in the cluster,  it prints the following, and then later deploy ends in error.
[Cloud Code]: Checking kubectl current context...
[Cloud Code]: Starting minikube if profile exists...

The config present at ~./kube/config is pointing to minikube context. So it seems like its picking this context instead of the context provided in the kubeconfig file i uploaded earlier.

<img width="600" alt="Screenshot 2022-08-10 at 12 28 53 PM" src="https://user-images.githubusercontent.com/88426870/183836376-5f26a86d-d595-44eb-9e8e-9042b0dd737e.png">

<img width="1019" alt="Screenshot 2022-08-10 at 12 35 34 PM" src="https://user-images.githubusercontent.com/88426870/183836946-3a92c0a6-d809-4ae3-8be3-ea0d8dad8ab9.png">

Additional details: I am using the sample application hello-world-java and have followed all configuration instructions provided in the documentation. 

Would appreciate any help here. Could this be a bug if its still picking up minikube context instead of that of the remote cluster ?

**Repro step**:

**Comment by SKrupa** [comment]
Hi Priyanka, the minikube message gets printed even if deploying against a cluster, so I believe it is correctly trying to deploy against the cluster, but running into an error when launching skaffold. Could you provide the detailed logs for the deployment? In the Output window in the top down, drop down to "Run on Kuberenetes - Detailed", which should surface the underlying error that we can debug. Thank you!
