### ISSUE TITLE
Cannot diff a yaml file with deployed cluster resource 

### ISSUE THREAD

**Issue by idanya** [GoogleCloudPlatform/cloud-code-vscode#63]
**Environment**:
Extension version: 0.0.7
VSCode version: 1.33.0
OS: darwin

**Description**:
Cannot use "Diff the current YAML file with Kubernetes deployed resource" feature. 
Opening a YAML file which is deployed to the cluster (after setting the cluster as the active one) gives the message:
`Can't diff - The open document contains some items that are not Kubernetes resource`

Also trying to apply the file gives a message: `Can't show what changes will be applied (The open document contains some items that are not Kubernetes resource). Apply anyway?`

**Repro step**:
Open a YAML file of a deployed object and try to Diff/apply it.

**Comment by iantalarico** [comment]
@idanya Do you happen to have a copy of the YAML you can share? Or an example YAML that will trigger this?

**Comment by redborian** [comment]
I do have a repro for this. Will fix it.

**Comment by idanya** [comment]
Found the issue (or not issue). 

Some of my yaml files had multiple objects in them separated with `---`.
Some files just had `---` at the end (which probably broke the parsing). 
So don't know if the feature should support multiple objects or not but with single object files all is working well.

**Comment by redborian** [comment]
Thanks Idan. We will support that scenario in a future release.
