### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by MrGeeCore** [GoogleCloudPlatform/cloud-code-vscode#630]
- Issue Type: `Performance`
- Extension Name: `cloudcode`
- Extension Version: `1.20.0`
- OS Version: `Windows_NT x64 10.0.22000`
- VS Code version: `1.70.1`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-loa
[googlecloudtools.cloudcode-unresponsive.cpuprofile.txt](https://github.com/GoogleCloudPlatform/cloud-code-vscode/files/9303961/googlecloudtools.cloudcode-unresponsive.cpuprofile.txt)

**Comment by SKrupa** [comment]
Thank you for reporting this issue. We're tracking cpu load in the extension and investigating how we can reduce it.
