### ISSUE TITLE
Avira is recognizing gcloud-crc32c.exe as a trojan

### ISSUE THREAD

**Issue by nemanja899** [GoogleCloudPlatform/cloud-code-vscode#631]
![Screenshot 2022-08-15 160718](https://user-images.githubusercontent.com/34772552/184651353-4502ba3b-7344-478c-8bdc-fe520905a0fb.jpg)

Type: <b>Bug</b>

*Context*
- Managed Dependencies: on
- Cloud SDK Version: 397.0.0
- Skaffold Version: v1.39.1
- Minikube Version: 1.26.1

Extension version: 1.20.1
VS Code version: Code 1.70.1 (6d9b74a70ca9c7733b29f0456fd8195364076dda, 2022-08-10T06:08:33.642Z)
OS version: Windows_NT x64 10.0.19043
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4810MQ CPU @ 2.80GHz (8 x 2794)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (3.84GB free)|
|Process Argv|--crash-reporter-id 11b074e4-99b5-40d1-a6c1-f41fb139f21e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411cf:30542925
vsaa593cf:30376535
pythonvs932:30410667
wslgetstarted:30449410
cppdebug:30492333
pylanb8912:30545647
vsclangdf:30486550
c4g48928:30535728
hb751961:30543456
dsvsc012cf:30540253
azure-dev_surveyonecf:30545436

```

</details>

**Comment by sushicw** [comment]
Thanks for the report! We will investigate this.

**Comment by thomasmaclean** [comment]
I reported this as a false positive to Avira and I got a notification that they processed my request, although the response is pretty ambiguous.

@nemanja899 can you confirm this is still a problem once you update Avira's database?

**Comment by nemanja899** [comment]
Just updated Avira and reinstalled  Cloud code. It seems everything is fine , avira is no longer flagging cloud code as a virus.
Cheers.
