### ISSUE TITLE
Logs Viewer does not work - "The cluster request failed for an unknown reason: getaddrinfo"

### ISSUE THREAD

**Issue by eugeneo** [GoogleCloudPlatform/cloud-code-vscode#632]
Type: <b>Bug</b>

I am trying to view logs of my app but logs view fails to load.

*Context*
- Managed Dependencies: on
- Cloud SDK Version: 397.0.0
- Skaffold Version: v1.39.1
- Minikube Version: 1.26.1

Extension version: 1.20.1
VS Code version: Code 1.70.1 (6d9b74a70ca9c7733b29f0456fd8195364076dda, 2022-08-10T06:08:33.642Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Remote OS version: Linux x64 5.15.57.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.83GB (15.21GB free)|
|Process Argv|--crash-reporter-id d3246887-b841-4d92-a6c7-c342096dae7a|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.57.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3599)|
|Memory (System)|15.54GB (8.23GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
wslgetstarted:30449410
cppdebug:30492333
vscaat:30438848
pylanb8912:30545647
vsclangdf:30486550
c4g48928:30535728
hb751961:30543456
dsvsc012:30540252
azure-dev_surveyonecf:30545436

```

</details>

**Comment by eugeneo** [comment]
![Screenshot](https://user-images.githubusercontent.com/287917/184674533-28cbd1c8-f6e1-4c97-8ef2-48a4e10ba8d8.png)

This is Windows 10/remote on WSL (WSL config in the bug description)

**Comment by kschaab** [comment]
Hi @eugeneo looks like ENOTFOUND for your DNS name.  Assuming ping to this resolves correctly.  Would you set verbose logs for Cloud Code and let us know what comes out when attempting to view logs?

**Comment by eugeneo** [comment]
I am not sure where that host name is coming from. I am working on Firebase/GCP project and I most definitely did not deploy anything on AKS (unless Firebase does something underneath).

**Comment by eugeneo** [comment]
I fixed the problem by manually choosing "Cloud Run" in the top-right corner. I think I played with AKS some time ago and probably had some Kubernetes configuration on my machine.
