### ISSUE TITLE
Cloud Code Apigee enforces incorrect naming restrictions

### ISSUE THREAD

**Issue by velsietis** [GoogleCloudPlatform/cloud-code-vscode#633]
### Summary

Cloud Code Apigee wizard to "Create policy", does not let you use a dot in the name, only dashes and underscores.  This is not consistent with Apigee itself or the documented naming guidelines for for adding.

See "[Policy name (or step definition) in the naming guidelines table](https://cloud.google.com/apigee/docs/api-platform/reference/naming-guidelines)"

> Alphanumeric, space, and the following: _ - .

### Repro steps

- Use the Cloud Code extension to set up an Apigee workspace and API proxy ([steps 1 and 2 in these instructions](https://cloud.google.com/apigee/docs/api-platform/local-development/vscode/get-started))
- Use the Cloud Code / Apigee navigation panel, go to apiproxies > {proxy name} > apiproxy> policies and click the "+" (hover over message shows "Create policy")
- When prompted select any category and policy
- When prompted for a name, type something with dot and/or a space

**Expected**: 
 - XML file added to "policies" folder and named the same as inputted policy name
 - Added XML file contains scaffolded XML with a name attribute matching the inputted policy name

**Actual**:
- Prompt does not accept the input and shows warning "Invalid policy name - Specific alphanumeric characters, dash (-), or underscore(_)

### Version information

**Cloud Code Extension version:** 1.20.1

**VSCode version:** 1.70.2 (user setup)

**OS:** Windows 10 Enterprise, 10.0.19044

**Cloud SDK:** 398.0.0

**Comment by velsietis** [comment]
I updated the title of this issue, as I noticed that the intellisense/wizards also gives incorrect warnings about the names of Products and Key Value Maps

**Comment by sushicw** [comment]
Thanks for the report! We'll take a look.

**Comment by shirishtrivikr** [comment]
Thanks for reporting the issue.  We will fix the validations

**Comment by shirishtrivikr** [comment]
This has been fixed and the fixes are available in the latest insider
