### ISSUE TITLE
Fail to deploy cloud run for anthos workload to Anthos bare metal cluster

### ISSUE THREAD

**Issue by B046090010** [GoogleCloudPlatform/cloud-code-vscode#637]
Hello,

When deploying cloud run for anthos workload to Anthos bare metal cluster, 
We can't click on the cloud run for Anthos option. 
The UI shows that we don't have any cluster with Cloud Run for Anthos enabled.

![test](https://user-images.githubusercontent.com/43258644/186314497-234a7d5c-f120-44d7-8409-c761f2bacbf0.png)

However, we have already created the cluster whose type is anthos bare metal.

![test2](https://user-images.githubusercontent.com/43258644/186317025-979c20b6-c9b1-42ee-8065-5888a1ee7442.jpg)

Is it available for ABM cluster, or is it only working with GKE cluster?

**Comment by kschaab** [comment]
This is only supported with GKE clusters and is very limited.
