### ISSUE TITLE
Cloud Code extension can not find kubectl or gcloud binaries

### ISSUE THREAD

**Issue by stm9443** [GoogleCloudPlatform/cloud-code-vscode#64]
**Environment**:
Extension version: 0.0.7
VSCode version: 1.33.0
OS: darwin

**Description**: Cloud Code extension is unable to locate the kubectl or gcloud binaries.  Both binaries were installed as a part of the gcloud components.  I have updated all of the gcloud components.  Typing "which" in the VSCode integrated terminal for both commands points to the correct "google-cloud-sdk/bin" directory.  I have also validated that the "google-cloud-sdk/bin" directory is included in the output of the $PATH in the integrated terminal.  I had the same issue initially with the Kubernetes extension provided by Microsoft, but they provide settings which allow manually specifying the kubectl path, which worked.

kubectl version (output from integrated terminal):
* Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.7", GitCommit:"6f482974b76db3f1e0f5d24605a9d1d38fad9a2b", GitTreeState:"clean", BuildDate:"2019-03-25T02:52:13Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"darwin/amd64"}
* Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.6-gke.7", GitCommit:"aeaa96020ec0614a8773799058c3b8d58c19b9ff", GitTreeState:"clean", BuildDate:"2019-03-13T11:22:57Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}

gcloud version (output from integrated terminal):
* Google Cloud SDK 241.0.0
* beta 2019.02.22
* bq 2.0.43
* cloud-datastore-emulator 2.1.0
* core 2019.04.02
* gcloud 
* gsutil 4.38
* kubectl 2019.04.02

**Comment by redborian** [comment]
I suspect they are not truly being added to your $PATH variable. Can you try opening VS Code from a terminal that has gcloud in its $PATH variable?

**Comment by stm9443** [comment]
That worked, thanks.  So, the path isn't being set correctly when opening VS Code via the .app in macOS.  Is that a bug or did I miss a setting somewhere?

**Comment by redborian** [comment]
That is great! You would need to add it into your login shell. Please refer to tips from [here].(https://apple.stackexchange.com/questions/106778/how-do-i-set-environment-variables-on-os-x)
