### ISSUE TITLE
Extension does not recognize kustomize component

### ISSUE THREAD

**Issue by damlys** [GoogleCloudPlatform/cloud-code-vscode#649]
**Version information**

- Cloud Code Extension version: `1.20.1`
- VSCode version: `1.71.0`
- OS: macOS
- Cloud SDK: `401.0.0`
- Skaffold: `1.39.2`
- Kubectl: `1.25.0`
- kubectl kustomize: `4.5.7` 

**Description**:

IDE does not recognize kustomize components objects.

**Repro step**:

Create file with `Component` object within IDE, e.g.:

```yaml
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - deploy.yaml
  - svc.yaml
```

See warning:

```
This apiVersion and/or kind does not reference a schema known by Cloud Code. Please ensure you are using a valid apiVersion and kind.
```

<img width="1512" alt="Screen Shot 2022-09-13 at 07 07 16" src="https://user-images.githubusercontent.com/11075393/189830099-608e4c90-facf-4447-b76a-4e8c69c513df.png">

**Comment by ChaseMor** [comment]
At the moment, it looks like Cloud Code supports `kustomize` schema for only `v1beta1`. We will look into updating and adding support for other version in future releases.

**Comment by ChaseMor** [comment]
As a current workaround, you can add support for schemas that are not included by default by following the steps here: https://cloud.google.com/code/docs/vscode/yaml-editing#using_custom_schema

**Comment by ChaseMor** [comment]
Is there a reason you cannot use `v1beta1`?

**Comment by damlys** [comment]
I would like to use `v1beta1` but it seems that there is no `kustomize.config.k8s.io/v1beta1 Component` object. Not sure if it's deprecated or something 🤔 Maybe I'll try to use `kustomize.config.k8s.io/v1beta1 Kustomization` instead of that

---

yaml:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Component
...
```

console:

```console
$ kubectl kustomize ./deploy/goapp/overlays/dev/
error: accumulating components: accumulateDirectory: "couldn't make target for path '/workspaces/gomod/deploy/goapp/components/mongodb': Failed to read kustomization file under /workspaces/gomod/deploy/goapp/components/mongodb:\napiVersion for Component should be kustomize.config.k8s.io/v1alpha1
```
