### ISSUE TITLE
CD support in monorepo

### ISSUE THREAD

**Issue by glevine** [GoogleCloudPlatform/cloud-code-vscode#65]
**Use case**
My team has a monorepo with many services. Each service has its own k8s configurations -- each service has its own k8s folder. Running `skaffold dev` from within a single service's k8s folder -- where the `skaffold.yaml` for that service lives -- will deploy the service to the specified cluster.

**Feature**
It appears that Cloud Code looks for a `skaffold.yaml` at the root of the project. I would like to see the ability to control which `skaffold.yaml` is used in conjunction with the Continuous Deploy command.

We use Jenkins and Spinnaker to deploy to staging and production, so this level of control only applies to use with a local cluster for me. But it would also be cool to be able to use the Deploy command if I needed to deploy multiple services locally using their own `skaffold.yaml` and then the Continuous Deploy command for a single service -- that consumes those other services -- so I can make changes to it.

**Comment by iantalarico** [comment]
@sujit-kamireddy Can we take a look at that it would take to be sure we support cases like this?

**Comment by sujit-kamireddy** [comment]
@glevine ,
  Thank you for filing this feature request. I will look into this.

**Comment by sujit-kamireddy** [comment]
@glevine ,
I have few questions to understand your scenario better. Can you please take a look and respond?

1. Is the skaffold configuration file you would like to use, in the sub-tree of the root directory hierarchy? or is it outside the root directory hierarchy?

2. Will you have more than one skaffold configuration file in the root directory hierarchy?

3. Do you use a name other than skaffold.yaml for the skaffold configuration file?

**Comment by glevine** [comment]
@sujit-kamireddy 

Sorry it's taken me so long to respond. I must have missed the notification.

1. In the sub-tree of the root directory hierarchy. For example, our API's are defined in `repo/apis`, our source code for our services lives in `repo/projects`, and our skaffold configuration files live in `repo/k8s/`.

Let's say I have a service for managing photos named `photos`. My proto files would go in `repo/apis/photos`. The implementation would go in `repo/projects/photos`. The skaffold files would go in `repo/k8s/services/photos`. And the manifests would be generated to `repo/k8s/manifests/<cluster>/photos`.

2. Yes. I could add a service for managing videos named `videos`, next to the `photos` service. My proto files would go in `repo/apis/videos`. The implementation would go in `repo/projects/videos`. The skaffold files would go in `repo/k8s/services/videos`. And the manifests would be generated to `repo/k8s/manifests/<cluster>/videos`.

3. No, we use `skaffold.yaml`.

Let me know if you have any other questions. I'll make sure to check back. Thanks

**Comment by sujit-kamireddy** [comment]
Thanks @glevine for the response. I am currently working on this. I will post an update soon.

**Comment by sujit-kamireddy** [comment]
@glevine ,
This feature has been released in our latest release 0.0.10. However you need to turn on the vscode workspace/user setting "enableMultiSkaffoldConfigsKey" to enable it.

Please try it and give your feedback. Thanks.

**Comment by glevine** [comment]
@sujit-kamireddy,

Thanks! I'm enabling it now. I look forward to using it.

**Comment by sujit-kamireddy** [comment]
Thanks @glevine .

**Comment by sujit-kamireddy** [comment]
@glevine, there were couple of bugs that may prevent you from successfully using the feature. I fixed them and they will be available in the next release. So please hold off on trying this feature till next release. 
Thank you.

**Comment by redborian** [comment]
This has been fixed in the latest release of Cloud Code (v0.0.13)

**Comment by sujit-kamireddy** [comment]
This will be fixed in a future release. We are changing the way deploy and debug works, which will give great flexibility going forward.

I will update this thread when that's ready.

**Comment by sujit-kamireddy** [comment]
Hi @glevine , we are pleased to let you know that we have added a new command 'Cloud Code: Run on Kubernetes' in our latest release (v1.1.1) that should help with your use cases.

This new command guides you to create a run configuration (in .vscode/launch.json), where you can configure any skaffold.yaml file or skaffold profile. You can create as many run configurations as you would like.

For more details, please read the documentation ([link1](https://cloud.google.com/code/docs/vscode/running-an-application), [link2](https://cloud.google.com/code/docs/vscode/setting-up-an-existing-app)).

_Note that we deprecated the old commands 'Cloud Code: Deploy' and 'Cloud Code: Continuous Deploy' in favor of this new command ._
