### ISSUE TITLE
"Encountered an error while attempting to enable addon 'gcp-auth' on minikube. Error: MK_ADDON_ENABLE"

### ISSUE THREAD

**Issue by shoomkloom** [GoogleCloudPlatform/cloud-code-vscode#655]
**Version information**

Cloud Code Extension version:  v1.20.2
VSCode version:
Version: 1.71.2 (user setup)
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0

Sandboxed: No

OS:  Windows_NT x64 10.0.19042

Cloud SDK: Storage

**Description**:
Getting exception when debugging node.js project in container and trying to download from bucket
**Repro step**:
1. Installed Docker Desktop - Run as Admin
2. Cloud Code extension logged in properly to my 'Cloud Run' service project.
3. Start debug -> image is downloaded, started and connected.
    try to download from bucket -> get exception:
    

> Anonymous caller does not have storage.objects.get access to the Google Cloud Storage object.

4. In 'Cloud Run: Run/Debug Locally - Detailed' output I see the following error (everything else seems to be OK):

> Failed to configure minikube gcp-auth addon. Your app might not be able to authenticate Google or GCP APIs it calls. The addon has been disabled. More details can be found in the detailed logs.
> Encountered an error while attempting to enable addon 'gcp-auth' on minikube. Error: MK_ADDON_ENABLE

5. This worked yesterday...

**Comment by sushicw** [comment]
Thanks for the report! 

Can you try opening a terminal window in vscode, and then running `minikube start` followed by `minikube addons enable gcp-auth`? And then paste the output here.

**Comment by shoomkloom** [comment]
Hi Chris,

Thanks for the quick response.
I attached the log mentioned below
Here is the output:

PS C:\sources\repos\MyProject\my-service> minikube start
😄  minikube v1.27.0 on Microsoft Windows 10 Enterprise 10.0.19042 Build
19042
✨  Using the docker driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
🔥  Creating docker container (CPUs=2, Memory=4000MB) ...
🐳  Preparing Kubernetes v1.24.3 on Docker 20.10.17 ...
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🌟  Enabled addons: storage-provisioner, default-storageclass

❗
C:\Users\Levs\AppData\Local\cloud-code\installer\google-cloud-sdk\bin\kubectl.exe
is version 1.22.14-dispatcher-dirty, which may have incompatibilites with
Kubernetes 1.24.3.
    ▪ Want kubectl v1.24.3? Try 'minikube kubectl -- get pods -A'
🏄  Done! kubectl is now configured to use "minikube" cluster and "default"
namespace by default
PS C:\sources\repos\MyProject\my-service> minikube addons enable gcp-auth?

❌  Exiting due to MK_ADDON_ENABLE: run callbacks: gcp-auth? is not a valid
addon

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│
                               │
│    😿  If the above advice does not help, please let us know:
                               │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose
                               │
│
                               │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the
GitHub issue.                  │
│    Please also attach the following file to the GitHub issue:
                               │
│    -
C:\Users\MyUserName\AppData\Local\Temp\minikube_addons_dd0fc9838c72e4f1145a19d657b9a1649cbdbf32_0.log
  │
│
                               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Thanks,
Oren

**Comment by sushicw** [comment]
It looks like an extra '?' got included at the end of your `minikube addons enable gcp-auth` call, try again without that.

**Comment by shoomkloom** [comment]
Sorry about that, it did look suspicious...
I'll try again tonight.

**Comment by shoomkloom** [comment]
Hey Chris,

Any thoughts why auth is still not working on Cloud Code extension?

Thanks,
Oren

**Comment by sushicw** [comment]
Hi Oren,

Can you run `minikube addons enable gcp-auth` from the terminal in vscode (without the trailing question mark this time) and post what you see? I was hoping that could tell us something about why it's not able to enable the gcp-auth plugin.

Another thing you can try is to turn on verbose logging and check the "Cloud Code" output channel to see if there is any extra error info recorded around when it tries to enable the auth plugin for minikube. You can do this via the `Cloudcode: verbose logging` setting or by including `"cloudcode.verboseLogging": true` in your settings.json.

**Comment by shoomkloom** [comment]
Hi Chris,

I already sent you the results of running minikube addons enable gcp-auth in
the previous message.
Here is the output again:
PS C:\sources\repos\MyProject\my-service>  minikube start
😄  minikube v1.27.0 on Microsoft Windows 10 Enterprise 10.0.19042 Build
19042
🆕  Kubernetes 1.25.0 is now available. If you would like to upgrade,
specify: --kubernetes-version=v1.25.0
✨  Using the docker driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
🔄  Restarting existing docker container for "minikube" ...
🐳  Preparing Kubernetes v1.24.3 on Docker 20.10.17 ...
🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🌟  Enabled addons: storage-provisioner, default-storageclass

❗  C:\Users\MyUser\AppData\Local\cloud-code\installer\google-cloud-sdk\bin\kubectl.exe
is version 1.22.14-dispatcher-dirty, which may have incompatibilites with
Kubernetes 1.24.3.
    ▪ Want kubectl v1.24.3? Try 'minikube kubectl -- get pods -A'
🏄  Done! kubectl is now configured to use "minikube" cluster and "default"
namespace by default
PS C:\sources\repos\ MyProject\my-service> minikube addons enable gcp-auth
💡  gcp-auth is an addon maintained by Google. For any concerns contact
minikube on GitHub.
You can view the list of minikube maintainers at:
https://github.com/kubernetes/minikube/blob/master/OWNERS
    ▪ Using image k8s.gcr.io/ingress-nginx/kube-webhook-certgen:v1.0
    ▪ Using image gcr.io/k8s-minikube/gcp-auth-webhook:v0.0.11
🔎  Verifying gcp-auth addon...
📌  Your GCP credentials will now be mounted into every pod created in the
minikube cluster.
📌  If you don't want your credentials mounted into a specific pod, add a
label with the `gcp-auth-skip-secret` key to your pod configuration.
📌  If you want existing pods to be mounted with credentials, either
recreate them or rerun addons enable with --refresh.
🌟  The 'gcp-auth' addon is enabled

I'll try verbose logging next and send you that output as well.

Thanks,
Oren

**Comment by shoomkloom** [comment]
Hey again,

[image: image.png]

Cloud Code Verbose logging already on.

Thanks,
Oren

**Comment by sushicw** [comment]
Hmm, ok. It looks like running manually isn't producing the error, which makes this trickier to track down. 

I guess one other thing to try: have you tried logging out of Cloud Code and back in?

**Comment by shoomkloom** [comment]
Hey Chris,

Please find attached the 2 outputs of 'Cloud:Run Run/Debug' and 'Cloud:Run
Run/Debug - Detailed'

Notice the following line in 'Cloud:Run Run/Debug':
Failed to configure minikube gcp-auth addon. Your app might not be able to
authenticate Google or GCP APIs it calls. The addon has been disabled. More
details can be found in the detailed logs.

I really appreciate your help.
I'm stuck with important features I cannot develop...
Thanks,
Oren

**Comment by shoomkloom** [comment]
Hi Chris,

I managed to get it working again.
All I did was delete every Image using Docker Desktop and then delete from
my User folder everything with the name '.docker', '.minikube',
'.kubernetes' etc...
I also deleted the extensions 'Cloud Code', 'Docker' etc (all relating to
kubernetes) and then reinstalled only 'Cloud Code' extension.
I guess there was some problematic setting or corrupt cache.
Now everything is working again.

Thanks for the effort.
Oren

**Comment by sushicw** [comment]
Hi Oren,

Really glad to hear you were able to unblock yourself! 🥳 Thanks for including how you did it, that may be useful to future travelers.

**Comment by shoomkloom** [comment]
Hey Chris,

Here is the new output:
PS C:\sources\repos\MyProject\my-service>  minikube start
😄  minikube v1.27.0 on Microsoft Windows 10 Enterprise 10.0.19042 Build
19042
🆕  Kubernetes 1.25.0 is now available. If you would like to upgrade,
specify: --kubernetes-version=v1.25.0
✨  Using the docker driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
🔄  Restarting existing docker container for "minikube" ...
🐳  Preparing Kubernetes v1.24.3 on Docker 20.10.17 ...
🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🌟  Enabled addons: storage-provisioner, default-storageclass

❗
 C:\Users\MyUser\AppData\Local\cloud-code\installer\google-cloud-sdk\bin\kubectl.exe
is version 1.22.14-dispatcher-dirty, which may have incompatibilites with
Kubernetes 1.24.3.
    ▪ Want kubectl v1.24.3? Try 'minikube kubectl -- get pods -A'
🏄  Done! kubectl is now configured to use "minikube" cluster and "default"
namespace by default
PS C:\sources\repos\ MyProject\my-service> minikube addons enable gcp-auth
💡  gcp-auth is an addon maintained by Google. For any concerns contact
minikube on GitHub.
You can view the list of minikube maintainers at:
https://github.com/kubernetes/minikube/blob/master/OWNERS
    ▪ Using image k8s.gcr.io/ingress-nginx/kube-webhook-certgen:v1.0
    ▪ Using image gcr.io/k8s-minikube/gcp-auth-webhook:v0.0.11
🔎  Verifying gcp-auth addon...
📌  Your GCP credentials will now be mounted into every pod created in the
minikube cluster.
📌  If you don't want your credentials mounted into a specific pod, add a
label with the `gcp-auth-skip-secret` key to your pod configuration.
📌  If you want existing pods to be mounted with credentials, either
recreate them or rerun addons enable with --refresh.
🌟  The 'gcp-auth' addon is enabled

BTW: I tried running my own container after this and still get the same
error.

Thanks,
Oren

**Comment by sushicw** [comment]
Hi Oren,

To clarify: after getting the MK_ADDON_ENABLE error to go away, it's back?

**Comment by shoomkloom** [comment]
Hi Chris,
Once I fixed it, everything is working ok.
Cheers,
Oren
