### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by silasrangel** [GoogleCloudPlatform/cloud-code-vscode#656]
- Issue Type: `Performance`
- Extension Name: `cloudcode`
- Extension Version: `1.20.2`
- OS Version: `Windows_NT x64 10.0.19044`
- VS Code version: `1.71.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/User/AppData/Local/Temp/googlecloudtools.cloudcode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by sbland** [comment]
If this is on startup a temporary solution is to set the following setting `cloudcode.autoDependencies` to `off`
