### ISSUE TITLE
Error relaunching debugger

### ISSUE THREAD

**Issue by ekimia** [GoogleCloudPlatform/cloud-code-vscode#66]
**Environment**:
Extension version: 0.0.7
VSCode version: 1.33.0
OS: darwin

**Description**:
If you the debugger is unable to attach, you are unable to start another debug session without hitting a "This launch configuration is already running" error.
**Repro step**:
- For the python example, *dont* run the app with the python debugger enabled
- Try debugging. It will fail to connect.
- Run the app with python debugging enabled
- Try debugging again

**Workaround**
- Close out the window and reopen

**Comment by quoctruong** [comment]
@ekimia When the debugger failed to connect the first time, did the session stop for you? Or does it still linger there? It would also be great if you can attach a screenshot for this.

**Comment by ekimia** [comment]
it lingers. 1 sec ill add a screenshot

**Comment by ekimia** [comment]
initial error case:
<img width="538" alt="Screen Shot 2019-04-10 at 5 23 27 PM" src="https://user-images.githubusercontent.com/357513/55922311-829c4b80-5bb5-11e9-8f0a-44ee282adec7.png">

After reenabling the debugger:
<img width="644" alt="Screen Shot 2019-04-10 at 5 24 13 PM" src="https://user-images.githubusercontent.com/357513/55922320-89c35980-5bb5-11e9-9743-23e94c063a12.png">

Totally get this is beta. It also totally made my day with you guys launching this! No more debugging using logs!

**Comment by quoctruong** [comment]
@ekimia Thank you for trying out the debug feature. Yes, I can repro this as well. Most likely a bug from the extension not terminating the session. Will fix this.

**Comment by quoctruong** [comment]
@ekimia This should be fixed in the latest version of the release. Feel free to reopen if it still does not work for you.

**Comment by ekimia** [comment]
thanks @quoctruong !!!
