### ISSUE TITLE
Unresponsive machine

### ISSUE THREAD

**Issue by leohklee** [GoogleCloudPlatform/cloud-code-vscode#660]
Type: <b>Bug</b>

Multiple apps outside of VSCode becomes unresponsive including Chrome and Slack. Apps also cannot close gracefully and I cannot launch new instances of the apps. Machine cannot shut down normally either. As a result, I must hard reset my machine.

Note: Activity monitor does not show any abnormal behavior. CPU usage remains low, memory usage is low, disk activity is low.

Extension version: 1.20.3
VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:15:55.763Z)
OS version: Darwin arm64 21.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 2, 3|
|Memory (System)|32.00GB (6.74GB free)|
|Process Argv|--crash-reporter-id 63578e7f-b153-461a-8007-52798cca74c0|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
i497e931:30553904
vscccc:30566498
pyindex848cf:30577861
nodejswelcome1cf:30587006
fc301958:30573243

```

</details>

**Comment by glouischandra** [comment]
Hi @leohklee this doesn't seem to be connected to VSCode extension, but can you try turning off Auto Dependencies setting: 
<img width="1149" alt="image" src="https://user-images.githubusercontent.com/3677364/196502080-a5b375f1-50de-47d3-b685-f3dde2094fc5.png">

And see if the issue repros?

**Comment by kschaab** [comment]
Closing due to lack of response
