### ISSUE TITLE
Can't see the stream logs in a deployment if there are several containers into it

### ISSUE THREAD

**Issue by scraly** [GoogleCloudPlatform/cloud-code-vscode#67]
Hi,

I want to see the logs of my deployments.
I selected one of my cluster, then right click on one of my deployment and then clicked on "stream logs" action.

The result:

Streaming Logs from deployment my-deployment
Found 3 pods, using pod/my-deployment-7df1234fb9-fj2zr
Error from server (BadRequest): a container name must be specified for pod my-deployment-7df1234fb9-fj2zr, choose one of: [my-deployment toto istio-proxy] or one of the init containers: [istio-init]

The issue here is that I can't see the logs because I don't have a select list in order to select my container.

Thanks!

**Comment by iantalarico** [comment]
@scraly Thanks for the feedback!

@quoctruong Can you take a look at this?

**Comment by quoctruong** [comment]
@scraly As a temporary workaround, you can right click on the container and stream logs from it. I will work to improve this experience.

**Comment by iantalarico** [comment]
@scraly Can you give this a try with the latest release, this should be fixed.
