### ISSUE TITLE
Deploying Cloud Functions fails when local workspace isn't in drive C: on Windows

### ISSUE THREAD

**Issue by lisardggY** [GoogleCloudPlatform/cloud-code-vscode#675]
Type: <b>Bug</b>

*Context*
- Managed Dependencies: on
- Cloud SDK Version: 409.0.0
- Skaffold Version: v1.39.3
- Minikube Version: 1.28.0

1. Create initial Cloud Function on Cloud Console.
2. Download code to local workspace via Cloud Code extension (Insiders build). Local workspace created by default under `D:\Stuff\` on my machine.
3. Update code.
4. Click "Deploy Code" from local workspace.

*Expected Result:*
Cloud Function is uploaded to GCP.

*Actual Result:*
Error message is shown saying "ENOENT: No such file or directory, scandir `C:\d:\stuff\....`., showing that the path to my workspace is badly constructed and attempts to add `C:\` to a path that is already rooted in D:\.

Extension version: 1.21.0-insiders.4
VS Code version: Code - Insiders 1.74.0-insider (2282be522a8031209a739783baede67bfa9fc95a, 2022-11-08T05:23:21.062Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8600 CPU @ 3.10GHz (6 x 3096)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.95GB (7.28GB free)|
|Process Argv|--crash-reporter-id e47c8e7c-c5fb-4dd3-b768-9ae931d36e35|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pylantcb52:30590116
vscccc:30564267
pyindex848:30577858
nodejswelcome1:30587009
gswce1:30602633
34cci188:30599831
pyind779:30600159
dbltrim-noruby:30604474

```

</details>

**Comment by glouischandra** [comment]
Thank you for the bug @lisardggY we're looking into this.

**Comment by glouischandra** [comment]
hello @lisardggY we have identified the issue and redeployed fix to the insiders channel, Cloud Code should auto update to the latest insiders build automatically (if not, try restarting your VSCode) and ensure that you are on insiders.5 build: 
<img width="963" alt="image" src="https://user-images.githubusercontent.com/3677364/202045286-a348bde8-fe0d-49b2-b43f-a4263fdc918e.png">

Can you retry deployment on Cloud Function again and see if you run into further issue? Thanks!

**Comment by lisardggY** [comment]
Works! Thanks for the super-fast turnaround!

![image](https://user-images.githubusercontent.com/555329/202247619-e2a91918-22bd-4d4c-a117-8e8ef8bba048.png)

**Comment by glouischandra** [comment]
Thanks for confirming!
