### ISSUE TITLE
Managed Dependency Check Failed

### ISSUE THREAD

**Issue by michelle54725** [GoogleCloudPlatform/cloud-code-vscode#677]
**Environment**: zsh / Mac M2

**Version information**

Cloud Code Extension version: 1.20.3

VSCode version: 1.73.0

OS: MacOS Monterey

Cloud SDK: 409.0.0

Skaffold: 1.39.3

Kubectl: 1.22.14

**Description**:

Received these two errors when installing Cloud Code extension. Attempted to uninstall/reinstall, quit/reopen VSCode, and restart computer but still received this error.
![image](https://user-images.githubusercontent.com/28771021/201725293-500238ad-4572-4d5a-a505-dbc31459baf6.png)
![image](https://user-images.githubusercontent.com/28771021/201725575-48b7391d-c239-4383-a01e-ca099d7db681.png)

Then these errors when trying to "Run on Cloud Run Emulator"
![image](https://user-images.githubusercontent.com/28771021/201723791-bbf50435-e106-4212-a483-e069e121d408.png)

But gcloud is installed and in PATH. I tried manually installing skaffold with `gcloud components install skaffold` which succeeded but still get same error as above when trying to run.
![image](https://user-images.githubusercontent.com/28771021/201724731-b5466de7-af68-41fb-8fae-39ab9b0a57e4.png)

Any help appreciated!

**Comment by michelle54725** [comment]
1. This worked, thanks!
2. local VS Code

**Comment by davidponder** [comment]
Awesome! Glad to hear that worked :).

I'll close this ticket for now but feel free to re-open this issue or submit a new one should any issues arise.

Thanks!
