### ISSUE TITLE
Application deployment failed/aborted.

### ISSUE THREAD

**Issue by c0h1b4** [GoogleCloudPlatform/cloud-code-vscode#68]
**Environment**:
Extension version: 0.0.7
VSCode version: 1.33.0
OS: darwin

**Description**:
time="2019-04-11T10:24:54-03:00" level=fatal msg="deploy failed: reading manifests: kubectl create: Running [kubectl --context docker-for-desktop create --dry-run -oyaml -f /Users/mauro/cloudcode-projects/nodejs-hello-world-1/kubernetes-manifests/hello.deployment.yaml -f /Users/mauro/cloudcode-projects/nodejs-hello-world-1/kubernetes-manifests/hello.service.yaml]: stdout , stderr: The connection to the server localhost:6443 was refused - did you specify the right host or port?\n, err: exit status 1: exit status 1"

**Repro step**:
1) create new demo nodeJs application (hello world)
2) Deploy locally
3) get the error

the big issue here is that on the bottom bar of VS Code, I see "Cloud Code: Deployment in progress..." but the local deployment failed, and I don't have any command to stop/abort the deployment or restart it.

**Comment by iantalarico** [comment]
@c0h1b4 Can you provide some more details?
- What version of kubectl are you using?
- Are you deploying to minikube, docker desktop or something else?

**Comment by quoctruong** [comment]
@c0h1b4 We are improving the skaffold integration in the extension and this should address this problem. In the mean time, a workaround is to reload vscode.

**Comment by iantalarico** [comment]
@quoctruong The Skaffold Eventing will be in the next release right?  This should fix this problem right?

**Comment by quoctruong** [comment]
@c0h1b4 Please try again with the latest version of the extension. Thanks!
