### ISSUE TITLE
no disk

### ISSUE THREAD

**Issue by BrechtCorbeel** [GoogleCloudPlatform/cloud-code-vscode#681]
Type: <b>Bug</b>

*Context*
- Managed Dependencies: on
- Cloud SDK Version: 410.0.0
- Skaffold Version: v1.39.3
- Minikube Version: 1.28.0

supposedly I have 10 GB of disk space, but I get "no disk found for this instance" and googling didn't do me anything either.

Extension version: 1.20.3
VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.19043
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10900F CPU @ 2.80GHz (20 x 2808)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|95.86GB (19.29GB free)|
|Process Argv|--crash-reporter-id 3221e13e-8e6c-4a9b-93cf-c030f644197b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848cf:30577861
nodejswelcome1cf:30587006
fc301958:30595537
3biah626:30602489
gswce1:30612156
iaj6b796:30613358
dbltrim-noruby:30604474
f6dab269:30613381

```

</details>

**Comment by davidponder** [comment]
Hello @BrechtCorbeel , sorry to hear you're hitting this friction.

Could you elaborate a bit on what actions led to this error?

**Comment by BrechtCorbeel** [comment]
@davidponder Hello, I installed Google SDK, CLI all the extensions, but when when in Cloud code I can access the machine and it says active, but I cannot access the disk or write any file to it. My current idea is that I need skaffold for the SSH extension, but when I open the exe or try installing through shell I have  get nothing or an error making skaffold impossible to install

**Comment by BrechtCorbeel** [comment]
I got it to work by creating a new machine. I think creating a container as one of the options in the creation of my machines might be what did it, yet still I do not really have access to the files or can write my software from VS code the way I was expecting this to work.

**Comment by sushicw** [comment]
Hi @BrechtCorbeel, it sounds like you are trying to use the Compute Engine integration described here: https://cloud.google.com/blog/products/application-development/develop-applications-for-compute-engine-in-your-ide-with-cloud-code. Is that correct?

**Comment by BrechtCorbeel** [comment]
@sushicw yes, bit it does not function as I imagined, why do I need to upload the file? VS code saves my files and changes automatically on my local device when working on projects, I want to use this functionality with my server so I can just work locally and see the changes happen as I write the code and execute new scripts added, I don't want to do that all by hand replacing and executing scripts by writing it in the terminal of the SSH, I would rather have better ways of handling the VM from my machine.

It might just be I haven't fully figured it out yet. 

The disks are visible now though, but I seem to not be able to interact with anything on the vm the way I would interact on my regular machine or with a cloud drive.

**Comment by sushicw** [comment]
Thank you, that makes sense. At this time Cloud Code does not have any custom support for this but it's a possible future improvement. I agree that it would be very useful!

In the meantime, have you tried using vscode's built-in [remote ssh](https://code.visualstudio.com/docs/remote/ssh) features? That should go a long way towards letting you use vscode on your local machine, while interacting with the filesystem and executing on a remote host.

**Comment by BrechtCorbeel** [comment]
@sushicw This is where further problems come in it says to install docker and it says it is installed, but it keeps prompting me to install it. The other way I tried doing it is the SSH FS extension, which tells me to install skaffold, but every option of installing skaffold has either given me a brief black command window or bugs.

**Comment by sushicw** [comment]
> This is where further problems come in it says to install docker and it says it is installed, but it keeps prompting me to install it.

Can you clarify where you are encountering this and what steps you took to get there? I'm afraid this isn't specific enough for me to understand exactly what you are experiencing and how it connects to Cloud Code.

> The other way I tried doing it is the SSH FS extension, which tells me to install skaffold, but every option of installing skaffold has either given me a brief black command window or bugs.

This is puzzling to me because Skaffold is used for working with containers and Kubernetes... I don't see why that extension would prompt you to install Skaffold.


> I can try getting the remote SSH from the built in extension, but now I am at a loss which email adress to get Gcloud literally has a couple pages with auto generated email adresses that all could be the one thatworks or none of them work.

For remote SSH, you should be able to use the same username and credentials that you would use for an SSH session to the host outside of vscode. The email addresses you're referring to are probably mostly service accounts, but most likely you want to log in as yourself. 

Once you are able to SSH into a remote machine outside of vscode, the built-in remote SSH extension and the SSH FS extension should both work with the same credentials.

**Comment by sushicw** [comment]
I'm closing this, please re-open with more details if you still require support. Thank you!
