### ISSUE TITLE
Unable to deploy to GKE without local docker install

### ISSUE THREAD

**Issue by drush1980** [GoogleCloudPlatform/cloud-code-vscode#69]
**Environment**:
*(Hint: "Report Kubernetes Extension Issue on Github" command will fill these out for you.)*
Extension version: 0.0.7
VSCode version: 1.33.1
OS: MacOS Mojave

**Description**:
I do not have docker installed locally and wish to deploy to GKE clusters instead. When I choose the Deploy action I do not get prompted to pick the cloudbuild profile. Instead I just get an error that docker is not installed locally:

"docker is not available in path. Ensure docker is installed and available in path."

**Repro step**:
Install gcloud sdk, kubectl and skaffold.  Install VS Code and the Cloud Code extension.  Do not install docker.  Create the guest book sample and run the Deploy action from VS code.

**Comment by redborian** [comment]
Fixed in release v0.0.8
