### ISSUE TITLE
(eval):export:1: not valid in this context: Support/cloud-code/installer/google-cloud-sdk/bin:...

### ISSUE THREAD

**Issue by jasondamour** [GoogleCloudPlatform/cloud-code-vscode#690]
Hello,

Every time I open a terminal in vscode, I see this error:
```
(eval):export:1: not valid in this context: Support/cloud-code/installer/google-cloud-sdk/bin:...
```

`...` is the rest of my PATH, which is valid. The issue only happens in the vscode terminal, no other shell. I know that cloud-code is trying to add the path `~/Library/Application\ Support/cloud-code/installer/google-cloud-sdk/bin`, but it looks like the path isn't quoted so its splitting on the whitespace in `Application Support/`. 

Details:
MacOS Monterey 12.6 (M1 chip)
Version 1.20.4 (Nov 2022)
`"cloudcode.autoDependencies": "off"` 
The error happens whether the above is "on" or "off"

**Comment by SKrupa** [comment]
Thank you for reporting this, we're working on a fix to properly format the filepath in the terminal

**Comment by jasondamour** [comment]
Got an update today for `Cloud Code 1.21.0` and no longer see the issue!

**Comment by SKrupa** [comment]
Great! Thank you for confirming it's working now.

**Comment by jasondamour** [comment]
Hi, this issue has returned
