### ISSUE TITLE
sorun

### ISSUE THREAD

**Issue by qapris** [GoogleCloudPlatform/cloud-code-vscode#694]
Type: <b>Bug</b>

*Context*
- Managed Dependencies: on
- Cloud SDK Version: 412.0.0
- Skaffold Version: v0.0
- Minikube Version: 1.28.0

*Additional Information*
- Affected Module: Cloud APIs (Code Samples)
- Sample Language: NODEJS
- Sample Title: List datasets
- Sample URL: https://github.com/googleapis/google-cloud-node/blob/e265944ab919a313acb618c12f76985ce63d60cf/packages/google-cloud-datalabeling/samples/quickstart.js#L23-L34

Extension version: 1.21.0
VS Code version: Code 1.74.0 (Universal) (5235c6bb189b60b01b1f49062f4ffa42384f8c91, 2022-12-05T16:43:37.594Z)
OS version: Darwin x64 19.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|32, 19, 19|
|Memory (System)|8.00GB (0.08GB free)|
|Process Argv|--crash-reporter-id bc42ca70-90c9-4cc2-b613-c43122f60e7e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848cf:30577861
nodejswelcome1:30587005
282f8724:30602487
gswce1:30612156
iaj6b796:30613358
dbltrim-noruby:30604474
f6dab269:30613381
fim-prod:30623723

```

</details>

**Comment by sushicw** [comment]
Hello!

Can you please include more information about what you were attempting to do, and what error you ran into?
