### ISSUE TITLE
The pipe program 'kubectl' exited unexpectedly with code 1.

### ISSUE THREAD

**Issue by exitia-com2us** [GoogleCloudPlatform/cloud-code-vscode#697]
**Environment**:

Windows 10

**Version information**

Cloud Code Extension version: 1.21.0

VSCode version: 1.74.2

OS: Windows 10

Cloud SDK: 410.0.0

**Description**:

I tried to remote debugging a pod on GKE following [this docs](https://cloud.google.com/code/docs/vscode/debug-k8-pod), but I got an error `The pipe program 'kubectl' exited unexpectedly with code 1.`.

I read #537, but its error code is different from me.

**Repro step**:

1. Build .NET application as a docker image with `Debug` profile and run.
2. Install `vsdbg` following [docs](https://cloud.google.com/code/docs/vscode/debug-k8-pod#setting_up_a_container) in the container.
3. Login with service account. `gcloud auth activate-service-account <service-account>.iam.gserviceaccount.com --key-file=<key-file-name>.json`
4. Write `.vscode/launch.json`.
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Attach to Kubernetes Pod (.NET Core)",
            "type": "cloudcode.kubernetes",
            "request": "attach",
            "language": "NETCore",
            "podSelector": {
                "type": "proxy"
            },
            "localRoot": "${workspaceFolder}",
            "remoteRoot": "/app"
        }
    ]
}
```
5. Run 'Attach to Kubernetes Pod (.NET Core)' and select the container and process.
6. Error `The pipe program 'kubectl' exited unexpectedly with code 1.` occurs.
![image](https://user-images.githubusercontent.com/105626017/208845092-c0a24de2-90a2-4eba-8678-1d7d3f00904f.png)

**Comment by exitia-com2us** [comment]
I found that executable `vsdbg` should be in `/dbg/netcore` while document says `/vsdbg`.

It is solved after running following commands in the container.

```
mkdir /dbg
mv /vsdbg /dbg/netcore
```

**Comment by davidponder** [comment]
Hi @exitia-com2us !

Sorry to hear you hit this friction, but relieved that you have since found a workaround! I'll bounce this over to the documentation folks so this can be fixed in the docs you were following.

Thanks!

**Comment by davidponder** [comment]
The documentation has been updated; thank you for bringing this to our attention!
