### ISSUE TITLE
Kubectl command config view --output json failed

### ISSUE THREAD

**Issue by fcwu** [GoogleCloudPlatform/cloud-code-vscode#70]
**Environment**:
Extension version: 0.0.7
VSCode version: 1.33.1
OS: linux

**Description**:
Cluster created by minikube failed to detect in CLUSTER EXPLORER. Press refresh it show "Kubectl command config view --output json failed."
In terminal, 
```
$ which kubectl 
/usr/local/bin/kubectl
$ kubectl version    
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:45:25Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
$ kubectl config view
apiVersion: v1
clusters:
- cluster:
    certificate-authority: /home/u/.minikube/ca.crt
    server: https://192.168.99.100:8443
  name: minikube
contexts:
- context:
    cluster: minikube
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: /home/u/.minikube/client.crt
    client-key: /home/u/.minikube/client.key
```

**Repro step**:
press refresh

**Comment by redborian** [comment]
@fcwu, can you confirm that you are indeed able to access the cluster through the command line?

**Comment by fcwu** [comment]
@redborian 
Sceenshot as following
<img width="1440" alt="Screen Shot 2019-04-13 at 6 34 09 AM" src="https://user-images.githubusercontent.com/165370/56069585-4dab1700-5db6-11e9-8301-a0da8c7acb36.png">

I am not sure it's useful for you that `kubectl` was installed by snap. So I made a link from /snap/bin/kubectl to /usr/local/bin/.

**Comment by fcwu** [comment]
BTW, it worked before when I had a kubectl v1.10 at /usr/local/bin/. But it's too old (API mismatch) to deploy an application. So I removed it and install the latest one by snap and link it to /usr/local/bin/.

**Comment by redborian** [comment]
Looks like it is unable to find `kubectl` at `$PATH`. Can you try opening VS Code from a terminal that has `kubectl` in `$PATH`?

**Comment by elebeaup** [comment]
I have the same issue. I have configured a kubernetes cluster by microk8s (snap). Vscode was installed by snap and also `kubectl` (included in microk8s installation).

Through the vscode terminal, `kubectl config view` works.

In the meantime, my workaround is to install kubectl using native package management and it works. My cluster is detected.

**Comment by aszenz** [comment]
@elebeaup  Same for me, working with native package but not with snap. 
Also received this error for deploy command: `Kubernetes context is not set` for snap version of kubectl, but working fine with the apt package.

**Comment by fcwu** [comment]
@elebeaup workaround works for me. 
@redborian you may close this issue.

**Comment by sabhi8226** [comment]
if we changed the context of config file for some aws eks cluster then how we can get the defailt config file of kubernetes back  command ?
