### ISSUE TITLE
Cloud Code failed to install dlv.

### ISSUE THREAD

**Issue by Lakmal-Fernando** [GoogleCloudPlatform/cloud-code-vscode#704]
Type: <b>Bug</b>

*Context*
- Managed Dependencies: on
- Cloud SDK Version: 412.0.0
- Skaffold Version: v2.0.3
- Minikube Version: 1.28.0

I have tried to debug pod on K8s pod but prompt to install dlv but it is not installed by giving following error.

Executing task: /opt/homebrew/bin/go get -u github.com/go-delve/delve/cmd/dlv 

go: go.mod file not found in current directory or any parent directory.
        'go get' is no longer supported outside a module.
        To build and install a command, use 'go install' with a version,
        like 'go install example.com/cmd@latest'
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.

 *  The terminal process "/opt/homebrew/bin/go 'get', '-u', 'github.com/go-delve/delve/cmd/dlv'" failed to launch (exit code: 1). 
 *  Terminal will be reused by tasks, press any key to close it. 
I have installed dlv locally and debugger is working locally. but Cloud Code does not recognize that

Extension version: 1.21.0
VS Code version: Code 1.73.1 (Universal) (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T02:08:38.961Z)
OS version: Darwin arm64 21.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 3, 3|
|Memory (System)|8.00GB (0.28GB free)|
|Process Argv|--crash-reporter-id fb005a09-df79-45a6-88b3-61f48f974165|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848cf:30577861
nodejswelcome1:30587005
282f8724:30602487
iaj6b796:30613358
f6dab269:30613381
fim-prod:30623723

```

</details>

**Comment by davidponder** [comment]
Hi @Lakmal-Fernando !

Sorry to hear you're encountering this friction. I'll bounce this over to the team so we can take a further look.

In the meantime, would you mind updating with your current version of go? This can be accomplished by typing `go version` in a VS Code terminal window.

Thanks!

**Comment by Lakmal-Fernando** [comment]
Hi @davidponder,
I'm currently using go 1.19.3
here is the `go version` output
`go version go1.19.3 darwin/arm64`
Thank you

**Comment by sushicw** [comment]
Hello!

This should be fixed by our next release of Cloud Code.
