### ISSUE TITLE
Apigee Cloud Code "Create API Proxy" dialog does not allow wildcard base paths

### ISSUE THREAD

**Issue by emarcotte** [GoogleCloudPlatform/cloud-code-vscode#708]
Type: <b>Bug</b>

*Context*
- Managed Dependencies: on
- Cloud SDK Version: 412.0.0
- Skaffold Version: v2.0.3
- Minikube Version: 1.28.0

Repro steps:

1. Create apigee workspace
2. Add an api proxy, select any parameters until base path option (step 5 for me)
3. Add a wildcard in the name, such as `/widgets/*/hello`

Observe the error and you cannot make progress.

Cloud Code Extension version:
![Screenshot 2023-01-05 at 1 55 34 PM](https://user-images.githubusercontent.com/249390/210858728-60429324-ce7a-48df-af64-47a415e4c8a1.png)

Note: the documentation (and a real apigee installation) will take wildcards happily: https://docs.apigee.com/api-platform/reference/api-proxy-configuration-reference

Extension version: 1.22.0-insiders.1
VS Code version: Code 1.74.2 (e8a3071ea4344d9d48ef8a4df2c097372b0c5161, 2022-12-20T10:26:09.430Z)
OS version: Darwin x64 22.2.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (0.02GB free)|
|Process Argv|--crash-reporter-id 843a7241-19bf-4b7a-8e54-6e6292eb284c|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848cf:30577861
nodejswelcome1:30587005
282f8724:30602487
iaj6b796:30613358
f6dab269:30613381
fim-prod:30623723

```

</details>

**Comment by davidponder** [comment]
Hello @emarcotte !

Sorry to hear you're hitting this; I'll forward this to the team so we can take a look and get this fixed ASAP!

Thanks!
