### ISSUE TITLE
Set new image for a controller (statefulset / Deployment / etc) and create necessary pull secret

### ISSUE THREAD

**Issue by feloy** [GoogleCloudPlatform/cloud-code-vscode#71]
**Use case**

I have deployed an application that pulls images from a registry (let's say the Prod registry). As a developer, I want to change the image of a statefulset / deployment to debug my app, and this image is stored in a registry (let's say the Dev registry), potentially different from the Prod registry.

**Feature**

The recurrent problem, in this case, is that you have to create a pull secret in the namespace of the Statefulset / Deployment with the credentials to access the Dev registry, then reference this pull secret in the Statefulset / Deployment.

It would be interesting to have a function to "Set the image" of a Statefulset / Deployment (for example by right-clicking the entry in the explorer), that would 
- query the image path
- if the registry is different from the registry of the current image and no pull secret exists for this registry/repo, query the type of pull secret and the necessary information to create the [ Docker / GCR / etc ] pull secret
- create the pull secret in the correct namespace
- reference this pull secret in the list of imagePullSecrets of the statefulset / deployment

**Comment by jmah-cc** [comment]
Thanks for your feedback. We've reviewed this again and this is not at the top of our priority list. I've added it to our backlog for tracking in the future.
