### ISSUE TITLE
Add support for Apigee's Configurable API Proxies

### ISSUE THREAD

**Issue by DKbyo** [GoogleCloudPlatform/cloud-code-vscode#716]
**Use case**
Currently is possible to create a template directory with this extension and deploy it using the beta command `gcloud beta apigee archives deploy`, but would be great to have full support for create and edit Configurable API yaml files using Cloud Code extension commandss 

**Feature**
- Add Configurable API Proxy yaml file validation
- Add a command to create some common proxies using Configutable API Proxy yaml files, like the ones specified on https://cloud.google.com/apigee/docs/api-platform/develop/configurable-proxy-examples

**Comment by ChaseMor** [comment]
@shirishtrivikr

**Comment by shirishtrivikr** [comment]
Configurable proxies have been deprecated as per https://cloud.google.com/apigee/docs/deprecations/configurable-proxies.
