### ISSUE TITLE
aws-iam-authenticator not in $PATH

### ISSUE THREAD

**Issue by jicowan** [GoogleCloudPlatform/cloud-code-vscode#73]
**Environment**:
Extension version: 0.0.7
VSCode version: 1.33.1
OS: darwin

**Description**:
Cannot list namespaces: Unable to connect to the server: getting credentials: exec: exec: "aws-iam-authenticator": executable file not found in $PATH
. The Kubernetes Explorer will use the current namespace.

I am able to manage clusters from the integrated VS Code terminal (using kubectl), but when I try expanding the clusters that appear in the Cluster Explorer, I get the error shown above.  I don't see where I can specify the PATH to the aws-iam-authenticator in the extension settings. The aws-iam-authenticator is in my PATH (/usr/local/bin). 

**Repro step**:
Create a context for an EKS cluster
Try connecting to the cluster from the Cluster Explorer

Where can I find the YAML schema for the Cloud Code extension?

**Comment by redborian** [comment]
Thanks for reporting the issue. We rely on `eksctl` to provision EKS clusters. Can you see if the discussion here helps solve your issue? https://github.com/weaveworks/eksctl/issues/169
For your second question, can you elaborate on which YAML schema are you looking for?

**Comment by jicowan** [comment]
Sorry I mean json.  I'm looking for the all of the options you can add to the settings.json file for the cloud code extension. `eksctl` doesn't install the aws-iam-authenticator.  You have to install that separately.

**Comment by redborian** [comment]
You would need to run `"Open Settings(UI)"` command in VS Code. In that, under `Extensions` -> `Cloud Code`, you would be able to find the extension's settings.
For your main issue, can you run VS Code from a terminal that has `aws-iam-authenticator` in its PATH already? This seems similar to this issue: https://github.com/GoogleCloudPlatform/cloud-code-vscode/issues/64

**Comment by jicowan** [comment]
Yes, I can run `kubectl` from the vscode terminal pane and connect to my clusters.  The aws-iam-authenticator is in my path.  

```
$ which aws-iam-authenticator
/usr/local/bin/aws-iam-authenticator
```

**Comment by redborian** [comment]
VS Code terminal would run its own bash initialization (.bashrc, .bash_profile etc). If you can confirm that you are indeed starting VS Code from a terminal, that would be helpful in troubleshooting this issue.
What is the value of `users.user.auth_provider.config` in your '.kubeconfig' file? (Without the access token)

Our extension just uses the command in kubeconfig file to connect to the cluster.

**Comment by jicowan** [comment]
I am not starting vscode from a terminal.  I'm launching it from OSX; it's in my dock.  

I don't have `auth_provider` in my kubeconfig file.  This is what my kubeconfig looks like: 

```
user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - token
      - -i
      - riverrun
      command: aws-iam-authenticator
      env: null
```
The kubeconfig was generated by `eksctl`.

**Comment by redborian** [comment]
Thanks for that information @jicowan. If you try starting it from the terminal, or add `/usr/local/bin/` to your login shell `$PATH` variable, it should work.
We will improve this experience in the upcoming releases.

**Comment by jicowan** [comment]
Launching it from a terminal works.  Thanks.

**Comment by redborian** [comment]
I will go ahead and close this issue. We will update our FAQ section to include this.

**Comment by sbd** [comment]
I'm currently experiencing roughly the same issue: 

Error: Unable to connect to the server: getting credentials: exec: exec: "aws": executable file not found in $PATH 

I successfully created a cluster from: `$ eksctl create cluster`
Then successfully ran: `$ sudo aws2 eks --region ${REGION} update-kubeconfig --name ${CLUSTER_ID}`

Then tried `$ kubectl get nodes` but got the error listed above. 

In addition, `$ aws-iam-authenticator init`
could not get config: cluster ID cannot be empty
