### ISSUE TITLE
Cloud Code causing high CPU usage

### ISSUE THREAD

**Issue by danielkalen** [GoogleCloudPlatform/cloud-code-vscode#730]
Type: <b>Bug</b>

Have cloud code installed

Extension version: 1.21.2
VS Code version: Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:26:31.005Z)
OS version: Darwin arm64 22.1.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|9, 23, 27|
|Memory (System)|32.00GB (6.69GB free)|
|Process Argv|--crash-reporter-id 8ec5dd64-bc46-4506-973a-87ef027540f5|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848cf:30577861
nodejswelcome1:30587005
3biah626:30602489
pyind779:30657576
89544117:30613380
pythonsymbol12cf:30657549
a9j8j154:30646983

```

</details>

**Comment by JustinHoyt** [comment]
We're aware of the issue and are planning on a solution that will fix these types of high cpu usage cases. I'm sorry for your bad experience!

**Comment by kingofsystem** [comment]
Bump. Experiencing the same issue. It makes the plugin unusable when I'm away from the power source.

**Comment by SKrupa** [comment]
We're actively working on a fix, its proving to be a bit involved. We'll update this thread once we have an estimate of when the fix is expected to release. Thank you for your patience!

**Comment by j-windsor** [comment]
Please see #790 for updates and more details.

**Comment by j-windsor** [comment]
Issues around managed dependencies are now fixed. Please see #790.
