### ISSUE TITLE
v1.2.2 Apigee section is no longer visible in the sidebar.

### ISSUE THREAD

**Issue by velsietis** [GoogleCloudPlatform/cloud-code-vscode#733]
Type: <b>Bug</b>

The Apigee section is no longer visible in the sidebar.  Previous versions of the extensions provided access to view the Apigee workspace, proxies, environments, emulator etc.  

**Context**
- Managed Dependencies: on
- Cloud SDK Version: 417.0.0
- Skaffold Version: v2.1.0
- Minikube Version: 1.29.0

**Repro step**: Install version 1.2.2, click on the "Cloud Code" button, observe the sections listed below(Apigee not included):
 - Development Sessions
 - Kubernetes
 - Cloud Run
 - Cloud APIs
 - Secret Manager
 - Compute Engine
 - Cloud Functions
 - Help and Feedback

Extension version: 1.21.2
VS Code version: Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:23:45.584Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.89GB (3.39GB free)|
|Process Argv|--crash-reporter-id e7c9964b-b31e-4d76-8cb9-f8037a755c2b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1:30587005
2e4cg342:30602488
f6dab269:30613381
pythonsymbol12cf:30657549
2i9eh265:30646982

```

</details>

**Comment by JustinHoyt** [comment]
It's possible the sidebar was disabled somehow. Can you check this dropdown to see if Apigee is enabled?

<img width="595" alt="Screenshot 2023-02-08 at 9 50 47 AM" src="https://user-images.githubusercontent.com/12431992/217611726-08848046-82e7-4cdf-adbb-4b5a3f2ce8c4.png">

**Comment by anthonygnolan** [comment]
Can confirm that Apogee is not available to enable
![google-cloud-code](https://user-images.githubusercontent.com/19191596/217790203-421e237c-b199-4af9-a57c-bedfa68818b1.png)

**Comment by JustinHoyt** [comment]
We identified the issue and are working on a new release to restore the explorer.

**Comment by glouischandra** [comment]
Cloud Code v1.21.3 is out and should fix this issue.
