### ISSUE TITLE
Cannot deploy multiple cloud functions from one workspace/directory

### ISSUE THREAD

**Issue by caddac** [GoogleCloudPlatform/cloud-code-vscode#734]
Type: <b>Bug</b>

*Context*
- Managed Dependencies: on
- Cloud SDK Version: 417.0.0
- Skaffold Version: v2.1.0
- Minikube Version: 1.29.0

I have one Cloud Code workspace with two functions (they are the identical source code with different entrypoints). I have two code deployment blocks in my .vscode/launch.json, however no matter which function I choose to deploy, only the configuration which is first in the launch.json file is deployed. 

Extension version: 1.21.2
VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T17:05:47.808Z)
OS version: Darwin arm64 22.1.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|5, 5, 4|
|Memory (System)|32.00GB (3.01GB free)|
|Process Argv|--crash-reporter-id 682f972d-9a12-4310-b73e-b818e5903129|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848:30577860
nodejswelcome1cf:30587006
2e4cg342:30602488
pyind779:30657576
89544117:30613380
pythonsymbol12cf:30657549

```

</details>

**Comment by JustinHoyt** [comment]
It's in our roadmap to add support for this, but we don't have any timelines in place at this time.

**Comment by SKrupa** [comment]
This functionality has been added as part of the 1.21.5 release so you should be able to deploy independent functions from the same workspace now. Let us know if you run into any further issues, thanks!
