### ISSUE TITLE
Managed Dependency Check Failed

### ISSUE THREAD

**Issue by aUsABuisnessman** [GoogleCloudPlatform/cloud-code-vscode#736]
**Environment**:
*(Hint: "Report Extension Issue on Github" command will fill these out for you.)*

**Version information**

Cloud Code Extension version:

VSCode version:run / debug on cloud run emulator

OS: windows

Cloud SDK:yes

Skaffold: no

Kubectl:yes

**Description**:just wont go

**Repro step**:

**Comment by glouischandra** [comment]
Hello @aUsABuisnessman can you include the versions of dependencies, you can get this by clicking on "File issues/Request a feature" button in Cloud Code explorer

![image](https://user-images.githubusercontent.com/3677364/218837225-3d7947f0-5e30-4d06-9a7a-4b3f024cc1d4.png)

![image](https://user-images.githubusercontent.com/3677364/218837187-6cc2062a-dce5-489c-a4d6-2290f060f0a4.png)

**Comment by davidponder** [comment]
Hi,

Please re-open with additional details; thanks!
