### ISSUE TITLE
Heads up: when clauses may be broken with the next VS Code release

### ISSUE THREAD

**Issue by ulugbekna** [GoogleCloudPlatform/cloud-code-vscode#748]
Hi 👋

VS Code team engineer here 🙂

We're reworking how we parse [when clause contexts](https://code.visualstudio.com/api/references/when-clause-contexts) and noticed that we may break some of the when clauses used in your extension. You can read more in this [issue](https://github.com/microsoft/vscode/issues/175540), which describes upcoming changes: new features, breakages, and migration advice (latest VS Code Insiders now has a linter for when clauses and runs the new parser as default). You can also leave us feedback there.

Thanks for a great extension, it's very popular! 

Best,
Ulugbek

**Comment by SKrupa** [comment]
Hi Ulugbek, thanks for the heads up! From the linter, looks like we should be unaffected but we're going through and double checking for our next release.

**Comment by ulugbekna** [comment]
Keep in mind that `g` and `y` flags in regexes are accepted but ignored.
