### ISSUE TITLE
Using too much cpu

### ISSUE THREAD

**Issue by fedevilensky** [GoogleCloudPlatform/cloud-code-vscode#749]
Type: <b>Bug</b>

Vscode was using a full cpu thread's capacity. After running bisect, this extension was found to be the one responsible for the performance issues

Extension version: 1.21.3
VS Code version: Code 1.76.0 (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:25:16.105Z)
OS version: Linux x64 6.2.2-arch1-1
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 3564)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|15.48GB (11.51GB free)|
|Process Argv|--unity-launch --crash-reporter-id 590f3d56-f46b-4997-aa42-697ca699b87d|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|xmonad|
|XDG_CURRENT_DESKTOP||
|XDG_SESSION_DESKTOP||
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30669237
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1:30587005
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
6233i204:30672705
vsctsb:30677850
vscodedisable:30660115
pythonb192cf:30669361
funwalk2:30676043

```

</details>

**Comment by davidponder** [comment]
Hi @fedevilensky ,

Sorry to hear you're hitting this friction and thanks for bringing this to our attention.  Did this happen during any particular action through Cloud Code or was this spontaneous?

**Comment by fedevilensky** [comment]
It happened when I opened vscode, not into any project or anything, just the main page

**Comment by j-windsor** [comment]
Please see #790 for updates and more details.
