### ISSUE TITLE
DigitalOcean Kubernetes

### ISSUE THREAD

**Issue by MattMorgis** [GoogleCloudPlatform/cloud-code-vscode#75]
**Feature**
**What are you trying to do that our extension doesn't let you?**

Create a [DigitalOcean Kubernetes](https://www.digitalocean.com/products/kubernetes/) cluster.

**Comment by iantalarico** [comment]
Hey Matt,

Great suggestion.  This isn't in our immediate plan but we will look into this for future work.

Thanks
Ian

**Comment by kschaab** [comment]
We have this tagged as reassess in the future, closing for now.
