### ISSUE TITLE
Managed Dependency Check Failed

### ISSUE THREAD

**Issue by djpeter2** [GoogleCloudPlatform/cloud-code-vscode#752]
Min supported version check failed for kubectl. Min supported version v1.12.0. Current version . Err: Failed to install required Cloud SDK components. , Your current Google Cloud CLI version is: 421.0.0 ,Installing components from version: 421.0.0 , ,┌─────────────────────────────────────────────────────────────────────────────┐, ,│ These components will be installed. │, ,├─────────────────────────────────────────────────────┬────────────┬──────────┤, ,│ Name │ Version │ Size │, ,├─────────────────────────────────────────────────────┼────────────┼──────────┤, ,│ ,Cloud Storage Command Line Tool , ,│ , 5.21, ,│ ,15.5 MiB, ,│, ,│ ,Cloud Storage Command Line Tool (Platform Specific), ,│ , 5.13, ,│ , < 1 MiB, ,│, ,│ ,Google Cloud CLI Core Libraries , ,│ ,2023.03.03, ,│ ,26.8 MiB, ,│, ,│ ,Google Cloud CLI Core Libraries (Platform Specific), ,│ ,2022.09.20, ,│ , < 1 MiB, ,│, ,│ ,Minikube , ,│ , 1.29.0, ,│ ,32.5 MiB, │ │ gcloud Alpha Commands │ 2023.03.03 │ , < 1 MiB, ,│, ,│ ,gcloud Beta Commands , ,│ ,2023.03.03, ,│ , < 1 MiB, ,│, ,│ ,gcloud cli dependencies , ,│ ,2023.02.24, ,│ ,11.2 MiB, ,│, ,│ ,gcloud cli dependencies , ,│ ,2021.04.16, ,│ , < 1 MiB, ,│, ,│ ,gke-gcloud-auth-plugin , ,│ , 0.5.0, ,│ , 7.5 MiB, ,│, ,│ ,kubectl , ,│ , 1.24.11, ,│ , < 1 MiB, ,│, ,│ ,kubectl , ,│ , 1.24.11, ,│ ,97.1 MiB, ,│, ,└─────────────────────────────────────────────────────┴────────────┴──────────┘, , ,For the latest full release notes, please visit: https://cloud.google.com/sdk/release_notes ,╔════════════════════════════════════════════════════════════╗ ╠═ Creating update staging area ═╣ ,╚,══════,══════,══════,══════════════════════════════════════════,╝ ,ERROR: (gcloud.components.install) Unable to read file [/Users/danielpeters/Library/Application Support/cloud-code/installer/google-cloud-sdk/.install/skaffold-darwin-x86_64.manifest]: [Errno 2] No such file or directory: '/Users/danielpeters/Library/Application Support/cloud-code/installer/google-cloud-sdk/.install/skaffold-darwin-x86_64.manifest'

**Comment by JustinHoyt** [comment]
Hi, can you please provide what version of vscode and Cloud Code you're running and what OS you're on?

**Comment by davidponder** [comment]
Hello!

Please re-open with additional details; thanks!
