### ISSUE TITLE
Command "apigee.explorer.refresh" not found issue

### ISSUE THREAD

**Issue by olgunkaya** [GoogleCloudPlatform/cloud-code-vscode#755]
**Environment**:
- Managed Dependencies: on
- Skaffold Version: v2.1.0
- Minikube Version: 1.29.0

**Version information**

Cloud Code Extension version: 
v1.21.3

VSCode version:
Version: 1.76.1

OS: 
macOS Monterey 12.6

Cloud SDK:
Cloud SDK Version: 421.0.0

Skaffold: 
v2.1.0

Kubectl:
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.6", GitCommit:"b39bf148cd654599a52e867485c02c4f9d28b312", GitTreeState:"clean", BuildDate:"2022-09-21T13:19:24Z", GoVersion:"go1.18.6", Compiler:"gc", Platform:"darwin/amd64"}

**Description**:
Following the installation of extension, I can not see the Items in explorer like;
Apigee emulators
Apigee instance on connected gcp project. 

There is the error text shown :
"Error running command apigee.explorer.refresh: command 'apigee.explorer.refresh' not found. This is likely caused by the extension that contributes apigee.explorer.refresh."

**Repro step**:
1. Install extension. 
2. Switch to extension pane. 
   a. No "APIGEE EMULATORS" shown. 
   b. Even the gcp connection done and available, under Apigee menu, there is no workspace shown.  

Edit : The environment in the apigee currently is in "Proxy deployment" mode. Would it be something related to "non arcihive  deployment" mode ?

**Comment by olgunkaya** [comment]
I believe that's enough to hear. I wish I can see that in the UI with proper messaging or tooltips so that we can save your time :)

**Comment by shirishtrivikr** [comment]
@olgunkaya Thank you for the feedback!  Will work on making the UI messaging clear on this aspect.
