### ISSUE TITLE
Add KVM support for apigee vscode extension

### ISSUE THREAD

**Issue by jatovar** [GoogleCloudPlatform/cloud-code-vscode#756]
Type: <b>Feature Request</b>

*Context*
- Managed Dependencies: on
- Cloud SDK Version: 422.0.0
- Skaffold Version: v2.2.0
- Minikube Version: 1.29.0

Extension version: 1.21.3
VS Code version: Code 1.76.1 (5e805b79fcb6ba4c2d23712967df89a089da575b, 2023-03-08T16:32:00.131Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

**Comment by davidponder** [comment]
Hey @jatovar !

Thanks for suggesting this! I'll bounce this over to the Apigee folks as an enhancement item for a later sprint.

Thanks again!

**Comment by shirishtrivikr** [comment]
Hey @jatovar,

The apigee extension already has a support for KVMs via test resources.  You can add a KVM with a bunch of values for testing your API proxies. Please see https://cloud.google.com/apigee/docs/api-platform/local-development/vscode/build-test-resources#defining_key_value_maps_mapsjson.  

Please let us know if you had something else in mind w.r.t. KVM support. 

Thanks again!

**Comment by OGmenas** [comment]
Hi i would like to reopen as i cant generate a proper kvm for testing as shown above. I generated a kvm thru the vscode extension but when exported it just shows the name but no value at all.
![image](https://github.com/user-attachments/assets/0a368058-c2da-4b87-88cf-58c6c67473ed)
![image](https://github.com/user-attachments/assets/3d797251-678b-4ba1-aa16-b2dd007a643e)
