### ISSUE TITLE
Deployment Profile Wizard spins indefinitely when creating Deployment Profile

### ISSUE THREAD

**Issue by alfietham** [GoogleCloudPlatform/cloud-code-vscode#76]
**Environment**:
Extension version: 0.0.7
VSCode version: 1.33.0
OS: darwin
Skaffold version: 0.26.0

**Description**:
When using the Deployment Profile Wizard to create a Deployment Profile, the Wizard is stuck loading indefinitely. When tab is closed, the output shows: `The workspace is not supported as it does not have the deployment config (skaffold.yaml). Please create one and try again.`

Found that upgrading to Skaffold to the latest release (v0.27) gets around the issue. I was using v0.26 before.

Thought this failure mode wasn't very obvious, so just wanted to post this and the workaround somewhere for reference. Happy to contribute docs or fixes, just point me in the right direction.

**Repro step**:
1. Given an app with k8s manifest.yaml files, but no skaffold.yaml
2. Run `Cloud Code: Deploy` on VSCode
3. The Deployment Profile Wizard appears with the loading bar spinning for a while with nothing happening

**Workaround**:
Update Skaffold to v0.27.
- [Skaffold installation docs](https://skaffold.dev/docs/getting-started/#installing-skaffold)
- Ensure Skaffold is v0.27: run `skaffold version`

**Comment by redborian** [comment]
Thanks for your feedback and for the workaround! Appreciate it. We will investigate this issue and update this thread.

**Comment by sujit-kamireddy** [comment]
Thanks @alfietham for filing the issue and for the update. Deployment Wizard relies on some of the latest APIs added in the recent versions of Skaffold. We will update the documentation.

**Comment by sujit-kamireddy** [comment]
Updated the documentation. Thanks @alfietham
