### ISSUE TITLE
Te

### ISSUE THREAD

**Issue by SHOPEK** [GoogleCloudPlatform/cloud-code-vscode#760]
ADD ISSUE DESCRIPTION HERE

Version: 1.76.1
Commit: 5e805b79fcb6ba4c2d23712967df89a089da575b
User Agent: Mozilla/5.0 (Linux; Android 11; 220333QPG Build/RD2A.211001.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/111.0.5563.58 Mobile Safari/537.36
Embedder: server-distro

Extension version: 1.21.3

**Comment by JustinHoyt** [comment]
Can you please provide more information? What issue are you having and can you post the relevant logs?
