### ISSUE TITLE
Apigee Emulator - Override gcr.io via docker mirrors for enterprise environments

### ISSUE THREAD

**Issue by gosunilgo** [GoogleCloudPlatform/cloud-code-vscode#765]
**Use case**
For corporate/enterprise environments,  we need to use docker-mirrors (https://gcr-mirror.docker.mycompany)  vs. direct link https://gcr.io 

Note: I tried adding to "apigee.dockerOptions" but doesn't seem to work

![image](https://user-images.githubusercontent.com/10015502/230136322-ca483daf-65c9-40b3-b126-fe31aa79c9b8.png)
![image](https://user-images.githubusercontent.com/10015502/230136844-6454428f-2c0e-4aea-abca-b30c40e4e8ef.png)

**Feature**
Would like ability/feature/config to override default docker registry - gcr.io for Apigee Emulators.

**Comment by shirishtrivikr** [comment]
@gosunilgo 

Thanks for reporting the issue.  You can already achieve this today.. Have you tried using the steps documented here [Using a different version of the Apigee Emulator ](https://cloud.google.com/apigee/docs/api-platform/local-development/vscode/manage-apigee-emulator#using_a_different_version_of_the_apigee_emulator).  

Please let us know if this does not work for you.

Thanks
Shirish

**Comment by gosunilgo** [comment]
@shirishtrivikr  -  Works great.  I will keep testing.
