### ISSUE TITLE
GOOGLE_APPLICATION_CREDENTIALS  settings via settings.json.

### ISSUE THREAD

**Issue by mma-pivotal** [GoogleCloudPlatform/cloud-code-vscode#77]
**Environment**:
Extension version: 0.0.7
VSCode version: 1.33.1
OS: Windows 10 Pro

**Description**:
I created a sample go app with cloud-code plugin and then trying to deploy application onto GKE.
Get the following errors from output screen.

```
time="2019-04-16T21:53:31+09:00" level=fatal msg="build failed: building [gcr.io/xxx/go-hello-world]: getting google client: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information."
```

My understanding is that I need to setup Environment Variable GOOGLE_APPLICATION_CREDENTIALS with the following command.

`$env:GOOGLE_APPLICATION_CREDENTIALS="C:\Users\username\Downloads\[FILE_NAME].json"`

However, this would only work for the shell session that I ran this command and vscode would create a separate session when trying to deploy the application.

I managed to workaround this issue by adding a global environment variable for GOOGLE_APPLICATION_CREDENTIALS but I think it make more sense to be able to set this via settings.json.

**Comment by redborian** [comment]
This is a known issue. A workaround would be to run `gcloud auth application-default login` once from your terminal. We will make this experience better in future releases.

**Comment by shashankvivek** [comment]
> gcloud auth application-default login

@redborian When can we expect this feature ?

**Comment by redborian** [comment]
@shashankvivek We are working with the underlying tooling team to refine the deployment experience. This is the work-around as of now. I don't have a strict timeline on which release it will be part of although we are striving hard to fix these issues.

I will keep you posted.

**Comment by kschaab** [comment]
This is pending in our next release.

**Comment by sujit-kamireddy** [comment]
The fix for this issue is in our latest [release](https://github.com/GoogleCloudPlatform/cloud-code-vscode/releases/tag/v0.0.12). Please update the extension and retry the scenario.
