### ISSUE TITLE
Apigee explorer not working 

### ISSUE THREAD

**Issue by CA-Mukesh** [GoogleCloudPlatform/cloud-code-vscode#770]
Type: <b>Bug</b>

*Context*
- Managed Dependencies: on
- Cloud SDK Version: 426.0.0
- Skaffold Version: v2.3.0
- Minikube Version: 1.30.1

Error running command apigee.explorer.refresh: command 'apigee.explorer.refresh' not found. This is likely caused by the extension that contributes apigee.explorer.refresh.

Extension version: 1.21.4
VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:02.548Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 1690)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.73GB (4.01GB free)|
|Process Argv|--crash-reporter-id 17034598-7eb4-41ac-9fc6-40d0b56db634|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1:30587005
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
vsctsb:30705553
vscodeenable:30660116
azdwalk:30687957
pythonms35:30701012
pythonclientmv:30713943

```

</details>

**Comment by shirishtrivikr** [comment]
Hi @CA-Mukesh Thanks for reporting the issue

The refresh button available in the apigee view should have been disabled when no apigee workspace is open. We are working on fixing this issue. 

In the mean time you would need to create an Apigee workspace to explore the functioning of the view. Apigee workspaces provides a complete offline development experience for developers to create and test their proxies on their desktop and against the code in their source code repository. The emulators can be used to quickly verify that the developed proxies work as expected before they can be uploaded to the cloud. Please find the detailed documentation on this topic [Overview of local development with Apigee](https://cloud.google.com/apigee/docs/api-platform/local-development/overview)


Thanks
Shirish
