### ISSUE TITLE
ADD ISSUE DESCRIPTION HERE

### ISSUE THREAD

**Issue by drmoney2014** [GoogleCloudPlatform/cloud-code-vscode#774]
ADD ISSUE DESCRIPTION HERE

Version: 1.77.3
Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
Embedder: codespaces

Extension version: 1.21.5

**Comment by j-windsor** [comment]
Please reopen with additional information. Thanks!
