### ISSUE TITLE
Editing YAML is not show snippets

### ISSUE THREAD

**Issue by rsoutar** [GoogleCloudPlatform/cloud-code-vscode#78]
**Environment**:
Extension version: 0.0.7
VSCode version: 1.33.1
OS: MacOS Mojave

**Description**:
I have a test cluster running which show up on both Cluster Explorer and GKE Explorer. I then `Command + Shift + P` and select `New Application`. I choose `Node.js: Hello World`.

Then I open `kubernetes-manifests/hello.deployment.yaml` and try to use Edit YAML by using `Command + Space`. It show a popup on bottom right `Cannot read property 'KubeObject' of undefined`.

**Comment by iantalarico** [comment]
@redborian Can you take a look at this?  Looks like and issue with the language server

**Comment by redborian** [comment]
@rsoutar Are you seeing this error message in the "Cloud Code Yaml Support" output channel?

**Comment by rsoutar** [comment]
@redborian I saw it on VSCode when I press the keyboard shortcut for `Cloud Code: Edit YAML`

<img width="1031" alt="Screen Shot 2562-04-16 at 22 29 30" src="https://user-images.githubusercontent.com/13177655/56222999-2777c680-6097-11e9-8456-dbafe7d29570.png">

**Comment by iantalarico** [comment]
@redborian Any update here? Was this fixed?

**Comment by redborian** [comment]
@rsoutar `Cloud Code: Edit YAML` command has since been hidden as it is not suitable for direct consumption by the user. Feel free to choose `Edit YAML` on a particular resource from the `Cluster Explorer`. I will close this issue. Feel free to reopen it with additional comments.
