### ISSUE TITLE
Apigee Emulator Deployment Fails Silently

### ISSUE THREAD

**Issue by velsietis** [GoogleCloudPlatform/cloud-code-vscode#783]
Type: <b>Bug</b>

*Context*
- Managed Dependencies: on
- Cloud SDK Version: 430.0.0
- Skaffold Version: v2.3.0
- Minikube Version: 1.30.1
- Apigee Emulator: gcr.io/apigee-release/hybrid/apigee-emulator:1.6.1

*Reproduction steps*
- create an Apigee proxy, add a policy, e.g. RaiseFault, but in the XML add a line break in the value of the name attribute on the root node, e.g. 

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<RaiseFault async="false" continueOnError="false" enabled="true" name="RaiseFault-MissingOrInvalidParameters
">
    <FaultResponse>
        <AssignVariable>
            <Name>main.error.status</Name>
            <Value>400</Value>
        </AssignVariable>
    </FaultResponse>
</RaiseFault>
```
Then try to deploy this proxy to the Apigee emulator.

The proxy does not deploy but there is no error or warning displayed in the output.

I expected an error message explaining why the proxy has not deployed

Extension version: 1.21.5
VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-1245U (12 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.69GB (4.47GB free)|
|Process Argv|--crash-reporter-id 03bf9ff2-8423-4f15-bd8e-defde181ebf3|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
pyind779:30671433
f6dab269:30613381
vscrpc:30673769
pythonsymbol12:30671437
showlangstatbar:30737416
vsccsb:30705552
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30731395
fixhidewlkth:30730051
hidesbindicator:30730055
pythongtdpath:30739704

```

</details>

**Comment by shirishtrivikr** [comment]
Hi @velsietis 

Thanks for reporting the issue. I am able to recreate the problem and will keep you updated on the fix status.

Thanks
Shirish

**Comment by shirishtrivikr** [comment]
This has been fixed in the later versions of the emualtor.
