### ISSUE TITLE
FR - Allow scale workloads like deployments through explorer

### ISSUE THREAD

**Issue by msgongora** [GoogleCloudPlatform/cloud-code-vscode#79]
**Use case**
This FR is in the DevOps side of this awesome addon. 
From the perspective of a developer who never has interacted with k8s yaml it's kind of scaring having to edit them. That's why I think it will be nice if they could just hit right click at a workload level and select scale from the explorer. or maybe edit the section `Desired Replicas: X` under the workload level. I know this can be done hitting the edit pencil at the workload level but again:  Developers are sometimes scared of yaml. Devops or whoever has been supporting developer teams will know what I'm talking about.

**Comment by iantalarico** [comment]
@msgongora I think this is a good idea, I don't think we have bandwidth to do this right now but will keep it in mind for future work.

**Comment by msgongora** [comment]
@iantalarico 
I would work in this feature if I could :( It was me the guy asking you about the open source license after you finished GoogleNext presentation ;) I'd love to write some code for this extension.

**Comment by sujit-kamireddy** [comment]
This issue has been fixed in the latest release 0.0.10. Please try it out.

As always, please keep issues coming our way.
