### ISSUE TITLE
Frequent timeouts when hitting refresh or other actions

### ISSUE THREAD

**Issue by ioannis-ganotis** [GoogleCloudPlatform/cloud-code-vscode#796]
Type: <b>Bug</b>

I get frequent timeouts when hitting refresh or doing other actions (like view logs) on kubernetes like the one below.

Error while monitoring Ingress resources: [Error: connect ETIMEDOUT 35.195.243.206:443 at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)] { errno: -110, code: 'ETIMEDOUT', syscall: 'connect', address: '35.195.243.206', port: 443 }

Notes:
- Kubernetes is a GKE cluster.
- Internet connection is stable

- Managed Dependencies: off
- Cloud SDK Version: 430.0.0
- Skaffold Version: v2.3.0
- Minikube Version: 1.30.1

Extension version: 1.21.5
VS Code version: Code 1.76.0 (Universal) (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:23:45.993Z)
OS version: Darwin x64 21.6.0
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.15.89+

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 2, 2|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv|--crash-reporter-id d97af282-2858-43a3-8275-fa41a77147e1|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: localhost-gcp-ws|
|OS|Linux x64 5.15.89+|
|CPUs|Intel(R) Xeon(R) CPU @ 2.20GHz (4 x 2200)|
|Memory (System)|15.63GB (13.47GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
showlangstatbar:30737416
pythonms35:30701012
pythonfmttext:30731395
fixshowwlkth:30730052
hidesbindicator:30730055
pythongtdpath:30739704

```

</details>

**Comment by davidponder** [comment]
Hello!

Sorry for the late reply! We coincidentally have some new improvements coming with the next release (1.21.6) that we're hoping will tackle some of this friction. 

We'll close this for now, but please feel free to re-open if you're still encountering this after the release of 1.21.6!
