### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Loukoss** [GoogleCloudPlatform/cloud-code-vscode#798]
- Issue Type: `Performance`
- Extension Name: `cloudcode`
- Extension Version: `1.21.5`
- OS Version: `Windows_NT x64 6.1.7601`
- VS Code version: `1.70.3`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/NFT/AppData/Local/Temp/googlecloudtools.cloudcode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by JustinHoyt** [comment]
Please reopen with more information when you get a chance. Thanks!
