### ISSUE TITLE
"Set as Active Cluster" doesn't update Cluster Explorer and loading message in bottom right never finishes loading

### ISSUE THREAD

**Issue by russwolf** [GoogleCloudPlatform/cloud-code-vscode#80]
**Environment**:
Extension version: 0.0.7
VSCode version: 1.33.0
OS: darwin

**Description**:
"Set as Active Cluster" doesn't update Cluster Explorer and loading message in bottom right never finishes loading

You can choose to manually cancel the loading message and refresh the cluster explorer and it will show that newly selected cluster. 

**Repro step**:
1) Right click on a cluster within a project in the GKE Explorer and select "Set as Active Cluster" 

Expected: 
Cluster explorer refreshes 

Actual: 
Cluster explorer does not refresh and loading message never finishes

**Comment by iantalarico** [comment]
This was fixed in a previous release.
