### ISSUE TITLE
Cloud Run deployments wipe out secret references after v1.21.6 release

### ISSUE THREAD

**Issue by matt-allpress** [GoogleCloudPlatform/cloud-code-vscode#804]
**Version information**

Cloud Code Extension version: v1.21.6
VSCode version: 1.79.0 (Universal)
OS: MacOS Ventura
Cloud SDK: 434.0.0
Skaffold: v2.4.1
minikube Version: 1.30.1

**Description**:

We have a Cloud Run service that is configured to expose Cloud Secrets as environment variables, for example:
![image](https://github.com/GoogleCloudPlatform/cloud-code-vscode/assets/15386356/1b373204-d9c6-4b78-ba60-45dbcd976885)

Since the latest Cloud Code update, when we deploy to Cloud Run it wipes out all our secret references, and they need to be manually added in a new revision.

I deployed last night (UK time) without issue. This morning I opened a new project and saw the UI changes to Cloud Code for the first time, then got the issue above when deploying.

**Repro step**:

- Create a Cloud Run service that exposes Cloud Secrets as environment variables
- Cloud Code --> Deploy to Cloud Run using the default settings (see screenshot below for a snippet of settings we use)
- The build fails with the message:
```
Failed to deploy the app. Error: Revision '[MASKED]-00064-2j6' is not ready and cannot serve traffic. The user-provided container failed to start and listen on the port defined provided by the PORT=8080 environment variable. Logs for this revision might contain more information.

Logs URL: https://console.cloud.google.com/logs/viewer?project=[MASKED]&resource=cloud_run_revision/service_name/[MASKED]/revision_name/[MASKED]-00064-2j6&advancedFilter=resource.type%3D%22cloud_run_revision%22%0Aresource.labels.service_name%3D%22[MASKED]%22%0Aresource.labels.revision_name%3D%22[MASKED]-00064-2j6%22 
For more troubleshooting guidance, see https://cloud.google.com/run/docs/troubleshooting#container-failed-to-start
Retrieving builders.
```

![image](https://github.com/GoogleCloudPlatform/cloud-code-vscode/assets/15386356/d83a0f35-dcf1-4530-b0af-6add2ece9c33)

**Comment by davidponder** [comment]
Hey @matt-allpress ,

Thank you for reporting this! I'll bounce this over to the team so we can mitigate and remedy this ASAP.

**Comment by GarrickBrown** [comment]
I am having the same issue.

I would add that as recently as v1.21.3, the VPC Connector settings from the current revision would be maintained in the new revision. At some point between v1.21.3 and v1.21.6, these settings are no longer maintained when deploying a new revision with Cloud Code, the VPC Connector gets set to "None".

I wonder if the two issues are related?

**Comment by peppySrJ** [comment]
I am also having the same issue. Both the secrets and the cloud run connections are getting wiped out.

**Comment by tenonedesign** [comment]
Same issue with 1.21.6.  Config is wiped during deploy.  Using 1.21.5 for now.

**Comment by tenonedesign** [comment]
Tried 1.21.7, but we still lose h2c port setting, all volumes, startupProbe, database connections, and resource limits when deploying.

**Comment by matt-allpress** [comment]
1.21.7 fixed the issue for us, but it has introduced a new issue where most of the time deployments don't record a new revision and changes don't take affect. We have to click "Edit and deploy new revision" in the Cloud Run UI before we see a new revision, and before the change we deployed takes affect.

**Comment by j-windsor** [comment]
All issues should now be fixed in the 1.21.8 release.

**Comment by tenonedesign** [comment]
No deployment issues encountered with 1.22.0.  Thanks!

**Comment by GarrickBrown** [comment]
Same here, no issues with deployments using 1.22.0. Great work!
