### ISSUE TITLE
Opening AWS Settings actually opens the settings.json for GKE

### ISSUE THREAD

**Issue by russwolf** [GoogleCloudPlatform/cloud-code-vscode#81]
**Environment**:
Extension version: 0.0.7
VSCode version: 1.33.0
OS: darwin

**Description**:
Opening AWS Settings actually opens the settings.json for GKE

**Repro step**:
Click on open settings for Aws in the VS Code Cloud Code settings panel

**Comment by iantalarico** [comment]
This has been fixed
