### ISSUE TITLE
Select a Google Cloud Project

### ISSUE THREAD

**Issue by Gaardsholt** [GoogleCloudPlatform/cloud-code-vscode#813]
Type: <b>Bug</b>

1. Open vscode
2. Wait for Cloud Code extension to finish load
3. See that you get asked to select a Google Cloud project
4. Select a project
5. Close vscode
6. Go to step 1

It just keeps asking me to select a Google Cloud project

*Context*
- Managed Dependencies: on
- Cloud SDK Version: 436.0.0
- Skaffold Version: v2.5.0
- minikube Version: 1.30.1

Extension version: 1.21.7
VS Code version: Code 1.79.2 (Universal) (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:58:52.392Z)
OS version: Darwin arm64 22.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|7, 6, 5|
|Memory (System)|24.00GB (0.57GB free)|
|Process Argv|dev/flux-config --crash-reporter-id 9369fbe5-b3c7-46d0-8d11-73e686fb7792|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30773603
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
7ij38806:30736111
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
pythongtdpath:30769146
bgfeh915:30769767
dh2dc718:30770000
pythonidxptcf:30772540
pythondjangots:30772535

```

</details>

**Comment by SKrupa** [comment]
Thanks for reporting this bug. Sorry for the inconvenience, we are are working on a hotfix release to alleviate this. We'll keep you posted when we've released the fix.

**Comment by SKrupa** [comment]
1.21.8 has been released with a fix for this bug, please let us know if you face any other issues.
