### ISSUE TITLE
Allow to stop a continuous deployment

### ISSUE THREAD

**Issue by dbolkensteyn** [GoogleCloudPlatform/cloud-code-vscode#82]
**Use case**
After adding a `spec.containers.ports.containerPort` field to a pod in my Kubernetes Yaml file to get port-forwarding, Skaffold tried to patch the pod and failed because `ports` "cannot be updated" as specified in the doc:
```
The Pod "..." is invalid: spec: Forbidden: pod updates may not change fields other than `spec.containers[*].image`, `spec.initContainers[*].image`, `spec.activeDeadlineSeconds` or `spec.tolerations` (only additions to existing tolerations)
```

So now my deployment is not in the state I want, and I want to stop it and redeploy it from scratch, instead of patching it. However I did not find how to stop/delete/cancel the current ongoing deployment.

Attempting to simply relaunch the deploy command fails with: `Multiple deployment sessions not supported.`

**Feature**
A new `Cloud Code: Stop deployment` action?
And/or, offer to stop the deployment when I attempt a new deployment (instead of just erroring).

**Comment by iantalarico** [comment]
@dbolkensteyn You can stop this from the status bar (see screenshots below) although I think a command to stop it from the command palette also would be good (especially if this is how you start the deployment).

@redborian Do you think we can get a command palette action for this into the next release?

Clicking here will open the command palette
![Screen Shot 2019-04-16 at 2 36 42 PM](https://user-images.githubusercontent.com/5264734/56245868-49e8f000-6055-11e9-9c98-740a43d9d836.png)
![Screen Shot 2019-04-16 at 2 36 46 PM](https://user-images.githubusercontent.com/5264734/56245874-4b1a1d00-6055-11e9-9f99-303cc782a00d.png)

**Comment by dbolkensteyn** [comment]
Thank you @iantalarico

**Comment by pratikvarma** [comment]
@iantalarico I do not see 'Cloud Code: Deployment in progress' in the status bar. I only see 'Cloud Code', clicking on which does not show me a Stop Continuous Deploy option.

**Comment by quoctruong** [comment]
@pratikvarma The `Cloud Code: Deployment in progress` will only show up when continuous deployment is happening

**Comment by pratikvarma** [comment]
@iantalarico right, first I ran the `Cloud Code: Continuous Deploy` in the command palette (cmd+shift+p). The application started and deployed correctly as I was able to go to the page. But when i make some changes, I see the output say `Deploy complete in XYZms` but the changes do not show when i update the browser.

**Comment by quoctruong** [comment]
@pratikvarma Is it possible to capture some screenshots or GIFs of the deployment?

**Comment by pratikvarma** [comment]
@quoctruong 
![Screen Shot 2019-05-08 at 3 59 20 PM](https://user-images.githubusercontent.com/1262305/57413786-57a01a00-71aa-11e9-8cad-aa575852f007.png)

----Output----
Running: skaffold dev -v info --rpc-http-port 62636
time="2019-05-08T15:58:37-07:00" level=info msg="Skaffold &{Version:v0.28.0 ConfigVersion:skaffold/v1beta9 GitVersion: GitCommit:2b6143bb6d185de9b9fbf2eaa981c8e7acff7339 GitTreeState:clean BuildDate:2019-04-26T23:01:14Z GoVersion:go1.12.4 Compiler:gc Platform:darwin/amd64}"

time="2019-05-08T15:58:37-07:00" level=warning msg="config version (skaffold/v1beta6) out of date: upgrading to latest (skaffold/v1beta9)"

time="2019-05-08T15:58:37-07:00" level=info msg="no config entry found for kube-context minikube"

time="2019-05-08T15:58:37-07:00" level=info msg="Using kubectl context: minikube"
time="2019-05-08T15:58:37-07:00" level=info msg="no config entry found for kube-context minikube"
time="2019-05-08T15:58:37-07:00" level=info msg="no config entry found for kube-context minikube"

time="2019-05-08T15:58:38-07:00" level=info msg="no config entry found for kube-context minikube"

time="2019-05-08T15:58:38-07:00" level=info msg="starting gRPC server on port 50052"

time="2019-05-08T15:58:38-07:00" level=info msg="starting gRPC HTTP server on port 62636"

Generating tags...
 - node-hello-world -> node-hello-world:latest
Tags generated in 131.85µs
Starting build...
Found [minikube] context, using local docker daemon.
Building [node-hello-world]...
Sending build context to Docker daemon  145.4kB

Step 1/6 : FROM node:8
 ---> a5c31320f223
Step 2/6 : WORKDIR /hello-world
 ---> Using cache
 ---> 7b4cd5bdc45f
Step 3/6 : COPY package*.json ./
 ---> Using cache
 ---> 46947b570736
Step 4/6 : RUN npm install
 ---> Using cache
 ---> f3c6807fcf56
Step 5/6 : COPY . .
 ---> Using cache
 ---> 2dd67976a765
Step 6/6 : ENTRYPOINT ["node", "--inspect=9229", "src/app.js"]
 ---> Using cache
 ---> b2a685b116a4
Successfully built b2a685b116a4
Successfully tagged node-hello-world:latest
Build complete in 168.702612ms
Starting test...
Test complete in 8.623µs
Starting deploy...
kubectl client version: 1.14
deployment.apps/node-hello-world created
service/node-hello-world-external created
Deploy complete in 877.735006ms
Watching for changes every 1s...
time="2019-05-08T15:58:40-07:00" level=info msg="Stream logs from pod: node-hello-world-59b797f587-qzll8 container: server"

Forwarding container server to local port 8081.
Port Forwarding node-hello-world-59b797f587-qzll8/server 8080 -> 8081
[node-hello-world-59b797f587-qzll8 server] Debugger listening on ws://127.0.0.1:9229/1002d52a-7087-4363-ba61-21dc4ad2b71f
[node-hello-world-59b797f587-qzll8 server] For help see https://nodejs.org/en/docs/inspector
[node-hello-world-59b797f587-qzll8 server] App listening on port 8080
[node-hello-world-59b797f587-qzll8 server] Press Ctrl+C to quit.

**Comment by quoctruong** [comment]
@pratikvarma What happened if you changed something (let's say change the "hello world" string to something else and then saves the file?

**Comment by pratikvarma** [comment]
@quoctruong I see this added to the output as soon as I save the file:

Step 1/6 : FROM node:8
 ---> a5c31320f223
Step 2/6 : WORKDIR /hello-world
 ---> Using cache
 ---> 7b4cd5bdc45f
Step 3/6 : COPY package*.json ./
 ---> Using cache
 ---> 46947b570736
Step 4/6 : RUN npm install
 ---> Using cache
 ---> f3c6807fcf56
Step 5/6 : COPY . .
 ---> bbfa5e8405b6
Step 6/6 : ENTRYPOINT ["node", "--inspect=9229", "src/app.js"]
 ---> Running in 1db666784225
Removing intermediate container 1db666784225
 ---> 1ebb103da2ad
Successfully built 1ebb103da2ad
Successfully tagged node-hello-world:latest
Build complete in 399.527027ms
Starting test...
Test complete in 7.534µs
Starting deploy...
kubectl client version: 1.14
deployment.apps/node-hello-world created
Deploy complete in 730.465318ms
Watching for changes every 1s...
time="2019-05-08T16:12:34-07:00" level=info msg="Stream logs from pod: node-hello-world-77977d955b-ldpwz container: server"

Forwarding container server to local port 8082.
Port Forwarding node-hello-world-77977d955b-ldpwz/server 8080 -> 8082
[node-hello-world-77977d955b-ldpwz server] Debugger listening on ws://127.0.0.1:9229/f410b1fa-ce94-4d76-9f37-72f394cc5a41
[node-hello-world-77977d955b-ldpwz server] For help see https://nodejs.org/en/docs/inspector
[node-hello-world-77977d955b-ldpwz server] App listening on port 8080
[node-hello-world-77977d955b-ldpwz server] Press Ctrl+C to quit.

**Comment by quoctruong** [comment]
@pratikvarma That means the new changes are deployed, which is what you are looking for right?

**Comment by pratikvarma** [comment]
@quoctruong it seems to be changing ports with every deployment. Is that expected?
Also the problem is there is no way for me to `stop` the continuous deployment. I do not see an option from the status bar `Cloud Code` section to stop the deployment.

**Comment by quoctruong** [comment]
@pratikvarma The port that it used to port forward to locally is expected to change. Can you give me more details about the extension version and your operating system?

**Comment by pratikvarma** [comment]
@quoctruong 
macOS mojave: 10.14.3
VSCode: 1.33.1
Cloud Code: 0.0.8

**Comment by sujit-kamireddy** [comment]
It seems to me that there is a bug where we are incorrectly reverting the status bar to "Cloud Code" even though the continuously deployment is in progress. Workaround to get out of this situation is to kill the skaffold process from the terminal.

@pratikvarma , do you have a consistent repro of this?
We were unable to repro this issue in Windows. @quoctruong is working to repro this in Mac.

**Comment by pratikvarma** [comment]
@sujit-kamireddy my colleague on windows does not have this issue either. For me, the `stop continuous deployment` option has never shown up on the status bar. For now I am just doing deploy every time i need to.

**Comment by sujit-kamireddy** [comment]
Thank you for the update @pratikvarma . We will keep you posted on our findings.

**Comment by pratikvarma** [comment]
@sujit-kamireddy Can you tell me how to kill the skaffold process from the terminal? 
When i do `ps -ef | grep skaffold`, i am not seeing any process. 
But even after deleting the pod using `kubectl`, it seems to be coming back up again so it seems the continuous deployment is taking over.

**Comment by sujit-kamireddy** [comment]
I think there are 2 things here.
1. If the Cloud Code Continuous Deploy command is indeed running, there should be a skaffold process running. (ps -ef | grep skaffold is working as expected for me)
2. If you have used a k8s deployment resource to deploy the application to a k8s cluster, k8s automatically brings up a new pod (to ensure the number of corresponding pods matches with the replica count in the deployment resource) when a pod is removed. This has nothing to do with the skaffold. https://kubernetes.io/docs/concepts/workloads/controllers/deployment/

**Comment by sujit-kamireddy** [comment]
In the latest release (v1.1.1), we have deprecated the commands 'Cloud Code: Deploy' and 'Cloud Code: Continuous Deploy' in favor of a new command 'Cloud Code: Run on Kubernetes'.

This new command uses the vscode debugger infra to run an app. You can simply click on the "Red Square button in the debug tool window" to stop your deployment.

![image](https://user-images.githubusercontent.com/40217533/73887203-f2a05000-481f-11ea-99e0-1a33d5615811.png)
