### ISSUE TITLE
Bug report 

### ISSUE THREAD

**Issue by ThagodDynasty** [GoogleCloudPlatform/cloud-code-vscode#826]
**Environment**:
*(Hint: "Report Extension Issue on Github" command will fill these out for you.)*

**Version information**

Cloud Code Extension version:

VSCode version:

OS: 

Cloud SDK:

Skaffold: 

Kubectl:

**Description**:

**Repro step**:

**Comment by j-windsor** [comment]
Please reopen with more info.
