### ISSUE TITLE
billing acc

### ISSUE THREAD

**Issue by Mlmolefe2** [GoogleCloudPlatform/cloud-code-vscode#827]
Type: <b>Bug</b>

*Context*
- Managed Dependencies: on
- Cloud SDK Version: 438.0.0
- Skaffold Version: v2.6.0
- minikube Version: 1.30.1

Extension version: 1.22.0
VS Code version: Code - Insiders 1.81.0-insider (dc142e4cd111b8f370d0549d8c207df7de55facd, 2023-07-14T10:43:06.630Z)
OS version: Windows_NT x64 10.0.25393
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz (8 x 1190)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.75GB (0.57GB free)|
|Process Argv|C:\\Users\\MASAM_~1\\AppData\\Local\\Temp\\MicrosoftEdgeDownloads\\17b82f88-249d-4433-9733-99cd8e99d45f\\code-1.80.1-1689183644.el7.x86_64.rpm --crash-reporter-id a1b89f11-fb35-47f7-a2ca-9912213a7608|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
pylantcb52:30590116
pyind779:30611226
pythonsymbol12:30651887
showlangstatbar:30737417
pythonms35:30671666
24365598:30687740
pythonfmttext:30716741
pythoncmvfstr:30726892
fixshowwlkth:30771523
showindicator:30766888
pythongtdpath:30726887
bgfeh915:30780428
gsofb:30778559
pythonnosmt12:30779711
pythonidxpt:30768918
pythondjangots:30768917
pythonnoceb:30776497
copilotsettingt:30767686
e537b577:30772214
h0f32768:30779712
synctok:30783813
dsvsc013:30777762
dsvsc014:30777825
diffeditorv1:30786205

```

</details>

**Comment by j-windsor** [comment]
Please reopen with more information.
