### ISSUE TITLE
Enter key not working properly

### ISSUE THREAD

**Issue by guilherme-turing** [GoogleCloudPlatform/cloud-code-vscode#829]
The "Enter" key doesn't work. I have to press "Shift + Enter" to add a new line.

Version: 1.77.3
Commit: 2f8bf8c44a820ca826b591c5c6e987d2048b8e7d
User Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0
Embedder: unknown

**Comment by davidponder** [comment]
Heyo!

What part of the extension are you interacting with?

**Comment by guilherme-turing** [comment]
@davidponder I just logged in today again and it's working fine :sweat_smile: . I'll just close the issue
