### ISSUE TITLE
Cancelling switching to unresponsive kubecontext 

### ISSUE THREAD

**Issue by balopat** [GoogleCloudPlatform/cloud-code-vscode#83]
**Environment**:
Extension version: 0.0.7
VSCode version: 1.32.3
OS: linux

**Description**:

I tend to create and delete GKE clusters, thus I have a bunch of stale kubecontext definitions. When I click into a non-existing one, VSCode waits until the connection times out that can take a long time. It would be great to have the ability to cancel it - or just maybe connect with a shorter timeout? 

![image](https://user-images.githubusercontent.com/635073/56244674-4bfd7f80-6052-11e9-8323-6ac4f68c1e8f.png)

**Repro step**:

Switch to a kubecontext that points to a non-existent GKE cluster.

**Comment by sujit-kamireddy** [comment]
This issue has been fixed in the latest release 0.0.10. Please try it out.

As always, please keep issues coming our way.
