### ISSUE TITLE
Extension stopped working with Rancher Desktop in version 1.22.0

### ISSUE THREAD

**Issue by gaeshi** [GoogleCloudPlatform/cloud-code-vscode#830]
**Environment**:
*(Hint: "Report Extension Issue on Github" command will fill these out for you.)*

**Version information**

Cloud Code Extension version: 1.22.0 (July 2023)

VSCode version: 1.80.1 (system setup)
```
Version: 1.80.1 (system setup)
Commit: 74f6148eb9ea00507ec113ec51c489d6ffb4b771
Date: 2023-07-12T17:22:07.651Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045
```

- Cloud SDK Version: 439.0.0 (Upgraded from version 437.0.1, but still no luck.)
- Skaffold Version: v2.6.0
- minikube Version: 1.30.1

**Description**:

Cloud Code extension stopped working with Rancher Desktop in version 1.22.0 (July 2023).

**Repro step**:

Open a project with Apigee X proxies in VS Code.
After a few seconds, you will wee these error messages in OUTPUT tab.

```
07/19/2023 10:37 AM EMULATOR ERROR Error: Cannot find path to Docker Desktop.exe in registry, make sure docker is installed propertly.
07/19/2023 10:37 AM EMULATOR ERROR Error: Cannot find path to Docker Desktop.exe in registry, make sure docker is installed propertly.
```

Rancher Desktop can be used fine after rolling back to Version 1.21.8 (June 2023).

**Comment by glouischandra** [comment]
thanks for the bug report @gaeshi we're taking a look.

**Comment by progvb** [comment]
I've tried updating from v1.21.8 to the latest version (v2.1.1), but it still seems to have some problems with Docker. It doesn't show any debug info anymore though.

![image](https://github.com/GoogleCloudPlatform/cloud-code-vscode/assets/45557691/9a066788-5670-4d2d-bb56-eb1e6eeae821)

**Comment by progvb** [comment]
This exact problem still persists in extension version 2.3.0.

**Comment by ametelski** [comment]
This is still a problem in v.2.11.1
![image](https://github.com/GoogleCloudPlatform/cloud-code-vscode/assets/17239648/57c6744b-c6a7-4dc4-af89-cf8c9939f38d)
