### ISSUE TITLE
Apigee Creating API Proxy from Open API Spec

### ISSUE THREAD

**Issue by Muthukkannan** [GoogleCloudPlatform/cloud-code-vscode#836]
**Use case**
What are you trying to do that our extension doesn't let you?
I want to create API proxy from API spec (Open API Spec) document, as we do in the UI.  This feature is not available in the current version of the plugin
**Feature**
What would help?
This will help in seamless movement from design to development.  Otherwise would need to use the Apigee UI to create the proxy, export them and add them in the local repository, check in those and continue with the rest of the development of API.

**Comment by shirishtrivikr** [comment]
@Muthukkannan 
Thank you for feature request.  We will get back to you with more information soon.

**Comment by shirishtrivikr** [comment]
you should be able to create the proxy from an openapi 3 spec from the vscode now.
