### ISSUE TITLE
Resources not found: Unexpected end of JSON Input

### ISSUE THREAD

**Issue by balopat** [GoogleCloudPlatform/cloud-code-vscode#84]
**Environment**:
Extension version: 0.0.7
VSCode version: 1.32.3
OS: linux

**Description**:

In the cluster explorer, when opening certain items in the `kube-system` namespace resulted in an error seemingly: 

![image](https://user-images.githubusercontent.com/635073/56244120-012f3800-6051-11e9-890a-940adfc88286.png)

After `refresh` this went away and the nodes actually loaded.

**Repro step**:

I couldn't reproduce this even via uninstalling/reinstalling Cloud Code - but this happened right after I installed the plugin - i.e. there was no previous state/cache, anything available for Cloud Code to work with. Maybe this is limited to a first time error? Or it is just a spurious error that sometimes happens on connection errors and Cloud Code should just retry?

**Comment by redborian** [comment]
@balopat Which version of `kubectl` and `gcloud` are you using?

**Comment by quoctruong** [comment]
@balopat Since we couldn't repro this issue with newer releases. I'll close this as resolved. Feel free to open it if it happens again.
