### ISSUE TITLE
[Question] How to connect Google Cloud Run Emulator to serverless vpc access connector?

### ISSUE THREAD

**Issue by Donlouigi** [GoogleCloudPlatform/cloud-code-vscode#845]
Hi,

Is it possible to connect to Cloud Run Emulator to a serverless vpc access connector? 
If yes, how do I do it?
I tried it with the launch.json file and added something like this, but wihtout success:
```
"service":{
 "name": "cloud-run",
 "containerPort": 8080,
 "vpc-access-egress": "all-traffic",
 "vpc-access-connector": "projects/{project-id}/locations/europe-west3/connectors/my-connector",
...
}

```
Best regards

**Comment by j-windsor** [comment]
Hello! Unfortunately this is not possible at the moment. We will take this in as a feature request. Thanks!
