### ISSUE TITLE
Deployment with 1 replica running 2 pods

### ISSUE THREAD

**Issue by sunnygoel8** [GoogleCloudPlatform/cloud-code-vscode#85]
**Environment**:

Extension version: 0.0.7
VSCode version: 1.33.1
OS:  Windows 10 Enterprise

**Description**: Deployed a `Hello world` Node.js application on GKE using Cloud code extension in VS code IDE. Kubernetes deployment had `replicas: 1` but post deploying the application, I see 2/2 when issued `kubectl get pods` command. 

`PS C:\Users\sunny.goel\cloudcode-projects\nodejs-hello-world-1> kubectl get deployments`
`NAME               DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE`
`node-hello-world   1         1         1            1           59m`

`PS C:\Users\sunny.goel\cloudcode-projects\nodejs-hello-world-1> kubectl get pods`
`NAME                                READY     STATUS    RESTARTS   AGE`
`node-hello-world-548f8bb9cc-vmtbv   2/2       Running   0          48m`

**Repro step**: Deploy any Node.js app on GKE with `replicas:1` in Kubernetes deployment file and deploy the application using Cloud code extension in VS code IDE.

**Comment by sunnygoel8** [comment]
Can someone help me with this issue ?

**Comment by redborian** [comment]
Thanks for reporting the issue @sunnygoel8! I will look into this issue and update this thread.

**Comment by sunnygoel8** [comment]
Thanks @redborian

**Comment by redborian** [comment]
In `node-hello-world-548f8bb9cc-vmtbv 2/2 Running 0 48m`, `2/2` means there are two containers running inside the pod.
I just tried out the nodejs-hello-world sample and got this output:
`node-hello-world-7d9ffd565c-526cs            1/1       Running   0          1m`

You might be having local modifications to your pod template. Can you try again by creating a new application using nodejs-hello-world template and deploying it?

**Comment by sunnygoel8** [comment]
@redborian , My bad. Actually while creating the GKE cluster using template in VS code, I enabled "Run Istio" checkbox as well. And 2nd container in the pod doesn't belong to helloworld node.js app. 

it's **istio-proxy**. Thanks for your response.
