### ISSUE TITLE
Make managed dependecy optional

### ISSUE THREAD

**Issue by bhack** [GoogleCloudPlatform/cloud-code-vscode#856]
**Use case**
With the managed option I want to have some components excluded (e.g. minikube) 

**Feature**
I think it could often happen that you could not need `minikube` if you are working on GKE without it isrequired to switch to the unmanaged setup.

**Comment by j-windsor** [comment]
Thanks for the request! Managed dependencies at this point is a convenience option that we are looking to reduce the usage for. We have no plans to develop the feature further.

**Comment by bhack** [comment]
So what alternative are you planning to the managed dependencies?
