### ISSUE TITLE
Google Client Library manager support in VS Code

### ISSUE THREAD

**Issue by sunnygoel8** [GoogleCloudPlatform/cloud-code-vscode#86]
**Use case**
We would like to integrate with other API's such as cloud storage, cloud translation etc. in k8s application. And may be even with Stackdriver APIs in some cases. If this support is available in IDE, we don't even need to manually enable the APIs either using cloud console or CLI 

**Feature**
Google cloud Library support in VS code, similar to IntelliJ IDE

**Comment by iantalarico** [comment]
@sunnygoel8 We don't have an exact date for this but it is in our roadmap!

**Comment by sunnygoel8** [comment]
Thanks @iantalarico . and are following features as well on the roadmap for VS Code ?

- Google App Engine Support
- Cloud Storage Browser support for viewing buckets and blobs
- Stackdriver snapshot based Production workload debugging

**Comment by iantalarico** [comment]
We are planning to publish a more detailed roadmap here soon.

In the mean time:
> Google App Engine Support
> Cloud Storage Browser support for viewing buckets and blobs
These aren't on any explicit roadmaps but this is something we will look into as we look at feature parity between VS Code and IntelliJ

> Stackdriver snapshot based Production workload debugging
This is on the roadmap but we don't have an exact date for this.

**Comment by sunnygoel8** [comment]
@iantalarico , Thanks for the quick response.

**Comment by kschaab** [comment]
This feature is planned for our January release.

**Comment by jmah-cc** [comment]
This functionality is available in v1.1.0
