### ISSUE TITLE
Java Callout with Apigee Emulator

### ISSUE THREAD

**Issue by varuntit101** [GoogleCloudPlatform/cloud-code-vscode#860]
I am trying to get the sample java callout with properties (from the github apigee-platform-samples/doc-samples/java-properties) working in the vscode Apigee emulator.

However when I try to run a sample proxy using the above within an Emulator within VSCode, I experience the following "No appropriate constructor found in JavaCallout class com.apigeesample.JavaProperties" error when deploying the API proxy to a sample environment:

11/03/2023 1:36 AM EMULATOR INFO Deploying environment eval, to Container apigee (1.10.3)
11/03/2023 1:36 AM EMULATOR ERROR Code   : steps.javacallout.NoAppropriateConstructor
11/03/2023 1:36 AM EMULATOR ERROR Message: No appropriate constructor found in JavaCallout class

**Version information**

Cloud Code Extension version: 2.1.0

VSCode version: 1.83.1

OS: Windows 11

Cloud SDK: 

Skaffold: 

Kubectl:

**Description**:

**Repro step**:

**Comment by shirishtrivikr** [comment]
@varuntit101 Thanks for reporting the issue.  

I was able to reproduce the issue and analyzing further

**Comment by shirishtrivikr** [comment]
I have narrowed down the problem in the emulator and will proceed towards a fix.

**Comment by shirishtrivikr** [comment]
The fix is now available in the latest emulator releases 1.11.0 and above
