### ISSUE TITLE
Auto logout issue, always need to re-login

### ISSUE THREAD

**Issue by khewdev** [GoogleCloudPlatform/cloud-code-vscode#869]
**Environment**: Mac M1 Pro

**Version information**

Cloud Code Extension version: v2.1.1

VSCode version: Version: 1.84.2 (Universal)

OS: macOS Monterey

**Comment by glouischandra** [comment]
Hi @khewdev we're rolling a fix in the next release for Cloud Code, should land around next week (2.2.0).

Once its up, please see if login sticks and if you're still seeing the issue, file a feedback using the IDE feedback button:
![image](https://github.com/GoogleCloudPlatform/cloud-code-vscode/assets/3677364/e0b20b56-4242-4d15-aece-dc2b44c4f9bc)

Please ensure "Send Cloud Code logs" is also checked 
![image](https://github.com/GoogleCloudPlatform/cloud-code-vscode/assets/3677364/fb6871e4-06bc-42dc-bc6b-a019ef4e04f0)

Thanks!

**Comment by khewdev** [comment]
> Hi @khewdev we're rolling a fix in the next release for Cloud Code, should land around next week (2.2.0).
> 
> Once its up, please see if login sticks and if you're still seeing the issue, file a feedback using the IDE feedback button: ![image](https://private-user-images.githubusercontent.com/3677364/288552750-e0b20b56-4242-4d15-aece-dc2b44c4f9bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxNDU4NzMsIm5iZiI6MTcwMjE0NTU3MywicGF0aCI6Ii8zNjc3MzY0LzI4ODU1Mjc1MC1lMGIyMGI1Ni00MjQyLTRkMTUtYWVjZS1kYzJiNDRjNGY5YmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDlUMTgxMjUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzUyOGE1YTBkY2IzMmEyOWU0YmUzZTJlOWExMWZkOWUwNTdkMTM3NzJjMjA0MDY4YWU4NDg0ZjdiZGNkOTVjMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.h8HiFoTQ9zXmrWa_3KZ_2cTkNJzsGD57TsMSrbPCCKA)
> 
> Please ensure "Send Cloud Code logs" is also checked ![image](https://private-user-images.githubusercontent.com/3677364/288552818-fb6871e4-06bc-42dc-bc6b-a019ef4e04f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxNDU4NzMsIm5iZiI6MTcwMjE0NTU3MywicGF0aCI6Ii8zNjc3MzY0LzI4ODU1MjgxOC1mYjY4NzFlNC0wNmJjLTQyZGMtYmM2Yi1hMDE5ZWY0ZTA0ZjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDlUMTgxMjUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGFhZTUxNDMyOWJkZTY0MzhiOGUxYTAwMDFmOWFkMzg5ODQ4ZjliYjljMzMzOTJmYzkxZDM5ZjY3YmU0MjRkYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.F6LKHx-T8mZhmjHSf--RrXsXq7eiEzrOPnsvOXGpqw0)
> 
> Thanks!

Thanks a lot for the updates!

**Comment by taisph** [comment]
This has gotten real bad lately (v2.2.1). I've sent feedback via VScode.

**Comment by glouischandra** [comment]
Thank you @taisph for the feedback submission, we received it and investigating further. Apologies for the inconvenience.

**Comment by glouischandra** [comment]
Hi @taisph We're testing a potential fix in our Insiders channel, if you would like to test it too you can switch to that channel using "cloudcode.updateChannel": "Insiders" in settings.json. 

The version that we're looking for is 2.3.0-insiders.1
![image](https://github.com/GoogleCloudPlatform/cloud-code-vscode/assets/3677364/a5e9d120-a503-45d3-bc34-297401a8a9f4)

And please file further feedback with the logs if the problem persist.

**Comment by taisph** [comment]
> Hi @taisph We're testing a potential fix in our Insiders channel, if you would like to test it too you can switch to that channel using "cloudcode.updateChannel": "Insiders" in settings.json.
> 
> The version that we're looking for is 2.3.0-insiders.1
> And please file further feedback with the logs if the problem persist.

Just a follow-up: I have been on the insiders version since shortly after your comment. Currently on v2.3.0-insiders.3. I still get signed out once or twice a day and I am not sure what to expect here, but it is a lot better than the release version.

**Comment by glouischandra** [comment]
Hi @taisph can you submit IDE feedback with Duet & Cloud Code logs attached? Ideally its only once per day login or less.

**Comment by glouischandra** [comment]
Hi @taisph we've been testing the 2.2.3 releases and found that the auto logout issue due to Context Cancelled issue has been fixed. Going to close this work item for now. If you still see the issue, please feel free to reopen and submit in IDE feedback with the logs.
