### ISSUE TITLE
Duet AI works for 1 prompt, then fails

### ISSUE THREAD

**Issue by aperepel** [GoogleCloudPlatform/cloud-code-vscode#870]
**Environment**:
*(Hint: "Report Extension Issue on Github" command will fill these out for you.)*

**Version information**

Cloud Code Extension version: 2.2.1

VSCode version:

OS: 

Cloud SDK:

Skaffold: 

Kubectl:

**Description**:
Set up Duet AI in a new cloud project, added permissions. After a full reset, the Duet AI chat works 1 time, then every prompt returns with "Sorry can't help you with that". No errors in the Duet logs.

Performed a Duet AI set up in IntellIJ and things work consistently. Something broke in 12/15/23 release for VSCode

**Repro step**:

**Comment by Slava-Astrolog** [comment]
this is how it works now it's normal.


пн, 18 дек. 2023 г., 3:38 Andrew Grande ***@***.***>:

**Comment by aperepel** [comment]
I'm sorry, I don't follow. Same GCP project setup from JetBrains IDE worked on the same prompts multiple times. Is there anything going on with the Duet API I'm not aware of?

**Comment by maxrandolph** [comment]
Hi @aperepel, could you repro this on your end and then file a bug with the following flow:

![image](https://github.com/GoogleCloudPlatform/cloud-code-vscode/assets/9055234/8e102ba4-6813-46b1-b6bb-78e9dd16bbf3)

This will enable us to get a bit more diagnostic info around what's happening here.

Please ensure the following settings are checked prior to submission:

<img width="382" alt="image" src="https://github.com/GoogleCloudPlatform/cloud-code-vscode/assets/9055234/93e43397-9975-4277-a4c6-b7480cf4af01">

Thanks!

**Comment by kschaab** [comment]
This is obsolete.
