### ISSUE TITLE
Bank of America Checking - Advantage - Safe - Balance  - account _ 4815 - 8203 - 7832 - 6191_  -routing - ACH 121000358 - number - 3251- 8641 - 0228 @ Project NAME Vaulted - Aleph ID Numbers # 399400Tru Connect Cloud C7 Mobile 1 + (213) 431- 9626  -Project number 581534159925 - SSA#617-09-3845.iam.Gserviceaccount.com

### ISSUE THREAD

**Issue by Peter-Miranda** [GoogleCloudPlatform/cloud-code-vscode#871]
**Environment**:
*(Hint: "Report Extension Issue on Github" command will fill these out for you.)*

**Version information**

Cloud Code Extension version:

VSCode version:

OS: 

Cloud SDK:

Skaffold: 

Kubectl:

**Description**:

**Repro step**:

**Comment by displague** [comment]
I don't know how I got to this issue - `github.com/goo" browser autocompleted to this.

Was this issue description line used for sensitive data scanning or is this a problem? I feel bad for someone somewhere. How about a comment of reassurance that this was spam, or scanning, or addressed.

**Comment by glouischandra** [comment]
It has been reported as spam
