### ISSUE TITLE
[Cloud Run] "Login to Google Cloud" Button does nothing

### ISSUE THREAD

**Issue by davitykale** [GoogleCloudPlatform/cloud-code-vscode#872]
**Environment**:
*(Hint: "Report Extension Issue on Github" command will fill these out for you.)*

**Version information**

Cloud Code Extension version: v2.2.1

VSCode version: 1.86.0-insider

OS: Mac OS Sonoma 14.3

Cloud SDK: Google Cloud SDK 458.0.1

Skaffold: 2.9.0

Kubectl: 1.27.8

**Description**:
When I navigate to the Cloud Code tab within VSCode, it asks me to "Login to Google Cloud", but clicking the button does nothing. I am logged in via `gcloud` but this seems to have no effect on the tab.

**Repro step**:

<img width="254" alt="Screenshot 2024-01-04 at 3 46 34 PM" src="https://github.com/GoogleCloudPlatform/cloud-code-vscode/assets/84422567/0116078b-3e06-48ee-aec9-280f9d2331c8">

- Navigate to the Cloud Code extension tab
- Click "Login to Google Cloud"
- See that nothing happens

**Comment by kirlosik** [comment]
I have the same issue

When I click 'refresh' or 'create' I get the following error:
```
Error running command cloudcode.refreshSecretsExplorer: command 'cloudcode.refreshSecretsExplorer' not found. This is likely caused by the extension that contributes cloudcode.refreshSecretsExplorer.
```

I also tried to roll back to previous versions but the error persists.

<img width="1492" alt="Screen Shot 2024-01-07 at 3 48 54 pm" src="https://github.com/GoogleCloudPlatform/cloud-code-vscode/assets/97167558/fb6b8314-128a-4dd8-8023-ac2720ceb650">

**Comment by j-windsor** [comment]
It looks like your "Help and Feedback" explorer says "There is no data provider registered that...", which signals to me that the extension did not activate correctly. Can you send logs from the "Cloud Code" output channel to help us debug?

**Comment by davitykale** [comment]
I don't actually see an output channel for Cloud Code. I only see "Google Cloud CLI Installation", which is blank.

For what it's worth, I get the following error when I try to refresh:
`Error running command cloudcode.refreshCloudRunExplorer: command 'cloudcode.refreshCloudRunExplorer' not found. This is likely caused by the extension that contributes cloudcode.refreshCloudRunExplorer.`

**Comment by j-windsor** [comment]
Hmm ok. If you do not see an output channel for Cloud Code, something is very wrong. It is likely the extension did not install correctly. Can you first reinstall the extension? If that doesn't work, set the `cloudcode.verboseLogging` VS Code setting to `true` and try to see the Cloud Code logs again.

**Comment by hwdtw** [comment]
check the content of credentials file. 
C:\Users\<your name>\AppData\Local\cloud-code\vscode\auth\credentials.json

remove null and error string, then restart vscode.

**Comment by galz10** [comment]
Please send a report through Vscode so we can see the logs.

**Comment by simonebracaloni** [comment]
I have the same problem 

**Version information**

Cloud Code Extension version: v2.11.0

VSCode: 
    Version: 1.89.1 (Universal)
    Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
    Date: 2024-05-07T05:14:24.611Z
    Electron: 28.2.8
    ElectronBuildId: 27744544
    Chromium: 120.0.6099.291
    Node.js: 18.18.2
    V8: 12.0.267.19-electron.0
    OS: Darwin x64 23.5.0

OS: Mac OS Sonoma 14.5

Cloud SDK: Google Cloud SDK 464.0.0



Everthing I see in the log is the following, even afger setting cloudcode.verboseLogging to true

```
[31/05/2024, 10:40:14] Logging enabled
[31/05/2024, 10:40:14] Cloud Code version 2.11.0
[31/05/2024, 10:40:14] Version detail: 637016144 built on 2024-05-28T20:35:17.644Z
```

I found this in the "Extension Host" Log

```
2024-05-31 10:40:15.136 [error] Activating extension googlecloudtools.cloudcode failed due to an error:
2024-05-31 10:40:15.136 [error] SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at t.OAuthProvider.<anonymous> (/Users/simonebracaloni/.vscode/extensions/googlecloudtools.cloudcode-2.11.0/dist/extension.js:14:10764871)
    at Generator.next (<anonymous>)
    at i (/Users/simonebracaloni/.vscode/extensions/googlecloudtools.cloudcode-2.11.0/dist/extension.js:14:10757078)
```

**Comment by Keepertje** [comment]
I have the same error in the "Extension Host" log

**Comment by maxrandolph** [comment]
This appears to have the same cause as https://github.com/GoogleCloudPlatform/cloud-code-vscode/issues/908. A fix for this issue should be making it into our next release.
