### ISSUE TITLE
Cannot login to Duet AI from vscode in WSL

### ISSUE THREAD

**Issue by avila-m-6** [GoogleCloudPlatform/cloud-code-vscode#875]
**Environment**:

**Version information**

Cloud Code Extension version: v2.2.2

VSCode version: 1.82.2 (user)

OS: Windows - WSL Ubuntu 22.04

Cloud SDK:

[1/18/2024, 11:21:45 AM] Cloud Code version 2.2.1
[1/18/2024, 11:21:45 AM] Version detail: 591077733 built on 2023-12-15T00:31:31.883Z

Skaffold: -

Kubectl: -

**Description**:
Cannot login to Duet AI with VS Code Remote WSL connection. I do have access because it works on windows vs code.

![image](https://github.com/GoogleCloudPlatform/cloud-code-vscode/assets/75078878/474b59f7-0cb4-4b3b-9293-92416c230883)

**Repro step**:

1. Open Remote VS Code
2. Sign in to Duet AI
3. Get error screen

**Comment by sripasg** [comment]
That is unexpected. We should investigte. Can you please send logs from the "Cloud Code" output channel to help us debug?

**Comment by avila-m-6** [comment]
Sorry I'm not familiar with the process. Where can I get those?

**Comment by sripasg** [comment]
Sure, no worries.

Can you please  repro this on your end and then file a bug with the following flow:
![image](https://github.com/GoogleCloudPlatform/cloud-code-vscode/assets/111310667/debfb508-8e79-4cd5-a6cd-d1e27a88597e)

This will enable us to get a bit more diagnostic info around what's happening here.
Please ensure the following settings are checked prior to submission:

![image](https://github.com/GoogleCloudPlatform/cloud-code-vscode/assets/111310667/a9943ed0-f06e-44ec-bd45-e8f060eb4c12)

Thank you.

**Comment by avila-m-6** [comment]
I'm getting this error:

![image](https://github.com/GoogleCloudPlatform/cloud-code-vscode/assets/75078878/9a532508-c99f-4986-b43e-44b0c7bf351e)

I do use a proxy sometimes, but it's not that host nor port. I also enable/disable it when required, so no default proxy is setup in any shell. That looks like some default config from vscode?

**Comment by avila-m-6** [comment]
Also I just sent the bug report using the feedback feature:

![image](https://github.com/GoogleCloudPlatform/cloud-code-vscode/assets/75078878/248a99a7-554d-4b86-8871-563755d0b5d2)

**Comment by maxrandolph** [comment]
Hi @avila-m-6, can you try with the VS Code setting "Proxy Support" both on/off and see if there is any change? It may also be overridden in your remote/WSL settings:

![image](https://github.com/GoogleCloudPlatform/cloud-code-vscode/assets/9055234/87e519ee-f16f-4f91-9123-d2e67c751e1d)

**Comment by avila-m-6** [comment]
It worked. Previous value was on `override` by default

![image](https://github.com/GoogleCloudPlatform/cloud-code-vscode/assets/75078878/d63df338-200e-44b1-8ba6-709ceec99dfe)

Thank you!
