### ISSUE TITLE
Question about Cloud Code extension from "remoted" instance

### ISSUE THREAD

**Issue by snassimr** [GoogleCloudPlatform/cloud-code-vscode#876]
I did install of Remote SSH  and Cloud Code extensions . I am working with SSH on on of GCP projects . I guess Cloud Code extension has been designed to work from local . Any way to run GCP Shell from Remote SSH on GCP ?

![image](https://github.com/GoogleCloudPlatform/cloud-code-vscode/assets/6830626/a37b2cd0-0627-47c4-a775-483cf722213c)

**Comment by maxrandolph** [comment]
Hi @snassimr, what have you tried so far? Are you encountering a specific issue? Could you please describe exactly what steps you've taken and where you encounter issues?

**Comment by snassimr** [comment]
I am ok . Actually , shell is available from terminal. Thanks
