### ISSUE TITLE
Knative, not KNative

### ISSUE THREAD

**Issue by steren** [GoogleCloudPlatform/cloud-code-vscode#88]
Knative is lower case n.

![image](https://user-images.githubusercontent.com/360895/56379433-943caf00-61c4-11e9-8b09-26359886cbb9.png)

**Comment by steren** [comment]
CC @rgregg

**Comment by redborian** [comment]
Is this in the welcome page?

**Comment by steren** [comment]
Yes

**Comment by redborian** [comment]
I will keep this open until next release

**Comment by redborian** [comment]
Fixed in release v0.0.8
