### ISSUE TITLE
Cloud Code Extension: Default XML Policy Template Not Generated When Creating New Policy Files

### ISSUE THREAD

**Issue by kvrao33** [GoogleCloudPlatform/cloud-code-vscode#880]
**Version information**

- Cloud Code Extension version: V2.3.0
- VSCode version: 1.86.0
- OS: Ubuntu

**Description**: 
When attempting to create a new policy using the Cloud Code extension, the expected behavior is to generate a new XML file with the default template for the selected policy. However, the issue observed is that a blank XML file is created instead of the expected default XML template for the policy.

**Repro steps**:

1. Open Visual Studio Code.
2. Ensure that the Cloud Code extension is installed and activated.
3. Navigate to the desired directory in the Explorer view.
4. Right-click in the Explorer view or within the editor area to open the context menu.
5. Select the option to create a new policy file.
6. Observe that a new XML file is created, but it is blank instead of containing the default XML template for the selected policy.

**Expected behavior**: 
When creating a new policy file using the Cloud Code extension, the default XML template for the selected policy should be generated automatically in the newly created file.

**Comment by shirishtrivikr** [comment]
This has been fixed in the latest version.
