### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by emagnu** [GoogleCloudPlatform/cloud-code-vscode#881]
- Issue Type: `Performance`
- Extension Name: `cloudcode`
- Extension Version: `2.3.0`
- OS Version: `Linux x64 6.5.0-17-generic`
- VS Code version: `1.86.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///tmp/googlecloudtools.cloudcode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by galz10** [comment]
Please reopen with the file attached.
