### ISSUE TITLE
Unable to load project using Cloud Code in VS Code

### ISSUE THREAD

**Issue by pigaur** [GoogleCloudPlatform/cloud-code-vscode#882]
**Environment**:
*(Hint: "Report Extension Issue on Github" command will fill these out for you.)*

**Version information**

Cloud Code Extension version: v2.4.0

VSCode version: 1.86.2

OS: MacOS

Cloud SDK:

Skaffold: 

Kubectl:

**Description**: I am using Cloud Code extension for VS Code. But it's been a while since it allowed me to select a project and just keep checking for the projects. 

**Repro step**: Install Cloud Code extension for VS Code and try to select a project after signing in.

<img width="835" alt="image" src="https://github.com/GoogleCloudPlatform/cloud-code-vscode/assets/107780440/02cf7f7b-611a-4316-b2a1-611208782a34">

**Comment by j-windsor** [comment]
Closing this out. This is a one off issue only for google.com users who have an absurd number of projects.
