### ISSUE TITLE
Google cloud disabling git

### ISSUE THREAD

**Issue by ryunosuke21** [GoogleCloudPlatform/cloud-code-vscode#883]
Type: <b>Bug</b>

Google cloud for some reason disabled GIT when working on a private Gitlab repo. 

Extension version: 2.4.0
VS Code version: Code 1.87.0 (019f4d1419fbc8219a181fab7892ebccf7ee29a2, 2024-02-27T23:41:44.469Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|11.79GB (2.57GB free)|
|Process Argv|--crash-reporter-id 003eb927-9875-459a-9605-6c5ccad59cff|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
d34g3935:30971562
edj9j583:30969295
fegfb526:30973843
bg6jg535:30958357
dsvsc020:30973508

```

</details>

**Comment by sripasg** [comment]
What makes you think Cloud Code is causing your issue ?

**Comment by ryunosuke21** [comment]
Sorry about it, disregard it. I was trying out a thing from VS Code about an extension restarting on its own. It was the google cloud one trying to look for my cloud stuff but not being able to find them. 

I accidentally hit the "Send Report" thing and I thought it would send it to Microsoft but not here. Sorry x1000
