### ISSUE TITLE
This extension has disabled emmet

### ISSUE THREAD

**Issue by Tudor1415** [GoogleCloudPlatform/cloud-code-vscode#884]
Type: <b>Bug</b>

I really don't know,  I opened vs code and emmet didn't work. I did extension bisect and once I have disabled the google cloud code extension, emmet worked.

Extension version: 2.4.0
VS Code version: Code 1.87.0 (019f4d1419fbc8219a181fab7892ebccf7ee29a2, 2024-02-27T23:41:44.469Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (6.04GB free)|
|Process Argv|C:\\Users\\raduo\\Documents\\GitHub\\pagadastar --crash-reporter-id 4ae9ebc7-c900-42f9-9ce9-90c963b2ea39|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
vscaac:30438847
c4g48928:30535728
azure-dev_surveyonecf:30548226
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30968133
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
pydisww2:30959801
d34g3935:30971562
edj9j583:30969295
a89i1917:30973842
e3gdj431:30958358
78248357:30976999
ccp1r3:30958155
dsvsc020:30976470
jchc7451:30973076

```

</details>

**Comment by sripasg** [comment]
Can you try repro'ing this by disabling just Duet AI part of the  Cloud Code plugin ?
Here's how to do it :
Navigate to Settings by clicking the Settings Icon on the left side bar and Choosing `Settings`
Search for `Duet AI` in the Settings Search
Unclick - `Enable Duet AI` setting
Reload Developer Window

Now try to use the built in Emmet functionality to see if it's still blocked.

**Comment by glouischandra** [comment]
hi @Tudor1415 Can you try sri's suggestion above? Please feel free to reopen this ticket if you have more information.
