### ISSUE TITLE
Cluster creation form should say "Cloud Run on GKE"

### ISSUE THREAD

**Issue by steren** [GoogleCloudPlatform/cloud-code-vscode#89]
The Cluster creation form has an option that say: "Enable Cloud Run"
It should say "Enable Cloud Run on GKE"

Indeed, "Cloud Run" designates by default the fully managed version of Cloud Run. To talk about the add-on that can be installed inside GKE, you must use "Cloud Run on GKE"

![image](https://user-images.githubusercontent.com/360895/56383858-bee03500-61cf-11e9-8036-b9470c83342b.png)

Also, instead of "Microservices", you should probably use "Additional features", to be consistent with the Cloud Console terminology.

![image](https://user-images.githubusercontent.com/360895/56384057-5180d400-61d0-11e9-86ea-9d9587972a8e.png)

CC @rgregg

**Comment by redborian** [comment]
Fixed in the latest release. Keeping this open until next release is out the door.

**Comment by redborian** [comment]
Fixed in release v0.0.8
