### ISSUE TITLE
Continuous Prompt to Update & Reload the Extension

### ISSUE THREAD

**Issue by adnanfida** [GoogleCloudPlatform/cloud-code-vscode#890]
**Environment**:
*(Hint: "Report Extension Issue on Github" command will fill these out for you.)*

**Version information**

Cloud Code Extension version: v2.5.0-trusted-testers.1

VSCode version: Version: 
1.87.2 (Universal)
Commit: 863d2581ecda6849923a2118d93a088b0745d9d6
Date: 2024-03-08T15:21:31.043Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0

OS: OS: Darwin arm64 23.4.0

Cloud SDK:

Skaffold: 

Kubectl:

**Description**: Continuous Prompt to Update & Reload the Extension

**Repro step**: Install extension, wait for Update prompt, Update and Reload

![image](https://github.com/GoogleCloudPlatform/cloud-code-vscode/assets/52178390/82cb6b80-f586-414f-ac0a-d1399f72b83c)

**Comment by galz10** [comment]
Can you submit this feedback through the IDE so we can see your cloud code logs.

**Comment by adnanfida** [comment]
> Can you submit this feedback through the IDE so we can see your cloud code logs.

Submitted.

**Comment by galz10** [comment]
Are you still seeing this issue in the latest version of trusted-testers, your logs attached to the report don't show any update messages

**Comment by adnanfida** [comment]
seems to have resolved. Thanks.

**Comment by adnanfida** [comment]
closing.
