### ISSUE TITLE
Citation Warnings are not going away

### ISSUE THREAD

**Issue by jjdelorme** [GoogleCloudPlatform/cloud-code-vscode#895]
**Environment**:
*(Hint: "Report Extension Issue on Github" command will fill these out for you.)*

**Version information**

Cloud Code Extension version: 2.8.1

VSCode version: 1.88.1

OS: ChromeOS

Cloud SDK:

Skaffold: 

Kubectl:

**Description**:
Despite clicking on the "Quick Fix" Smart Action: `Ignore Citation Warning` the citation warning still persists, nothing I can do to get it to go away.  This has happened on every citation warning I've received since installing 2.8.1.  The only way I can get rid of it is to close VS Code and restart.

**Repro step**:
Ask Gemini Code Assist for a suggestion, it returns something with a citation warning with yellow squiggles.  
Click Smart Action "Ignore citation warning"
It does not remove the squiggle.

**Comment by ghost** [comment]
Same here.

![image](https://github.com/GoogleCloudPlatform/cloud-code-vscode/assets/137609917/a6b121b8-9396-42cd-8f30-55942cb0bdaa)

![image](https://github.com/GoogleCloudPlatform/cloud-code-vscode/assets/137609917/0adead7e-d0ab-459e-ae3f-3dec91d1e13e)

**Comment by RosanaRufer** [comment]
We need a way to disable that 🙏

**Comment by sripasg** [comment]
We are aware of this issue and tracking internally to fix it for the next release.

**Comment by ImMALWARE** [comment]
Is it possible to totally disable these warnings?

**Comment by glouischandra** [comment]
Hello, this has been fixed on the latest v 2.12.0 of Gemini Cloud Code: https://marketplace.visualstudio.com/items/GoogleCloudTools.cloudcode/changelog
