### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by ramymedhat25** [GoogleCloudPlatform/cloud-code-vscode#903]
- Issue Type: `Performance`
- Extension Name: `cloudcode`
- Extension Version: `2.9.1`
- OS Version: `Windows_NT x64 10.0.19045`
- VS Code version: `1.89.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/ramym/AppData/Local/Temp/googlecloudtools.cloudcode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by maxrandolph** [comment]
Hi @ramymedhat25, could you please share the cpuprofile.txt file you generated? It doesn't look to be included here.

**Comment by kschaab** [comment]
Please reopen if you still get the issue and are willing to share the profile data.
