### ISSUE TITLE
Extension updates to 2.10 then auto-downgrades to 2.9 then wants to update to 2.10 and so on

### ISSUE THREAD

**Issue by Hermholtz** [GoogleCloudPlatform/cloud-code-vscode#905]
See the following screencast documenting the erroneous behaviour. 

![2024-05-18_02-12-27_Code](https://github.com/GoogleCloudPlatform/cloud-code-vscode/assets/15248889/d95fcd53-2f3a-497c-942a-703369666348)

**Version information**

VSCode version: 1.89.1

OS: Windows 10

**Description**:

**Repro step**:

**Comment by kschaab** [comment]
Are you still getting this?

**Comment by Hermholtz** [comment]
I've stopped using this extension, so cannot tell if the issue is occurring in the current version. You may close it at your will.
