### ISSUE TITLE
cannot copy application template while running guest Linux in Virtual Box

### ISSUE THREAD

**Issue by Maziak2520** [GoogleCloudPlatform/cloud-code-vscode#91]
Extension version:
VSCode version: Version: 1.33.1
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:20:22.771Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-20-generic (Linux Mint 19.2) in Virtual Box 5.2.28

**Description**:
When creating new application from template, it will not create nor copy the content to destination directory.

**Repro step**:
Install Linux, Install Virtual Box, Install guest Linux, Install VS Code, Install Cloud Code
Click :gear: Cloud Code, Select New Application, Select whatever, e.g. Python Hello World, press Enter on the selected directory
then the error occurs..
Unable to copy application template to /home/%USERNAME%/cloudcode-projects/python-hello-world-2: undefined Please check the write permissions and try again.

Permissions are fine, on Linux installation that is not in VirtualBox this does not happen and everything is fine.
Replicated on guest OS - Linux Mint 18.2, Linux Mint 19.2., Ubuntu 18.2.

**Comment by Red-Five** [comment]
I am seeing same issue on GCE Debian with a fresh install a few days ago. There is some unclear permissions issue; folder permission appears Ok and other plugins such as Spring Initializr are able to write to same folder.)

**Comment by iantalarico** [comment]
@quoctruong or @sujit-kamireddy Can one of you take a look at this?

**Comment by quoctruong** [comment]
I’m working on kubeconfig but I can look into this after.

**Comment by indraforyou** [comment]
I am observing the same on windows 10: 
`Unable to copy application template to C:\Users\USER\cloudcode-projects\python-hello-world-1: undefined Please check the write permissions and try again.`

**Comment by sujit-kamireddy** [comment]
@indraforyou , Can you check if the user under which vscode is running have the write permissions to the folder?

**Comment by indraforyou** [comment]
@sujit-kamireddy , its able to create `cloudcode-projects\python-hello-world-*` So I don't think its write permission. It worked on linux system though.

**Comment by Maziak2520** [comment]
It is working on Linux, it's also working in Lunch VM in Crostini, but it's not working in Linux in VM Virtual box....

**Comment by sujit-kamireddy** [comment]
@quoctruong will look into this after his current work.

**Comment by pongad** [comment]
@Maziak2520 I unfortunately cannot repro this problem. Can you verify that this is still a problem? There's a bug with the error message: right now the extension always asks users to check write permission even though that might not be the problem. A few months ago (after you opened the issue) we merged a PR to fix the "undefined" error. Could you update the bug with a new error message? That should give us a better idea of what's going on.

**Comment by sujit-kamireddy** [comment]
The fix for this issue is in our latest [release](https://github.com/GoogleCloudPlatform/cloud-code-vscode/releases/tag/v0.0.12). Please update the extension and retry the scenario.

**Comment by redborian** [comment]
This has been fixed in our latest version of Cloud Code (v0.0.13)
