### ISSUE TITLE
Extension isn't working with Rancher Desktop

### ISSUE THREAD

**Issue by progvb** [GoogleCloudPlatform/cloud-code-vscode#917]
Same as https://github.com/GoogleCloudPlatform/cloud-code-vscode/issues/830 - the issue still persists even with the latest version:

**Version information**

Cloud Code Extension version: v2.13.0

VSCode version: 1.91.0

OS: Windows 11

Cloud SDK: 482.0.0 (2024-06-25)

Skaffold: N/A

Kubectl: N/A

**Description**:

**Repro step**:

1. Open a project with Apigee X proxies in VS Code.
2. Go to APIGEE tab in CLOUD CODE extension. Under `emulators` you will see "❗ Listing failed due to Docker errors".

<img width="539" alt="image" src="https://github.com/GoogleCloudPlatform/cloud-code-vscode/assets/45557691/1c841c91-305b-4581-b319-3b9ff25a5dce">

See https://github.com/GoogleCloudPlatform/cloud-code-vscode/issues/830#issuecomment-1927150135 and https://github.com/GoogleCloudPlatform/cloud-code-vscode/issues/830#issuecomment-2146482030 as well.

CC: @ametelski

**Comment by progvb** [comment]
Why does Cloud Code even need to use "Docker Desktop.exe"? Why not just "docker.exe"?

<img width="528" alt="image" src="https://github.com/GoogleCloudPlatform/cloud-code-vscode/assets/45557691/57a200c3-dd26-4f38-9c7a-9ea0fadf55bc">

**Comment by progvb** [comment]
Rancher Desktop 1.15.0 has been released. I've updated my system to use it.
I also updated to the latest Cloud Code extension version (2.16.0).

Unfortunately, the Cloud Code extension still doesn't work with Rancher Desktop (any version from the past 2 years).

**Comment by witodev** [comment]
Same problem, looks like plugin is searching for Docker Desktop.exe:
![Screenshot 2024-08-09 120433](https://github.com/user-attachments/assets/21fab31d-415e-46ac-afda-220f99222523)

**Comment by glouischandra** [comment]
Hello @progvb are you running vscode in WSL or directly in Windows? If directly on Windows, if you have Docker Desktop installed or you run docker in some other way?

**Comment by progvb** [comment]
@glouischandra 

> are you running vscode in WSL or directly in Windows? If directly on Windows, if you have Docker Desktop installed or you run docker in some other way?

No (to both questions).

I'm running VS Code directly in Windows.

I can't run Docker Desktop on my machine - it's prohibited by the company policy. We must use Rancher Desktop instead.

The extension stopped working with Rancher Desktop in version 1.22.0 (July 2023). It never got fixed since then, please see issue #830 as well.

I've updated gcloud components, Cloud Code extension, VS Code, Rancher Desktop to the latest versions, but still getting the same error message:

![image](https://github.com/user-attachments/assets/72931b84-4cdd-40dc-8281-71e5198e744d)

I'm running on:

- Cloud Code version "Gemini Code Assist + Google Cloud Code v2.17.0"
- gcloud components 494.0.0
- VS Code 1.93.1
- Rancher Desktop 1.16.0
- Windows 11 Pro version 23H2

**Comment by AlbertoMonteiro** [comment]
@progvb did you found any workaround?

I am facing same issue as you, Windows + Rancher Desktop

**Comment by AlbertoMonteiro** [comment]
@progvb Fun fac, I opened VS Code from my WSL Ubuntu, and the emulator worked.

![image](https://github.com/user-attachments/assets/28c5861f-2b25-4f1a-865a-9237ebbadaa7)

But in Windows, it required the Docker Desktop

![image](https://github.com/user-attachments/assets/526e30c2-7784-4fa8-8844-f790a3ba468e)

**Comment by gaeshi** [comment]
@AlbertoMonteiro 
Unfortunately, I had to stop developing with Apigee Emulator because of the circumstances I described above, but I'll try your workaround and then update this message. Thank you for sharing.

**Comment by progvb** [comment]
@AlbertoMonteiro 

Thanks for sharing your workaround.

Unfortunately, it doesn't seem to work on my machine. I'm still getting the same error.

![image](https://github.com/user-attachments/assets/6c34e887-ef77-4a59-92da-da87c3d025c8)

**Comment by progvb** [comment]
@AlbertoMonteiro

Thank you for sharing your workaround. 

Running VSCode from WSL Ubuntu did seem to solve the "Cannot find path to Docker Desktop.exe in registry" issue!

**Comment by maxrandolph** [comment]
Hi @progvb, could you update your extension to the latest version (2.20.0) and see if this issue is persisting? This should be fixed in today's release.

**Comment by AlbertoMonteiro** [comment]
@maxrandolph 

I am with the newest version but it didn't change, same error.

![image](https://github.com/user-attachments/assets/64660e66-28d2-4acb-9119-45a0afa1c98f)

**Comment by progvb** [comment]
@maxrandolph 

Thank you for the update. Unfortunately this is not working on my machine.

![image](https://github.com/user-attachments/assets/9f66af94-7772-4142-963e-7cf05dcb084b)

I've opened a new issue #955 since this one was closed.
