### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by acctiveoffice** [GoogleCloudPlatform/cloud-code-vscode#919]
**Environment**:
*(Hint: "Report Extension Issue on Github" command will fill these out for you.)*

**Version information**

Cloud Code Extension version:

VSCode version:

OS: 

Cloud SDK:

Skaffold: 

Kubectl:

**Description**:

**Repro step**:

**Comment by davidponder** [comment]
Please re-open with additional details; thanks!
