### ISSUE TITLE
Create Cluster Machine Type Bug

### ISSUE THREAD

**Issue by Red-Five** [GoogleCloudPlatform/cloud-code-vscode#92]
**Environment**:
Extension version: 0.0.7 (Licence to Kill) 
VSCode version: 1.33.1
OS: Linux x64 4.9.0-8-amd64

**Description**:
Create a cluster, the machine type variable not working. 
![image](https://user-images.githubusercontent.com/25078066/56532919-b6b42c80-6524-11e9-9bdc-3002505f02b5.png)

Note [object Object] where the machine type should be in the command.
A default n1-standard-1 machine is created instead.

**Repro step**:

**Comment by redborian** [comment]
Thanks for reporting this! This is a known issue and is already fixed in the upcoming release.

**Comment by redborian** [comment]
Fixed in release v0.0.8

**Comment by Red-Five** [comment]
@redborian Please can we re-open this issue?

Although the [object Object] is replaced with n1-standard-1; its is ignoring the user selected menu item.

E.g. Select n1-standard-2 and  n1-standard-1 is created.

![image](https://user-images.githubusercontent.com/25078066/56761778-32ec8100-676c-11e9-9334-4d2abab161ee.png)

**Comment by redborian** [comment]
Thanks for bringing this up! We will look into this right away.

**Comment by redborian** [comment]
This is now part of the latest release
