### ISSUE TITLE
Cannot connect on remote server

### ISSUE THREAD

**Issue by Charlescad** [GoogleCloudPlatform/cloud-code-vscode#921]
Type: <b>Bug</b>

Cloude Code for VS Code sign-id failed.
"Error: The authentication flow did not complete successfully, and Cloud Code for VS Code is not authorized to access your account."

Extension version: 2.14.0
VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:06:49.809Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 4.18.0-513.24.1.el8_9.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 1805)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (8.86GB free)|
|Process Argv|--crash-reporter-id 24667df3-e461-47d5-b358-21086a04288a|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: em-tdp-edge-1|
|OS|Linux x64 4.18.0-513.24.1.el8_9.x86_64|
|CPUs|Intel(R) Xeon(R) Silver 4309Y CPU @ 2.80GHz (16 x 0)|
|Memory (System)|30.82GB (9.25GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyonecf:30548226
vscrpc:30673769
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
chatpanelc:31048052
dsvsc021:30996838
bdiig495:31013172
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
legacy_priority:31094926
refactorc:31093864
0c838689:31092287

```

</details>

**Comment by davidponder** [comment]
Hi @Charlescad,

Could you please submit feedback via the Help and Feedback explorer within the extension? Doing so opens an internal issue for us to look into as well as attaches the logs from the extension, which would be tremendously helpful.

Thanks!

**Comment by davidponder** [comment]
Hello!

We'll close this item for now, but please follow the above guidance to open an internally tracking item for us; thanks!
