### ISSUE TITLE
Retrieving builders. Automatic image build detection failed. Error: skaffold is not installed. 

### ISSUE THREAD

**Issue by hash2004** [GoogleCloudPlatform/cloud-code-vscode#922]
Retrieving builders.
Automatic image build detection failed. Error: skaffold is not installed. Please install the latest version of skaffold.. Consider adding a Dockerfile to the workspace and try again. See https://skaffold.dev/docs/pipeline-stages/builders/ for more information.

Even though I already have it installed and dockerfile is also there

**Comment by glouischandra** [comment]
Hello @hash2004 using VSCode's terminal can you see if "which skaffold" returns a valid path?

**Comment by davidponder** [comment]
Hello!

Due to lack of activity here, we're going to close this item. Please re-open with additional details if needed; thanks!
