### ISSUE TITLE
Add support for quick chat in Vscode

### ISSUE THREAD

**Issue by enzoenrico** [GoogleCloudPlatform/cloud-code-vscode#924]
**Use case**
I wanna use the chat feature in VSCode's quick chat (like copilot)

**Feature**
Returning the generated code / answers in the quickchat

**Comment by kschaab** [comment]
Thank you for the feature request.  We have shipped out a similar feature to what is in Copilot.  The actual API that Copilot uses for the inline chat window can only be used by Copilot unfortunately.  If you use cmd+i/ctrl+i with Gemini Code Assist you will get a similar experience that we are currently working on making better.
