### ISSUE TITLE
Add support for .gcloudignore

### ISSUE THREAD

**Issue by remcohaszing** [GoogleCloudPlatform/cloud-code-vscode#93]
GCloud using an ignore file called _.gcloudignore_. This file should be syntax highlighted as an ignore file. This can be done by adding the following to the extension’s _package.json_:

```json
"languages": [
  {
    "id": "ignore",
    "filenames": [
      ".gcloudignore"
    ]
  }
]
```

For a reference implementation, see https://github.com/Microsoft/vscode-eslint/blob/master/package.json#L273-L280

**Comment by sujit-kamireddy** [comment]
This issue has been fixed in the latest release 0.0.10. Please try it out.

As always, please keep issues coming our way.
