### ISSUE TITLE
Gemini Stalled Due to Error - TypeError: Cannot read properties of undefined (reading 'forEach') at t.AILanguageClient.<anonymous> 

### ISSUE THREAD

**Issue by jordantrizz** [GoogleCloudPlatform/cloud-code-vscode#930]
Type: <b>Bug</b>

Open up an extensive zsh shell script file and just start working on it.

Extension version: 2.16.7
VS Code version: Code 1.92.2 (Universal) (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Darwin arm64 23.3.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M3 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|3, 3, 4|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv|--crash-reporter-id ca5487ad-6dde-47eb-869f-4c838bb5cde7|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl1:31104043
refactort:31108082
pythonrstrctxt:31112756
flightc:31119335
wkspc-onlycs-t:31111718
wkspc-ranged-t:31125599
ei213698:31121563
aajjf12562:31125793

```

</details>

**Comment by ttosta-google** [comment]
Hello,

Thanks for reporting this issue. We'll investigate it and get back to you ASAP. Feel free to keep us posted on anything else you may notice in the meantime.

Thanks!

**Comment by kschaab** [comment]
We have a fix and will ship it out in the next release.

**Comment by jimmyff** [comment]
I'm having to restart VS Code multiple times per day for this issue and so tempted to switch back to copilot. Seems to hang every hour or two:
![Screenshot 2024-09-07 at 10 24 21](https://github.com/user-attachments/assets/c249e994-1e41-4355-b913-17d0277ba640)
![Screenshot 2024-09-07 at 10 26 15](https://github.com/user-attachments/assets/8596bf34-dfc3-4e3f-a952-85c26c45395f)
![Screenshot 2024-09-07 at 10 26 46](https://github.com/user-attachments/assets/6729fe26-5676-4d8a-b164-47e802094af4)

**Comment by jordantrizz** [comment]
> We have a fix and will ship it out in the next release.

Thanks for the update, what's the ETA on the next release?

**Comment by jimmyff** [comment]
@kschaab any update? Could really do with knowing when your team is planning to release the fix for this. It's seriously affecting productivity having to restart VS code multiple times per day.

**Comment by kschaab** [comment]
We pushed a fix on Monday, can you verify you have version 2.17.0?

**Comment by jimmyff** [comment]
Oh, I disabled Gemini code assist extension this morning after the third crash of the day and renewed my copilot subscription.

![image](https://github.com/user-attachments/assets/34f990fb-685d-4016-8269-068bb7d64d44)

It says v2.17.0 at the top, not sure if that is the version installed.
```
Published
2019-04-08, 16:05:09
Last released
2024-09-09, 18:41:28
Last updated
2024-09-10, 04:39:18
Identifier
googlecloudtools.cloudcode
```

As I'm no longer using this extension I'll leave the follow up's to people who are (this issue has already caused a frustrating amount of time!). I'll give it another try at some point in the future.
