### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by aliston-gomes** [GoogleCloudPlatform/cloud-code-vscode#934]
ADD ISSUE DESCRIPTION HERE

Version: 1.89.1
Commit: cf213cd39a3bfb26ce45d2c85949fee44b9d03d9
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
Embedder: unknown

Extension version: 1.0.0

**Comment by ttosta-google** [comment]
Please feel free to open with more data.
