### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by christomah0** [GoogleCloudPlatform/cloud-code-vscode#948]
- Issue Type: `Performance`
- Extension Name: `cloudcode`
- Extension Version: `2.19.0`
- OS Version: `Linux x64 6.11.3-200.fc40.x86_64`
- VS Code version: `1.94.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///tmp/googlecloudtools.cloudcode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by maxrandolph** [comment]
Please reopen this issue with the file attached. Thanks.
