### ISSUE TITLE
Typescript autocomplete stops working after a while of using Code assist

### ISSUE THREAD

**Issue by gtanczyk** [GoogleCloudPlatform/cloud-code-vscode#953]
**Environment**:
*(Hint: "Report Extension Issue on Github" command will fill these out for you.)*

**Version information**

Cloud Code Extension version: latest

VSCode version: latest

OS: mac

Cloud SDK: ??

Skaffold: ??

Kubectl: ??

**Description**:

**Repro step**:

Install and start using, need to restart VS Code to fix the issue.

When disabled the GCA entirely, the issue stopped happening.

**Comment by maxrandolph** [comment]
Hi @gtanczyk, it's not clear what the issue is. Could you provide more details? It would also be helpful if you file a bug through the feedback portion of the extension. Thanks.

**Comment by gtanczyk** [comment]
There is a IntelliSense for Typescript feature in VS Code: https://code.visualstudio.com/docs/languages/typescript#_intellisense

This feature stops working after a while of using Gemini Code Assist extension (googlecloudtools.cloudcode). Disabling the extension solves the problem: IntelliSense for TS in VSCode starts working.

I have observed this behaviour in two different projects/repositories.

**Comment by kschaab** [comment]
This should be fixed in the last release.
