### ISSUE TITLE
BigQuery support

### ISSUE THREAD

**Issue by portalhacker** [GoogleCloudPlatform/cloud-code-vscode#954]
**Use case**
What are you trying to do that our extension doesn't let you?

Explore BigQuery assets, launch queries and view results within VS Code, where I can easily version my queries and use the AI code assistant of my choice, with auto-completions I do not have in the web UI.

**Feature**
What would help?

A BigQuery assets panel, launching queries from SQL files, and a results preview panel.

**Comment by kschaab** [comment]
This has been added with 2.22.0.
