### ISSUE TITLE
Not Stopping at Breakpoints

### ISSUE THREAD

**Issue by Red-Five** [GoogleCloudPlatform/cloud-code-vscode#96]
**Environment**:
Extension version: 0.0.8
VSCode version: 1.33.1
OS: Linux

**Description**:
Debugger attaches to server on GKE and I see threads in the call stack window.
Not stopping at Breakpoints

More info about my setup: https://github.com/Red-Five/google-cloud-code-forseti-security/wiki

It almost appears as if its attached Ok, but in run mode rather than debug mode.

**Repro step**:

**Comment by Red-Five** [comment]
Another related finding.
If I do a default (local) build, deploy to GKE, I can attach to the debugger and see threads at least.

If I do a cloudbuild I cannot attach to the debugger:

E0426 18:24:24.295856   32308 portforward.go:400] an error occurred forwarding 36015 -> 3000: error forwarding port 3000 to pod 66967f7780ba0b1d1bca56a056def735acc8974b18b8fd7049ab263f443ad72f, uid : exit status 1: 2019/04/26 18:24:24 socat[10016] E connect(5, AF=2 127.0.0.1:3000, 16): Connection refused

**Comment by quoctruong** [comment]
@Red-Five What version of ptvsd are you using for the server?

**Comment by Red-Five** [comment]
@quoctruong I just added ptvsd to requirements.txt.

Ill have to verify the exact version that gets deployed

 (I assumed it just pulls the latest stable release if a version not specified but I could be wrong.)

**Comment by quoctruong** [comment]
@Red-Five There was a bug with the previous version of `ptvsd` where the path mapping wouldn't work and breakpoint information wouldn't show up.

**Comment by Red-Five** [comment]
@quoctruong  Are u referring to having to move apps out of the /usr folder?

Our app is in /forseti-security in remote docker and /home/${USER}/forseti-security on local dev

**Comment by quoctruong** [comment]
@Red-Five I mean it just wouldn't work at all on Linux. Though I believe the latest version should have this fixed.

**Comment by Red-Five** [comment]
Name: ptvsd
Version: 4.2.8
Location: /usr/local/lib/python2.7/dist-packages

**Comment by Red-Five** [comment]
@quoctruong Pls see this comment: https://github.com/Microsoft/ptvsd/issues/1364#issuecomment-489223060

I tried with the pathMappings field, but still same issue. Also the IntelliSense says that pathMappings is not a valid entry.

**Comment by Red-Five** [comment]
I suspect an issue with my local and remote path mappings. Will close this issue once I confirm.

**Comment by quoctruong** [comment]
@Red-Five Were you able to stop at the breakpoint?
