### ISSUE TITLE
Latest version blocks Google Cloud login over SSH

### ISSUE THREAD

**Issue by bogdan-matei-oxb** [GoogleCloudPlatform/cloud-code-vscode#960]
**Environment**:
*(Hint: "Report Extension Issue on Github" command will fill these out for you.)*

**Version information**

Cloud Code Extension version: 2.20.1

VSCode version: 1.95.2

OS: Linux

Cloud SDK: 500.0.0

Skaffold: 

Kubectl:

**Description**: After installing the extension on a machine that VSCode is connected to over SSH, the Google Cloud Login button does nothing.

**Repro step**:
- Install extension in VSCode.
- Connect over SSH to remote machine.
- Install extension in SSH.
- Try to login. Clicking the button does nothing.
- Downgrade to version 2.20.0.
- Clicking the login button opens the browser.

**Comment by glouischandra** [comment]
Hello @bogdan-matei-oxb Please try version 2.20.2 or newer, you might be blocked by the same bug as https://github.com/GoogleCloudPlatform/cloud-code-vscode/issues/961
