### ISSUE TITLE
Unable to initialize the AuthProvider, err: The ADC file was inaccessible

### ISSUE THREAD

**Issue by andrejmaya** [GoogleCloudPlatform/cloud-code-vscode#961]
**Environment**: 
*(Hint: "Report Extension Issue on Github" command will fill these out for you.)*

**Version information** 

Cloud Code Extension version: v2.20.1

VSCode version: 1.95.2

OS: MacOS 15.1 Intel

Cloud SDK: 500.0.0

Skaffold: 

Kubectl:

**Description**:
After fresh installation of the extension while clicking on the Gemini icon on the left panel the progress bar keeps running and an error pops up in the bottom right corner "Unable to initialize the AuthProvider, err: The ADC file was inaccessible"

I already signed in with `gcloud auth application-default login` and the file `application_default_credentials.json` exists and is accessible by my user.

**Repro step**:

<img width="1400" alt="image" src="https://github.com/user-attachments/assets/fb5b33e2-1e37-4737-885b-7edb7f88dfcf">

**Comment by glouischandra** [comment]
Hello @andrejmaya we are aware of this issue and will release a hotfix asap

**Comment by kschaab** [comment]
We have shipped a fix for this issue.

**Comment by glouischandra** [comment]
Please use v2.20.2 that has the fix

**Comment by sbuys** [comment]
@kschaab @glouischandra  - I still see this error on 2.20.2.

Unable to initialize the AuthProvider, err: ENOENT: no such file or directory, mkdir '/Users/x/Library/Application Support/cloud-code/ADC_FILE_UPDATE_LOCK'

**Comment by adpajdarova** [comment]
I use version 2.23.1, and I still receive this error.

**Comment by adpajdarova** [comment]
I use version 2.23.1, and I still receive this error.
