### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by SirikanyaRa** [GoogleCloudPlatform/cloud-code-vscode#964]
- Issue Type: `Performance`
- Extension Name: `cloudcode`
- Extension Version: `2.21.0`
- OS Version: `Windows_NT x64 10.0.22621`
- VS Code version: `1.95.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/srattana/AppData/Local/Temp/googlecloudtools.cloudcode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by kschaab** [comment]
Please reopen with the log from above.
