### ISSUE TITLE
Just started getting this error, but gemini works without issue (Mac M2): Managed dependencies are currently unavailable due to failure. Cloud Code will reattempt to install managed dependencies after Visual Studio Code is restarted. Failed to install Cloud SDK. Unsupported architecture: linux/arm64

### ISSUE THREAD

**Issue by red8888** [GoogleCloudPlatform/cloud-code-vscode#965]
**Environment**:
Macos: 14.4 (23E214)
Chip: Apple M2 Max

**Version information**
Version: 1.95.3 (Universal)
Commit: f1a4fb101478ce6ec82fe9627c43efbf9e98c813
Date: 2024-11-13T14:50:04.152Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Darwin arm64 23.4.0

Cloud Code Extension version:
v2.21.0

VSCode version:
Version: 1.95.3 (Universal)

OS: 
Macos: 14.4 (23E214)

**Description**:
I just started getting this annoying error every time I launch a dev container. I only use gemini none of the other "cloud code" stuff. Gemini works without issue so can I just tell it to shut up about the other unsupported stuff? This just started happening I was not getting this error before.

**Comment by waynetaylor** [comment]
+1 of this issue.

**Comment by kschaab** [comment]
We're working on a fix, please feel free to turn off managed dependencies if you aren't using them.
`"cloudcode.autoDependencies": "off",` or  
<img width="817" alt="image" src="https://github.com/user-attachments/assets/dc5e35ae-e8b4-4d5f-870e-0e3f16daec07">

**Comment by sripasg** [comment]
Please let us know if you see this when you update to 2.22.0

**Comment by kschaab** [comment]
This is fixed in 2.22.0.
