### ISSUE TITLE
is VScode broken?

### ISSUE THREAD

**Issue by Beartheeipicone** [GoogleCloudPlatform/cloud-code-vscode#980]
![Screenshot 2024-12-14 172436](https://github.com/user-attachments/assets/c4735135-c043-41d1-8140-106850a4eeca)

So when i try running my code. It pop this in output

Does anyone know how to fix it pls

**Comment by maxrandolph** [comment]
Hi @Beartheeipicone, this doesn't look to be necessarily related to the cloud code extension. If this behavior is observed only through something related to the Cloud Code extension, feel free to reopen your issue with repro steps. 

Thanks.

**Comment by Beartheeipicone** [comment]
The problem is maybe fixed for now.
i didn't see the erorr now so i think is fixed for now. Thanks maxrandolph.

**Comment by Beartheeipicone** [comment]
nvm i try to fix it
