### ISSUE TITLE
Unable to Login Gemini from VS Code

### ISSUE THREAD

**Issue by cigoic** [GoogleCloudPlatform/cloud-code-vscode#983]
**Environment**:
Surface Pro 11 with Win 11 Home (ARM)

**Version information**

Cloud Code Extension version:

VSCode version:

OS: Win 11 Home (ARM)

Cloud SDK:

Skaffold: 

Kubectl:

**Description**:
When I click the Login to Gemini button, a pop-up asks for trust google certification. Then, I choose to trust all google.com (sub-)domains. An localhost ERR_SSL_PROTOCOL_ERROR shows up. 

Any suggestion? Thanks.

**Repro step**:

**Comment by maxrandolph** [comment]
Hi @cigoic, could you repro this issue, and submit a feedback report with logs attached from inside the extension? Thanks!

![image](https://github.com/user-attachments/assets/b82c3a6a-e54f-47be-919d-ca5f42a0b544)

**Comment by cigoic** [comment]
Thanks. I end up using Brave (without logging into Google account first) and successfully enable Gemini AI extension.
