### ISSUE TITLE
Erro: o fluxo de autenticação não foi concluído, e o Cloud Code para VS Code não tem autorização para acessar sua conta

### ISSUE THREAD

**Issue by brunotomaz-dev** [GoogleCloudPlatform/cloud-code-vscode#984]
Type: <b>Bug</b>

request to https://oauth2.googleapis.com/token failed, reason: self signed certificate in certificate chain

Tenho tido problemas similares com o github copilot

Extension version: 2.23.1
VS Code version: Code 1.96.2 (fabdb6a30b49f79a7aba0f2ad9df9b399473380f, 2024-12-19T10:22:47.216Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i5-1335U (12 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.69GB (0.58GB free)|
|Process Argv|--crash-reporter-id 4b22f572-1d41-4d27-9ace-853b4e550933|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythonnoceb:30805159
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
nativerepl1:31139838
pythonrstrctxt:31112756
nativeloc1:31192215
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530
6074i472:31201624

```

</details>

**Comment by maxrandolph** [comment]
Hi @brunotomaz-dev, is it possible that your machine is using some kind of proxy or internal self-signed certificate within your network configuration?

**Comment by brunotomaz-dev** [comment]
> Hi @maxrandolph, 
I believe not.
I tried again, and this time it worked. Apparently, it was a temporary issue.
