### ISSUE TITLE
provide a way to set gcloud project from IDE

### ISSUE THREAD

**Issue by pongad** [GoogleCloudPlatform/cloud-code-vscode#99]
**Use case**
If we have multiple projects, we can only switch between them from the CLI.

**Feature**
A command to do this might help: just forward to `gcloud config set project <new project>`.

**Comment by jmah-cc** [comment]
@pongad We were reviewing our backlog and wanted more information on this issue. Can you clarify which scenarios this applies to?

**Comment by jmah-cc** [comment]
This functionality will be in the next release.

**Comment by sujit-kamireddy** [comment]
We now have switch project option available in Cloud Run explorer and Deploy to Cloud Run UI.
Users can also pin projects in the GKE explorer.
